#	$NetBSD: Makefile,v 1.25 2008/01/19 13:11:17 chris Exp $

INCSDIR= /usr/include/hpcarm

INCS=	ansi.h apmvar.h aout_machdep.h asm.h \
	bswap.h bus.h \
	cdefs.h cpu.h \
	disklabel.h \
	elf_machdep.h endian.h endian_machdep.h \
	float.h fp.h frame.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intr.h \
	limits.h lock.h \
	math.h mcontext.h mutex.h \
	param.h pcb.h pmap.h pmc.h proc.h profile.h ptrace.h \
	reg.h rwlock.h \
	setjmp.h signal.h stdarg.h sysarch.h \
	trap.h types.h \
	varargs.h vmparam.h \
	wchar_limits.h

.include <bsd.kinc.mk>
