#	$NetBSD: Makefile,v 1.2 2018/05/01 00:04:35 christos Exp $

NOMAN=	# defined

.include <bsd.init.mk>

HOSTPROGNAME=   ${_TOOL_PREFIX}cvslatest
HOST_SRCDIR=    usr.bin/cvslatest

.include "${.CURDIR}/../Makefile.nbincludes"
.include "${.CURDIR}/../Makefile.host"
