#	$NetBSD: Makefile,v 1.11 2001/04/14 22:46:23 kleink Exp $

KDIR=	/sys/arch/mac68k/include
INCSDIR= /usr/include/mac68k

INCS=	adbsys.h ansi.h aout_machdep.h asm.h autoconf.h \
	bswap.h bus.h \
	cdefs.h cpu.h \
	db_machdep.h disklabel.h \
	elf_machdep.h endian.h endian_machdep.h \
	float.h frame.h \
	grfioctl.h \
	ieee.h ieeefp.h int_const.h int_mwgwtypes.h int_types.h intr.h \
	iteioctl.h \
	kcore.h keyboard.h \
	limits.h lock.h \
	param.h math.h pcb.h pio.h pmap.h proc.h profile.h psc.h psl.h \
	pte.h ptrace.h \
	reg.h \
	scsi_5380.h setjmp.h signal.h stdarg.h svr4_machdep.h \
	trap.h types.h \
	varargs.h viareg.h vmparam.h \
	z8530var.h

.include <bsd.kinc.mk>
