#	$NetBSD: Makefile,v 1.4 2000/06/26 15:42:38 kleink Exp $

KDIR=	/sys/arch/luna68k/include
INCSDIR= /usr/include/luna68k

INCS=	ansi.h aout_machdep.h asm.h autoconf.h bswap.h bus.h cdefs.h \
	cpu.h db_machdep.h disklabel.h endian.h endian_machdep.h float.h \
	frame.h ieee.h ieeefp.h int_types.h intr.h kcore.h limits.h lock.h \
	math.h param.h pcb.h pmap.h proc.h profile.h psl.h pte.h ptrace.h \
	reg.h setjmp.h signal.h stdarg.h trap.h types.h varargs.h vmparam.h

.include <bsd.kinc.mk>
