#	$NetBSD: Makefile,v 1.6 1997/10/25 06:58:35 lukem Exp $

PROG=	rarpd
MAN=	rarpd.8

# Uncomment the following to require a boot file in TFTP_DIR
# to exist for a rarp reply to be sent.
# CPPFLAGS+=-DREQUIRE_TFTPBOOT -DTFTP_DIR=\"/tftpboot\"


.include <bsd.prog.mk>
