#	$NetBSD: Makefile.common,v 1.1.4.1 2002/01/10 20:00:52 thorpej Exp $

.include "../Makefile.inc"

.PATH:	$S/compat/svr4 $S/arch/${MACHINE_ARCH}/${MACHINE_ARCH}

CPPFLAGS+= -DCOMPAT_SVR4${USE_32} -DSYSVSEM -DSYSVMSG -DSYSVSHM \
		-DSVR4_COMPAT_SOLARIS2
AFLAGS=		-x assembler-with-cpp -traditional-cpp -D_LOCORE \
		-I. -I${S}

KMOD=	compat_svr4${USE_32}
