.\" $NetBSD: btuartd.8,v 1.4.4.2 2008/01/09 02:01:56 matt Exp $
.\"
.\" Copyright (c) 2007 KIYOHARA Takashi
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\" DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
.\" ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.\" $Id: btuartd.8,v 1.4.4.2 2008/01/09 02:01:56 matt Exp $
.\"
.Dd November 2, 2007
.Dt BTUARTD 8
.Os
.Sh NAME
.Nm btuartd
.Nd Bluetooth HCI UART (H4) daemon
.Sh SYNOPSIS
.Nm
.Op Fl d
.Op Fl c Ar conffile
.Nm
.Op Fl f
.Op Fl p Op Fl o
.Op Fl i Ar init_speed
.Op Ar type
.Ar comdev speed
.Sh DESCRIPTION
The
.Nm
daemon configures and attaches Bluetooth HCI UART devices.
It opens
.Ar comdev
like
.Xr com 4
and compatible devices, also configures
.Ar speed
and flow, parity.
The
.Nm
daemon supports HCI UART and BCSP.
With
.Fl c
it reads the configuration file and with
.Fl d
it runs in foreground mode.
With a
.Ar comdev
argument, it configures that device.
.Pp
When the SIGHUP signal is received in daemon mode, all devices are closed,
and the daemon rereads the configuration files.
.Pp
If the
.Ar type
is given, then
.Nm
sets
.Xr btuart 4
to
.Ar type .
Otherwise that for unspecified HCI UART interface.
Supported
.Ar types
are:
.Bl -tag -width XXXXXX
.It Cm bcm2035
Broadcom BCM2035
.It Cm bcsp
BCSP (BlueCore Serial Protocol)
.It Cm bgb2xx
Philips BGB2xx Module
.It Cm csr
Cambridge Silicon Radio Casira serial adapter or BrainBoxes serial dongle
(BL642)
.Pp
AmbiCom BT2000C Bluetooth PC/CF Card
.It Cm ericsson
Ericsson based modules
.It Cm digi
Digianswer based cards
.It Cm st
ST Microelectronics minikits based on STLC2410/STLC2415
.It Cm stlc2500
ST Microelectronics minikits based on STLC2500
.It Cm swave
Silicon Wave kits
.It Cm texas
Texas Instruments
.El
.Pp
The command line options are as follows:
.Bl -tag -width XXXX
.It Fl c Ar conffile
Specify the configuration file.
The default is
.Pa /etc/bluetooth/btuartd.conf .
.It Fl d
Run in foreground (do not detach).
.It Fl f
Enable flow control as
.Xr com 4 .
.It Fl i Ar init_speed
Specify the initial speed for the Bluetooth module. It first sets to this
value, and it initializes it if specified. Afterwards, the speed is set to
.Ar speed .
.It Fl o
Enable odd parity, if enabled parity.
.It Fl p
Enable parity (even parity).
.El
.Sh EXAMPLES
ericsson based modules with
.Pa /dev/dty00 :
.Dl btuartd -f ericsson /dev/dty00 57600
Also sets no flow, working speed 115200.
.Dl btuartd -i 57600 ericsson /dev/dty01 115200
.Pp
If you know unknown LSI works speed 115200 with
.Pa /dev/dty01 :
.Dl btuartd -f /dev/dty01 115200
.Pp
Broadcom BCM2035:
.Dl btuartd -f bcm2035 /dev/dty00 115200
.Pp
BCSP (BlueCore Serial Protocol):
.Dl btuartd -p bcsp /dev/dty00 57600
.Dl btuartd -p bcsp /dev/dty00 115200
.Pp
Philips BGB2xx Module:
.Dl btuartd -f bgb2xx /dev/dty00 115200
.Pp
CSR Casira serial adapter or BrainBoxes serial dongle (BL642) or BrainBoxes
PCMCIA card (BL620) or 3Com Bluetooth Card (Version 3.0):
.Dl btuartd -f csr /dev/dty00 115200
AmbiCom BT2000C Bluetooth PC/CF Card:
.Dl btuartd -f csr /dev/dty00 57600
.Pp
Digianswer based cards:
.Dl btuartd -f digi /dev/dty00 9600
.Pp
ST Microelectronics minikits based on STLC2410/STLC2415:
.Dl btuartd -f st /dev/dty00 57600
.Pp
ST Microelectronics minikits based on STLC2500:
.Dl btuartd -f stlc2500 /dev/dty00 115200
.Pp
Silicon Wave kits:
.Dl btuartd -f swave /dev/dty00 115200
.Pp
Texas Instruments:
.Dl btuartd -f texas /dev/dty00 115200
.Sh FILES
.Bl -tag -compact
.It Pa /etc/bluetooth/btuartd.conf
.It Pa /var/run/btuartd.pid
.El
.Sh SEE ALSO
.Xr bcsp 4 ,
.Xr bluetooth 4 ,
.Xr btuart 4 ,
.Xr btconfig 8
.Sh HISTORY
The
.Nm
daemon was written for
.Nx 4.0 .
.Sh AUTHORS
.An KIYOHARA Takashi Aq kiyohara@kk.iij4u.or.jp
