/* $NetBSD: netbsd32_syscall.h,v 1.70.4.2 2008/01/20 17:51:28 bouyer Exp $ */

/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from	NetBSD: syscalls.master,v 1.65 2008/01/19 22:25:12 dsl Exp
 */

#ifndef _NETBSD32_SYS_SYSCALL_H_
#define	_NETBSD32_SYS_SYSCALL_H_

#define	NETBSD32_SYS_MAXSYSARGS	8

/* syscall: "syscall" ret: "int" args: "int" "..." */
#define	NETBSD32_SYS_syscall	0

/* syscall: "netbsd32_exit" ret: "void" args: "int" */
#define	NETBSD32_SYS_netbsd32_exit	1

/* syscall: "fork" ret: "int" args: */
#define	NETBSD32_SYS_fork	2

/* syscall: "netbsd32_read" ret: "netbsd32_ssize_t" args: "int" "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_read	3

/* syscall: "netbsd32_write" ret: "netbsd32_ssize_t" args: "int" "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_write	4

/* syscall: "netbsd32_open" ret: "int" args: "netbsd32_charp" "int" "..." */
#define	NETBSD32_SYS_netbsd32_open	5

/* syscall: "netbsd32_close" ret: "int" args: "int" */
#define	NETBSD32_SYS_netbsd32_close	6

/* syscall: "netbsd32_wait4" ret: "int" args: "int" "netbsd32_intp" "int" "netbsd32_rusagep_t" */
#define	NETBSD32_SYS_netbsd32_wait4	7

/* syscall: "compat_43_netbsd32_ocreat" ret: "int" args: "netbsd32_charp" "mode_t" */
#define	NETBSD32_SYS_compat_43_netbsd32_ocreat	8

/* syscall: "netbsd32_link" ret: "int" args: "netbsd32_charp" "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_link	9

/* syscall: "netbsd32_unlink" ret: "int" args: "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_unlink	10

				/* 11 is obsolete execv */
/* syscall: "netbsd32_chdir" ret: "int" args: "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_chdir	12

/* syscall: "netbsd32_fchdir" ret: "int" args: "int" */
#define	NETBSD32_SYS_netbsd32_fchdir	13

/* syscall: "netbsd32_mknod" ret: "int" args: "netbsd32_charp" "mode_t" "dev_t" */
#define	NETBSD32_SYS_netbsd32_mknod	14

/* syscall: "netbsd32_chmod" ret: "int" args: "netbsd32_charp" "mode_t" */
#define	NETBSD32_SYS_netbsd32_chmod	15

/* syscall: "netbsd32_chown" ret: "int" args: "netbsd32_charp" "uid_t" "gid_t" */
#define	NETBSD32_SYS_netbsd32_chown	16

/* syscall: "netbsd32_break" ret: "int" args: "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_break	17

/* syscall: "compat_20_netbsd32_getfsstat" ret: "int" args: "netbsd32_statfsp_t" "netbsd32_long" "int" */
#define	NETBSD32_SYS_compat_20_netbsd32_getfsstat	18

/* syscall: "compat_43_netbsd32_olseek" ret: "netbsd32_long" args: "int" "netbsd32_long" "int" */
#define	NETBSD32_SYS_compat_43_netbsd32_olseek	19

/* syscall: "getpid" ret: "pid_t" args: */
#define	NETBSD32_SYS_getpid	20

/* syscall: "netbsd32_mount" ret: "int" args: "netbsd32_charp" "netbsd32_charp" "int" "netbsd32_voidp" */
#define	NETBSD32_SYS_netbsd32_mount	21

/* syscall: "netbsd32_unmount" ret: "int" args: "netbsd32_charp" "int" */
#define	NETBSD32_SYS_netbsd32_unmount	22

/* syscall: "netbsd32_setuid" ret: "int" args: "uid_t" */
#define	NETBSD32_SYS_netbsd32_setuid	23

/* syscall: "getuid" ret: "uid_t" args: */
#define	NETBSD32_SYS_getuid	24

/* syscall: "geteuid" ret: "uid_t" args: */
#define	NETBSD32_SYS_geteuid	25

/* syscall: "netbsd32_ptrace" ret: "int" args: "int" "pid_t" "netbsd32_caddr_t" "int" */
#define	NETBSD32_SYS_netbsd32_ptrace	26

/* syscall: "netbsd32_recvmsg" ret: "netbsd32_ssize_t" args: "int" "netbsd32_msghdrp_t" "int" */
#define	NETBSD32_SYS_netbsd32_recvmsg	27

/* syscall: "netbsd32_sendmsg" ret: "netbsd32_ssize_t" args: "int" "netbsd32_msghdrp_t" "int" */
#define	NETBSD32_SYS_netbsd32_sendmsg	28

/* syscall: "netbsd32_recvfrom" ret: "netbsd32_ssize_t" args: "int" "netbsd32_voidp" "netbsd32_size_t" "int" "netbsd32_sockaddrp_t" "netbsd32_intp" */
#define	NETBSD32_SYS_netbsd32_recvfrom	29

/* syscall: "netbsd32_accept" ret: "int" args: "int" "netbsd32_sockaddrp_t" "netbsd32_intp" */
#define	NETBSD32_SYS_netbsd32_accept	30

/* syscall: "netbsd32_getpeername" ret: "int" args: "int" "netbsd32_sockaddrp_t" "netbsd32_intp" */
#define	NETBSD32_SYS_netbsd32_getpeername	31

/* syscall: "netbsd32_getsockname" ret: "int" args: "int" "netbsd32_sockaddrp_t" "netbsd32_intp" */
#define	NETBSD32_SYS_netbsd32_getsockname	32

/* syscall: "netbsd32_access" ret: "int" args: "netbsd32_charp" "int" */
#define	NETBSD32_SYS_netbsd32_access	33

/* syscall: "netbsd32_chflags" ret: "int" args: "netbsd32_charp" "netbsd32_u_long" */
#define	NETBSD32_SYS_netbsd32_chflags	34

/* syscall: "netbsd32_fchflags" ret: "int" args: "int" "netbsd32_u_long" */
#define	NETBSD32_SYS_netbsd32_fchflags	35

/* syscall: "sync" ret: "void" args: */
#define	NETBSD32_SYS_sync	36

/* syscall: "netbsd32_kill" ret: "int" args: "int" "int" */
#define	NETBSD32_SYS_netbsd32_kill	37

/* syscall: "compat_43_netbsd32_stat43" ret: "int" args: "netbsd32_charp" "netbsd32_stat43p_t" */
#define	NETBSD32_SYS_compat_43_netbsd32_stat43	38

/* syscall: "getppid" ret: "pid_t" args: */
#define	NETBSD32_SYS_getppid	39

/* syscall: "compat_43_netbsd32_lstat43" ret: "int" args: "netbsd32_charp" "netbsd32_stat43p_t" */
#define	NETBSD32_SYS_compat_43_netbsd32_lstat43	40

/* syscall: "netbsd32_dup" ret: "int" args: "int" */
#define	NETBSD32_SYS_netbsd32_dup	41

/* syscall: "pipe" ret: "int" args: */
#define	NETBSD32_SYS_pipe	42

/* syscall: "getegid" ret: "gid_t" args: */
#define	NETBSD32_SYS_getegid	43

/* syscall: "netbsd32_profil" ret: "int" args: "netbsd32_caddr_t" "netbsd32_size_t" "netbsd32_u_long" "u_int" */
#define	NETBSD32_SYS_netbsd32_profil	44

/* syscall: "netbsd32_ktrace" ret: "int" args: "netbsd32_charp" "int" "int" "int" */
#define	NETBSD32_SYS_netbsd32_ktrace	45

/* syscall: "netbsd32_sigaction" ret: "int" args: "int" "netbsd32_sigactionp_t" "netbsd32_sigactionp_t" */
#define	NETBSD32_SYS_netbsd32_sigaction	46

/* syscall: "getgid" ret: "gid_t" args: */
#define	NETBSD32_SYS_getgid	47

/* syscall: "compat_13_sigprocmask13" ret: "int" args: "int" "int" */
#define	NETBSD32_SYS_compat_13_sigprocmask13	48

/* syscall: "netbsd32___getlogin" ret: "int" args: "netbsd32_charp" "u_int" */
#define	NETBSD32_SYS_netbsd32___getlogin	49

/* syscall: "netbsd32_setlogin" ret: "int" args: "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_setlogin	50

/* syscall: "netbsd32_acct" ret: "int" args: "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_acct	51

/* syscall: "compat_13_sigpending13" ret: "int" args: */
#define	NETBSD32_SYS_compat_13_sigpending13	52

/* syscall: "compat_13_netbsd32_sigaltstack13" ret: "int" args: "netbsd32_sigaltstack13p_t" "netbsd32_sigaltstack13p_t" */
#define	NETBSD32_SYS_compat_13_netbsd32_sigaltstack13	53

/* syscall: "netbsd32_ioctl" ret: "int" args: "int" "netbsd32_u_long" "..." */
#define	NETBSD32_SYS_netbsd32_ioctl	54

/* syscall: "compat_12_netbsd32_reboot" ret: "int" args: "int" */
#define	NETBSD32_SYS_compat_12_netbsd32_reboot	55

/* syscall: "netbsd32_revoke" ret: "int" args: "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_revoke	56

/* syscall: "netbsd32_symlink" ret: "int" args: "netbsd32_charp" "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_symlink	57

/* syscall: "netbsd32_readlink" ret: "int" args: "netbsd32_charp" "netbsd32_charp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_readlink	58

/* syscall: "netbsd32_execve" ret: "int" args: "netbsd32_charp" "netbsd32_charpp" "netbsd32_charpp" */
#define	NETBSD32_SYS_netbsd32_execve	59

/* syscall: "netbsd32_umask" ret: "mode_t" args: "mode_t" */
#define	NETBSD32_SYS_netbsd32_umask	60

/* syscall: "netbsd32_chroot" ret: "int" args: "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_chroot	61

/* syscall: "compat_43_netbsd32_fstat43" ret: "int" args: "int" "netbsd32_stat43p_t" */
#define	NETBSD32_SYS_compat_43_netbsd32_fstat43	62

/* syscall: "compat_43_netbsd32_ogetkerninfo" ret: "int" args: "int" "netbsd32_charp" "netbsd32_intp" "int" */
#define	NETBSD32_SYS_compat_43_netbsd32_ogetkerninfo	63

/* syscall: "compat_43_ogetpagesize" ret: "int" args: */
#define	NETBSD32_SYS_compat_43_ogetpagesize	64

/* syscall: "compat_12_netbsd32_msync" ret: "int" args: "netbsd32_caddr_t" "netbsd32_size_t" */
#define	NETBSD32_SYS_compat_12_netbsd32_msync	65

/* syscall: "vfork" ret: "int" args: */
#define	NETBSD32_SYS_vfork	66

				/* 67 is obsolete vread */
				/* 68 is obsolete vwrite */
/* syscall: "netbsd32_sbrk" ret: "int" args: "netbsd32_intptr_t" */
#define	NETBSD32_SYS_netbsd32_sbrk	69

/* syscall: "netbsd32_sstk" ret: "int" args: "int" */
#define	NETBSD32_SYS_netbsd32_sstk	70

/* syscall: "compat_43_netbsd32_ommap" ret: "int" args: "netbsd32_caddr_t" "netbsd32_size_t" "int" "int" "int" "netbsd32_long" */
#define	NETBSD32_SYS_compat_43_netbsd32_ommap	71

/* syscall: "vadvise" ret: "int" args: "int" */
#define	NETBSD32_SYS_vadvise	72

/* syscall: "netbsd32_munmap" ret: "int" args: "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_munmap	73

/* syscall: "netbsd32_mprotect" ret: "int" args: "netbsd32_voidp" "netbsd32_size_t" "int" */
#define	NETBSD32_SYS_netbsd32_mprotect	74

/* syscall: "netbsd32_madvise" ret: "int" args: "netbsd32_voidp" "netbsd32_size_t" "int" */
#define	NETBSD32_SYS_netbsd32_madvise	75

				/* 76 is obsolete vhangup */
				/* 77 is obsolete vlimit */
/* syscall: "netbsd32_mincore" ret: "int" args: "netbsd32_caddr_t" "netbsd32_size_t" "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_mincore	78

/* syscall: "netbsd32_getgroups" ret: "int" args: "int" "netbsd32_gid_tp" */
#define	NETBSD32_SYS_netbsd32_getgroups	79

/* syscall: "netbsd32_setgroups" ret: "int" args: "int" "netbsd32_gid_tp" */
#define	NETBSD32_SYS_netbsd32_setgroups	80

/* syscall: "getpgrp" ret: "int" args: */
#define	NETBSD32_SYS_getpgrp	81

/* syscall: "netbsd32_setpgid" ret: "int" args: "int" "int" */
#define	NETBSD32_SYS_netbsd32_setpgid	82

/* syscall: "netbsd32_setitimer" ret: "int" args: "int" "netbsd32_itimervalp_t" "netbsd32_itimervalp_t" */
#define	NETBSD32_SYS_netbsd32_setitimer	83

/* syscall: "compat_43_owait" ret: "int" args: */
#define	NETBSD32_SYS_compat_43_owait	84

/* syscall: "compat_12_netbsd32_oswapon" ret: "int" args: "netbsd32_charp" */
#define	NETBSD32_SYS_compat_12_netbsd32_oswapon	85

/* syscall: "netbsd32_getitimer" ret: "int" args: "int" "netbsd32_itimervalp_t" */
#define	NETBSD32_SYS_netbsd32_getitimer	86

/* syscall: "compat_43_netbsd32_ogethostname" ret: "int" args: "netbsd32_charp" "u_int" */
#define	NETBSD32_SYS_compat_43_netbsd32_ogethostname	87

/* syscall: "compat_43_netbsd32_osethostname" ret: "int" args: "netbsd32_charp" "u_int" */
#define	NETBSD32_SYS_compat_43_netbsd32_osethostname	88

/* syscall: "compat_43_ogetdtablesize" ret: "int" args: */
#define	NETBSD32_SYS_compat_43_ogetdtablesize	89

/* syscall: "netbsd32_dup2" ret: "int" args: "int" "int" */
#define	NETBSD32_SYS_netbsd32_dup2	90

/* syscall: "netbsd32_fcntl" ret: "int" args: "int" "int" "..." */
#define	NETBSD32_SYS_netbsd32_fcntl	92

/* syscall: "netbsd32_select" ret: "int" args: "int" "netbsd32_fd_setp_t" "netbsd32_fd_setp_t" "netbsd32_fd_setp_t" "netbsd32_timevalp_t" */
#define	NETBSD32_SYS_netbsd32_select	93

/* syscall: "netbsd32_fsync" ret: "int" args: "int" */
#define	NETBSD32_SYS_netbsd32_fsync	95

/* syscall: "netbsd32_setpriority" ret: "int" args: "int" "int" "int" */
#define	NETBSD32_SYS_netbsd32_setpriority	96

/* syscall: "compat_30_netbsd32_socket" ret: "int" args: "int" "int" "int" */
#define	NETBSD32_SYS_compat_30_netbsd32_socket	97

/* syscall: "netbsd32_connect" ret: "int" args: "int" "netbsd32_sockaddrp_t" "int" */
#define	NETBSD32_SYS_netbsd32_connect	98

/* syscall: "compat_43_netbsd32_oaccept" ret: "int" args: "int" "netbsd32_caddr_t" "netbsd32_intp" */
#define	NETBSD32_SYS_compat_43_netbsd32_oaccept	99

/* syscall: "netbsd32_getpriority" ret: "int" args: "int" "int" */
#define	NETBSD32_SYS_netbsd32_getpriority	100

/* syscall: "compat_43_netbsd32_osend" ret: "int" args: "int" "netbsd32_caddr_t" "int" "int" */
#define	NETBSD32_SYS_compat_43_netbsd32_osend	101

/* syscall: "compat_43_netbsd32_orecv" ret: "int" args: "int" "netbsd32_caddr_t" "int" "int" */
#define	NETBSD32_SYS_compat_43_netbsd32_orecv	102

/* syscall: "compat_13_sigreturn13" ret: "int" args: "netbsd32_sigcontextp_t" */
#define	NETBSD32_SYS_compat_13_sigreturn13	103

/* syscall: "netbsd32_bind" ret: "int" args: "int" "netbsd32_sockaddrp_t" "int" */
#define	NETBSD32_SYS_netbsd32_bind	104

/* syscall: "netbsd32_setsockopt" ret: "int" args: "int" "int" "int" "netbsd32_voidp" "int" */
#define	NETBSD32_SYS_netbsd32_setsockopt	105

/* syscall: "netbsd32_listen" ret: "int" args: "int" "int" */
#define	NETBSD32_SYS_netbsd32_listen	106

				/* 107 is obsolete vtimes */
/* syscall: "compat_43_netbsd32_osigvec" ret: "int" args: "int" "netbsd32_sigvecp_t" "netbsd32_sigvecp_t" */
#define	NETBSD32_SYS_compat_43_netbsd32_osigvec	108

/* syscall: "compat_43_netbsd32_sigblock" ret: "int" args: "int" */
#define	NETBSD32_SYS_compat_43_netbsd32_sigblock	109

/* syscall: "compat_43_netbsd32_sigsetmask" ret: "int" args: "int" */
#define	NETBSD32_SYS_compat_43_netbsd32_sigsetmask	110

/* syscall: "compat_13_sigsuspend13" ret: "int" args: "int" */
#define	NETBSD32_SYS_compat_13_sigsuspend13	111

/* syscall: "compat_43_netbsd32_osigstack" ret: "int" args: "netbsd32_sigstackp_t" "netbsd32_sigstackp_t" */
#define	NETBSD32_SYS_compat_43_netbsd32_osigstack	112

/* syscall: "compat_43_netbsd32_orecvmsg" ret: "int" args: "int" "netbsd32_omsghdrp_t" "int" */
#define	NETBSD32_SYS_compat_43_netbsd32_orecvmsg	113

/* syscall: "compat_43_netbsd32_osendmsg" ret: "int" args: "int" "netbsd32_caddr_t" "int" */
#define	NETBSD32_SYS_compat_43_netbsd32_osendmsg	114

				/* 115 is obsolete vtrace */
/* syscall: "netbsd32_gettimeofday" ret: "int" args: "netbsd32_timevalp_t" "netbsd32_timezonep_t" */
#define	NETBSD32_SYS_netbsd32_gettimeofday	116

/* syscall: "netbsd32_getrusage" ret: "int" args: "int" "netbsd32_rusagep_t" */
#define	NETBSD32_SYS_netbsd32_getrusage	117

/* syscall: "netbsd32_getsockopt" ret: "int" args: "int" "int" "int" "netbsd32_voidp" "netbsd32_intp" */
#define	NETBSD32_SYS_netbsd32_getsockopt	118

				/* 119 is obsolete resuba */
/* syscall: "netbsd32_readv" ret: "netbsd32_ssize_t" args: "int" "netbsd32_iovecp_t" "int" */
#define	NETBSD32_SYS_netbsd32_readv	120

/* syscall: "netbsd32_writev" ret: "netbsd32_ssize_t" args: "int" "netbsd32_iovecp_t" "int" */
#define	NETBSD32_SYS_netbsd32_writev	121

/* syscall: "netbsd32_settimeofday" ret: "int" args: "netbsd32_timevalp_t" "netbsd32_timezonep_t" */
#define	NETBSD32_SYS_netbsd32_settimeofday	122

/* syscall: "netbsd32_fchown" ret: "int" args: "int" "uid_t" "gid_t" */
#define	NETBSD32_SYS_netbsd32_fchown	123

/* syscall: "netbsd32_fchmod" ret: "int" args: "int" "mode_t" */
#define	NETBSD32_SYS_netbsd32_fchmod	124

/* syscall: "compat_43_netbsd32_orecvfrom" ret: "int" args: "int" "netbsd32_caddr_t" "netbsd32_size_t" "int" "netbsd32_caddr_t" "netbsd32_intp" */
#define	NETBSD32_SYS_compat_43_netbsd32_orecvfrom	125

/* syscall: "netbsd32_setreuid" ret: "int" args: "uid_t" "uid_t" */
#define	NETBSD32_SYS_netbsd32_setreuid	126

/* syscall: "netbsd32_setregid" ret: "int" args: "gid_t" "gid_t" */
#define	NETBSD32_SYS_netbsd32_setregid	127

/* syscall: "netbsd32_rename" ret: "int" args: "netbsd32_charp" "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_rename	128

/* syscall: "compat_43_netbsd32_otruncate" ret: "int" args: "netbsd32_charp" "netbsd32_long" */
#define	NETBSD32_SYS_compat_43_netbsd32_otruncate	129

/* syscall: "compat_43_netbsd32_oftruncate" ret: "int" args: "int" "netbsd32_long" */
#define	NETBSD32_SYS_compat_43_netbsd32_oftruncate	130

/* syscall: "netbsd32_flock" ret: "int" args: "int" "int" */
#define	NETBSD32_SYS_netbsd32_flock	131

/* syscall: "netbsd32_mkfifo" ret: "int" args: "netbsd32_charp" "mode_t" */
#define	NETBSD32_SYS_netbsd32_mkfifo	132

/* syscall: "netbsd32_sendto" ret: "netbsd32_ssize_t" args: "int" "netbsd32_voidp" "netbsd32_size_t" "int" "netbsd32_sockaddrp_t" "int" */
#define	NETBSD32_SYS_netbsd32_sendto	133

/* syscall: "netbsd32_shutdown" ret: "int" args: "int" "int" */
#define	NETBSD32_SYS_netbsd32_shutdown	134

/* syscall: "netbsd32_socketpair" ret: "int" args: "int" "int" "int" "netbsd32_intp" */
#define	NETBSD32_SYS_netbsd32_socketpair	135

/* syscall: "netbsd32_mkdir" ret: "int" args: "netbsd32_charp" "mode_t" */
#define	NETBSD32_SYS_netbsd32_mkdir	136

/* syscall: "netbsd32_rmdir" ret: "int" args: "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_rmdir	137

/* syscall: "netbsd32_utimes" ret: "int" args: "netbsd32_charp" "netbsd32_timevalp_t" */
#define	NETBSD32_SYS_netbsd32_utimes	138

				/* 139 is obsolete 4.2 sigreturn */
/* syscall: "netbsd32_adjtime" ret: "int" args: "netbsd32_timevalp_t" "netbsd32_timevalp_t" */
#define	NETBSD32_SYS_netbsd32_adjtime	140

/* syscall: "compat_43_netbsd32_ogetpeername" ret: "int" args: "int" "netbsd32_caddr_t" "netbsd32_intp" */
#define	NETBSD32_SYS_compat_43_netbsd32_ogetpeername	141

/* syscall: "compat_43_ogethostid" ret: "int32_t" args: */
#define	NETBSD32_SYS_compat_43_ogethostid	142

/* syscall: "compat_43_netbsd32_sethostid" ret: "int" args: "int32_t" */
#define	NETBSD32_SYS_compat_43_netbsd32_sethostid	143

/* syscall: "compat_43_netbsd32_ogetrlimit" ret: "int" args: "int" "netbsd32_orlimitp_t" */
#define	NETBSD32_SYS_compat_43_netbsd32_ogetrlimit	144

/* syscall: "compat_43_netbsd32_osetrlimit" ret: "int" args: "int" "netbsd32_orlimitp_t" */
#define	NETBSD32_SYS_compat_43_netbsd32_osetrlimit	145

/* syscall: "compat_43_netbsd32_killpg" ret: "int" args: "int" "int" */
#define	NETBSD32_SYS_compat_43_netbsd32_killpg	146

/* syscall: "setsid" ret: "int" args: */
#define	NETBSD32_SYS_setsid	147

/* syscall: "netbsd32_quotactl" ret: "int" args: "netbsd32_charp" "int" "int" "netbsd32_caddr_t" */
#define	NETBSD32_SYS_netbsd32_quotactl	148

/* syscall: "compat_43_oquota" ret: "int" args: */
#define	NETBSD32_SYS_compat_43_oquota	149

/* syscall: "compat_43_netbsd32_ogetsockname" ret: "int" args: "int" "netbsd32_caddr_t" "netbsd32_intp" */
#define	NETBSD32_SYS_compat_43_netbsd32_ogetsockname	150

#if defined(NFS) || defined(NFSSERVER) || !defined(_KERNEL)
/* syscall: "netbsd32_nfssvc" ret: "int" args: "int" "netbsd32_voidp" */
#define	NETBSD32_SYS_netbsd32_nfssvc	155

#else
				/* 155 is excluded netbsd32_nfssvc */
#endif
/* syscall: "compat_43_netbsd32_ogetdirentries" ret: "int" args: "int" "netbsd32_charp" "u_int" "netbsd32_longp" */
#define	NETBSD32_SYS_compat_43_netbsd32_ogetdirentries	156

/* syscall: "compat_20_netbsd32_statfs" ret: "int" args: "netbsd32_charp" "netbsd32_statfsp_t" */
#define	NETBSD32_SYS_compat_20_netbsd32_statfs	157

/* syscall: "compat_20_netbsd32_fstatfs" ret: "int" args: "int" "netbsd32_statfsp_t" */
#define	NETBSD32_SYS_compat_20_netbsd32_fstatfs	158

/* syscall: "compat_30_netbsd32_getfh" ret: "int" args: "netbsd32_charp" "netbsd32_compat_30_fhandlep_t" */
#define	NETBSD32_SYS_compat_30_netbsd32_getfh	161

/* syscall: "compat_09_netbsd32_ogetdomainname" ret: "int" args: "netbsd32_charp" "int" */
#define	NETBSD32_SYS_compat_09_netbsd32_ogetdomainname	162

/* syscall: "compat_09_netbsd32_osetdomainname" ret: "int" args: "netbsd32_charp" "int" */
#define	NETBSD32_SYS_compat_09_netbsd32_osetdomainname	163

/* syscall: "compat_09_netbsd32_uname" ret: "int" args: "netbsd32_outsnamep_t" */
#define	NETBSD32_SYS_compat_09_netbsd32_uname	164

/* syscall: "netbsd32_sysarch" ret: "int" args: "int" "netbsd32_voidp" */
#define	NETBSD32_SYS_netbsd32_sysarch	165

#if defined(SYSVSEM) || !defined(_KERNEL)
/* syscall: "compat_10_osemsys" ret: "int" args: "int" "int" "int" "int" "int" */
#define	NETBSD32_SYS_compat_10_osemsys	169

#else
				/* 169 is excluded netbsd32_sys_semsys */
#endif
#if defined(SYSVMSG) || !defined(_KERNEL)
/* syscall: "compat_10_omsgsys" ret: "int" args: "int" "int" "int" "int" "int" "int" */
#define	NETBSD32_SYS_compat_10_omsgsys	170

#else
				/* 170 is excluded netbsd32_sys_msgsys */
#endif
#if defined(SYSVSHM) || !defined(_KERNEL)
/* syscall: "compat_10_oshmsys" ret: "int" args: "int" "int" "int" "int" */
#define	NETBSD32_SYS_compat_10_oshmsys	171

#else
				/* 171 is excluded netbsd32_sys_shmsys */
#endif
/* syscall: "netbsd32_pread" ret: "netbsd32_ssize_t" args: "int" "netbsd32_voidp" "netbsd32_size_t" "int" "off_t" */
#define	NETBSD32_SYS_netbsd32_pread	173

/* syscall: "netbsd32_pwrite" ret: "netbsd32_ssize_t" args: "int" "netbsd32_voidp" "netbsd32_size_t" "int" "off_t" */
#define	NETBSD32_SYS_netbsd32_pwrite	174

/* syscall: "compat_30_netbsd32_ntp_gettime" ret: "int" args: "netbsd32_ntptimevalp_t" */
#define	NETBSD32_SYS_compat_30_netbsd32_ntp_gettime	175

/* syscall: "netbsd32_ntp_adjtime" ret: "int" args: "netbsd32_timexp_t" */
#define	NETBSD32_SYS_netbsd32_ntp_adjtime	176

/* syscall: "netbsd32_setgid" ret: "int" args: "gid_t" */
#define	NETBSD32_SYS_netbsd32_setgid	181

/* syscall: "netbsd32_setegid" ret: "int" args: "gid_t" */
#define	NETBSD32_SYS_netbsd32_setegid	182

/* syscall: "netbsd32_seteuid" ret: "int" args: "uid_t" */
#define	NETBSD32_SYS_netbsd32_seteuid	183

#if defined(LFS) || !defined(_KERNEL)
/* syscall: "lfs_bmapv" ret: "int" args: "netbsd32_fsid_tp_t" "netbsd32_block_infop_t" "int" */
#define	NETBSD32_SYS_lfs_bmapv	184

/* syscall: "lfs_markv" ret: "int" args: "netbsd32_fsid_tp_t" "netbsd32_block_infop_t" "int" */
#define	NETBSD32_SYS_lfs_markv	185

/* syscall: "lfs_segclean" ret: "int" args: "netbsd32_fsid_tp_t" "netbsd32_u_long" */
#define	NETBSD32_SYS_lfs_segclean	186

/* syscall: "lfs_segwait" ret: "int" args: "netbsd32_fsid_tp_t" "netbsd32_timevalp_t" */
#define	NETBSD32_SYS_lfs_segwait	187

#else
				/* 184 is excluded netbsd32_sys_lfs_bmapv */
				/* 185 is excluded netbsd32_sys_lfs_markv */
				/* 186 is excluded netbsd32_sys_lfs_segclean */
				/* 187 is excluded netbsd32_sys_lfs_segwait */
#endif
/* syscall: "compat_12_netbsd32_stat12" ret: "int" args: "netbsd32_charp" "netbsd32_stat12p_t" */
#define	NETBSD32_SYS_compat_12_netbsd32_stat12	188

/* syscall: "compat_12_netbsd32_fstat12" ret: "int" args: "int" "netbsd32_stat12p_t" */
#define	NETBSD32_SYS_compat_12_netbsd32_fstat12	189

/* syscall: "compat_12_netbsd32_lstat12" ret: "int" args: "netbsd32_charp" "netbsd32_stat12p_t" */
#define	NETBSD32_SYS_compat_12_netbsd32_lstat12	190

/* syscall: "netbsd32_pathconf" ret: "netbsd32_long" args: "netbsd32_charp" "int" */
#define	NETBSD32_SYS_netbsd32_pathconf	191

/* syscall: "netbsd32_fpathconf" ret: "netbsd32_long" args: "int" "int" */
#define	NETBSD32_SYS_netbsd32_fpathconf	192

/* syscall: "netbsd32_getrlimit" ret: "int" args: "int" "netbsd32_rlimitp_t" */
#define	NETBSD32_SYS_netbsd32_getrlimit	194

/* syscall: "netbsd32_setrlimit" ret: "int" args: "int" "netbsd32_rlimitp_t" */
#define	NETBSD32_SYS_netbsd32_setrlimit	195

/* syscall: "compat_12_netbsd32_getdirentries" ret: "int" args: "int" "netbsd32_charp" "u_int" "netbsd32_longp" */
#define	NETBSD32_SYS_compat_12_netbsd32_getdirentries	196

/* syscall: "netbsd32_mmap" ret: "netbsd32_voidp" args: "netbsd32_voidp" "netbsd32_size_t" "int" "int" "int" "netbsd32_long" "off_t" */
#define	NETBSD32_SYS_netbsd32_mmap	197

/* syscall: "__syscall" ret: "quad_t" args: "quad_t" "..." */
#define	NETBSD32_SYS___syscall	198

/* syscall: "netbsd32_lseek" ret: "off_t" args: "int" "int" "off_t" "int" */
#define	NETBSD32_SYS_netbsd32_lseek	199

/* syscall: "netbsd32_truncate" ret: "int" args: "netbsd32_charp" "int" "off_t" */
#define	NETBSD32_SYS_netbsd32_truncate	200

/* syscall: "netbsd32_ftruncate" ret: "int" args: "int" "int" "off_t" */
#define	NETBSD32_SYS_netbsd32_ftruncate	201

/* syscall: "netbsd32___sysctl" ret: "int" args: "netbsd32_intp" "u_int" "netbsd32_voidp" "netbsd32_size_tp" "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32___sysctl	202

/* syscall: "netbsd32_mlock" ret: "int" args: "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_mlock	203

/* syscall: "netbsd32_munlock" ret: "int" args: "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_munlock	204

/* syscall: "netbsd32_undelete" ret: "int" args: "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_undelete	205

/* syscall: "netbsd32_futimes" ret: "int" args: "int" "netbsd32_timevalp_t" */
#define	NETBSD32_SYS_netbsd32_futimes	206

/* syscall: "netbsd32_getpgid" ret: "int" args: "pid_t" */
#define	NETBSD32_SYS_netbsd32_getpgid	207

/* syscall: "netbsd32_reboot" ret: "int" args: "int" "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_reboot	208

/* syscall: "netbsd32_poll" ret: "int" args: "netbsd32_pollfdp_t" "u_int" "int" */
#define	NETBSD32_SYS_netbsd32_poll	209

#if defined(LKM) || !defined(_KERNEL)
#else	/* !LKM || !_KERNEL */
				/* 210 is excluded lkmnosys */
				/* 211 is excluded lkmnosys */
				/* 212 is excluded lkmnosys */
				/* 213 is excluded lkmnosys */
				/* 214 is excluded lkmnosys */
				/* 215 is excluded lkmnosys */
				/* 216 is excluded lkmnosys */
				/* 217 is excluded lkmnosys */
				/* 218 is excluded lkmnosys */
				/* 219 is excluded lkmnosys */
#endif	/* !LKM || !_KERNEL */
#if defined(SYSVSEM) || !defined(_KERNEL)
/* syscall: "compat_14_netbsd32___semctl" ret: "int" args: "int" "int" "int" "netbsd32_semunu_t" */
#define	NETBSD32_SYS_compat_14_netbsd32___semctl	220

/* syscall: "netbsd32_semget" ret: "int" args: "netbsd32_key_t" "int" "int" */
#define	NETBSD32_SYS_netbsd32_semget	221

/* syscall: "netbsd32_semop" ret: "int" args: "int" "netbsd32_sembufp_t" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_semop	222

/* syscall: "netbsd32_semconfig" ret: "int" args: "int" */
#define	NETBSD32_SYS_netbsd32_semconfig	223

#else
				/* 220 is excluded compat_14_netbsd32_semctl */
				/* 221 is excluded netbsd32_semget */
				/* 222 is excluded netbsd32_semop */
				/* 223 is excluded netbsd32_semconfig */
#endif
#if defined(SYSVMSG) || !defined(_KERNEL)
/* syscall: "compat_14_netbsd32_msgctl" ret: "int" args: "int" "int" "netbsd32_msqid_dsp_t" */
#define	NETBSD32_SYS_compat_14_netbsd32_msgctl	224

/* syscall: "netbsd32_msgget" ret: "int" args: "netbsd32_key_t" "int" */
#define	NETBSD32_SYS_netbsd32_msgget	225

/* syscall: "netbsd32_msgsnd" ret: "int" args: "int" "netbsd32_voidp" "netbsd32_size_t" "int" */
#define	NETBSD32_SYS_netbsd32_msgsnd	226

/* syscall: "netbsd32_msgrcv" ret: "netbsd32_ssize_t" args: "int" "netbsd32_voidp" "netbsd32_size_t" "netbsd32_long" "int" */
#define	NETBSD32_SYS_netbsd32_msgrcv	227

#else
				/* 224 is excluded compat_14_netbsd32_msgctl */
				/* 225 is excluded netbsd32_msgget */
				/* 226 is excluded netbsd32_msgsnd */
				/* 227 is excluded netbsd32_msgrcv */
#endif
#if defined(SYSVSHM) || !defined(_KERNEL)
/* syscall: "netbsd32_shmat" ret: "netbsd32_voidp" args: "int" "netbsd32_voidp" "int" */
#define	NETBSD32_SYS_netbsd32_shmat	228

/* syscall: "compat_14_netbsd32_shmctl" ret: "int" args: "int" "int" "netbsd32_shmid_dsp_t" */
#define	NETBSD32_SYS_compat_14_netbsd32_shmctl	229

/* syscall: "netbsd32_shmdt" ret: "int" args: "netbsd32_voidp" */
#define	NETBSD32_SYS_netbsd32_shmdt	230

/* syscall: "netbsd32_shmget" ret: "int" args: "netbsd32_key_t" "netbsd32_size_t" "int" */
#define	NETBSD32_SYS_netbsd32_shmget	231

#else
				/* 228 is excluded netbsd32_shmat */
				/* 229 is excluded compat_14_netbsd32_shmctl */
				/* 230 is excluded netbsd32_shmdt */
				/* 231 is excluded netbsd32_shmget */
#endif
/* syscall: "netbsd32_clock_gettime" ret: "int" args: "netbsd32_clockid_t" "netbsd32_timespecp_t" */
#define	NETBSD32_SYS_netbsd32_clock_gettime	232

/* syscall: "netbsd32_clock_settime" ret: "int" args: "netbsd32_clockid_t" "netbsd32_timespecp_t" */
#define	NETBSD32_SYS_netbsd32_clock_settime	233

/* syscall: "netbsd32_clock_getres" ret: "int" args: "netbsd32_clockid_t" "netbsd32_timespecp_t" */
#define	NETBSD32_SYS_netbsd32_clock_getres	234

/* syscall: "netbsd32_timer_create" ret: "int" args: "netbsd32_clockid_t" "netbsd32_sigeventp_t" "netbsd32_timerp_t" */
#define	NETBSD32_SYS_netbsd32_timer_create	235

/* syscall: "netbsd32_timer_delete" ret: "int" args: "netbsd32_timer_t" */
#define	NETBSD32_SYS_netbsd32_timer_delete	236

/* syscall: "netbsd32_timer_settime" ret: "int" args: "netbsd32_timer_t" "int" "netbsd32_itimerspecp_t" "netbsd32_itimerspecp_t" */
#define	NETBSD32_SYS_netbsd32_timer_settime	237

/* syscall: "netbsd32_timer_gettime" ret: "int" args: "netbsd32_timer_t" "netbsd32_itimerspecp_t" */
#define	NETBSD32_SYS_netbsd32_timer_gettime	238

/* syscall: "netbsd32_timer_getoverrun" ret: "int" args: "netbsd32_timer_t" */
#define	NETBSD32_SYS_netbsd32_timer_getoverrun	239

/* syscall: "netbsd32_nanosleep" ret: "int" args: "netbsd32_timespecp_t" "netbsd32_timespecp_t" */
#define	NETBSD32_SYS_netbsd32_nanosleep	240

/* syscall: "netbsd32_fdatasync" ret: "int" args: "int" */
#define	NETBSD32_SYS_netbsd32_fdatasync	241

/* syscall: "netbsd32_mlockall" ret: "int" args: "int" */
#define	NETBSD32_SYS_netbsd32_mlockall	242

/* syscall: "munlockall" ret: "int" args: */
#define	NETBSD32_SYS_munlockall	243

/* syscall: "netbsd32___sigtimedwait" ret: "int" args: "netbsd32_sigsetp_t" "netbsd32_siginfop_t" "netbsd32_timespecp_t" */
#define	NETBSD32_SYS_netbsd32___sigtimedwait	244

#if defined(P1003_1B_SEMAPHORE) || (!defined(_KERNEL) && defined(_LIBC))
/* syscall: "netbsd32__ksem_init" ret: "int" args: "unsigned int" "netbsd32_semidp_t" */
#define	NETBSD32_SYS_netbsd32__ksem_init	247

/* syscall: "netbsd32__ksem_open" ret: "int" args: "netbsd32_charp" "int" "mode_t" "unsigned int" "netbsd32_semidp_t" */
#define	NETBSD32_SYS_netbsd32__ksem_open	248

/* syscall: "netbsd32__ksem_unlink" ret: "int" args: "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32__ksem_unlink	249

/* syscall: "netbsd32__ksem_close" ret: "int" args: "netbsd32_semid_t" */
#define	NETBSD32_SYS_netbsd32__ksem_close	250

/* syscall: "netbsd32__ksem_post" ret: "int" args: "netbsd32_semid_t" */
#define	NETBSD32_SYS_netbsd32__ksem_post	251

/* syscall: "netbsd32__ksem_wait" ret: "int" args: "netbsd32_semid_t" */
#define	NETBSD32_SYS_netbsd32__ksem_wait	252

/* syscall: "netbsd32__ksem_trywait" ret: "int" args: "netbsd32_semid_t" */
#define	NETBSD32_SYS_netbsd32__ksem_trywait	253

/* syscall: "netbsd32__ksem_getvalue" ret: "int" args: "netbsd32_semid_t" "netbsd32_intp" */
#define	NETBSD32_SYS_netbsd32__ksem_getvalue	254

/* syscall: "netbsd32__ksem_destroy" ret: "int" args: "netbsd32_semid_t" */
#define	NETBSD32_SYS_netbsd32__ksem_destroy	255

#else
				/* 247 is excluded sys__ksem_init */
				/* 248 is excluded sys__ksem_open */
				/* 249 is excluded sys__ksem_unlink */
				/* 250 is excluded sys__ksem_close */
				/* 251 is excluded sys__ksem_post */
				/* 252 is excluded sys__ksem_wait */
				/* 253 is excluded sys__ksem_trywait */
				/* 254 is excluded sys__ksem_getvalue */
				/* 255 is excluded sys__ksem_destroy */
#endif
/* syscall: "netbsd32___posix_rename" ret: "int" args: "netbsd32_charp" "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32___posix_rename	270

/* syscall: "netbsd32_swapctl" ret: "int" args: "int" "netbsd32_voidp" "int" */
#define	NETBSD32_SYS_netbsd32_swapctl	271

/* syscall: "compat_30_netbsd32_getdents" ret: "int" args: "int" "netbsd32_charp" "netbsd32_size_t" */
#define	NETBSD32_SYS_compat_30_netbsd32_getdents	272

/* syscall: "netbsd32_minherit" ret: "int" args: "netbsd32_voidp" "netbsd32_size_t" "int" */
#define	NETBSD32_SYS_netbsd32_minherit	273

/* syscall: "netbsd32_lchmod" ret: "int" args: "netbsd32_charp" "mode_t" */
#define	NETBSD32_SYS_netbsd32_lchmod	274

/* syscall: "netbsd32_lchown" ret: "int" args: "netbsd32_charp" "uid_t" "gid_t" */
#define	NETBSD32_SYS_netbsd32_lchown	275

/* syscall: "netbsd32_lutimes" ret: "int" args: "netbsd32_charp" "netbsd32_timevalp_t" */
#define	NETBSD32_SYS_netbsd32_lutimes	276

/* syscall: "netbsd32___msync13" ret: "int" args: "netbsd32_voidp" "netbsd32_size_t" "int" */
#define	NETBSD32_SYS_netbsd32___msync13	277

/* syscall: "compat_30_netbsd32___stat13" ret: "int" args: "netbsd32_charp" "netbsd32_stat13p_t" */
#define	NETBSD32_SYS_compat_30_netbsd32___stat13	278

/* syscall: "compat_30_netbsd32___fstat13" ret: "int" args: "int" "netbsd32_stat13p_t" */
#define	NETBSD32_SYS_compat_30_netbsd32___fstat13	279

/* syscall: "compat_30_netbsd32___lstat13" ret: "int" args: "netbsd32_charp" "netbsd32_stat13p_t" */
#define	NETBSD32_SYS_compat_30_netbsd32___lstat13	280

/* syscall: "netbsd32___sigaltstack14" ret: "int" args: "netbsd32_sigaltstackp_t" "netbsd32_sigaltstackp_t" */
#define	NETBSD32_SYS_netbsd32___sigaltstack14	281

/* syscall: "__vfork14" ret: "int" args: */
#define	NETBSD32_SYS___vfork14	282

/* syscall: "netbsd32___posix_chown" ret: "int" args: "netbsd32_charp" "uid_t" "gid_t" */
#define	NETBSD32_SYS_netbsd32___posix_chown	283

/* syscall: "netbsd32___posix_fchown" ret: "int" args: "int" "uid_t" "gid_t" */
#define	NETBSD32_SYS_netbsd32___posix_fchown	284

/* syscall: "netbsd32___posix_lchown" ret: "int" args: "netbsd32_charp" "uid_t" "gid_t" */
#define	NETBSD32_SYS_netbsd32___posix_lchown	285

/* syscall: "netbsd32_getsid" ret: "pid_t" args: "pid_t" */
#define	NETBSD32_SYS_netbsd32_getsid	286

/* syscall: "netbsd32___clone" ret: "int" args: "int" "netbsd32_voidp" */
#define	NETBSD32_SYS_netbsd32___clone	287

/* syscall: "netbsd32_fktrace" ret: "int" args: "int" "int" "int" "int" */
#define	NETBSD32_SYS_netbsd32_fktrace	288

/* syscall: "netbsd32_preadv" ret: "netbsd32_ssize_t" args: "int" "netbsd32_iovecp_t" "int" "int" "off_t" */
#define	NETBSD32_SYS_netbsd32_preadv	289

/* syscall: "netbsd32_pwritev" ret: "netbsd32_ssize_t" args: "int" "netbsd32_iovecp_t" "int" "int" "off_t" */
#define	NETBSD32_SYS_netbsd32_pwritev	290

/* syscall: "netbsd32___sigaction14" ret: "int" args: "int" "netbsd32_sigactionp_t" "netbsd32_sigactionp_t" */
#define	NETBSD32_SYS_netbsd32___sigaction14	291

/* syscall: "netbsd32___sigpending14" ret: "int" args: "netbsd32_sigsetp_t" */
#define	NETBSD32_SYS_netbsd32___sigpending14	292

/* syscall: "netbsd32___sigprocmask14" ret: "int" args: "int" "netbsd32_sigsetp_t" "netbsd32_sigsetp_t" */
#define	NETBSD32_SYS_netbsd32___sigprocmask14	293

/* syscall: "netbsd32___sigsuspend14" ret: "int" args: "netbsd32_sigsetp_t" */
#define	NETBSD32_SYS_netbsd32___sigsuspend14	294

/* syscall: "compat_16_netbsd32___sigreturn14" ret: "int" args: "netbsd32_sigcontextp_t" */
#define	NETBSD32_SYS_compat_16_netbsd32___sigreturn14	295

/* syscall: "netbsd32___getcwd" ret: "int" args: "netbsd32_charp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32___getcwd	296

/* syscall: "netbsd32_fchroot" ret: "int" args: "int" */
#define	NETBSD32_SYS_netbsd32_fchroot	297

/* syscall: "compat_30_netbsd32_fhopen" ret: "int" args: "netbsd32_fhandlep_t" "int" */
#define	NETBSD32_SYS_compat_30_netbsd32_fhopen	298

/* syscall: "compat_30_netbsd32_fhstat" ret: "int" args: "netbsd32_fhandlep_t" "netbsd32_stat13p_t" */
#define	NETBSD32_SYS_compat_30_netbsd32_fhstat	299

/* syscall: "compat_20_netbsd32_fhstatfs" ret: "int" args: "netbsd32_fhandlep_t" "netbsd32_statp_t" */
#define	NETBSD32_SYS_compat_20_netbsd32_fhstatfs	300

#if defined(SYSVSEM) || !defined(_KERNEL)
/* syscall: "netbsd32___semctl14" ret: "int" args: "int" "int" "int" "..." */
#define	NETBSD32_SYS_netbsd32___semctl14	301

#else
				/* 301 is excluded __semctl14 */
#endif
#if defined(SYSVMSG) || !defined(_KERNEL)
/* syscall: "netbsd32___msgctl13" ret: "int" args: "int" "int" "netbsd32_msqid_dsp_t" */
#define	NETBSD32_SYS_netbsd32___msgctl13	302

#else
				/* 302 is excluded __msgctl13 */
#endif
#if defined(SYSVSHM) || !defined(_KERNEL)
/* syscall: "netbsd32___shmctl13" ret: "int" args: "int" "int" "netbsd32_shmid_dsp_t" */
#define	NETBSD32_SYS_netbsd32___shmctl13	303

#else
				/* 303 is excluded __shmctl13 */
#endif
/* syscall: "netbsd32_lchflags" ret: "int" args: "netbsd32_charp" "netbsd32_u_long" */
#define	NETBSD32_SYS_netbsd32_lchflags	304

/* syscall: "issetugid" ret: "int" args: */
#define	NETBSD32_SYS_issetugid	305

/* syscall: "netbsd32_utrace" ret: "int" args: "netbsd32_charp" "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_utrace	306

/* syscall: "netbsd32_getcontext" ret: "int" args: "netbsd32_ucontextp" */
#define	NETBSD32_SYS_netbsd32_getcontext	307

/* syscall: "netbsd32_setcontext" ret: "int" args: "netbsd32_ucontextp" "uint32_t" "netbsd32_lwpidp" */
#define	NETBSD32_SYS_netbsd32_setcontext	308

/* syscall: "netbsd32__lwp_create" ret: "int" args: "netbsd32_ucontextp" "netbsd32_u_long" "netbsd32_lwpidp" */
#define	NETBSD32_SYS_netbsd32__lwp_create	309

/* syscall: "_lwp_exit" ret: "int" args: */
#define	NETBSD32_SYS__lwp_exit	310

/* syscall: "_lwp_self" ret: "lwpid_t" args: */
#define	NETBSD32_SYS__lwp_self	311

/* syscall: "netbsd32__lwp_wait" ret: "int" args: "lwpid_t" "netbsd32_lwpidp" */
#define	NETBSD32_SYS_netbsd32__lwp_wait	312

/* syscall: "netbsd32__lwp_suspend" ret: "int" args: "lwpid_t" */
#define	NETBSD32_SYS_netbsd32__lwp_suspend	313

/* syscall: "netbsd32__lwp_continue" ret: "int" args: "lwpid_t" */
#define	NETBSD32_SYS_netbsd32__lwp_continue	314

/* syscall: "netbsd32__lwp_wakeup" ret: "int" args: "lwpid_t" */
#define	NETBSD32_SYS_netbsd32__lwp_wakeup	315

/* syscall: "_lwp_getprivate" ret: "void *" args: */
#define	NETBSD32_SYS__lwp_getprivate	316

/* syscall: "netbsd32__lwp_setprivate" ret: "void" args: "netbsd32_voidp" */
#define	NETBSD32_SYS_netbsd32__lwp_setprivate	317

/* syscall: "netbsd32__lwp_kill" ret: "int" args: "lwpid_t" "int" */
#define	NETBSD32_SYS_netbsd32__lwp_kill	318

/* syscall: "netbsd32__lwp_detach" ret: "int" args: "lwpid_t" */
#define	NETBSD32_SYS_netbsd32__lwp_detach	319

/* syscall: "netbsd32__lwp_park" ret: "int" args: "netbsd32_timespecp_t" "lwpid_t" "netbsd32_voidp" "netbsd32_voidp" */
#define	NETBSD32_SYS_netbsd32__lwp_park	320

/* syscall: "netbsd32__lwp_unpark" ret: "int" args: "lwpid_t" "netbsd32_voidp" */
#define	NETBSD32_SYS_netbsd32__lwp_unpark	321

/* syscall: "netbsd32__lwp_unpark_all" ret: "netbsd32_size_t" args: "netbsd32_lwpidp" "netbsd32_size_t" "netbsd32_voidp" */
#define	NETBSD32_SYS_netbsd32__lwp_unpark_all	322

/* syscall: "netbsd32__lwp_setname" ret: "int" args: "lwpid_t" "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32__lwp_setname	323

/* syscall: "netbsd32__lwp_getname" ret: "int" args: "lwpid_t" "netbsd32_charp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32__lwp_getname	324

/* syscall: "netbsd32__lwp_ctl" ret: "int" args: "int" "netbsd32_pointer_t" */
#define	NETBSD32_SYS_netbsd32__lwp_ctl	325

				/* 330 is obsolete netbsd32_sa_register */
				/* 331 is obsolete netbsd32_sa_stacks */
				/* 332 is obsolete sys_sa_enable */
				/* 333 is obsolete netbsd32_sa_setconcurrency */
				/* 334 is obsolete sys_sa_yield */
				/* 335 is obsolete netbsd32_sa_preempt */
				/* 336 is obsolete sys_sa_unblockyield */
/* syscall: "netbsd32___sigaction_sigtramp" ret: "int" args: "int" "netbsd32_sigactionp_t" "netbsd32_sigactionp_t" "netbsd32_voidp" "int" */
#define	NETBSD32_SYS_netbsd32___sigaction_sigtramp	340

/* syscall: "netbsd32_rasctl" ret: "int" args: "netbsd32_caddr_t" "netbsd32_size_t" "int" */
#define	NETBSD32_SYS_netbsd32_rasctl	343

/* syscall: "kqueue" ret: "int" args: */
#define	NETBSD32_SYS_kqueue	344

/* syscall: "netbsd32_kevent" ret: "int" args: "int" "netbsd32_keventp_t" "netbsd32_size_t" "netbsd32_keventp_t" "netbsd32_size_t" "netbsd32_timespecp_t" */
#define	NETBSD32_SYS_netbsd32_kevent	345

/* syscall: "sched_yield" ret: "int" args: */
#define	NETBSD32_SYS_sched_yield	350

/* syscall: "netbsd32_fsync_range" ret: "int" args: "int" "int" "off_t" "off_t" */
#define	NETBSD32_SYS_netbsd32_fsync_range	354

/* syscall: "netbsd32_uuidgen" ret: "int" args: "netbsd32_uuidp_t" "int" */
#define	NETBSD32_SYS_netbsd32_uuidgen	355

/* syscall: "netbsd32_getvfsstat" ret: "int" args: "netbsd32_statvfsp_t" "netbsd32_size_t" "int" */
#define	NETBSD32_SYS_netbsd32_getvfsstat	356

/* syscall: "netbsd32_statvfs1" ret: "int" args: "netbsd32_charp" "netbsd32_statvfsp_t" "int" */
#define	NETBSD32_SYS_netbsd32_statvfs1	357

/* syscall: "netbsd32_fstatvfs1" ret: "int" args: "int" "netbsd32_statvfsp_t" "int" */
#define	NETBSD32_SYS_netbsd32_fstatvfs1	358

/* syscall: "compat_30_netbsd32_fhstatvfs1" ret: "int" args: "netbsd32_fhandlep_t" "netbsd32_statvfsp_t" "int" */
#define	NETBSD32_SYS_compat_30_netbsd32_fhstatvfs1	359

/* syscall: "netbsd32_extattrctl" ret: "int" args: "netbsd32_charp" "int" "netbsd32_charp" "int" "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_extattrctl	360

/* syscall: "netbsd32_extattr_set_file" ret: "int" args: "netbsd32_charp" "int" "netbsd32_charp" "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_extattr_set_file	361

/* syscall: "netbsd32_extattr_get_file" ret: "int" args: "netbsd32_charp" "int" "netbsd32_charp" "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_extattr_get_file	362

/* syscall: "netbsd32_extattr_delete_file" ret: "int" args: "netbsd32_charp" "int" "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_extattr_delete_file	363

/* syscall: "netbsd32_extattr_set_fd" ret: "int" args: "int" "int" "netbsd32_charp" "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_extattr_set_fd	364

/* syscall: "netbsd32_extattr_get_fd" ret: "int" args: "int" "int" "netbsd32_charp" "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_extattr_get_fd	365

/* syscall: "netbsd32_extattr_delete_fd" ret: "int" args: "int" "int" "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_extattr_delete_fd	366

/* syscall: "netbsd32_extattr_set_link" ret: "int" args: "netbsd32_charp" "int" "netbsd32_charp" "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_extattr_set_link	367

/* syscall: "netbsd32_extattr_get_link" ret: "int" args: "netbsd32_charp" "int" "netbsd32_charp" "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_extattr_get_link	368

/* syscall: "netbsd32_extattr_delete_link" ret: "int" args: "netbsd32_charp" "int" "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_extattr_delete_link	369

/* syscall: "netbsd32_extattr_list_fd" ret: "int" args: "int" "int" "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_extattr_list_fd	370

/* syscall: "netbsd32_extattr_list_file" ret: "int" args: "netbsd32_charp" "int" "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_extattr_list_file	371

/* syscall: "netbsd32_extattr_list_link" ret: "int" args: "netbsd32_charp" "int" "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_extattr_list_link	372

/* syscall: "netbsd32_pselect" ret: "int" args: "int" "netbsd32_fd_setp_t" "netbsd32_fd_setp_t" "netbsd32_fd_setp_t" "netbsd32_timespecp_t" "netbsd32_sigsetp_t" */
#define	NETBSD32_SYS_netbsd32_pselect	373

/* syscall: "netbsd32_pollts" ret: "int" args: "netbsd32_pollfdp_t" "u_int" "netbsd32_timespecp_t" "netbsd32_sigsetp_t" */
#define	NETBSD32_SYS_netbsd32_pollts	374

/* syscall: "netbsd32_setxattr" ret: "int" args: "netbsd32_charp" "netbsd32_charp" "netbsd32_voidp" "netbsd32_size_t" "int" */
#define	NETBSD32_SYS_netbsd32_setxattr	375

/* syscall: "netbsd32_lsetxattr" ret: "int" args: "netbsd32_charp" "netbsd32_charp" "netbsd32_voidp" "netbsd32_size_t" "int" */
#define	NETBSD32_SYS_netbsd32_lsetxattr	376

/* syscall: "netbsd32_fsetxattr" ret: "int" args: "int" "netbsd32_charp" "netbsd32_voidp" "netbsd32_size_t" "int" */
#define	NETBSD32_SYS_netbsd32_fsetxattr	377

/* syscall: "netbsd32_getxattr" ret: "int" args: "netbsd32_charp" "netbsd32_charp" "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_getxattr	378

/* syscall: "netbsd32_lgetxattr" ret: "int" args: "netbsd32_charp" "netbsd32_charp" "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_lgetxattr	379

/* syscall: "netbsd32_fgetxattr" ret: "int" args: "int" "netbsd32_charp" "netbsd32_voidp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_fgetxattr	380

/* syscall: "netbsd32_listxattr" ret: "int" args: "netbsd32_charp" "netbsd32_charp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_listxattr	381

/* syscall: "netbsd32_llistxattr" ret: "int" args: "netbsd32_charp" "netbsd32_charp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_llistxattr	382

/* syscall: "netbsd32_flistxattr" ret: "int" args: "int" "netbsd32_charp" "netbsd32_size_t" */
#define	NETBSD32_SYS_netbsd32_flistxattr	383

/* syscall: "netbsd32_removexattr" ret: "int" args: "netbsd32_charp" "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_removexattr	384

/* syscall: "netbsd32_lremovexattr" ret: "int" args: "netbsd32_charp" "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_lremovexattr	385

/* syscall: "netbsd32_fremovexattr" ret: "int" args: "int" "netbsd32_charp" */
#define	NETBSD32_SYS_netbsd32_fremovexattr	386

/* syscall: "__stat30" ret: "int" args: "netbsd32_charp" "netbsd32_statp_t" */
#define	NETBSD32_SYS___stat30	387

/* syscall: "__fstat30" ret: "int" args: "int" "netbsd32_statp_t" */
#define	NETBSD32_SYS___fstat30	388

/* syscall: "__lstat30" ret: "int" args: "netbsd32_charp" "netbsd32_statp_t" */
#define	NETBSD32_SYS___lstat30	389

/* syscall: "__getdents30" ret: "int" args: "int" "netbsd32_charp" "netbsd32_size_t" */
#define	NETBSD32_SYS___getdents30	390

/* syscall: "posix_fadvise" ret: "int" args: "int" "off_t" "off_t" "int" */
#define	NETBSD32_SYS_posix_fadvise	391

/* syscall: "compat_30___fhstat30" ret: "int" args: "netbsd32_fhandlep_t" "netbsd32_statp_t" */
#define	NETBSD32_SYS_compat_30___fhstat30	392

/* syscall: "netbsd32_ntp_gettime" ret: "int" args: "netbsd32_ntptimevalp_t" */
#define	NETBSD32_SYS_netbsd32_ntp_gettime	393

/* syscall: "__socket30" ret: "int" args: "int" "int" "int" */
#define	NETBSD32_SYS___socket30	394

/* syscall: "netbsd32___getfh30" ret: "int" args: "netbsd32_charp" "netbsd32_pointer_t" "netbsd32_size_tp" */
#define	NETBSD32_SYS_netbsd32___getfh30	395

/* syscall: "netbsd32___fhopen40" ret: "int" args: "netbsd32_pointer_t" "netbsd32_size_t" "int" */
#define	NETBSD32_SYS_netbsd32___fhopen40	396

/* syscall: "netbsd32___fhstatvfs140" ret: "int" args: "netbsd32_pointer_t" "netbsd32_size_t" "netbsd32_statvfsp_t" "int" */
#define	NETBSD32_SYS_netbsd32___fhstatvfs140	397

/* syscall: "netbsd32___fhstat40" ret: "int" args: "netbsd32_pointer_t" "netbsd32_size_t" "netbsd32_statp_t" */
#define	NETBSD32_SYS_netbsd32___fhstat40	398

/* syscall: "netbsd32_mremap" ret: "netbsd32_voidp" args: "netbsd32_voidp" "netbsd32_size_t" "netbsd32_voidp" "netbsd32_size_t" "int" */
#define	NETBSD32_SYS_netbsd32_mremap	411

#define	NETBSD32_SYS_MAXSYSCALL	412
#define	NETBSD32_SYS_NSYSENT	512
#endif /* _NETBSD32_SYS_SYSCALL_H_ */
