/* $NetBSD: netbsd32_sysent.c,v 1.110 2015/03/07 16:41:53 christos Exp $ */

/*
 * System call switch table.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from	NetBSD: syscalls.master,v 1.102 2015/02/25 13:16:33 christos Exp
 */

#include <sys/cdefs.h>
__KERNEL_RCSID(0, "$NetBSD: netbsd32_sysent.c,v 1.110 2015/03/07 16:41:53 christos Exp $");

#if defined(_KERNEL_OPT)
#include "opt_compat_netbsd.h"
#include "opt_ntp.h"
#include "opt_sysv.h"
#include "opt_compat_43.h"
#endif
#include <sys/param.h>
#include <sys/systm.h>
#include <sys/signal.h>
#include <sys/mount.h>
#include <sys/syscallargs.h>
#include <compat/netbsd32/netbsd32.h>
#include <compat/netbsd32/netbsd32_syscallargs.h>

#ifdef COMPAT_43
#define	compat_43(func) __CONCAT(compat_43_,func)
#else
#define	compat_43(func) sys_nosys
#endif

#ifdef COMPAT_09
#define	compat_09(func) __CONCAT(compat_09_,func)
#else
#define	compat_09(func) sys_nosys
#endif

#ifdef COMPAT_10
#define	compat_10(func) __CONCAT(compat_10_,func)
#else
#define	compat_10(func) sys_nosys
#endif

#ifdef COMPAT_11
#define	compat_11(func) __CONCAT(compat_11_,func)
#else
#define	compat_11(func) sys_nosys
#endif

#ifdef COMPAT_12
#define	compat_12(func) __CONCAT(compat_12_,func)
#else
#define	compat_12(func) sys_nosys
#endif

#ifdef COMPAT_13
#define	compat_13(func) __CONCAT(compat_13_,func)
#else
#define	compat_13(func) sys_nosys
#endif

#ifdef COMPAT_14
#define	compat_14(func) __CONCAT(compat_14_,func)
#else
#define	compat_14(func) sys_nosys
#endif

#ifdef COMPAT_15
#define	compat_15(func) __CONCAT(compat_15_,func)
#else
#define	compat_15(func) sys_nosys
#endif

#ifdef COMPAT_16
#define	compat_16(func) __CONCAT(compat_16_,func)
#else
#define	compat_16(func) sys_nosys
#endif

#ifdef COMPAT_20
#define	compat_20(func) __CONCAT(compat_20_,func)
#else
#define	compat_20(func) sys_nosys
#endif

#ifdef COMPAT_30
#define	compat_30(func) __CONCAT(compat_30_,func)
#else
#define	compat_30(func) sys_nosys
#endif

#ifdef COMPAT_40
#define	compat_40(func) __CONCAT(compat_40_,func)
#else
#define	compat_40(func) sys_nosys
#endif

#ifdef COMPAT_50
#define	compat_50(func) __CONCAT(compat_50_,func)
#else
#define	compat_50(func) sys_nosys
#endif

#ifdef COMPAT_60
#define	compat_60(func) __CONCAT(compat_60_,func)
#else
#define	compat_60(func) sys_nosys
#endif

#ifdef COMPAT_70
#define	compat_70(func) __CONCAT(compat_70_,func)
#else
#define	compat_70(func) sys_nosys
#endif

#define	s(type)	sizeof(type)
#define	n(type)	(sizeof(type)/sizeof (register32_t))
#define	ns(type)	n(type), s(type)

struct sysent netbsd32_sysent[] = {
	{ ns(struct netbsd32_syscall_args), SYCALL_INDIRECT,
	    (sy_call_t *)netbsd32_syscall, 0, 0 },	/* 0 = netbsd32_syscall */
	{ ns(struct netbsd32_exit_args), 0,
	    (sy_call_t *)netbsd32_exit, 0, 0 },	/* 1 = netbsd32_exit */
	{ 0, 0, 0,
	    (sy_call_t *)sys_fork, 0, 0 },		/* 2 = fork */
	{ ns(struct netbsd32_read_args), 0,
	    (sy_call_t *)netbsd32_read, 0, 0 },	/* 3 = netbsd32_read */
	{ ns(struct netbsd32_write_args), 0,
	    (sy_call_t *)netbsd32_write, 0, 0 },	/* 4 = netbsd32_write */
	{ ns(struct netbsd32_open_args), 0,
	    (sy_call_t *)netbsd32_open, 0, 0 },	/* 5 = netbsd32_open */
	{ ns(struct netbsd32_close_args), 0,
	    (sy_call_t *)netbsd32_close, 0, 0 },	/* 6 = netbsd32_close */
	{ ns(struct compat_50_netbsd32_wait4_args), 0,
	    (sy_call_t *)compat_50(netbsd32_wait4), 0, 0 },/* 7 = compat_50_netbsd32_wait4 */
	{ ns(struct compat_43_netbsd32_ocreat_args), 0,
	    (sy_call_t *)compat_43(netbsd32_ocreat), 0, 0 },/* 8 = compat_43_netbsd32_ocreat */
	{ ns(struct netbsd32_link_args), 0,
	    (sy_call_t *)netbsd32_link, 0, 0 },	/* 9 = netbsd32_link */
	{ ns(struct netbsd32_unlink_args), 0,
	    (sy_call_t *)netbsd32_unlink, 0, 0 },	/* 10 = netbsd32_unlink */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 11 = obsolete execv */
	{ ns(struct netbsd32_chdir_args), 0,
	    (sy_call_t *)netbsd32_chdir, 0, 0 },	/* 12 = netbsd32_chdir */
	{ ns(struct netbsd32_fchdir_args), 0,
	    (sy_call_t *)netbsd32_fchdir, 0, 0 },	/* 13 = netbsd32_fchdir */
	{ ns(struct compat_50_netbsd32_mknod_args), 0,
	    (sy_call_t *)compat_50(netbsd32_mknod), 0, 0 },/* 14 = compat_50_netbsd32_mknod */
	{ ns(struct netbsd32_chmod_args), 0,
	    (sy_call_t *)netbsd32_chmod, 0, 0 },	/* 15 = netbsd32_chmod */
	{ ns(struct netbsd32_chown_args), 0,
	    (sy_call_t *)netbsd32_chown, 0, 0 },	/* 16 = netbsd32_chown */
	{ ns(struct netbsd32_break_args), 0,
	    (sy_call_t *)netbsd32_break, 0, 0 },	/* 17 = netbsd32_break */
	{ ns(struct compat_20_netbsd32_getfsstat_args), 0,
	    (sy_call_t *)compat_20(netbsd32_getfsstat), 0, 0 },/* 18 = compat_20_netbsd32_getfsstat */
	{ ns(struct compat_43_netbsd32_olseek_args), 0,
	    (sy_call_t *)compat_43(netbsd32_olseek), 0, 0 },/* 19 = compat_43_netbsd32_olseek */
	{ 0, 0, 0,
	    (sy_call_t *)sys_getpid, 0, 0 },		/* 20 = getpid */
	{ ns(struct netbsd32_mount_args), 0,
	    (sy_call_t *)netbsd32_mount, 0, 0 },	/* 21 = netbsd32_mount */
	{ ns(struct netbsd32_unmount_args), 0,
	    (sy_call_t *)netbsd32_unmount, 0, 0 },	/* 22 = netbsd32_unmount */
	{ ns(struct netbsd32_setuid_args), 0,
	    (sy_call_t *)netbsd32_setuid, 0, 0 },	/* 23 = netbsd32_setuid */
	{ 0, 0, 0,
	    (sy_call_t *)sys_getuid, 0, 0 },		/* 24 = getuid */
	{ 0, 0, 0,
	    (sy_call_t *)sys_geteuid, 0, 0 },		/* 25 = geteuid */
	{ ns(struct netbsd32_ptrace_args), 0,
	    (sy_call_t *)netbsd32_ptrace, 0, 0 },	/* 26 = netbsd32_ptrace */
	{ ns(struct netbsd32_recvmsg_args), 0,
	    (sy_call_t *)netbsd32_recvmsg, 0, 0 },	/* 27 = netbsd32_recvmsg */
	{ ns(struct netbsd32_sendmsg_args), 0,
	    (sy_call_t *)netbsd32_sendmsg, 0, 0 },	/* 28 = netbsd32_sendmsg */
	{ ns(struct netbsd32_recvfrom_args), 0,
	    (sy_call_t *)netbsd32_recvfrom, 0, 0 },	/* 29 = netbsd32_recvfrom */
	{ ns(struct netbsd32_accept_args), 0,
	    (sy_call_t *)netbsd32_accept, 0, 0 },	/* 30 = netbsd32_accept */
	{ ns(struct netbsd32_getpeername_args), 0,
	    (sy_call_t *)netbsd32_getpeername, 0, 0 },/* 31 = netbsd32_getpeername */
	{ ns(struct netbsd32_getsockname_args), 0,
	    (sy_call_t *)netbsd32_getsockname, 0, 0 },/* 32 = netbsd32_getsockname */
	{ ns(struct netbsd32_access_args), 0,
	    (sy_call_t *)netbsd32_access, 0, 0 },	/* 33 = netbsd32_access */
	{ ns(struct netbsd32_chflags_args), 0,
	    (sy_call_t *)netbsd32_chflags, 0, 0 },	/* 34 = netbsd32_chflags */
	{ ns(struct netbsd32_fchflags_args), 0,
	    (sy_call_t *)netbsd32_fchflags, 0, 0 },	/* 35 = netbsd32_fchflags */
	{ 0, 0, 0,
	    (sy_call_t *)sys_sync, 0, 0 },		/* 36 = sync */
	{ ns(struct netbsd32_kill_args), 0,
	    (sy_call_t *)netbsd32_kill, 0, 0 },	/* 37 = netbsd32_kill */
	{ ns(struct compat_43_netbsd32_stat43_args), 0,
	    (sy_call_t *)compat_43(netbsd32_stat43), 0, 0 },/* 38 = compat_43_netbsd32_stat43 */
	{ 0, 0, 0,
	    (sy_call_t *)sys_getppid, 0, 0 },		/* 39 = getppid */
	{ ns(struct compat_43_netbsd32_lstat43_args), 0,
	    (sy_call_t *)compat_43(netbsd32_lstat43), 0, 0 },/* 40 = compat_43_netbsd32_lstat43 */
	{ ns(struct netbsd32_dup_args), 0,
	    (sy_call_t *)netbsd32_dup, 0, 0 },	/* 41 = netbsd32_dup */
	{ 0, 0, 0,
	    (sy_call_t *)sys_pipe, 0, 0 },		/* 42 = pipe */
	{ 0, 0, 0,
	    (sy_call_t *)sys_getegid, 0, 0 },		/* 43 = getegid */
	{ ns(struct netbsd32_profil_args), 0,
	    (sy_call_t *)netbsd32_profil, 0, 0 },	/* 44 = netbsd32_profil */
	{ ns(struct netbsd32_ktrace_args), 0,
	    (sy_call_t *)netbsd32_ktrace, 0, 0 },	/* 45 = netbsd32_ktrace */
	{ ns(struct netbsd32_sigaction_args), 0,
	    (sy_call_t *)netbsd32_sigaction, 0, 0 },	/* 46 = netbsd32_sigaction */
	{ 0, 0, 0,
	    (sy_call_t *)sys_getgid, 0, 0 },		/* 47 = getgid */
	{ ns(struct compat_13_netbsd32_sigprocmask_args), 0,
	    (sy_call_t *)compat_13(netbsd32_sigprocmask), 0, 0 },/* 48 = compat_13_sigprocmask13 */
	{ ns(struct netbsd32___getlogin_args), 0,
	    (sy_call_t *)netbsd32___getlogin, 0, 0 },	/* 49 = netbsd32___getlogin */
	{ ns(struct netbsd32_setlogin_args), 0,
	    (sy_call_t *)netbsd32_setlogin, 0, 0 },	/* 50 = netbsd32_setlogin */
	{ ns(struct netbsd32_acct_args), 0,
	    (sy_call_t *)netbsd32_acct, 0, 0 },	/* 51 = netbsd32_acct */
	{ 0, 0, 0,
	    (sy_call_t *)compat_13(sys_sigpending), 0, 0 },/* 52 = compat_13_sigpending13 */
	{ ns(struct compat_13_netbsd32_sigaltstack13_args), 0,
	    (sy_call_t *)compat_13(netbsd32_sigaltstack13), 0, 0 },/* 53 = compat_13_netbsd32_sigaltstack13 */
	{ ns(struct netbsd32_ioctl_args), 0,
	    (sy_call_t *)netbsd32_ioctl, 0, 0 },	/* 54 = netbsd32_ioctl */
	{ ns(struct compat_12_netbsd32_reboot_args), 0,
	    (sy_call_t *)compat_12(netbsd32_reboot), 0, 0 },/* 55 = compat_12_netbsd32_reboot */
	{ ns(struct netbsd32_revoke_args), 0,
	    (sy_call_t *)netbsd32_revoke, 0, 0 },	/* 56 = netbsd32_revoke */
	{ ns(struct netbsd32_symlink_args), 0,
	    (sy_call_t *)netbsd32_symlink, 0, 0 },	/* 57 = netbsd32_symlink */
	{ ns(struct netbsd32_readlink_args), 0,
	    (sy_call_t *)netbsd32_readlink, 0, 0 },	/* 58 = netbsd32_readlink */
	{ ns(struct netbsd32_execve_args), 0,
	    (sy_call_t *)netbsd32_execve, 0, 0 },	/* 59 = netbsd32_execve */
	{ ns(struct netbsd32_umask_args), 0,
	    (sy_call_t *)netbsd32_umask, 0, 0 },	/* 60 = netbsd32_umask */
	{ ns(struct netbsd32_chroot_args), 0,
	    (sy_call_t *)netbsd32_chroot, 0, 0 },	/* 61 = netbsd32_chroot */
	{ ns(struct compat_43_netbsd32_fstat43_args), 0,
	    (sy_call_t *)compat_43(netbsd32_fstat43), 0, 0 },/* 62 = compat_43_netbsd32_fstat43 */
	{ ns(struct compat_43_netbsd32_ogetkerninfo_args), 0,
	    (sy_call_t *)compat_43(netbsd32_ogetkerninfo), 0, 0 },/* 63 = compat_43_netbsd32_ogetkerninfo */
	{ 0, 0, 0,
	    (sy_call_t *)compat_43(sys_getpagesize), 0, 0 },/* 64 = compat_43_ogetpagesize */
	{ ns(struct compat_12_netbsd32_msync_args), 0,
	    (sy_call_t *)compat_12(netbsd32_msync), 0, 0 },/* 65 = compat_12_netbsd32_msync */
	{ 0, 0, 0,
	    (sy_call_t *)sys_vfork, 0, 0 },		/* 66 = vfork */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 67 = obsolete vread */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 68 = obsolete vwrite */
	{ ns(struct netbsd32_sbrk_args), 0,
	    (sy_call_t *)netbsd32_sbrk, 0, 0 },	/* 69 = netbsd32_sbrk */
	{ ns(struct netbsd32_sstk_args), 0,
	    (sy_call_t *)netbsd32_sstk, 0, 0 },	/* 70 = netbsd32_sstk */
	{ ns(struct compat_43_netbsd32_ommap_args), 0,
	    (sy_call_t *)compat_43(netbsd32_ommap), 0, 0 },/* 71 = compat_43_netbsd32_ommap */
	{ ns(struct netbsd32_ovadvise_args), 0,
	    (sy_call_t *)netbsd32_ovadvise, 0, 0 },	/* 72 = vadvise */
	{ ns(struct netbsd32_munmap_args), 0,
	    (sy_call_t *)netbsd32_munmap, 0, 0 },	/* 73 = netbsd32_munmap */
	{ ns(struct netbsd32_mprotect_args), 0,
	    (sy_call_t *)netbsd32_mprotect, 0, 0 },	/* 74 = netbsd32_mprotect */
	{ ns(struct netbsd32_madvise_args), 0,
	    (sy_call_t *)netbsd32_madvise, 0, 0 },	/* 75 = netbsd32_madvise */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 76 = obsolete vhangup */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 77 = obsolete vlimit */
	{ ns(struct netbsd32_mincore_args), 0,
	    (sy_call_t *)netbsd32_mincore, 0, 0 },	/* 78 = netbsd32_mincore */
	{ ns(struct netbsd32_getgroups_args), 0,
	    (sy_call_t *)netbsd32_getgroups, 0, 0 },	/* 79 = netbsd32_getgroups */
	{ ns(struct netbsd32_setgroups_args), 0,
	    (sy_call_t *)netbsd32_setgroups, 0, 0 },	/* 80 = netbsd32_setgroups */
	{ 0, 0, 0,
	    (sy_call_t *)sys_getpgrp, 0, 0 },		/* 81 = getpgrp */
	{ ns(struct netbsd32_setpgid_args), 0,
	    (sy_call_t *)netbsd32_setpgid, 0, 0 },	/* 82 = netbsd32_setpgid */
	{ ns(struct compat_50_netbsd32_setitimer_args), 0,
	    (sy_call_t *)compat_50(netbsd32_setitimer), 0, 0 },/* 83 = compat_50_netbsd32_setitimer */
	{ 0, 0, 0,
	    (sy_call_t *)compat_43(sys_wait), 0, 0 },	/* 84 = compat_43_owait */
	{ ns(struct compat_12_netbsd32_oswapon_args), 0,
	    (sy_call_t *)compat_12(netbsd32_oswapon), 0, 0 },/* 85 = compat_12_netbsd32_oswapon */
	{ ns(struct compat_50_netbsd32_getitimer_args), 0,
	    (sy_call_t *)compat_50(netbsd32_getitimer), 0, 0 },/* 86 = compat_50_netbsd32_getitimer */
	{ ns(struct compat_43_netbsd32_ogethostname_args), 0,
	    (sy_call_t *)compat_43(netbsd32_ogethostname), 0, 0 },/* 87 = compat_43_netbsd32_ogethostname */
	{ ns(struct compat_43_netbsd32_osethostname_args), 0,
	    (sy_call_t *)compat_43(netbsd32_osethostname), 0, 0 },/* 88 = compat_43_netbsd32_osethostname */
	{ 0, 0, 0,
	    (sy_call_t *)compat_43(sys_getdtablesize), 0, 0 },/* 89 = compat_43_ogetdtablesize */
	{ ns(struct netbsd32_dup2_args), 0,
	    (sy_call_t *)netbsd32_dup2, 0, 0 },	/* 90 = netbsd32_dup2 */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 91 = unimplemented getdopt */
	{ ns(struct netbsd32_fcntl_args), 0,
	    (sy_call_t *)netbsd32_fcntl, 0, 0 },	/* 92 = netbsd32_fcntl */
	{ ns(struct compat_50_netbsd32_select_args), 0,
	    (sy_call_t *)compat_50(netbsd32_select), 0, 0 },/* 93 = compat_50_netbsd32_select */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 94 = unimplemented setdopt */
	{ ns(struct netbsd32_fsync_args), 0,
	    (sy_call_t *)netbsd32_fsync, 0, 0 },	/* 95 = netbsd32_fsync */
	{ ns(struct netbsd32_setpriority_args), 0,
	    (sy_call_t *)netbsd32_setpriority, 0, 0 },/* 96 = netbsd32_setpriority */
	{ ns(struct compat_30_netbsd32_socket_args), 0,
	    (sy_call_t *)compat_30(netbsd32_socket), 0, 0 },/* 97 = compat_30_netbsd32_socket */
	{ ns(struct netbsd32_connect_args), 0,
	    (sy_call_t *)netbsd32_connect, 0, 0 },	/* 98 = netbsd32_connect */
	{ ns(struct compat_43_netbsd32_oaccept_args), 0,
	    (sy_call_t *)compat_43(netbsd32_oaccept), 0, 0 },/* 99 = compat_43_netbsd32_oaccept */
	{ ns(struct netbsd32_getpriority_args), 0,
	    (sy_call_t *)netbsd32_getpriority, 0, 0 },/* 100 = netbsd32_getpriority */
	{ ns(struct compat_43_netbsd32_osend_args), 0,
	    (sy_call_t *)compat_43(netbsd32_osend), 0, 0 },/* 101 = compat_43_netbsd32_osend */
	{ ns(struct compat_43_netbsd32_orecv_args), 0,
	    (sy_call_t *)compat_43(netbsd32_orecv), 0, 0 },/* 102 = compat_43_netbsd32_orecv */
	{ ns(struct compat_13_netbsd32_sigreturn_args), 0,
	    (sy_call_t *)compat_13(netbsd32_sigreturn), 0, 0 },/* 103 = compat_13_sigreturn13 */
	{ ns(struct netbsd32_bind_args), 0,
	    (sy_call_t *)netbsd32_bind, 0, 0 },	/* 104 = netbsd32_bind */
	{ ns(struct netbsd32_setsockopt_args), 0,
	    (sy_call_t *)netbsd32_setsockopt, 0, 0 },	/* 105 = netbsd32_setsockopt */
	{ ns(struct netbsd32_listen_args), 0,
	    (sy_call_t *)netbsd32_listen, 0, 0 },	/* 106 = netbsd32_listen */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 107 = obsolete vtimes */
	{ ns(struct compat_43_netbsd32_osigvec_args), 0,
	    (sy_call_t *)compat_43(netbsd32_osigvec), 0, 0 },/* 108 = compat_43_netbsd32_osigvec */
	{ ns(struct compat_43_netbsd32_sigblock_args), 0,
	    (sy_call_t *)compat_43(netbsd32_sigblock), 0, 0 },/* 109 = compat_43_netbsd32_sigblock */
	{ ns(struct compat_43_netbsd32_sigsetmask_args), 0,
	    (sy_call_t *)compat_43(netbsd32_sigsetmask), 0, 0 },/* 110 = compat_43_netbsd32_sigsetmask */
	{ ns(struct compat_13_netbsd32_sigsuspend_args), 0,
	    (sy_call_t *)compat_13(netbsd32_sigsuspend), 0, 0 },/* 111 = compat_13_sigsuspend13 */
	{ ns(struct compat_43_netbsd32_osigstack_args), 0,
	    (sy_call_t *)compat_43(netbsd32_osigstack), 0, 0 },/* 112 = compat_43_netbsd32_osigstack */
	{ ns(struct compat_43_netbsd32_orecvmsg_args), 0,
	    (sy_call_t *)compat_43(netbsd32_orecvmsg), 0, 0 },/* 113 = compat_43_netbsd32_orecvmsg */
	{ ns(struct compat_43_netbsd32_osendmsg_args), 0,
	    (sy_call_t *)compat_43(netbsd32_osendmsg), 0, 0 },/* 114 = compat_43_netbsd32_osendmsg */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 115 = obsolete vtrace */
	{ ns(struct compat_50_netbsd32_gettimeofday_args), 0,
	    (sy_call_t *)compat_50(netbsd32_gettimeofday), 0, 0 },/* 116 = compat_50_netbsd32_gettimeofday */
	{ ns(struct compat_50_netbsd32_getrusage_args), 0,
	    (sy_call_t *)compat_50(netbsd32_getrusage), 0, 0 },/* 117 = compat_50_netbsd32_getrusage */
	{ ns(struct netbsd32_getsockopt_args), 0,
	    (sy_call_t *)netbsd32_getsockopt, 0, 0 },	/* 118 = netbsd32_getsockopt */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 119 = obsolete resuba */
	{ ns(struct netbsd32_readv_args), 0,
	    (sy_call_t *)netbsd32_readv, 0, 0 },	/* 120 = netbsd32_readv */
	{ ns(struct netbsd32_writev_args), 0,
	    (sy_call_t *)netbsd32_writev, 0, 0 },	/* 121 = netbsd32_writev */
	{ ns(struct compat_50_netbsd32_settimeofday_args), 0,
	    (sy_call_t *)compat_50(netbsd32_settimeofday), 0, 0 },/* 122 = compat_50_netbsd32_settimeofday */
	{ ns(struct netbsd32_fchown_args), 0,
	    (sy_call_t *)netbsd32_fchown, 0, 0 },	/* 123 = netbsd32_fchown */
	{ ns(struct netbsd32_fchmod_args), 0,
	    (sy_call_t *)netbsd32_fchmod, 0, 0 },	/* 124 = netbsd32_fchmod */
	{ ns(struct compat_43_netbsd32_orecvfrom_args), 0,
	    (sy_call_t *)compat_43(netbsd32_orecvfrom), 0, 0 },/* 125 = compat_43_netbsd32_orecvfrom */
	{ ns(struct netbsd32_setreuid_args), 0,
	    (sy_call_t *)netbsd32_setreuid, 0, 0 },	/* 126 = netbsd32_setreuid */
	{ ns(struct netbsd32_setregid_args), 0,
	    (sy_call_t *)netbsd32_setregid, 0, 0 },	/* 127 = netbsd32_setregid */
	{ ns(struct netbsd32_rename_args), 0,
	    (sy_call_t *)netbsd32_rename, 0, 0 },	/* 128 = netbsd32_rename */
	{ ns(struct compat_43_netbsd32_otruncate_args), 0,
	    (sy_call_t *)compat_43(netbsd32_otruncate), 0, 0 },/* 129 = compat_43_netbsd32_otruncate */
	{ ns(struct compat_43_netbsd32_oftruncate_args), 0,
	    (sy_call_t *)compat_43(netbsd32_oftruncate), 0, 0 },/* 130 = compat_43_netbsd32_oftruncate */
	{ ns(struct netbsd32_flock_args), 0,
	    (sy_call_t *)netbsd32_flock, 0, 0 },	/* 131 = netbsd32_flock */
	{ ns(struct netbsd32_mkfifo_args), 0,
	    (sy_call_t *)netbsd32_mkfifo, 0, 0 },	/* 132 = netbsd32_mkfifo */
	{ ns(struct netbsd32_sendto_args), 0,
	    (sy_call_t *)netbsd32_sendto, 0, 0 },	/* 133 = netbsd32_sendto */
	{ ns(struct netbsd32_shutdown_args), 0,
	    (sy_call_t *)netbsd32_shutdown, 0, 0 },	/* 134 = netbsd32_shutdown */
	{ ns(struct netbsd32_socketpair_args), 0,
	    (sy_call_t *)netbsd32_socketpair, 0, 0 },	/* 135 = netbsd32_socketpair */
	{ ns(struct netbsd32_mkdir_args), 0,
	    (sy_call_t *)netbsd32_mkdir, 0, 0 },	/* 136 = netbsd32_mkdir */
	{ ns(struct netbsd32_rmdir_args), 0,
	    (sy_call_t *)netbsd32_rmdir, 0, 0 },	/* 137 = netbsd32_rmdir */
	{ ns(struct compat_50_netbsd32_utimes_args), 0,
	    (sy_call_t *)compat_50(netbsd32_utimes), 0, 0 },/* 138 = compat_50_netbsd32_utimes */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 139 = obsolete 4.2 sigreturn */
	{ ns(struct compat_50_netbsd32_adjtime_args), 0,
	    (sy_call_t *)compat_50(netbsd32_adjtime), 0, 0 },/* 140 = compat_50_netbsd32_adjtime */
	{ ns(struct compat_43_netbsd32_ogetpeername_args), 0,
	    (sy_call_t *)compat_43(netbsd32_ogetpeername), 0, 0 },/* 141 = compat_43_netbsd32_ogetpeername */
	{ 0, 0, 0,
	    (sy_call_t *)compat_43(sys_gethostid), 0, 0 },/* 142 = compat_43_ogethostid */
	{ ns(struct compat_43_netbsd32_sethostid_args), 0,
	    (sy_call_t *)compat_43(netbsd32_sethostid), 0, 0 },/* 143 = compat_43_netbsd32_sethostid */
	{ ns(struct compat_43_netbsd32_ogetrlimit_args), 0,
	    (sy_call_t *)compat_43(netbsd32_ogetrlimit), 0, 0 },/* 144 = compat_43_netbsd32_ogetrlimit */
	{ ns(struct compat_43_netbsd32_osetrlimit_args), 0,
	    (sy_call_t *)compat_43(netbsd32_osetrlimit), 0, 0 },/* 145 = compat_43_netbsd32_osetrlimit */
	{ ns(struct compat_43_netbsd32_killpg_args), 0,
	    (sy_call_t *)compat_43(netbsd32_killpg), 0, 0 },/* 146 = compat_43_netbsd32_killpg */
	{ 0, 0, 0,
	    (sy_call_t *)sys_setsid, 0, 0 },		/* 147 = setsid */
	{ ns(struct compat_50_netbsd32_quotactl_args), 0,
	    (sy_call_t *)compat_50(netbsd32_quotactl), 0, 0 },/* 148 = compat_50_netbsd32_quotactl */
	{ 0, 0, 0,
	    (sy_call_t *)compat_43(sys_quota), 0, 0 },/* 149 = compat_43_oquota */
	{ ns(struct compat_43_netbsd32_ogetsockname_args), 0,
	    (sy_call_t *)compat_43(netbsd32_ogetsockname), 0, 0 },/* 150 = compat_43_netbsd32_ogetsockname */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 151 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 152 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 153 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 154 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 155 = unimplemented netbsd32_nfssvc */
	{ ns(struct compat_43_netbsd32_ogetdirentries_args), 0,
	    (sy_call_t *)compat_43(netbsd32_ogetdirentries), 0, 0 },/* 156 = compat_43_netbsd32_ogetdirentries */
	{ ns(struct compat_20_netbsd32_statfs_args), 0,
	    (sy_call_t *)compat_20(netbsd32_statfs), 0, 0 },/* 157 = compat_20_netbsd32_statfs */
	{ ns(struct compat_20_netbsd32_fstatfs_args), 0,
	    (sy_call_t *)compat_20(netbsd32_fstatfs), 0, 0 },/* 158 = compat_20_netbsd32_fstatfs */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 159 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 160 = unimplemented */
	{ ns(struct compat_30_netbsd32_getfh_args), 0,
	    (sy_call_t *)compat_30(netbsd32_getfh), 0, 0 },/* 161 = compat_30_netbsd32_getfh */
	{ ns(struct compat_09_netbsd32_ogetdomainname_args), 0,
	    (sy_call_t *)compat_09(netbsd32_ogetdomainname), 0, 0 },/* 162 = compat_09_netbsd32_ogetdomainname */
	{ ns(struct compat_09_netbsd32_osetdomainname_args), 0,
	    (sy_call_t *)compat_09(netbsd32_osetdomainname), 0, 0 },/* 163 = compat_09_netbsd32_osetdomainname */
	{ ns(struct compat_09_netbsd32_uname_args), 0,
	    (sy_call_t *)compat_09(netbsd32_uname), 0, 0 },/* 164 = compat_09_netbsd32_uname */
	{ ns(struct netbsd32_sysarch_args), 0,
	    (sy_call_t *)netbsd32_sysarch, 0, 0 },	/* 165 = netbsd32_sysarch */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 166 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 167 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 168 = unimplemented */
#if defined(SYSVSEM) || !defined(_KERNEL_OPT)
	{ ns(struct compat_10_netbsd32_semsys_args), 0,
	    (sy_call_t *)compat_10(netbsd32_semsys), 0, 0 },/* 169 = compat_10_osemsys */
#else
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 169 = excluded netbsd32_semsys */
#endif
#if defined(SYSVMSG) || !defined(_KERNEL_OPT)
	{ ns(struct compat_10_netbsd32_msgsys_args), 0,
	    (sy_call_t *)compat_10(netbsd32_msgsys), 0, 0 },/* 170 = compat_10_omsgsys */
#else
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 170 = excluded netbsd32_msgsys */
#endif
#if defined(SYSVSHM) || !defined(_KERNEL_OPT)
	{ ns(struct compat_10_netbsd32_shmsys_args), 0,
	    (sy_call_t *)compat_10(netbsd32_shmsys), 0, 0 },/* 171 = compat_10_oshmsys */
#else
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 171 = excluded netbsd32_shmsys */
#endif
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 172 = unimplemented */
	{ ns(struct netbsd32_pread_args), 0,
	    (sy_call_t *)netbsd32_pread, 0, 0 },	/* 173 = netbsd32_pread */
	{ ns(struct netbsd32_pwrite_args), 0,
	    (sy_call_t *)netbsd32_pwrite, 0, 0 },	/* 174 = netbsd32_pwrite */
#if defined(NTP) || !defined(_KERNEL_OPT)
	{ ns(struct compat_30_netbsd32_ntp_gettime_args), 0,
	    (sy_call_t *)compat_30(netbsd32_ntp_gettime), 0, 0 },/* 175 = compat_30_netbsd32_ntp_gettime */
	{ ns(struct netbsd32_ntp_adjtime_args), 0,
	    (sy_call_t *)netbsd32_ntp_adjtime, 0, 0 },/* 176 = netbsd32_ntp_adjtime */
#else
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 175 = excluded ntp_gettime */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 176 = excluded ntp_adjtime */
#endif
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 177 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 178 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 179 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 180 = unimplemented */
	{ ns(struct netbsd32_setgid_args), 0,
	    (sy_call_t *)netbsd32_setgid, 0, 0 },	/* 181 = netbsd32_setgid */
	{ ns(struct netbsd32_setegid_args), 0,
	    (sy_call_t *)netbsd32_setegid, 0, 0 },	/* 182 = netbsd32_setegid */
	{ ns(struct netbsd32_seteuid_args), 0,
	    (sy_call_t *)netbsd32_seteuid, 0, 0 },	/* 183 = netbsd32_seteuid */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 184 = excluded netbsd32_lfs_bmapv */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 185 = excluded netbsd32_lfs_markv */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 186 = excluded netbsd32_lfs_segclean */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 187 = excluded netbsd32_lfs_segwait */
	{ ns(struct compat_12_netbsd32_stat12_args), 0,
	    (sy_call_t *)compat_12(netbsd32_stat12), 0, 0 },/* 188 = compat_12_netbsd32_stat12 */
	{ ns(struct compat_12_netbsd32_fstat12_args), 0,
	    (sy_call_t *)compat_12(netbsd32_fstat12), 0, 0 },/* 189 = compat_12_netbsd32_fstat12 */
	{ ns(struct compat_12_netbsd32_lstat12_args), 0,
	    (sy_call_t *)compat_12(netbsd32_lstat12), 0, 0 },/* 190 = compat_12_netbsd32_lstat12 */
	{ ns(struct netbsd32_pathconf_args), 0,
	    (sy_call_t *)netbsd32_pathconf, 0, 0 },	/* 191 = netbsd32_pathconf */
	{ ns(struct netbsd32_fpathconf_args), 0,
	    (sy_call_t *)netbsd32_fpathconf, 0, 0 },	/* 192 = netbsd32_fpathconf */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 193 = unimplemented */
	{ ns(struct netbsd32_getrlimit_args), 0,
	    (sy_call_t *)netbsd32_getrlimit, 0, 0 },	/* 194 = netbsd32_getrlimit */
	{ ns(struct netbsd32_setrlimit_args), 0,
	    (sy_call_t *)netbsd32_setrlimit, 0, 0 },	/* 195 = netbsd32_setrlimit */
	{ ns(struct compat_12_netbsd32_getdirentries_args), 0,
	    (sy_call_t *)compat_12(netbsd32_getdirentries), 0, 0 },/* 196 = compat_12_netbsd32_getdirentries */
	{ ns(struct netbsd32_mmap_args), 0,
	    (sy_call_t *)netbsd32_mmap, 0, 0 },	/* 197 = netbsd32_mmap */
	{ ns(struct netbsd32____syscall_args), SYCALL_NARGS64_VAL(1) | SYCALL_ARG0_64 | SYCALL_RET_64 | SYCALL_INDIRECT,
	    (sy_call_t *)netbsd32____syscall, 0, 0 },	/* 198 = netbsd32____syscall */
	{ ns(struct netbsd32_lseek_args), 0,
	    (sy_call_t *)netbsd32_lseek, 0, 0 },	/* 199 = netbsd32_lseek */
	{ ns(struct netbsd32_truncate_args), 0,
	    (sy_call_t *)netbsd32_truncate, 0, 0 },	/* 200 = netbsd32_truncate */
	{ ns(struct netbsd32_ftruncate_args), 0,
	    (sy_call_t *)netbsd32_ftruncate, 0, 0 },	/* 201 = netbsd32_ftruncate */
	{ ns(struct netbsd32___sysctl_args), 0,
	    (sy_call_t *)netbsd32___sysctl, 0, 0 },	/* 202 = netbsd32___sysctl */
	{ ns(struct netbsd32_mlock_args), 0,
	    (sy_call_t *)netbsd32_mlock, 0, 0 },	/* 203 = netbsd32_mlock */
	{ ns(struct netbsd32_munlock_args), 0,
	    (sy_call_t *)netbsd32_munlock, 0, 0 },	/* 204 = netbsd32_munlock */
	{ ns(struct netbsd32_undelete_args), 0,
	    (sy_call_t *)netbsd32_undelete, 0, 0 },	/* 205 = netbsd32_undelete */
	{ ns(struct compat_50_netbsd32_futimes_args), 0,
	    (sy_call_t *)compat_50(netbsd32_futimes), 0, 0 },/* 206 = compat_50_netbsd32_futimes */
	{ ns(struct netbsd32_getpgid_args), 0,
	    (sy_call_t *)netbsd32_getpgid, 0, 0 },	/* 207 = netbsd32_getpgid */
	{ ns(struct netbsd32_reboot_args), 0,
	    (sy_call_t *)netbsd32_reboot, 0, 0 },	/* 208 = netbsd32_reboot */
	{ ns(struct netbsd32_poll_args), 0,
	    (sy_call_t *)netbsd32_poll, 0, 0 },	/* 209 = netbsd32_poll */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 210 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 211 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 212 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 213 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 214 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 215 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 216 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 217 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 218 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 219 = unimplemented */
#if defined(SYSVSEM) || !defined(_KERNEL_OPT)
	{ ns(struct compat_14_netbsd32___semctl_args), 0,
	    (sy_call_t *)compat_14(netbsd32___semctl), 0, 0 },/* 220 = compat_14_netbsd32___semctl */
	{ ns(struct netbsd32_semget_args), 0,
	    (sy_call_t *)netbsd32_semget, 0, 0 },	/* 221 = netbsd32_semget */
	{ ns(struct netbsd32_semop_args), 0,
	    (sy_call_t *)netbsd32_semop, 0, 0 },	/* 222 = netbsd32_semop */
	{ ns(struct netbsd32_semconfig_args), 0,
	    (sy_call_t *)netbsd32_semconfig, 0, 0 },	/* 223 = netbsd32_semconfig */
#else
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 220 = excluded compat_14_netbsd32_semctl */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 221 = excluded netbsd32_semget */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 222 = excluded netbsd32_semop */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 223 = excluded netbsd32_semconfig */
#endif
#if defined(SYSVMSG) || !defined(_KERNEL_OPT)
	{ ns(struct compat_14_netbsd32_msgctl_args), 0,
	    (sy_call_t *)compat_14(netbsd32_msgctl), 0, 0 },/* 224 = compat_14_netbsd32_msgctl */
	{ ns(struct netbsd32_msgget_args), 0,
	    (sy_call_t *)netbsd32_msgget, 0, 0 },	/* 225 = netbsd32_msgget */
	{ ns(struct netbsd32_msgsnd_args), 0,
	    (sy_call_t *)netbsd32_msgsnd, 0, 0 },	/* 226 = netbsd32_msgsnd */
	{ ns(struct netbsd32_msgrcv_args), 0,
	    (sy_call_t *)netbsd32_msgrcv, 0, 0 },	/* 227 = netbsd32_msgrcv */
#else
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 224 = excluded compat_14_netbsd32_msgctl */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 225 = excluded netbsd32_msgget */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 226 = excluded netbsd32_msgsnd */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 227 = excluded netbsd32_msgrcv */
#endif
#if defined(SYSVSHM) || !defined(_KERNEL_OPT)
	{ ns(struct netbsd32_shmat_args), 0,
	    (sy_call_t *)netbsd32_shmat, 0, 0 },	/* 228 = netbsd32_shmat */
	{ ns(struct compat_14_netbsd32_shmctl_args), 0,
	    (sy_call_t *)compat_14(netbsd32_shmctl), 0, 0 },/* 229 = compat_14_netbsd32_shmctl */
	{ ns(struct netbsd32_shmdt_args), 0,
	    (sy_call_t *)netbsd32_shmdt, 0, 0 },	/* 230 = netbsd32_shmdt */
	{ ns(struct netbsd32_shmget_args), 0,
	    (sy_call_t *)netbsd32_shmget, 0, 0 },	/* 231 = netbsd32_shmget */
#else
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 228 = excluded netbsd32_shmat */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 229 = excluded compat_14_netbsd32_shmctl */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 230 = excluded netbsd32_shmdt */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 231 = excluded netbsd32_shmget */
#endif
	{ ns(struct compat_50_netbsd32_clock_gettime_args), 0,
	    (sy_call_t *)compat_50(netbsd32_clock_gettime), 0, 0 },/* 232 = compat_50_netbsd32_clock_gettime */
	{ ns(struct compat_50_netbsd32_clock_settime_args), 0,
	    (sy_call_t *)compat_50(netbsd32_clock_settime), 0, 0 },/* 233 = compat_50_netbsd32_clock_settime */
	{ ns(struct compat_50_netbsd32_clock_getres_args), 0,
	    (sy_call_t *)compat_50(netbsd32_clock_getres), 0, 0 },/* 234 = compat_50_netbsd32_clock_getres */
	{ ns(struct netbsd32_timer_create_args), 0,
	    (sy_call_t *)netbsd32_timer_create, 0, 0 },/* 235 = netbsd32_timer_create */
	{ ns(struct netbsd32_timer_delete_args), 0,
	    (sy_call_t *)netbsd32_timer_delete, 0, 0 },/* 236 = netbsd32_timer_delete */
	{ ns(struct compat_50_netbsd32_timer_settime_args), 0,
	    (sy_call_t *)compat_50(netbsd32_timer_settime), 0, 0 },/* 237 = compat_50_netbsd32_timer_settime */
	{ ns(struct compat_50_netbsd32_timer_gettime_args), 0,
	    (sy_call_t *)compat_50(netbsd32_timer_gettime), 0, 0 },/* 238 = compat_50_netbsd32_timer_gettime */
	{ ns(struct netbsd32_timer_getoverrun_args), 0,
	    (sy_call_t *)netbsd32_timer_getoverrun, 0, 0 },/* 239 = netbsd32_timer_getoverrun */
	{ ns(struct compat_50_netbsd32_nanosleep_args), 0,
	    (sy_call_t *)compat_50(netbsd32_nanosleep), 0, 0 },/* 240 = compat_50_netbsd32_nanosleep */
	{ ns(struct netbsd32_fdatasync_args), 0,
	    (sy_call_t *)netbsd32_fdatasync, 0, 0 },	/* 241 = netbsd32_fdatasync */
	{ ns(struct netbsd32_mlockall_args), 0,
	    (sy_call_t *)netbsd32_mlockall, 0, 0 },	/* 242 = netbsd32_mlockall */
	{ 0, 0, 0,
	    (sy_call_t *)sys_munlockall, 0, 0 },	/* 243 = munlockall */
	{ ns(struct compat_50_netbsd32___sigtimedwait_args), 0,
	    (sy_call_t *)compat_50(netbsd32___sigtimedwait), 0, 0 },/* 244 = compat_50_netbsd32___sigtimedwait */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 245 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 246 = unimplemented */
	{ ns(struct netbsd32__ksem_init_args), 0,
	    (sy_call_t *)netbsd32__ksem_init, 0, 0 },	/* 247 = netbsd32__ksem_init */
	{ ns(struct netbsd32__ksem_open_args), 0,
	    (sy_call_t *)netbsd32__ksem_open, 0, 0 },	/* 248 = netbsd32__ksem_open */
	{ ns(struct netbsd32__ksem_unlink_args), 0,
	    (sy_call_t *)netbsd32__ksem_unlink, 0, 0 },/* 249 = netbsd32__ksem_unlink */
	{ ns(struct netbsd32__ksem_close_args), 0,
	    (sy_call_t *)netbsd32__ksem_close, 0, 0 },/* 250 = netbsd32__ksem_close */
	{ ns(struct netbsd32__ksem_post_args), 0,
	    (sy_call_t *)netbsd32__ksem_post, 0, 0 },	/* 251 = netbsd32__ksem_post */
	{ ns(struct netbsd32__ksem_wait_args), 0,
	    (sy_call_t *)netbsd32__ksem_wait, 0, 0 },	/* 252 = netbsd32__ksem_wait */
	{ ns(struct netbsd32__ksem_trywait_args), 0,
	    (sy_call_t *)netbsd32__ksem_trywait, 0, 0 },/* 253 = netbsd32__ksem_trywait */
	{ ns(struct netbsd32__ksem_getvalue_args), 0,
	    (sy_call_t *)netbsd32__ksem_getvalue, 0, 0 },/* 254 = netbsd32__ksem_getvalue */
	{ ns(struct netbsd32__ksem_destroy_args), 0,
	    (sy_call_t *)netbsd32__ksem_destroy, 0, 0 },/* 255 = netbsd32__ksem_destroy */
	{ ns(struct netbsd32__ksem_timedwait_args), 0,
	    (sy_call_t *)netbsd32__ksem_timedwait, 0, 0 },/* 256 = netbsd32__ksem_timedwait */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 257 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 258 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 259 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 260 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 261 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 262 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 263 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 264 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 265 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 266 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 267 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 268 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 269 = unimplemented */
	{ ns(struct netbsd32___posix_rename_args), 0,
	    (sy_call_t *)netbsd32___posix_rename, 0, 0 },/* 270 = netbsd32___posix_rename */
	{ ns(struct netbsd32_swapctl_args), 0,
	    (sy_call_t *)netbsd32_swapctl, 0, 0 },	/* 271 = netbsd32_swapctl */
	{ ns(struct compat_30_netbsd32_getdents_args), 0,
	    (sy_call_t *)compat_30(netbsd32_getdents), 0, 0 },/* 272 = compat_30_netbsd32_getdents */
	{ ns(struct netbsd32_minherit_args), 0,
	    (sy_call_t *)netbsd32_minherit, 0, 0 },	/* 273 = netbsd32_minherit */
	{ ns(struct netbsd32_lchmod_args), 0,
	    (sy_call_t *)netbsd32_lchmod, 0, 0 },	/* 274 = netbsd32_lchmod */
	{ ns(struct netbsd32_lchown_args), 0,
	    (sy_call_t *)netbsd32_lchown, 0, 0 },	/* 275 = netbsd32_lchown */
	{ ns(struct compat_50_netbsd32_lutimes_args), 0,
	    (sy_call_t *)compat_50(netbsd32_lutimes), 0, 0 },/* 276 = compat_50_netbsd32_lutimes */
	{ ns(struct netbsd32___msync13_args), 0,
	    (sy_call_t *)netbsd32___msync13, 0, 0 },	/* 277 = netbsd32___msync13 */
	{ ns(struct compat_30_netbsd32___stat13_args), 0,
	    (sy_call_t *)compat_30(netbsd32___stat13), 0, 0 },/* 278 = compat_30_netbsd32___stat13 */
	{ ns(struct compat_30_netbsd32___fstat13_args), 0,
	    (sy_call_t *)compat_30(netbsd32___fstat13), 0, 0 },/* 279 = compat_30_netbsd32___fstat13 */
	{ ns(struct compat_30_netbsd32___lstat13_args), 0,
	    (sy_call_t *)compat_30(netbsd32___lstat13), 0, 0 },/* 280 = compat_30_netbsd32___lstat13 */
	{ ns(struct netbsd32___sigaltstack14_args), 0,
	    (sy_call_t *)netbsd32___sigaltstack14, 0, 0 },/* 281 = netbsd32___sigaltstack14 */
	{ 0, 0, 0,
	    (sy_call_t *)sys___vfork14, 0, 0 },	/* 282 = __vfork14 */
	{ ns(struct netbsd32___posix_chown_args), 0,
	    (sy_call_t *)netbsd32___posix_chown, 0, 0 },/* 283 = netbsd32___posix_chown */
	{ ns(struct netbsd32___posix_fchown_args), 0,
	    (sy_call_t *)netbsd32___posix_fchown, 0, 0 },/* 284 = netbsd32___posix_fchown */
	{ ns(struct netbsd32___posix_lchown_args), 0,
	    (sy_call_t *)netbsd32___posix_lchown, 0, 0 },/* 285 = netbsd32___posix_lchown */
	{ ns(struct netbsd32_getsid_args), 0,
	    (sy_call_t *)netbsd32_getsid, 0, 0 },	/* 286 = netbsd32_getsid */
	{ ns(struct netbsd32___clone_args), 0,
	    (sy_call_t *)netbsd32___clone, 0, 0 },	/* 287 = netbsd32___clone */
	{ ns(struct netbsd32_fktrace_args), 0,
	    (sy_call_t *)netbsd32_fktrace, 0, 0 },	/* 288 = netbsd32_fktrace */
	{ ns(struct netbsd32_preadv_args), 0,
	    (sy_call_t *)netbsd32_preadv, 0, 0 },	/* 289 = netbsd32_preadv */
	{ ns(struct netbsd32_pwritev_args), 0,
	    (sy_call_t *)netbsd32_pwritev, 0, 0 },	/* 290 = netbsd32_pwritev */
	{ ns(struct netbsd32___sigaction14_args), 0,
	    (sy_call_t *)netbsd32___sigaction14, 0, 0 },/* 291 = netbsd32___sigaction14 */
	{ ns(struct netbsd32___sigpending14_args), 0,
	    (sy_call_t *)netbsd32___sigpending14, 0, 0 },/* 292 = netbsd32___sigpending14 */
	{ ns(struct netbsd32___sigprocmask14_args), 0,
	    (sy_call_t *)netbsd32___sigprocmask14, 0, 0 },/* 293 = netbsd32___sigprocmask14 */
	{ ns(struct netbsd32___sigsuspend14_args), 0,
	    (sy_call_t *)netbsd32___sigsuspend14, 0, 0 },/* 294 = netbsd32___sigsuspend14 */
	{ ns(struct compat_16_netbsd32___sigreturn14_args), 0,
	    (sy_call_t *)compat_16(netbsd32___sigreturn14), 0, 0 },/* 295 = compat_16_netbsd32___sigreturn14 */
	{ ns(struct netbsd32___getcwd_args), 0,
	    (sy_call_t *)netbsd32___getcwd, 0, 0 },	/* 296 = netbsd32___getcwd */
	{ ns(struct netbsd32_fchroot_args), 0,
	    (sy_call_t *)netbsd32_fchroot, 0, 0 },	/* 297 = netbsd32_fchroot */
	{ ns(struct compat_30_netbsd32_fhopen_args), 0,
	    (sy_call_t *)compat_30(netbsd32_fhopen), 0, 0 },/* 298 = compat_30_netbsd32_fhopen */
	{ ns(struct compat_30_netbsd32_fhstat_args), 0,
	    (sy_call_t *)compat_30(netbsd32_fhstat), 0, 0 },/* 299 = compat_30_netbsd32_fhstat */
	{ ns(struct compat_20_netbsd32_fhstatfs_args), 0,
	    (sy_call_t *)compat_20(netbsd32_fhstatfs), 0, 0 },/* 300 = compat_20_netbsd32_fhstatfs */
#if defined(SYSVSEM) || !defined(_KERNEL_OPT)
	{ ns(struct compat_50_netbsd32___semctl14_args), 0,
	    (sy_call_t *)compat_50(netbsd32___semctl14), 0, 0 },/* 301 = compat_50_netbsd32___semctl14 */
#else
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 301 = excluded __semctl14 */
#endif
#if defined(SYSVMSG) || !defined(_KERNEL_OPT)
	{ ns(struct compat_50_netbsd32___msgctl13_args), 0,
	    (sy_call_t *)compat_50(netbsd32___msgctl13), 0, 0 },/* 302 = compat_50_netbsd32___msgctl13 */
#else
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 302 = excluded __msgctl13 */
#endif
#if defined(SYSVSHM) || !defined(_KERNEL_OPT)
	{ ns(struct compat_50_netbsd32___shmctl13_args), 0,
	    (sy_call_t *)compat_50(netbsd32___shmctl13), 0, 0 },/* 303 = compat_50_netbsd32___shmctl13 */
#else
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 303 = excluded __shmctl13 */
#endif
	{ ns(struct netbsd32_lchflags_args), 0,
	    (sy_call_t *)netbsd32_lchflags, 0, 0 },	/* 304 = netbsd32_lchflags */
	{ 0, 0, 0,
	    (sy_call_t *)sys_issetugid, 0, 0 },	/* 305 = issetugid */
	{ ns(struct netbsd32_utrace_args), 0,
	    (sy_call_t *)netbsd32_utrace, 0, 0 },	/* 306 = netbsd32_utrace */
	{ ns(struct netbsd32_getcontext_args), 0,
	    (sy_call_t *)netbsd32_getcontext, 0, 0 },	/* 307 = netbsd32_getcontext */
	{ ns(struct netbsd32_setcontext_args), 0,
	    (sy_call_t *)netbsd32_setcontext, 0, 0 },	/* 308 = netbsd32_setcontext */
	{ ns(struct netbsd32__lwp_create_args), 0,
	    (sy_call_t *)netbsd32__lwp_create, 0, 0 },/* 309 = netbsd32__lwp_create */
	{ 0, 0, 0,
	    (sy_call_t *)sys__lwp_exit, 0, 0 },	/* 310 = _lwp_exit */
	{ 0, 0, 0,
	    (sy_call_t *)sys__lwp_self, 0, 0 },	/* 311 = _lwp_self */
	{ ns(struct netbsd32__lwp_wait_args), 0,
	    (sy_call_t *)netbsd32__lwp_wait, 0, 0 },	/* 312 = netbsd32__lwp_wait */
	{ ns(struct netbsd32__lwp_suspend_args), 0,
	    (sy_call_t *)netbsd32__lwp_suspend, 0, 0 },/* 313 = netbsd32__lwp_suspend */
	{ ns(struct netbsd32__lwp_continue_args), 0,
	    (sy_call_t *)netbsd32__lwp_continue, 0, 0 },/* 314 = netbsd32__lwp_continue */
	{ ns(struct netbsd32__lwp_wakeup_args), 0,
	    (sy_call_t *)netbsd32__lwp_wakeup, 0, 0 },/* 315 = netbsd32__lwp_wakeup */
	{ 0, 0, 0,
	    (sy_call_t *)sys__lwp_getprivate, 0, 0 },	/* 316 = _lwp_getprivate */
	{ ns(struct netbsd32__lwp_setprivate_args), 0,
	    (sy_call_t *)netbsd32__lwp_setprivate, 0, 0 },/* 317 = netbsd32__lwp_setprivate */
	{ ns(struct netbsd32__lwp_kill_args), 0,
	    (sy_call_t *)netbsd32__lwp_kill, 0, 0 },	/* 318 = netbsd32__lwp_kill */
	{ ns(struct netbsd32__lwp_detach_args), 0,
	    (sy_call_t *)netbsd32__lwp_detach, 0, 0 },/* 319 = netbsd32__lwp_detach */
	{ ns(struct compat_50_netbsd32__lwp_park_args), 0,
	    (sy_call_t *)compat_50(netbsd32__lwp_park), 0, 0 },/* 320 = compat_50_netbsd32__lwp_park */
	{ ns(struct netbsd32__lwp_unpark_args), 0,
	    (sy_call_t *)netbsd32__lwp_unpark, 0, 0 },/* 321 = netbsd32__lwp_unpark */
	{ ns(struct netbsd32__lwp_unpark_all_args), 0,
	    (sy_call_t *)netbsd32__lwp_unpark_all, 0, 0 },/* 322 = netbsd32__lwp_unpark_all */
	{ ns(struct netbsd32__lwp_setname_args), 0,
	    (sy_call_t *)netbsd32__lwp_setname, 0, 0 },/* 323 = netbsd32__lwp_setname */
	{ ns(struct netbsd32__lwp_getname_args), 0,
	    (sy_call_t *)netbsd32__lwp_getname, 0, 0 },/* 324 = netbsd32__lwp_getname */
	{ ns(struct netbsd32__lwp_ctl_args), 0,
	    (sy_call_t *)netbsd32__lwp_ctl, 0, 0 },	/* 325 = netbsd32__lwp_ctl */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 326 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 327 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 328 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 329 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 330 = obsolete netbsd32_sa_register */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 331 = obsolete netbsd32_sa_stacks */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 332 = obsolete sa_enable */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 333 = obsolete netbsd32_sa_setconcurrency */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 334 = obsolete sa_yield */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 335 = obsolete netbsd32_sa_preempt */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 336 = obsolete sys_sa_unblockyield */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 337 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 338 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 339 = unimplemented */
	{ ns(struct netbsd32___sigaction_sigtramp_args), 0,
	    (sy_call_t *)netbsd32___sigaction_sigtramp, 0, 0 },/* 340 = netbsd32___sigaction_sigtramp */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 341 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 342 = unimplemented */
	{ ns(struct netbsd32_rasctl_args), 0,
	    (sy_call_t *)netbsd32_rasctl, 0, 0 },	/* 343 = netbsd32_rasctl */
	{ 0, 0, 0,
	    (sy_call_t *)sys_kqueue, 0, 0 },		/* 344 = kqueue */
	{ ns(struct compat_50_netbsd32_kevent_args), 0,
	    (sy_call_t *)compat_50(netbsd32_kevent), 0, 0 },/* 345 = compat_50_netbsd32_kevent */
	{ ns(struct netbsd32__sched_setparam_args), 0,
	    (sy_call_t *)netbsd32__sched_setparam, 0, 0 },/* 346 = netbsd32__sched_setparam */
	{ ns(struct netbsd32__sched_getparam_args), 0,
	    (sy_call_t *)netbsd32__sched_getparam, 0, 0 },/* 347 = netbsd32__sched_getparam */
	{ ns(struct netbsd32__sched_setaffinity_args), 0,
	    (sy_call_t *)netbsd32__sched_setaffinity, 0, 0 },/* 348 = netbsd32__sched_setaffinity */
	{ ns(struct netbsd32__sched_getaffinity_args), 0,
	    (sy_call_t *)netbsd32__sched_getaffinity, 0, 0 },/* 349 = netbsd32__sched_getaffinity */
	{ 0, 0, 0,
	    (sy_call_t *)sys_sched_yield, 0, 0 },	/* 350 = sched_yield */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 351 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 352 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 353 = unimplemented */
	{ ns(struct netbsd32_fsync_range_args), 0,
	    (sy_call_t *)netbsd32_fsync_range, 0, 0 },/* 354 = netbsd32_fsync_range */
	{ ns(struct netbsd32_uuidgen_args), 0,
	    (sy_call_t *)netbsd32_uuidgen, 0, 0 },	/* 355 = netbsd32_uuidgen */
	{ ns(struct netbsd32_getvfsstat_args), 0,
	    (sy_call_t *)netbsd32_getvfsstat, 0, 0 },	/* 356 = netbsd32_getvfsstat */
	{ ns(struct netbsd32_statvfs1_args), 0,
	    (sy_call_t *)netbsd32_statvfs1, 0, 0 },	/* 357 = netbsd32_statvfs1 */
	{ ns(struct netbsd32_fstatvfs1_args), 0,
	    (sy_call_t *)netbsd32_fstatvfs1, 0, 0 },	/* 358 = netbsd32_fstatvfs1 */
	{ ns(struct compat_30_netbsd32_fhstatvfs1_args), 0,
	    (sy_call_t *)compat_30(netbsd32_fhstatvfs1), 0, 0 },/* 359 = compat_30_netbsd32_fhstatvfs1 */
	{ ns(struct netbsd32_extattrctl_args), 0,
	    (sy_call_t *)netbsd32_extattrctl, 0, 0 },	/* 360 = netbsd32_extattrctl */
	{ ns(struct netbsd32_extattr_set_file_args), 0,
	    (sy_call_t *)netbsd32_extattr_set_file, 0, 0 },/* 361 = netbsd32_extattr_set_file */
	{ ns(struct netbsd32_extattr_get_file_args), 0,
	    (sy_call_t *)netbsd32_extattr_get_file, 0, 0 },/* 362 = netbsd32_extattr_get_file */
	{ ns(struct netbsd32_extattr_delete_file_args), 0,
	    (sy_call_t *)netbsd32_extattr_delete_file, 0, 0 },/* 363 = netbsd32_extattr_delete_file */
	{ ns(struct netbsd32_extattr_set_fd_args), 0,
	    (sy_call_t *)netbsd32_extattr_set_fd, 0, 0 },/* 364 = netbsd32_extattr_set_fd */
	{ ns(struct netbsd32_extattr_get_fd_args), 0,
	    (sy_call_t *)netbsd32_extattr_get_fd, 0, 0 },/* 365 = netbsd32_extattr_get_fd */
	{ ns(struct netbsd32_extattr_delete_fd_args), 0,
	    (sy_call_t *)netbsd32_extattr_delete_fd, 0, 0 },/* 366 = netbsd32_extattr_delete_fd */
	{ ns(struct netbsd32_extattr_set_link_args), 0,
	    (sy_call_t *)netbsd32_extattr_set_link, 0, 0 },/* 367 = netbsd32_extattr_set_link */
	{ ns(struct netbsd32_extattr_get_link_args), 0,
	    (sy_call_t *)netbsd32_extattr_get_link, 0, 0 },/* 368 = netbsd32_extattr_get_link */
	{ ns(struct netbsd32_extattr_delete_link_args), 0,
	    (sy_call_t *)netbsd32_extattr_delete_link, 0, 0 },/* 369 = netbsd32_extattr_delete_link */
	{ ns(struct netbsd32_extattr_list_fd_args), 0,
	    (sy_call_t *)netbsd32_extattr_list_fd, 0, 0 },/* 370 = netbsd32_extattr_list_fd */
	{ ns(struct netbsd32_extattr_list_file_args), 0,
	    (sy_call_t *)netbsd32_extattr_list_file, 0, 0 },/* 371 = netbsd32_extattr_list_file */
	{ ns(struct netbsd32_extattr_list_link_args), 0,
	    (sy_call_t *)netbsd32_extattr_list_link, 0, 0 },/* 372 = netbsd32_extattr_list_link */
	{ ns(struct compat_50_netbsd32_pselect_args), 0,
	    (sy_call_t *)compat_50(netbsd32_pselect), 0, 0 },/* 373 = compat_50_netbsd32_pselect */
	{ ns(struct compat_50_netbsd32_pollts_args), 0,
	    (sy_call_t *)compat_50(netbsd32_pollts), 0, 0 },/* 374 = compat_50_netbsd32_pollts */
	{ ns(struct netbsd32_setxattr_args), 0,
	    (sy_call_t *)netbsd32_setxattr, 0, 0 },	/* 375 = netbsd32_setxattr */
	{ ns(struct netbsd32_lsetxattr_args), 0,
	    (sy_call_t *)netbsd32_lsetxattr, 0, 0 },	/* 376 = netbsd32_lsetxattr */
	{ ns(struct netbsd32_fsetxattr_args), 0,
	    (sy_call_t *)netbsd32_fsetxattr, 0, 0 },	/* 377 = netbsd32_fsetxattr */
	{ ns(struct netbsd32_getxattr_args), 0,
	    (sy_call_t *)netbsd32_getxattr, 0, 0 },	/* 378 = netbsd32_getxattr */
	{ ns(struct netbsd32_lgetxattr_args), 0,
	    (sy_call_t *)netbsd32_lgetxattr, 0, 0 },	/* 379 = netbsd32_lgetxattr */
	{ ns(struct netbsd32_fgetxattr_args), 0,
	    (sy_call_t *)netbsd32_fgetxattr, 0, 0 },	/* 380 = netbsd32_fgetxattr */
	{ ns(struct netbsd32_listxattr_args), 0,
	    (sy_call_t *)netbsd32_listxattr, 0, 0 },	/* 381 = netbsd32_listxattr */
	{ ns(struct netbsd32_llistxattr_args), 0,
	    (sy_call_t *)netbsd32_llistxattr, 0, 0 },	/* 382 = netbsd32_llistxattr */
	{ ns(struct netbsd32_flistxattr_args), 0,
	    (sy_call_t *)netbsd32_flistxattr, 0, 0 },	/* 383 = netbsd32_flistxattr */
	{ ns(struct netbsd32_removexattr_args), 0,
	    (sy_call_t *)netbsd32_removexattr, 0, 0 },/* 384 = netbsd32_removexattr */
	{ ns(struct netbsd32_lremovexattr_args), 0,
	    (sy_call_t *)netbsd32_lremovexattr, 0, 0 },/* 385 = netbsd32_lremovexattr */
	{ ns(struct netbsd32_fremovexattr_args), 0,
	    (sy_call_t *)netbsd32_fremovexattr, 0, 0 },/* 386 = netbsd32_fremovexattr */
	{ ns(struct compat_50_netbsd32___stat30_args), 0,
	    (sy_call_t *)compat_50(netbsd32___stat30), 0, 0 },/* 387 = compat_50_netbsd32___stat30 */
	{ ns(struct compat_50_netbsd32___fstat30_args), 0,
	    (sy_call_t *)compat_50(netbsd32___fstat30), 0, 0 },/* 388 = compat_50_netbsd32___fstat30 */
	{ ns(struct compat_50_netbsd32___lstat30_args), 0,
	    (sy_call_t *)compat_50(netbsd32___lstat30), 0, 0 },/* 389 = compat_50_netbsd32___lstat30 */
	{ ns(struct netbsd32___getdents30_args), 0,
	    (sy_call_t *)netbsd32___getdents30, 0, 0 },/* 390 = netbsd32___getdents30 */
	{ 0, 0, 0,
	    (sy_call_t *)nullop, 0, 0 },			/* 391 = ignored old posix fadvise */
	{ ns(struct compat_30_netbsd32___fhstat30_args), 0,
	    (sy_call_t *)compat_30(netbsd32___fhstat30), 0, 0 },/* 392 = compat_30_netbsd32___fhstat30 */
#if defined(NTP) || !defined(_KERNEL_OPT)
	{ ns(struct compat_50_netbsd32_ntp_gettime_args), 0,
	    (sy_call_t *)compat_50(netbsd32_ntp_gettime), 0, 0 },/* 393 = compat_50_netbsd32_ntp_gettime */
#else
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 393 = excluded __ntp_gettime30 */
#endif
	{ ns(struct netbsd32___socket30_args), 0,
	    (sy_call_t *)netbsd32___socket30, 0, 0 },	/* 394 = netbsd32___socket30 */
	{ ns(struct netbsd32___getfh30_args), 0,
	    (sy_call_t *)netbsd32___getfh30, 0, 0 },	/* 395 = netbsd32___getfh30 */
	{ ns(struct netbsd32___fhopen40_args), 0,
	    (sy_call_t *)netbsd32___fhopen40, 0, 0 },	/* 396 = netbsd32___fhopen40 */
	{ ns(struct netbsd32___fhstatvfs140_args), 0,
	    (sy_call_t *)netbsd32___fhstatvfs140, 0, 0 },/* 397 = netbsd32___fhstatvfs140 */
	{ ns(struct compat_50_netbsd32___fhstat40_args), 0,
	    (sy_call_t *)compat_50(netbsd32___fhstat40), 0, 0 },/* 398 = compat_50_netbsd32___fhstat40 */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 399 = unimplemented sys_aio_cancel */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 400 = unimplemented sys_aio_error */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 401 = unimplemented sys_aio_fsync */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 402 = unimplemented sys_aio_read */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 403 = unimplemented sys_aio_return */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 404 = unimplemented sys_aio_suspend */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 405 = unimplemented sys_aio_write */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 406 = unimplemented sys_lio_listio */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 407 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 408 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 409 = unimplemented */
	{ ns(struct netbsd32___mount50_args), 0,
	    (sy_call_t *)netbsd32___mount50, 0, 0 },	/* 410 = netbsd32___mount50 */
	{ ns(struct netbsd32_mremap_args), 0,
	    (sy_call_t *)netbsd32_mremap, 0, 0 },	/* 411 = netbsd32_mremap */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 412 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 413 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 414 = unimplemented */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 415 = unimplemented */
	{ ns(struct netbsd32___posix_fadvise50_args), 0,
	    (sy_call_t *)netbsd32___posix_fadvise50, 0, 0 },/* 416 = netbsd32___posix_fadvise50 */
	{ ns(struct netbsd32___select50_args), 0,
	    (sy_call_t *)netbsd32___select50, 0, 0 },	/* 417 = netbsd32___select50 */
	{ ns(struct netbsd32___gettimeofday50_args), 0,
	    (sy_call_t *)netbsd32___gettimeofday50, 0, 0 },/* 418 = netbsd32___gettimeofday50 */
	{ ns(struct netbsd32___settimeofday50_args), 0,
	    (sy_call_t *)netbsd32___settimeofday50, 0, 0 },/* 419 = netbsd32___settimeofday50 */
	{ ns(struct netbsd32___utimes50_args), 0,
	    (sy_call_t *)netbsd32___utimes50, 0, 0 },	/* 420 = netbsd32___utimes50 */
	{ ns(struct netbsd32___adjtime50_args), 0,
	    (sy_call_t *)netbsd32___adjtime50, 0, 0 },/* 421 = netbsd32___adjtime50 */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 422 = excluded __lfs_segwait50 */
	{ ns(struct netbsd32___futimes50_args), 0,
	    (sy_call_t *)netbsd32___futimes50, 0, 0 },/* 423 = netbsd32___futimes50 */
	{ ns(struct netbsd32___lutimes50_args), 0,
	    (sy_call_t *)netbsd32___lutimes50, 0, 0 },/* 424 = netbsd32___lutimes50 */
	{ ns(struct netbsd32___setitimer50_args), 0,
	    (sy_call_t *)netbsd32___setitimer50, 0, 0 },/* 425 = netbsd32___setitimer50 */
	{ ns(struct netbsd32___getitimer50_args), 0,
	    (sy_call_t *)netbsd32___getitimer50, 0, 0 },/* 426 = netbsd32___getitimer50 */
	{ ns(struct netbsd32___clock_gettime50_args), 0,
	    (sy_call_t *)netbsd32___clock_gettime50, 0, 0 },/* 427 = netbsd32___clock_gettime50 */
	{ ns(struct netbsd32___clock_settime50_args), 0,
	    (sy_call_t *)netbsd32___clock_settime50, 0, 0 },/* 428 = netbsd32___clock_settime50 */
	{ ns(struct netbsd32___clock_getres50_args), 0,
	    (sy_call_t *)netbsd32___clock_getres50, 0, 0 },/* 429 = netbsd32___clock_getres50 */
	{ ns(struct netbsd32___nanosleep50_args), 0,
	    (sy_call_t *)netbsd32___nanosleep50, 0, 0 },/* 430 = netbsd32___nanosleep50 */
	{ ns(struct netbsd32_____sigtimedwait50_args), 0,
	    (sy_call_t *)netbsd32_____sigtimedwait50, 0, 0 },/* 431 = netbsd32_____sigtimedwait50 */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 432 = unimplemented netbsd32___mq_timedsend50 */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 433 = unimplemented netbsd32___mq_timedreceive50 */
	{ ns(struct compat_60_netbsd32__lwp_park_args), 0,
	    (sy_call_t *)compat_60(netbsd32__lwp_park), 0, 0 },/* 434 = compat_60_netbsd32__lwp_park */
	{ ns(struct netbsd32___kevent50_args), 0,
	    (sy_call_t *)netbsd32___kevent50, 0, 0 },	/* 435 = netbsd32___kevent50 */
	{ ns(struct netbsd32___pselect50_args), 0,
	    (sy_call_t *)netbsd32___pselect50, 0, 0 },/* 436 = netbsd32___pselect50 */
	{ ns(struct netbsd32___pollts50_args), 0,
	    (sy_call_t *)netbsd32___pollts50, 0, 0 },	/* 437 = netbsd32___pollts50 */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 438 = unimplemented netbsd32___aio_suspend50 */
	{ ns(struct netbsd32___stat50_args), 0,
	    (sy_call_t *)netbsd32___stat50, 0, 0 },	/* 439 = netbsd32___stat50 */
	{ ns(struct netbsd32___fstat50_args), 0,
	    (sy_call_t *)netbsd32___fstat50, 0, 0 },	/* 440 = netbsd32___fstat50 */
	{ ns(struct netbsd32___lstat50_args), 0,
	    (sy_call_t *)netbsd32___lstat50, 0, 0 },	/* 441 = netbsd32___lstat50 */
#if defined(SYSVSEM) || !defined(_KERNEL_OPT)
	{ ns(struct netbsd32_____semctl50_args), 0,
	    (sy_call_t *)netbsd32_____semctl50, 0, 0 },/* 442 = netbsd32_____semctl50 */
#else
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 442 = excluded ____semctl50 */
#endif
#if defined(SYSVSHM) || !defined(_KERNEL_OPT)
	{ ns(struct netbsd32___shmctl50_args), 0,
	    (sy_call_t *)netbsd32___shmctl50, 0, 0 },	/* 443 = netbsd32___shmctl50 */
#else
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 443 = excluded ____shmctl50 */
#endif
#if defined(SYSVMSG) || !defined(_KERNEL_OPT)
	{ ns(struct netbsd32___msgctl50_args), 0,
	    (sy_call_t *)netbsd32___msgctl50, 0, 0 },	/* 444 = netbsd32___msgctl50 */
#else
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 444 = excluded ____msgctl50 */
#endif
	{ ns(struct netbsd32___getrusage50_args), 0,
	    (sy_call_t *)netbsd32___getrusage50, 0, 0 },/* 445 = netbsd32___getrusage50 */
	{ ns(struct netbsd32___timer_settime50_args), 0,
	    (sy_call_t *)netbsd32___timer_settime50, 0, 0 },/* 446 = netbsd32___timer_settime50 */
	{ ns(struct netbsd32___timer_gettime50_args), 0,
	    (sy_call_t *)netbsd32___timer_gettime50, 0, 0 },/* 447 = netbsd32___timer_gettime50 */
#if defined(NTP) || !defined(_KERNEL_OPT)
	{ ns(struct netbsd32___ntp_gettime50_args), 0,
	    (sy_call_t *)netbsd32___ntp_gettime50, 0, 0 },/* 448 = netbsd32___ntp_gettime50 */
#else
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 448 = excluded ___ntp_gettime50 */
#endif
	{ ns(struct netbsd32___wait450_args), 0,
	    (sy_call_t *)netbsd32___wait450, 0, 0 },	/* 449 = netbsd32___wait450 */
	{ ns(struct netbsd32___mknod50_args), 0,
	    (sy_call_t *)netbsd32___mknod50, 0, 0 },	/* 450 = netbsd32___mknod50 */
	{ ns(struct netbsd32___fhstat50_args), 0,
	    (sy_call_t *)netbsd32___fhstat50, 0, 0 },	/* 451 = netbsd32___fhstat50 */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 452 = obsolete 5.99 quotactl */
	{ ns(struct netbsd32_pipe2_args), 0,
	    (sy_call_t *)netbsd32_pipe2, 0, 0 },	/* 453 = netbsd32_pipe2 */
	{ ns(struct netbsd32_dup3_args), 0,
	    (sy_call_t *)netbsd32_dup3, 0, 0 },	/* 454 = netbsd32_dup3 */
	{ ns(struct netbsd32_kqueue1_args), 0,
	    (sy_call_t *)netbsd32_kqueue1, 0, 0 },	/* 455 = netbsd32_kqueue1 */
	{ ns(struct netbsd32_paccept_args), 0,
	    (sy_call_t *)netbsd32_paccept, 0, 0 },	/* 456 = netbsd32_paccept */
	{ ns(struct netbsd32_linkat_args), 0,
	    (sy_call_t *)netbsd32_linkat, 0, 0 },	/* 457 = netbsd32_linkat */
	{ ns(struct netbsd32_renameat_args), 0,
	    (sy_call_t *)netbsd32_renameat, 0, 0 },	/* 458 = netbsd32_renameat */
	{ ns(struct netbsd32_mkfifoat_args), 0,
	    (sy_call_t *)netbsd32_mkfifoat, 0, 0 },	/* 459 = netbsd32_mkfifoat */
	{ ns(struct netbsd32_mknodat_args), 0,
	    (sy_call_t *)netbsd32_mknodat, 0, 0 },	/* 460 = netbsd32_mknodat */
	{ ns(struct netbsd32_mkdirat_args), 0,
	    (sy_call_t *)netbsd32_mkdirat, 0, 0 },	/* 461 = netbsd32_mkdirat */
	{ ns(struct netbsd32_faccessat_args), 0,
	    (sy_call_t *)netbsd32_faccessat, 0, 0 },	/* 462 = netbsd32_faccessat */
	{ ns(struct netbsd32_fchmodat_args), 0,
	    (sy_call_t *)netbsd32_fchmodat, 0, 0 },	/* 463 = netbsd32_fchmodat */
	{ ns(struct netbsd32_fchownat_args), 0,
	    (sy_call_t *)netbsd32_fchownat, 0, 0 },	/* 464 = netbsd32_fchownat */
	{ ns(struct netbsd32_fexecve_args), 0,
	    (sy_call_t *)netbsd32_fexecve, 0, 0 },	/* 465 = netbsd32_fexecve */
	{ ns(struct netbsd32_fstatat_args), 0,
	    (sy_call_t *)netbsd32_fstatat, 0, 0 },	/* 466 = netbsd32_fstatat */
	{ ns(struct netbsd32_utimensat_args), 0,
	    (sy_call_t *)netbsd32_utimensat, 0, 0 },	/* 467 = netbsd32_utimensat */
	{ ns(struct netbsd32_openat_args), 0,
	    (sy_call_t *)netbsd32_openat, 0, 0 },	/* 468 = netbsd32_openat */
	{ ns(struct netbsd32_readlinkat_args), 0,
	    (sy_call_t *)netbsd32_readlinkat, 0, 0 },	/* 469 = netbsd32_readlinkat */
	{ ns(struct netbsd32_symlinkat_args), 0,
	    (sy_call_t *)netbsd32_symlinkat, 0, 0 },	/* 470 = netbsd32_symlinkat */
	{ ns(struct netbsd32_unlinkat_args), 0,
	    (sy_call_t *)netbsd32_unlinkat, 0, 0 },	/* 471 = netbsd32_unlinkat */
	{ ns(struct netbsd32_futimens_args), 0,
	    (sy_call_t *)netbsd32_futimens, 0, 0 },	/* 472 = netbsd32_futimens */
	{ ns(struct netbsd32___quotactl_args), 0,
	    (sy_call_t *)netbsd32___quotactl, 0, 0 },	/* 473 = netbsd32___quotactl */
	{ ns(struct netbsd32_posix_spawn_args), 0,
	    (sy_call_t *)netbsd32_posix_spawn, 0, 0 },/* 474 = netbsd32_posix_spawn */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 475 = unimplemented { int | netbsd32 | | recvmmsg ( int s , struct mmsghdr * mmsg , unsigned int vlen , unsigned int flags , netbsd32_timespecp_t timeout ) ; } */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 476 = unimplemented { int | netbsd32 | | sendmmsg ( int s , struct mmsghdr * mmsg , unsigned int vlen , unsigned int flags ) ; } */
	{ ns(struct netbsd32_clock_nanosleep_args), 0,
	    (sy_call_t *)netbsd32_clock_nanosleep, 0, 0 },/* 477 = netbsd32_clock_nanosleep */
	{ ns(struct netbsd32____lwp_park60_args), 0,
	    (sy_call_t *)netbsd32____lwp_park60, 0, 0 },/* 478 = netbsd32____lwp_park60 */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 479 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 480 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 481 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 482 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 483 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 484 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 485 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 486 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 487 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 488 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 489 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 490 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 491 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 492 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 493 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 494 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 495 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 496 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 497 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 498 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 499 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 500 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 501 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 502 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 503 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 504 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 505 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 506 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 507 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 508 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 509 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 510 = filler */
	{ 0, 0, 0,
	    sys_nosys, 0, 0 },			/* 511 = filler */
};
