#define TOP_PACKAGE "ipsec-tools"
#define TOP_PACKAGE_NAME "ipsec-tools"
#define TOP_PACKAGE_VERSION  "cvs"
#define TOP_PACKAGE_STRING  "ipsec-tools cvs"
#define TOP_PACKAGE_URL "http://ipsec-tools.sourceforge.net"
