#	$NetBSD: Makefile,v 1.4 2003/01/17 21:55:25 thorpej Exp $

INCSDIR= /usr/include/acorn26

INCS=	ansi.h aout_machdep.h asm.h \
	boot.h bswap.h bus.h \
	cdefs.h cpu.h \
	db_machdep.h disklabel.h \
	elf_machdep.h endian.h endian_machdep.h \
	float.h fp.h frame.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intr.h ipkdb.h irq.h \
	limits.h lock.h \
	math.h mcontext.h \
	param.h pcb.h pmap.h pmc.h proc.h profile.h ptrace.h \
	reg.h \
	setjmp.h signal.h stdarg.h sysarch.h \
	trap.h types.h \
	varargs.h vmparam.h

.include <bsd.kinc.mk>
