#	$NetBSD: Makefile,v 1.11.12.1 2013/02/25 00:28:17 tls Exp $

INCSDIR= /usr/include/acorn26

INCS=	ansi.h aout_machdep.h asm.h \
	boot.h bswap.h \
	cdefs.h cpu.h \
	disklabel.h \
	elf_machdep.h endian.h endian_machdep.h \
	float.h frame.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intr.h irq.h \
	limits.h lock.h \
	math.h mutex.h mcontext.h \
	param.h pcb.h pmap.h pmc.h proc.h profile.h ptrace.h \
	reg.h rwlock.h \
	setjmp.h signal.h sysarch.h \
	trap.h types.h \
	vmparam.h \
	wchar_limits.h

.include <bsd.kinc.mk>
