#	$NetBSD: Makefile,v 1.1 2004/11/28 07:00:53 jmc Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}amiga-aout2bb
HOST_SRCDIR=	sys/arch/amiga/stand/bootblock/aout2bb

HOST_CPPFLAGS+= -I${.CURDIR}

.include "${.CURDIR}/../Makefile.host"
