.\"	$NetBSD: lptctl.8,v 1.2 2004/01/19 23:32:42 jdolecek Exp $
.\"
.\" Copyright notice
.\"
.\" The uncommented requests are required for all man pages.
.\" The commented requests should be uncommented and used where appropriate.
.Dd January 20, 2004
.Dt LPTCTL 8
.Os 
.Sh NAME
.Nm lptctl 
.Nd manipulate lpt devices
.Sh SYNOPSIS
.Nm lptctl
.Ar /dev/device
.Oo
.Op Ar command arg
.Ar ...
.Oc
.Sh DESCRIPTION
.Nm
is used to manipulate lpt devices so that a user can change how a printer that 
is attached to a parallel port works. 
If no command-argument pairs are specified, the status of the device is printed to 
standard output using the following format: 
.Pp
dma=[on|off] mode=[standard|nibble|ps2|fast|ecp|epp] ieee=[yes|no]
.Pp
The status information is also output after commands are carried out.
.Sh DEVICE COMMANDS 
Multiple command-argument pairs can be specified up to a maximum of the total number 
of distinct commands possible. Available commands are:
.Bl -item
.It
.Cm dma 
.Ar on | off
.Pp
Enables or disables DMA.
.It
.Cm mode 
.Ar standard | nibble | ps2 | fast | ecp 
.Ar | epp 
.Pp
Sets port to use a mode of operation: standard centronics mode (standard), 
nibble mode, bidirectional mode (ps2), fast centronics mode (fast), enhanced 
capabilities port mode (ecp), or enhanced parallel port mode (epp). 
.It
.Cm ieee 
.Ar yes | no
.Pp
Enables or disables the use of IEEE 1284 negotiations during mode changes and 
channel direction changes.
.El
.Sh EXIT STATUS
.Nm 
returns 0 on success, >0  on failure.
.Sh FILES
.Bl -item
.It
.Pa /dev/lpt?
- interrupt-driven printer ports
.It
.Pa /dev/lpa?
- polled printer ports
.El
.Sh SEE ALSO
.Xr ioctl 2 ,
.Xr lpt 4 ,
.Xr ppbus 4
.Sh HISTORY
A similar utility called 
.Nm lptcontrol
exists in FreeBSD to control the lpt device. While similar in concept, 
the implementations are independent.
.Nm
was added in
.Nx 2.0 .
.Sh AUTHORS
This man page and the 
.Nm
utility were written by Gary Thorpe.
.Sh BUGS
.Nm
opens the printer device and causes device initialization if
.Pa /dev/lpa? 
or
.Pa /dev/lpt?
are used. Therefore, a printer must be connected and functioning 
to use this utility or you will have to create a lpt device with an 
appropriate minor number (see 
.Xr lpt 4 
for more details).
