# $NetBSD: Makefile,v 1.3.40.1 2009/05/13 19:20:28 jym Exp $
#
# Makefile to build lptctl and man page

SRCS=		lptctl.c
PROG=		lptctl
MAN=		lptctl.8

CPPFLAGS+=	-I${NETBSDSRCDIR}/sys

.include <bsd.prog.mk>
