/* This file is automatically generated.  DO NOT EDIT! */
/* Generated from: 	NetBSD: mknative,v 1.7 2002/02/27 17:55:32 tv Exp  */

#ifdef IN_GCC
#include "gansidecl.h"
#endif
#ifdef IN_GCC
#include "arm/xm-netbsd.h"
#endif
#ifdef IN_GCC
#include "arm/xm-arm.h"
#endif
#ifdef IN_GCC
#include "xm-netbsd.h"
#endif
