.\"	$NetBSD: eshconfig.8,v 1.8 2008/04/30 13:11:02 martin Exp $
.\"
.\" Copyright (c) 1998 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Kevin Lahey of the Numerical Aerospace Simulation Facility,
.\" NASA Ames Research Center.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd June 17, 2005
.Dt ESHCONFIG 8
.Os
.Sh NAME
.Nm eshconfig
.Nd configure Essential Communications' HIPPI network interface
.Sh SYNOPSIS
.Nm eshconfig
.Op Fl estx
.Op Fl b Ar bytes
.Op Fl c Ar bytes
.Op Fl d Ar filename
.Op Fl i Ar usecs
.Op Fl m Ar bytes
.Op Fl r Ar bytes
.Op Fl u Ar filename
.Op Fl w Ar bytes
.Op Ar interface
.Sh DESCRIPTION
.Nm
is used to configure device-specific parameters and download new firmware
to the Essential Communications RoadRunner-based HIPPI network interface.
The interface is very sensitive to the DMA performance characteristics
of the host, and so requires careful tuning to achieve reasonable
performance.
In addition, firmware is likely to change frequently, which necessitates
a reasonably easy way to update that firmware.
.Pp
Available operands for
.Nm eshconfig :
.Bl -tag -width Ds
.It Fl b Ar bytes
Adjust the burst size for read (by NIC of host memory) DMA.
.It Fl c Ar bytes
Adjust the burst size for write (by NIC of host memory) DMA.
.It Fl d Ar filename
Filename for file to download into NIC firmware.
This must be a file in the standard Essential format, with :04 preceding
every line, and a tag line at the end indicating the characteristics
of the firmware file.
.It Fl e
Write data to EEPROM.
Normally, setting tuning parameters will only persist until the
system is rebooted.
Setting this parameter ensures that the changes will be written to
EEPROM.
.It Fl i Ar usecs
Interrupt delay in microseconds.
.It Fl m Ar bytes
Minimum number of bytes to DMA in one direction (read or write)
before allowing a DMA in the other direction.
Tuning this prevents one direction from dominating the flow of
bytes, and artificially throttling the NIC.
.It Fl r Ar bytes
Bytes before DMA starts for read (from host to NIC).
This controls how soon the DMA is triggered;  until this many bytes
are requested, the DMA will not begin.
.It Fl s
Show statistics for the HIPPI NIC.
Repeat the option to suppress non-zero statistics.
.It Fl t
Show current tuning parameters on the host.
.It Fl u Ar filename
Name of file to which the NIC firmware should be uploaded.
Not currently supported.
.It Fl w Ar bytes
Number of bytes required before write (from NIC to host) DMA
is started.
Until this many bytes are ready to be written, the DMA will not start.
.It Fl x
Reset the NIC.
This is necessary for the HIPPI-FP support, as
.Xr ifconfig 8
will no longer physically reset the NIC when the interfaces goes
up and down.
.El
.Pp
Only the super-user may modify the configuration of a network interface.
.Sh DIAGNOSTICS
Messages indicating the specified interface does not exist
or the user is not privileged and
tried to alter an interface's configuration.
.Sh SEE ALSO
.Xr esh 4 ,
.Xr ifconfig 8
.Sh HISTORY
The
.Nm
command first appeared in
.Nx 1.4 .
