#	$NetBSD: Makefile.rumpdevcomp,v 1.7 2014/01/14 17:17:52 pgoyette Exp $
#

RUMPDEVCOMP=	audio bpf cgd disk dm drvctl fss md netsmb pad pud	\
		putter raidframe rnd scsipi scsitest sysmon wscons	\
		opencrypto

RUMPUSBDEVS=	ubt ucom ugenhc ulpt umass usb

.for var in ${RUMPDEVCOMP}
RUMPDEVLIBS+=lib${var}
RUMPDEVLDADD+=-lrumpdev_${var}
.endfor

.for var in ${RUMPUSBDEVS}
RUMPDEVLIBS+=lib${var}
.endfor
