#	$NetBSD: Makefile.rumpdevcomp,v 1.12 2014/07/17 08:16:12 prlw1 Exp $
#

RUMPDEVCOMP=	audio bpf cgd disk dm drvctl fss md netsmb pad pud	\
		putter raidframe rnd scsipi sysmon vnd wscons		\
		opencrypto

RUMPUSBDEVS=	ubt ucom ugenhc ulpt umass usb

RUMPPCIDEVS=	pci pci_if_iwn pci_if_wm
# Not really a PCI device, but ....
RUMPPCIDEVS+=	miiphy

.for var in ${RUMPDEVCOMP}
RUMPDEVLIBS+=lib${var}
RUMPDEVLDADD+=-lrumpdev_${var}
.endfor

.for var in ${RUMPUSBDEVS}
RUMPDEVLIBS+=lib${var}
.endfor

# Currently no NetBSD host support.
#.for var in ${RUMPPCIDEVS}
#RUMPDEVLIBS+=lib${var}
#.endfor
