#	$NetBSD: Makefile,v 1.1.2.2 2008/02/02 09:14:33 tsutsui Exp $
#
# Makefile for cobalt
#

MENUS_MD=	menus.md.${SYSINSTLANG} menus.mbr
MSG_MD=		msg.md.${SYSINSTLANG} msg.mbr.${SYSINSTLANG}

LANGUAGES=	# no translations ready yet

.include "../../Makefile.inc"
