#	$Id: Makefile.cc1,v 1.1 1993/08/23 09:20:27 cgd Exp $

NOMAN=

BINDIR=	/usr/libexec

CFLAGS+=-I${.CURDIR} -I${.CURDIR}/../common \
	-I${.CURDIR}/../arch -I${.CURDIR}/../arch/${MACHINE}
YFLAGS=

.if exists(${.CURDIR}/../common/obj)
LDADD+=	${.CURDIR}/../common/obj/libcc1.a
.else
LDADD+=	${.CURDIR}/../common/libcc1.a
.endif

.include <bsd.prog.mk>
