#	$NetBSD: Makefile,v 1.19.2.2 2002/06/23 17:43:18 jdolecek Exp $

KDIR=	/sys/arch/x68k/include
INCSDIR= /usr/include/x68k

INCS=	ansi.h aout_machdep.h asm.h \
	bootinfo.h bswap.h bus.h \
	cdefs.h cpu.h cpufunc.h \
	db_machdep.h disklabel.h \
	elf_machdep.h endian.h endian_machdep.h \
	float.h frame.h \
	grfioctl.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intr.h iteioctl.h \
	kbd.h kbio.h kcore.h \
	math.h \
	lock.h limits.h \
	opmbellio.h \
	param.h parioctl.h pcb.h pci_machdep.h pmap.h powioctl.h proc.h \
	profile.h psl.h pte.h ptrace.h \
	reg.h remote-sl.h \
	setjmp.h signal.h sram.h stdarg.h \
	trap.h types.h \
	varargs.h vmparam.h vuid_event.h

.include <bsd.kinc.mk>
