#	$NetBSD: Makefile,v 1.1.4.2 2014/05/22 11:37:52 yamt Exp $
#	from: @(#)Makefile	8.1 (Berkeley) 6/5/93

MAN=	boot.8 dosboot.8 boot_console.8 multiboot.8 pxeboot.8 mbr.8
MLINKS=	mbr.8 bootselect.8
MANSUBDIR=/x86

.include <bsd.man.mk>
