# $NetBSD: Makefile,v 1.2 2007/11/21 15:39:35 jmmv Exp $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/util/sh

TESTS_SH=	t_compexit
TESTS_SH+=	t_exitstatus
TESTS_SH+=	t_expand
TESTS_SH+=	t_fsplit
TESTS_SH+=	t_here
TESTS_SH+=	t_set_e
TESTS_SH+=	t_varquote

.include <bsd.test.mk>
