#	$NetBSD: Makefile,v 1.17 2005/05/07 02:21:09 perry Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/5/93

# missing: eqnchar.7 man.7 ms.7 term.7

MAN=	ascii.7 environ.7 hier.7 hostname.7 intro.7 mailaddr.7 \
	nls.7 operator.7 packages.7 release.7  \
	script.7 setuid.7 signal.7 sticky.7 symlink.7

.include <bsd.man.mk>
