#	$NetBSD: Makefile,v 1.12 2000/04/17 17:03:37 augustss Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/5/93

# missing: eqnchar.7 man.7 ms.7 term.7

MAN=	ascii.7 environ.7 hier.7 hostname.7 intro.7 mailaddr.7 \
	mdoc.7 mdoc.samples.7 operator.7 packages.7 release.7  \
	signal.7 symlink.7
MLINKS=mdoc.7 mandoc.7

.include <bsd.man.mk>
