.\"	$NetBSD: signal.7,v 1.1.4.1 1999/12/27 18:31:03 wrstuden Exp $
.\"
.\" Copyright (c) 1999 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"        This product includes software developed by the NetBSD
.\"        Foundation, Inc. and its contributors.
.\" 4. Neither the name of The NetBSD Foundation nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd September 27, 1999
.Dt SIGNAL 7
.Os
.Sh NAME
.Nm signal
.Nd signal facilities
.Sh DESCRIPTION
The
.Aq Pa signal.h
header file defines the following signals:
.Pp
.Bl -column "SIGVTALARM" "terminate process" -compact
.It Li Em "Name" Ta Em "Default Action" Ta Em "Description"
.It Li SIGHUP Ta "terminate process" Ta "terminal line hangup"
.It Li SIGINT Ta "terminate process" Ta "interrupt program"
.It Li SIGQUIT Ta "create core image" Ta "quit program"
.It Li SIGILL Ta "create core image" Ta "illegal instruction"
.It Li SIGTRAP Ta "create core image" Ta "trace trap"
.It Li SIGABRT Ta "create core image" Ta Xr abort 2
call (formerly
.Dv SIGIOT )
.It Li SIGEMT Ta "create core image" Ta "emulate instruction executed"
.It Li SIGFPE Ta "create core image" Ta "floating-point exception"
.It Li SIGKILL Ta "terminate process" Ta "kill program (cannot be caught or ignored)"
.It Li SIGBUS Ta "create core image" Ta "bus error"
.It Li SIGSEGV Ta "create core image" Ta "segmentation violation"
.It Li SIGSYS Ta "create core image" Ta "invalid system call argument"
.It Li SIGPIPE Ta "terminate process" Ta "write to a pipe with no reader"
.It Li SIGALRM Ta "terminate process" Ta "real-time timer expired"
.It Li SIGTERM Ta "terminate process" Ta "software termination signal"
.It Li SIGURG Ta "discard signal" Ta "urgent condition present on socket"
.It Li SIGSTOP Ta "stop process" Ta "stop (cannot be caught or ignored)"
.It Li SIGTSTP Ta "stop process" Ta "stop signal generated from keyboard"
.It Li SIGCONT Ta "discard signal" Ta "continue after stop"
.It Li SIGCHLD Ta "discard signal" Ta "child status has changed"
.It Li SIGTTIN Ta "stop process" Ta "background read attempted from control terminal"
.It Li SIGTTOU Ta "stop process" Ta "background write attempted to control terminal"
.It Li SIGIO Ta "discard signal" Ta "I/O is possible on a descriptor (see"
.Xr fcntl 2 )
.It Li SIGXCPU Ta "terminate process" Ta "CPU time limit exceeded (see"
.Xr setrlimit 2 )
.It Li SIGXFSZ Ta "terminate process" Ta "file size limit exceeded (see"
.Xr setrlimit 2 )
.It Li SIGVTALRM Ta "terminate process" Ta "virtual time alarm (see"
.Xr setitimer 2 )
.It Li SIGPROF Ta "terminate process" Ta "profiling timer alarm (see"
.Xr setitimer 2 )
.It Li SIGWINCH Ta "discard signal" Ta "window size change"
.It Li SIGINFO Ta "discard signal" Ta "status request from keyboard"
.It Li SIGUSR1 Ta "terminate process" Ta "user-defined signal 1"
.It Li SIGUSR2 Ta "terminate process" Ta "user-defined signal 2"
.It Li SIGPWR Ta "discard signal" Ta "power failure/restart"
.El
.Sh STANDARDS
The signals conform to
.St -p1003.1-90 ,
with the exception of
.Dv SIGTRAP ,
.Dv SIGEMT ,
.Dv SIGBUS ,
.Dv SIGSYS ,
.Dv SIGURG ,
.Dv SIGIO ,
.Dv SIGXCPU ,
.Dv SIGXFSZ ,
.Dv SIGVTALRM ,
.Dv SIGPROF ,
.Dv SIGWINCH ,
and
.Dv SIGINFO
which are Berkeley extensions (available on most
.Bx Ns \-derived
systems)
and
.Dv SIGPWR
which comes from System V. On NetBSD,
.Dv SIGPWR
was introduced in version 1.4.
.Sh NOTES
The current NetBSD kernel never generates the
.Dv SIGPWR
signal.
.Sh SEE ALSO
.Xr kill 1 ,
.Xr kill 2 ,
.Xr ptrace 2 ,
.Xr sigaction 2 ,
.Xr sigaltstack 2 ,
.Xr sigprocmask 2 ,
.Xr sigstack 2 ,
.Xr sigsuspend 2 ,
.Xr setjmp 3 ,
.Xr sigblock 3 ,
.Xr siginterrupt 3 ,
.Xr signal 3 ,
.Xr sigpause 3 ,
.Xr sigsetmask 3 ,
.Xr sigsetops 3 ,
.Xr tty 4
