#	$NetBSD: Makefile,v 1.33 2005/06/26 17:47:49 thorpej Exp $

SUBDIR=

SUBDIR+=	ramdisk-big
SUBDIR+=	ramdisk-small
SUBDIR+=	ramdisk-tiny
SUBDIR+=	ramdisk-rescuetiny

SUBDIR+=	.WAIT

SUBDIR+=	instkernel

SUBDIR+=	.WAIT

SUBDIR+=	bootfloppy
SUBDIR+=	bootfloppy-big
SUBDIR+=	bootfloppy-com
SUBDIR+=	bootfloppy-laptop-big
SUBDIR+=	bootfloppy-laptop
SUBDIR+=	bootfloppy-ps2
SUBDIR+=	bootfloppy-small
SUBDIR+=	bootfloppy-tiny
SUBDIR+=	rescue-tiny

TARGETS+=	release

.include <bsd.subdir.mk>
