# 	$NetBSD: Makefile,v 1.10.12.1 2007/11/06 23:23:32 matt Exp $

INCSDIR=/usr/include/x86

INCS=	aout_machdep.h \
	bootinfo.h bus.h \
	cacheinfo.h \
	cputypes.h \
	cpuvar.h \
	float.h \
	ieee.h ieeefp.h \
	intr.h intrdefs.h \
	lock.h \
	math.h mutex.h mtrr.h \
	pio.h \
	pmap.h \
	psl.h \
	rwlock.h \
	specialreg.h \
	sysarch.h \
	trap.h

.include <bsd.kinc.mk>
