#	$NetBSD: Makefile,v 1.3 2019/05/17 13:44:55 nakayama Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}clang-tblgen
HOSTPROG_CXX=	${_TOOL_PREFIX}clang-tblgen
HOST_SRCDIR=	external/bsd/llvm/bin/clang-tblgen

.include "${.CURDIR}/../Makefile.host"
