#!/bin/sh
# $NetBSD: script,v 1.1 2001/03/06 21:26:27 garbled Exp $

cp /dev/null /etc/usermgmt.conf
j=0
BIGLIST="group base_dir skel_dir shell inactive expire preserve password range"
for i in $BIGLIST
do
	j=`expr $j + 1`
	x=$(echo `eval echo \\$${j}` | sed -e 's/^ *//')
	if [ "$x" = "" ]; then
		continue
	fi
	n=`echo $i | wc -m`
	if [ $n -gt 7 ]; then
		echo "$i	$x" >>/etc/usermgmt.conf
	else
		echo "$i		$x" >>/etc/usermgmt.conf
	fi
done
chown root:wheel /etc/usermgmt.conf
chmod 644 /etc/usermgmt.conf
