#	$Id: Makefile,v 1.3 1993/08/02 17:43:50 mycroft Exp $

LIB=		bib
SRCS=		common.cc index.cc linear.cc search.cc map.c
CFLAGS+=	-I$(.CURDIR)/../include

NOMAN=		noman
NOPROFILE=	noprofile

install:

.include "../Makefile.cfg"
.include <bsd.lib.mk>
