.\"	$NetBSD: dosboot.8,v 1.7 2000/03/05 23:55:56 nathanw Exp $
.Dd June 20, 1997
.Os
.Dt DOSBOOT 8 i386
.Sh NAME
.Nm dosboot
.Nd boot NetBSD/i386 from DOS
.Sh SYNOPSIS
.Nm
.Op Fl u
.Op Fl c Ar <command>
.Op Fl i
.Op Ar path Op Fl bootopts
.Sh DESCRIPTION
.Nm
is an MS-DOS program.  It is a boot loader for the i386 version of
.Nx
designed to permit
.Nx
to be booted directly from MS-DOS. Per default, it boots a file with
name
.Pa NETBSD
in the current MS-DOS directory.
.Pp
The recognized options are
.Bl -tag -width bootopts
.It Fl u
Boot from an UFS filesystem instead of an MS-DOS filesystem.
.It Fl c
Execute <command> (see below).
.It Fl i
Enter interactive mode.
.Nm
will present a prompt, allowing input of commands (see below).
.Pp
.It path
Specifies the kernel file. In MS-DOS mode (default) a normal MS-DOS
filename (with or without drive specification) is accepted.
In UFS mode (after
.Fl u
or after a "mode ufs" command), a path in a
.Nx
filesystem
is expected. Per default, the file is looked up in partition 'a' of
the first harddisk. Another device or partition can be specified
by prepending a block device name in terms of
.Nx ,
followed
by a colon (see 
.Xr boot 8
and examples).
.It bootopts
Flags passed to the kernel, see
.Xr boot 8 .
.El

.Pp
The commands accepted after the
.Fl c
flag or in interactive mode are:
.Bl -tag -width help
.It help
Print an overview about commands and arguments.
.It ls Op path
Print a directory listing of path, containing inode number, filename
and file type. This command works in UFS mode only. path can
contain a device specification.
.It quit
Leave the
.Nm
program and exit to MS-DOS.
.It boot Op path Op Fl bootopts
Boot
.Nx .
.It mode { dos | ufs }
Switch filesystem type.
.It dev Op device
Set the default device and partition for subsequent filesystem operations.
Without an operand, print the current setting.
This setting doesn't apply to MS-DOS mode.
.El
.Sh EXAMPLES
To boot a
.Nx
kernel located on MS-DOS drive D, one would issue:
.Bd -literal -offset indent
dosboot D:\\NODOS\\NETBSD
.Ed
.Pp
To boot from a
.Nx
floppy into single user mode, type eg:
.Bd -literal -offset indent
dosboot -u fd0a:netbsd -s
.Ed
.Sh BUGS
.Nm
assumes that the processor is in real mode at startup. It does not work
well in the presence of MS-DOS extenders and memory managers.
.Pp
.Nm
does not run directly under Windows 95. See
.Xr w95boot 8
for a method of starting NetBSD from Windows 95 using dosboot.
.Pp
In UFS mode, files can only be loaded from devices known to the BIOS.
The device names do not necessarily comply with the names later
used by the booted
.Nx
kernel.
.Pp
In MS-DOS mode, no useful boot device specification is passed to
.Nx .
It is necessary to have the root device hardwired into the kernel
configuration or to enter it manually.
.Sh SEE ALSO
.Xr boot 8 ,
.Xr w95boot 8
.Sh HISTORY
The
.Nx Ns Tn /i386
.Nm
command first appeared in
.Nx 1.3 .
