#	$NetBSD: Makefile,v 1.4 1999/01/18 02:11:07 castor Exp $

KDIR=	/sys/arch/mips/include
INCSDIR= /usr/include/mips

INCS=	ansi.h aout_machdep.h asm.h bswap.h bsd-aout.h cachectl.h cdefs.h \
	conf.h cpu.h cpuregs.h db_machdep.h ecoff_machdep.h elf.h \
	elf_machdep.h  endian.h float.h ieeefp.h intr.h kcore.h kdbparam.h \
	limits.h locore.h mips1_pte.h mips3_pte.h mips_opcode.h mips_param.h \
	pcb.h pmap.h proc.h profile.h psl.h pte.h ptrace.h reg.h regnum.h \
	reloc.h setjmp.h signal.h stdarg.h sysarch.h trap.h types.h varargs.h \
	vmparam.h

.include <bsd.kinc.mk>
