# $NetBSD: Makefile,v 1.3.2.2 2008/01/09 01:59:06 matt Exp $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/fs

SUBDIR=	puffs tmpfs

FILES= h_funcs.subr
FILESDIR= ${TESTSDIR}

.include <bsd.test.mk>
.include <bsd.subdir.mk>
