# $NetBSD: Makefile,v 1.3 2007/12/26 20:50:31 jmmv Exp $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/fs

SUBDIR=	puffs tmpfs

FILES= h_funcs.subr
FILESDIR= ${TESTSDIR}

.include <bsd.test.mk>
.include <bsd.subdir.mk>
