.\"
.\" Copyright © 2007 Alistair Crooks.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote
.\"    products derived from this software without specific prior written
.\"    permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
.\" OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
.\" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
.\" GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\" WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
.\" NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd April 15, 2007
.Dt ID3FS 8
.Os
.Sh NAME
.Nm id3fs
.Nd refuse-based virtual file system to display mp3 tree by id3 tags
.Sh SYNOPSIS
.Nm
.Op Fl v
.Ar Fl p Ar music-directory
.Ar mount_point
.Sh DESCRIPTION
The
.Nm
utility can be used to mount a number of directory tree
under the
mount point, using id3 tags
to make the artists, genres and years appear as virtual directories.
The 
.Nm
utility makes use of the
.Xr virtdir 3
virtual directory routines.
Underneath those virtual directories, the individual trackes will be
displayed by category, allowing a different view of the id3-tagged
files from the standard one.
.Pp
The
.Xr refuse 3
library is used to provide the file system features.
.Pp
The mandatory parameter is
the local mount
point.
.Pp
The id3 package, found in pkgsrc/audio/id3, is necessary
to run this package.
.Pp
Two shel lscripts are also included, which must be used to build up an id3
database in advance. First id3info.sh must be run, followed by id3db.sh.
.Sh SEE ALSO
.Xr librefuse 3 ,
.Xr puffs 3 ,
.Xr virtdir 3 .
.Sh HISTORY
The
.Nm
utility first appeared in
.Nx 5.0 .
