# $NetBSD: Makefile,v 1.2.4.2 2007/12/20 16:54:00 apb Exp $

.include <bsd.own.mk>

SRCDIR=		${NETBSDSRCDIR}/dist/atf
.PATH:		${SRCDIR}/data

CONFIGFILES=	NetBSD.conf atf-run.hooks
FILESDIR=	/etc/atf
FILESMODE=	644

.include <bsd.files.mk>
