# $NetBSD: Makefile,v 1.2 2004/12/12 08:18:44 christos Exp $
# $FreeBSD: src/lib/libpam/modules/pam_exec/Makefile,v 1.2 2003/03/09 20:06:35 obrien Exp $

LIB=	pam_exec
SRCS=	pam_exec.c
MAN=	pam_exec.8

.include "${.CURDIR}/../mod.mk"
