#	$NetBSD: Makefile,v 1.5.10.3 2004/09/21 13:23:07 skrll Exp $

.if ${MACHINE} == sparc64
SUBDIR=	../../sparc/stand/ofwboot
SUBDIR+=../../sparc/stand/bootblk
SUBDIR+=../../sparc/stand/binstall 
.endif

.include <bsd.subdir.mk>
