#	$NetBSD: Makefile,v 1.2 2001/12/12 01:49:30 tv Exp $

FILES=	form help
FILESDIR=${BINDIR}/sushi/system/localtime
SCRIPTS= script script1
SCRIPTSDIR=${BINDIR}/sushi/system/localtime
NOOBJ=	# defined

.include "../../../Makefile.inc"
.include <bsd.prog.mk>
