#	$NetBSD: Makefile,v 1.1 2008/07/29 13:17:41 pooka Exp $
#

.PATH:		${.CURDIR}/../../sys/rump/librump/rumpuser

LIBDPLIBS+=     pthread ${.CURDIR}/../libpthread
MAN=		rumpuser.3

.include "${.CURDIR}/../../sys/rump/librump/rumpuser/Makefile"
