#	$NetBSD: Makefile.rumpfs,v 1.8.12.1 2008/09/18 04:37:03 wrstuden Exp $
#

RUMPFSLIST=	cd9660 efs ext2fs ffs hfs lfs msdos ntfs syspuffs sysvbfs
RUMPFSLIST+=	tmpfs udf

RUMPFSALL=	${RUMPFSLIST} ufs

.for var in ${RUMPFSALL}
RUMPFSLIBS+=lib${var}
RUMPFSLDADD+=-lrumpfs_${var}
.endfor
