.\"	$NetBSD: reboot_amiga.8,v 1.3 1995/03/18 14:59:28 cgd Exp $
.\"
.\" Copyright (c) 1991 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" This code is derived from software written and contributed
.\" to Berkeley by William Jolitz.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)reboot_i386.8	1.2 (Berkeley) 4/25/91
.\"
.Dd April 25, 1991
.Dt REBOOT 8
.Os
.Sh NAME
.Nm reboot
.Nd
.Tn NetBSD
bootstrapping procedures
.Sh SYNOPSIS
.Nm reboot
.Op Fl n
.Op Fl q
.Sh DESCRIPTION
The
.Tn NetBSD 
kernel, an ordinary executable file,
is placed into chip memory by bootstrap.
Upon startup, the system reorganizes memory to suit the needs of
the hardware configuration found and copies itself to virtual memory,
thus it is not designed to
be restartable without being reloaded on reboot.
Each time it is to be bootstrapped, it must be reloaded, usually from
a disk file.
.Pp
.Sy Rebooting a running system .
When a
.Tn NetBSD
kernel is running and a reboot is desired,
.Xr shutdown 8
is normally used.
If there are no users then
.Nm reboot
can be used.
Reboot causes the disks to be synced and allows the system
to perform other shutdown activities such as resynchronizing
hardware time-of-day clocks.
.Pp
Options to reboot are:
.Bl -tag -width indent
.It Fl n
option avoids the sync.  It can be used if a disk or the processor
is on fire. 
.It Fl q
reboots quickly and ungracefully, without shutting down running
processes first.
.El
.Pp
.Nm Reboot
normally logs the reboot using
.Xr syslog 8
and places a shutdown record in the login accounting file
.Pa /var/log/wtmp .
These actions are inhibited if the
.Fl n
or
.Fl q
options are present.
.Pp
.Sy Cold  starts .
The
.Tn "Amiga"
currently does not attempt to boot NetBSD on power up.
.Sh SEE ALSO
.Xr crash 8 ,
.Xr halt 8 ,
.Xr shutdown 8 ,
.Xr syslogd 8
