#	$NetBSD: Makefile,v 1.1 2007/03/06 21:56:58 bouyer Exp $
CDBASE=		evbarmcd		# gives ${CDBASE}.iso
CDRELEASE=	true			# include $RELEASEDIR/$MACHINE

.include "${.CURDIR}/../../../common/Makefile.bootcd"
