#	$NetBSD: Makefile,v 1.2.34.2 2020/04/13 07:45:26 martin Exp $

CDBASE=		evbarm-${MACHINE_ARCH}cd	# gives ${CDBASE}.iso
CDRELEASE=	true				# include $RELEASEDIR/$RELEASEMACHINEDIR
CDRELEASE_NODEBUG=	true

.include "${.CURDIR}/../../../common/Makefile.bootcd"
