#	$NetBSD: Makefile,v 1.1 1997/10/16 17:30:57 augustss Exp $

LIB=	ossaudio
MAN=	ossaudio.3

SRCS=	ossaudio.c

CFLAGS+= -I${.CURDIR}

INCS=	soundcard.h
INCSDIR=/usr/include/sys

.include <bsd.lib.mk>

