G_GDB_OBJS=\
ada-exp.o \
ada-lang.o \
ada-typeprint.o \
ada-valprint.o \
annotate.o \
arch-utils.o \
auxv.o \
ax-gdb.o \
ax-general.o \
bcache.o \
bfd-target.o \
block.o \
blockframe.o \
breakpoint.o \
bsd-kvm.o \
buildsym.o \
c-exp.o \
c-lang.o \
c-typeprint.o \
c-valprint.o \
charset.o \
cli-cmds.o \
cli-decode.o \
cli-dump.o \
cli-interp.o \
cli-logging.o \
cli-out.o \
cli-script.o \
cli-setshow.o \
cli-utils.o \
coff-pe-read.o \
coffread.o \
complaints.o \
completer.o \
copying.o \
corefile.o \
corelow.o \
cp-abi.o \
cp-name-parser.o \
cp-namespace.o \
cp-support.o \
cp-valprint.o \
dbxread.o \
dcache.o \
demangle.o \
dictionary.o \
disasm.o \
doublest.o \
dummy-frame.o \
dwarf2-frame.o \
dwarf2expr.o \
dwarf2loc.o \
dwarf2read.o \
dwarfread.o \
elfread.o \
environ.o \
eval.o \
event-loop.o \
event-top.o \
exceptions.o \
exec.o \
expprint.o \
f-exp.o \
f-lang.o \
f-typeprint.o \
f-valprint.o \
findvar.o \
fork-child.o \
frame-base.o \
frame-unwind.o \
frame.o \
gdb-events.o \
gdb.o \
gdbarch.o \
gdbtypes.o \
gnu-v2-abi.o \
gnu-v3-abi.o \
hpacc-abi.o \
i386-tdep.o \
i386bsd-nat.o \
i386bsd-tdep.o \
i386nbsd-nat.o \
i386nbsd-tdep.o \
i387-tdep.o \
inf-child.o \
inf-loop.o \
inf-ptrace.o \
infcall.o \
infcmd.o \
inflow.o \
infrun.o \
init.o \
interps.o \
jv-exp.o \
jv-lang.o \
jv-typeprint.o \
jv-valprint.o \
kod-cisco.o \
kod.o \
language.o \
linespec.o \
m2-exp.o \
m2-lang.o \
m2-typeprint.o \
m2-valprint.o \
macrocmd.o \
macroexp.o \
macroscope.o \
macrotab.o \
main.o \
maint.o \
mdebugread.o \
mem-break.o \
memattr.o \
mi-cmd-break.o \
mi-cmd-disas.o \
mi-cmd-env.o \
mi-cmd-file.o \
mi-cmd-stack.o \
mi-cmd-var.o \
mi-cmds.o \
mi-common.o \
mi-console.o \
mi-getopt.o \
mi-interp.o \
mi-main.o \
mi-out.o \
mi-parse.o \
mi-symbol-cmds.o \
minsyms.o \
mipsread.o \
nbsd-tdep.o \
nlmread.o \
objc-exp.o \
objc-lang.o \
objfiles.o \
observer.o \
osabi.o \
p-exp.o \
p-lang.o \
p-typeprint.o \
p-valprint.o \
parse.o \
printcmd.o \
regcache.o \
reggroups.o \
regset.o \
remote-fileio.o \
remote-utils.o \
remote.o \
scm-exp.o \
scm-lang.o \
scm-valprint.o \
sentinel-frame.o \
ser-base.o \
ser-pipe.o \
ser-tcp.o \
ser-unix.o \
serial.o \
signals.o \
solib-null.o \
solib-svr4.o \
solib.o \
source.o \
stabsread.o \
stack.o \
std-regs.o \
symfile.o \
symmisc.o \
symtab.o \
target.o \
thread.o \
top.o \
tracepoint.o \
trad-frame.o \
tramp-frame.o \
typeprint.o \
ui-file.o \
ui-out.o \
user-regs.o \
utils.o \
valarith.o \
valops.o \
valprint.o \
value.o \
varobj.o \
version.o \
wrapper.o \

G_TUI_OBJS=\
tui-command.o \
tui-data.o \
tui-disasm.o \
tui-file.o \
tui-hooks.o \
tui-interp.o \
tui-io.o \
tui-layout.o \
tui-main.o \
tui-out.o \
tui-regs.o \
tui-source.o \
tui-stack.o \
tui-win.o \
tui-windata.o \
tui-wingeneral.o \
tui-winsource.o \
tui.o

G_BFD_OBJS=\
aout32.o \
archive.o \
archive64.o \
archures.o \
bfd.o \
bfdio.o \
bfdwin.o \
binary.o \
cache.o \
coffgen.o \
corefile.o \
cpu-i386.o \
dwarf1.o \
dwarf2.o \
elf-eh-frame.o \
elf-strtab.o \
elf-vxworks.o \
elf.o \
elf32-gen.o \
elf32-i386.o \
elf32.o \
elflink.o \
format.o \
hash.o \
i386netbsd.o \
ihex.o \
init.o \
libbfd.o \
linker.o \
merge.o \
netbsd-core.o \
opncls.o \
reloc.o \
section.o \
simple.o \
srec.o \
stab-syms.o \
stabs.o \
syms.o \
targets.o \
tekhex.o \

G_BFD_CPPFLAGS=-DDEFAULT_VECTOR=bfd_elf32_i386_vec -DSELECT_VECS='&bfd_elf32_i386_vec,&i386netbsd_vec,&bfd_elf32_little_generic_vec,&bfd_elf32_big_generic_vec' -DSELECT_ARCHITECTURES='&bfd_i386_arch' -DHAVE_bfd_elf32_i386_vec -DHAVE_i386netbsd_vec -DHAVE_bfd_elf32_little_generic_vec -DHAVE_bfd_elf32_big_generic_vec

G_OPCODES_OBJS=\
dis-buf.o \
dis-init.o \
disassemble.o \
i386-dis.o
