#	$NetBSD: Makefile,v 1.12 1997/05/06 20:45:56 gwr Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

PROG=	xinstall
SRCS=	stat_flags.c xinstall.c
MAN=	install.1
.PATH.c: ${.CURDIR}/../../bin/ls

PROGNAME=install

.include <bsd.prog.mk>
