#	$NetBSD: Makefile,v 1.6.2.1 2001/04/21 17:49:10 bouyer Exp $

# use 'make -f Makefile.pcidevs' to make pcidevs.h and pcidevs_data.h

INCSDIR= /usr/include/dev/pci

# Only install includes which are used by userland
INCS=	if_lmc_types.h if_lmcioctl.h tgareg.h

.include <bsd.kinc.mk>
