#!/bin/sh
#
#	$NetBSD: gen_md5,v 1.1 2002/10/29 14:05:33 blymn Exp $
#
# This is a helper script that scans all the file systems for
# executables and generates an entry in the signatures file for
# each one found.  The script is probably best run by root and
# will move the old signatures file prior to starting the real work.
#
mv signatures signatures.old
echo "Fingerprinting the system, this may take a while...."
#
find / \( \( -type f -a \( -perm -0100 -o -perm -0010 -o -perm -0001 \) \) -o -name 'lib*so*' \) -print | while read line
do
	echo "Fingerprinting $line"
	hash=`md5 $line | cut -d'=' -f2 | tr -d ' '`
	flag=""
	if [ ! -x $line ]
	then
	    flag="	FILE"
	fi
	echo "$line	md5	${hash}${flag}" >> signatures
done
