#	$NetBSD: Makefile,v 1.2 2008/10/31 23:41:48 christos Exp $

.include <bsd.own.mk>

_CURDIR:= ${.CURDIR}

.CURDIR:=${NETBSDSRCDIR}/gnu/lib/libgcc4

.include "${.CURDIR}/Makefile"

.CURDIR:= ${_CURDIR}
