#	$NetBSD: Makefile,v 1.1.80.1 2018/09/30 01:45:06 pgoyette Exp $
CDBASE=		sun2cd			# gives ${CDBASE}.iso
CDRELEASE=	true			# include $RELEASEDIR/$MACHINE
CDRELEASE_NODEBUG=	true

.include "${.CURDIR}/../../../common/Makefile.bootcd"
