#	$NetBSD: Makefile,v 1.12 2002/03/07 19:34:37 thorpej Exp $

KDIR=	/sys/arch/sh3/include
INCSDIR= /usr/include/sh3

INCS=	ansi.h aout_machdep.h asm.h \
	bootinfo.h bscreg.h bswap.h bus.h \
	cdefs.h coff_machdep.h cpgreg.h cpu.h cputypes.h \
	db_disasm.h db_machdep.h disklabel.h \
	elf_machdep.h endian.h endian_machdep.h \
	float.h frame.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intcreg.h intr.h \
	limits.h lock.h \
	math.h \
	param.h pcb.h pfcreg.h pmap.h proc.h profile.h psl.h \
	pte.h ptrace.h \
	reg.h rtcreg.h \
	scifreg.h scireg.h setjmp.h sh_opcode.h shbvar.h \
	signal.h stdarg.h \
	tmureg.h trap.h trapreg.h types.h \
	ubcreg.h \
	va-sh.h varargs.h vmparam.h \
	wdogvar.h wdtreg.h

.include <bsd.kinc.mk>
