#	$NetBSD: Makefile,v 1.6 2000/03/17 22:36:40 tron Exp $

KDIR=	/sys/arch/sh3/include
INCSDIR= /usr/include/sh3

INCS=	ansi.h aout_machdep.h asm.h bootinfo.h bscreg.h bswap.h bus.h \
	ccrreg.h cdefs.h coff_machdep.h cpgreg.h cpu.h cpufunc.h cputypes.h \
	db_disasm.h db_machdep.h disklabel.h elf_machdep.h endian.h \
	endian_machdep.h float.h frame.h ieee.h ieeefp.h intcreg.h intr.h \
	limits.h math.h mmureg.h param.h pcb.h pfcreg.h pio.h pmap.h proc.h \
	profile.h psl.h pte.h ptrace.h reg.h rtcreg.h scifreg.h scireg.h \
	segments.h setjmp.h sh_opcode.h shbvar.h signal.h stdarg.h tmureg.h \
	trap.h trapreg.h types.h ubcreg.h va-sh.h varargs.h vmparam.h \
	wdogvar.h wdtreg.h

.include <bsd.kinc.mk>
