# $NetBSD: Makefile,v 1.3 2007/11/21 15:39:34 jmmv Exp $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/util

SUBDIR=		df id ps sh systrace

TESTS_SH=	t_cp
TESTS_SH+=	t_dd
TESTS_SH+=	t_expr
TESTS_SH+=	t_pax
TESTS_SH+=	t_tar

.include <bsd.test.mk>
.include <bsd.subdir.mk>
