#	$NetBSD: Makefile.giodevs,v 1.4.78.1 2009/05/04 08:11:49 yamt Exp $

.include <bsd.sys.mk>

giodevs.h: giodevs devlist2h.awk
	/bin/rm -f giodevs.h giodevs_data.h
	${TOOL_AWK} -f devlist2h.awk giodevs
