#	$Id: Makefile,v 1.4 1993/12/21 04:09:56 brezak Exp $

# missing: bin libexec sbin usr.bin usr.sbin share games gnu

SUBDIR+= include lib sys

regress: _SUBDIRUSE

install:

.include <bsd.subdir.mk>
