#	$NetBSD: Makefile,v 1.10 2026/03/31 20:24:19 yurix Exp $

# Important: Regenerate dtb set lists by running 'make update-sets' in
# sys/arch/dtb after changing this file.

TARGETS+=	dtblist

SUBDIR+=	allwinner
SUBDIR+=	amlogic
SUBDIR+=	arm
SUBDIR+=	broadcom
SUBDIR+=	nvidia
SUBDIR+=	intel
SUBDIR+=	nxp
SUBDIR+=	rockchip
SUBDIR+=	samsung
SUBDIR+=	ti
SUBDIR+=	xilinx

.include <bsd.subdir.mk>
