#	$NetBSD: Makefile,v 1.1.42.1 2015/12/27 12:10:13 skrll Exp $
#

.PATH:  ${.CURDIR}/../../../../ufs/mfs

LIB=	rumpfs_mfs
COMMENT=Memory File System (in-memory FFS)

SRCS=	mfs_vfsops.c mfs_vnops.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
