#	$NetBSD: Makefile,v 1.4 2003/03/24 15:04:04 atatat Exp $
#	install these sources in /usr/share/sendmail/hack

.include <bsd.own.mk>

DIST=		${NETBSDSRCDIR}/gnu/dist
.PATH: ${DIST}/sendmail/cf/hack

.include <Makefile.inc>

FILESDIR=	/usr/share/sendmail/hack
FILES=		${CF_HACK_FILES} Makefile.inc

all:

.include <bsd.prog.mk>
