#	from: @(#)Makefile	8.1 (Berkeley) 6/6/93
#	$Id: Makefile,v 1.4 1994/06/18 20:55:54 cgd Exp $

PROG=	chown
CFLAGS+=-DSUPPORT_DOT
MAN1=	chgrp.0
MAN8=	chown.0
LINKS=	${BINDIR}/chown /usr/bin/chgrp

.include <bsd.prog.mk>
