#	$NetBSD: Makefile,v 1.2 2018/05/31 05:27:46 mrg Exp $

NOMAN=	# defined

.include <bsd.own.mk>

.if ${MKFIRMWARE} != "no"
FILES=	run-rt2870 run-rt3071 run-license
.endif

# XXX
includes:

clean:

cleandir:

.include <bsd.files.mk>
