.\"	$NetBSD: new_panel.3,v 1.3 2015/10/28 10:22:40 wiz Exp $
.\"
.\" Copyright (c) 2015 Valery Ushakov
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd October 28, 2015
.Dt NEW_PANEL 3
.Os
.Sh NAME
.Nm new_panel ,
.Nm panel_window ,
.Nm replace_panel ,
.Nm del_panel
.Nd panel routines
.Sh LIBRARY
.Lb libpanel
.Sh SYNOPSIS
.In panel.h
.\"
.Ft PANEL *
.Fn new_panel "WINDOW *win"
.\"
.Ft WINDOW *
.Fn panel_window "PANEL *p"
.\"
.Ft int
.Fn replace_panel "PANEL *p" "WINDOW *win"
.\"
.Ft int
.Fn del_panel "PANEL *p"
.\"
.Sh DESCRIPTION
The funcion
.Fn new_panel
creates a new panel associated with the curses window
.Fa win .
The new panel is visible and is placed at the top of the deck.
.Pp
The curses window associated with a panel may be obtained with
.Fn panel_window
and changed with
.Fn replace_panel .
.Pp
The function
.Fn del_panel
hides the panel and deletes it.
Note that the curses window associated with the panel is not deleted.
.Sh RETURN VALUES
Functions returning pointers will return
.Dv NULL
if an error is detected.
The functions that return an int will return one of the following
values:
.Pp
.Bl -tag -width ".Dv ERR" -compact
.It Dv OK
The function completed successfully.
.It Dv ERR
An error occurred in the function.
.El
.Sh SEE ALSO
.Xr panel 3
