#	$NetBSD: Makefile.inc,v 1.3 2005/02/01 17:02:57 shige Exp $
#
#	etc.evbppc/Makefile.inc -- evbppc-specific etc Makefile targets
#

KERNEL_SETS=		WALNUT EV64260 EXPLORA451 OPENBLOCKS266
KERNEL_SUFFIXES=	img

BUILD_KERNELS=		INSTALL_WALNUT
