#	$NetBSD: Makefile,v 1.3 1997/10/11 20:24:06 mycroft Exp $

LIB=	common
SRCS=	allow.c board.c check.c fancy.c init.c odds.c one.c save.c subs.c \
	table.c

NOPROFILE=	noprofile
NOPIC=		nopic

# only needed during build
libinstall::

.include <bsd.lib.mk>
