#	$NetBSD: Makefile,v 1.8.18.1 2008/05/18 12:29:48 yamt Exp $

LIBISPRIVATE=	yes

LIB=		common
SRCS=		allow.c board.c check.c fancy.c init.c odds.c \
		one.c save.c subs.c table.c

.include <bsd.lib.mk>
