#	$NetBSD: Makefile,v 1.3 1998/10/01 04:16:33 erh Exp $

SUBDIR=	common alpha i386
#SUBDIR+= arm mips m68k ppc sparc sparc64

KDIR=	/sys/compat/linux
INCSDIR= /usr/include/compat/linux

.include <bsd.subdir.mk>
.include <bsd.kinc.mk>
