#	from: @(#)Makefile	5.16 (Berkeley) 4/26/91
#	$Id: Makefile,v 1.3 1993/07/31 15:26:00 mycroft Exp $

PROG=	xebec
SRCS=	llparse.c llscan.c main.c malloc.c procs.c putdriver.c sets.c xebec.c
CFLAGS+= -DDEBUG -traditional
NOMAN = noman

.include <bsd.prog.mk>
