#	$NetBSD: Makefile,v 1.7 1999/02/13 02:54:54 lukem Exp $
#	@(#)Makefile	5.16 (Berkeley) 4/26/91

PROG=	xebec
SRCS=	llparse.c llscan.c main.c malloc.c procs.c putdriver.c sets.c xebec.c
CPPFLAGS+= -DDEBUG -traditional
MKMAN=	no

.include <bsd.prog.mk>
