#	$NetBSD: Makefile,v 1.3 2004/09/28 15:06:15 erh Exp $

FILES=	form help
FILESDIR=${BINDIR}/sushi/system/dailyconf
SCRIPTS= script script1 script2 script3
SCRIPTSDIR=${BINDIR}/sushi/system/dailyconf
NOOBJ=	# defined

.include "../../../Makefile.inc"
.include <bsd.prog.mk>
