#	$NetBSD: Makefile,v 1.2 2001/12/12 01:49:28 tv Exp $

FILES=	form help
FILESDIR=${BINDIR}/sushi/procs/startprocs
SCRIPTS= script script1
SCRIPTSDIR=${BINDIR}/sushi/procs/startprocs
NOOBJ=	# defined

.include "../../../Makefile.inc"
.include <bsd.prog.mk>
