#	from: @(#)Makefile	5.3 (Berkeley) 5/27/90
#	$Id: Makefile,v 1.2 1993/07/31 15:19:24 mycroft Exp $

PROG=	whatis
SRCS=	whatis.c config.c
.PATH:	${.CURDIR}/../man

.include "../../Makefile.inc"
.include <bsd.prog.mk>
