/* $NetBSD: linux_sysent.c,v 1.27 2000/12/26 01:57:57 itohy Exp $ */

/*
 * System call switch table.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from	NetBSD: syscalls.master,v 1.26 2000/12/26 01:57:10 itohy Exp 
 */

#if defined(_KERNEL) && !defined(_LKM)
#include "opt_compat_netbsd.h"
#include "opt_compat_43.h"
#endif
#include <sys/param.h>
#include <sys/poll.h>
#include <sys/systm.h>
#include <sys/signal.h>
#include <sys/mount.h>
#include <sys/syscallargs.h>
#include <compat/linux/common/linux_types.h>
#include <compat/linux/common/linux_signal.h>
#include <compat/linux/common/linux_siginfo.h>
#include <compat/linux/common/linux_machdep.h>
#include <compat/linux/linux_syscallargs.h>

#define	s(type)	sizeof(type)

struct sysent linux_sysent[] = {
	{ 0, 0,
	    sys_nosys },			/* 0 = syscall */
	{ 1, s(struct sys_exit_args),
	    sys_exit },				/* 1 = exit */
	{ 0, 0,
	    sys_fork },				/* 2 = fork */
	{ 3, s(struct sys_read_args),
	    sys_read },				/* 3 = read */
	{ 3, s(struct sys_write_args),
	    sys_write },			/* 4 = write */
	{ 3, s(struct linux_sys_open_args),
	    linux_sys_open },			/* 5 = open */
	{ 1, s(struct sys_close_args),
	    sys_close },			/* 6 = close */
	{ 3, s(struct linux_sys_waitpid_args),
	    linux_sys_waitpid },		/* 7 = waitpid */
	{ 2, s(struct linux_sys_creat_args),
	    linux_sys_creat },			/* 8 = creat */
	{ 2, s(struct sys_link_args),
	    sys_link },				/* 9 = link */
	{ 1, s(struct linux_sys_unlink_args),
	    linux_sys_unlink },			/* 10 = unlink */
	{ 3, s(struct linux_sys_execve_args),
	    linux_sys_execve },			/* 11 = execve */
	{ 1, s(struct linux_sys_chdir_args),
	    linux_sys_chdir },			/* 12 = chdir */
	{ 1, s(struct linux_sys_time_args),
	    linux_sys_time },			/* 13 = time */
	{ 3, s(struct linux_sys_mknod_args),
	    linux_sys_mknod },			/* 14 = mknod */
	{ 2, s(struct linux_sys_chmod_args),
	    linux_sys_chmod },			/* 15 = chmod */
	{ 3, s(struct linux_sys_chown16_args),
	    linux_sys_chown16 },		/* 16 = chown16 */
	{ 0, 0,
	    sys_nosys },			/* 17 = obsolete break */
	{ 0, 0,
	    sys_nosys },			/* 18 = obsolete ostat */
#if !defined(_KERNEL) || defined(COMPAT_43)
	{ 3, s(struct compat_43_sys_lseek_args),
	    compat_43_sys_lseek },		/* 19 = lseek */
#else
	{ 0, 0,
	    sys_nosys },			/* 19 = unimplemented compat_43_sys_lseek */
#endif
	{ 0, 0,
	    sys_getpid },			/* 20 = getpid */
	{ 0, 0,
	    sys_nosys },			/* 21 = unimplemented mount */
	{ 0, 0,
	    sys_nosys },			/* 22 = obsolete umount */
	{ 1, s(struct linux_sys_setuid16_args),
	    linux_sys_setuid16 },		/* 23 = setuid16 */
	{ 0, 0,
	    linux_sys_getuid16 },		/* 24 = getuid16 */
	{ 1, s(struct linux_sys_stime_args),
	    linux_sys_stime },			/* 25 = stime */
	{ 4, s(struct linux_sys_ptrace_args),
	    linux_sys_ptrace },			/* 26 = ptrace */
	{ 1, s(struct linux_sys_alarm_args),
	    linux_sys_alarm },			/* 27 = alarm */
	{ 0, 0,
	    sys_nosys },			/* 28 = obsolete ofstat */
	{ 0, 0,
	    linux_sys_pause },			/* 29 = pause */
	{ 2, s(struct linux_sys_utime_args),
	    linux_sys_utime },			/* 30 = utime */
	{ 0, 0,
	    sys_nosys },			/* 31 = obsolete stty */
	{ 0, 0,
	    sys_nosys },			/* 32 = obsolete gtty */
	{ 2, s(struct linux_sys_access_args),
	    linux_sys_access },			/* 33 = access */
	{ 1, s(struct linux_sys_nice_args),
	    linux_sys_nice },			/* 34 = nice */
	{ 0, 0,
	    sys_nosys },			/* 35 = obsolete ftime */
	{ 0, 0,
	    sys_sync },				/* 36 = sync */
	{ 2, s(struct linux_sys_kill_args),
	    linux_sys_kill },			/* 37 = kill */
	{ 2, s(struct linux_sys_rename_args),
	    linux_sys_rename },			/* 38 = rename */
	{ 2, s(struct linux_sys_mkdir_args),
	    linux_sys_mkdir },			/* 39 = mkdir */
	{ 1, s(struct linux_sys_rmdir_args),
	    linux_sys_rmdir },			/* 40 = rmdir */
	{ 1, s(struct sys_dup_args),
	    sys_dup },				/* 41 = dup */
	{ 1, s(struct linux_sys_pipe_args),
	    linux_sys_pipe },			/* 42 = pipe */
	{ 1, s(struct linux_sys_times_args),
	    linux_sys_times },			/* 43 = times */
	{ 0, 0,
	    sys_nosys },			/* 44 = obsolete prof */
	{ 1, s(struct linux_sys_brk_args),
	    linux_sys_brk },			/* 45 = brk */
	{ 1, s(struct linux_sys_setgid16_args),
	    linux_sys_setgid16 },		/* 46 = setgid16 */
	{ 0, 0,
	    linux_sys_getgid16 },		/* 47 = getgid16 */
	{ 2, s(struct linux_sys_signal_args),
	    linux_sys_signal },			/* 48 = signal */
	{ 0, 0,
	    linux_sys_geteuid16 },		/* 49 = geteuid16 */
	{ 0, 0,
	    linux_sys_getegid16 },		/* 50 = getegid16 */
	{ 1, s(struct sys_acct_args),
	    sys_acct },				/* 51 = acct */
	{ 0, 0,
	    sys_nosys },			/* 52 = unimplemented umount */
	{ 0, 0,
	    sys_nosys },			/* 53 = obsolete lock */
	{ 3, s(struct linux_sys_ioctl_args),
	    linux_sys_ioctl },			/* 54 = ioctl */
	{ 3, s(struct linux_sys_fcntl_args),
	    linux_sys_fcntl },			/* 55 = fcntl */
	{ 0, 0,
	    sys_nosys },			/* 56 = obsolete mpx */
	{ 2, s(struct sys_setpgid_args),
	    sys_setpgid },			/* 57 = setpgid */
	{ 0, 0,
	    sys_nosys },			/* 58 = obsolete ulimit */
	{ 0, 0,
	    sys_nosys },			/* 59 = unimplemented oldolduname */
	{ 1, s(struct sys_umask_args),
	    sys_umask },			/* 60 = umask */
	{ 1, s(struct sys_chroot_args),
	    sys_chroot },			/* 61 = chroot */
	{ 0, 0,
	    sys_nosys },			/* 62 = unimplemented ustat */
	{ 2, s(struct sys_dup2_args),
	    sys_dup2 },				/* 63 = dup2 */
	{ 0, 0,
	    sys_getppid },			/* 64 = getppid */
	{ 0, 0,
	    sys_getpgrp },			/* 65 = getpgrp */
	{ 0, 0,
	    sys_setsid },			/* 66 = setsid */
	{ 3, s(struct linux_sys_sigaction_args),
	    linux_sys_sigaction },		/* 67 = sigaction */
	{ 0, 0,
	    linux_sys_siggetmask },		/* 68 = siggetmask */
	{ 1, s(struct linux_sys_sigsetmask_args),
	    linux_sys_sigsetmask },		/* 69 = sigsetmask */
	{ 2, s(struct linux_sys_setreuid16_args),
	    linux_sys_setreuid16 },		/* 70 = setreuid16 */
	{ 2, s(struct linux_sys_setregid16_args),
	    linux_sys_setregid16 },		/* 71 = setregid16 */
	{ 3, s(struct linux_sys_sigsuspend_args),
	    linux_sys_sigsuspend },		/* 72 = sigsuspend */
	{ 1, s(struct linux_sys_sigpending_args),
	    linux_sys_sigpending },		/* 73 = sigpending */
#if !defined(_KERNEL) || defined(COMPAT_43)
	{ 2, s(struct compat_43_sys_sethostname_args),
	    compat_43_sys_sethostname },	/* 74 = sethostname */
	{ 2, s(struct compat_43_sys_setrlimit_args),
	    compat_43_sys_setrlimit },		/* 75 = setrlimit */
	{ 2, s(struct compat_43_sys_getrlimit_args),
	    compat_43_sys_getrlimit },		/* 76 = getrlimit */
#else
	{ 0, 0,
	    sys_nosys },			/* 74 = unimplemented compat_43_sys_sethostname */
	{ 0, 0,
	    sys_nosys },			/* 75 = unimplemented compat_43_sys_setrlimit */
	{ 0, 0,
	    sys_nosys },			/* 76 = unimplemented compat_43_sys_getrlimit */
#endif
	{ 2, s(struct sys_getrusage_args),
	    sys_getrusage },			/* 77 = getrusage */
	{ 2, s(struct sys_gettimeofday_args),
	    sys_gettimeofday },			/* 78 = gettimeofday */
	{ 2, s(struct sys_settimeofday_args),
	    sys_settimeofday },			/* 79 = settimeofday */
	{ 2, s(struct sys_getgroups_args),
	    sys_getgroups },			/* 80 = getgroups */
	{ 2, s(struct sys_setgroups_args),
	    sys_setgroups },			/* 81 = setgroups */
	{ 1, s(struct linux_sys_oldselect_args),
	    linux_sys_oldselect },		/* 82 = oldselect */
	{ 2, s(struct linux_sys_symlink_args),
	    linux_sys_symlink },		/* 83 = symlink */
#if !defined(_KERNEL) || defined(COMPAT_43)
	{ 2, s(struct compat_43_sys_lstat_args),
	    compat_43_sys_lstat },		/* 84 = oolstat */
#else
	{ 0, 0,
	    sys_nosys },			/* 84 = unimplemented compat_43_sys_lstat */
#endif
	{ 3, s(struct linux_sys_readlink_args),
	    linux_sys_readlink },		/* 85 = readlink */
	{ 1, s(struct linux_sys_uselib_args),
	    linux_sys_uselib },			/* 86 = uselib */
	{ 1, s(struct linux_sys_swapon_args),
	    linux_sys_swapon },			/* 87 = swapon */
	{ 4, s(struct linux_sys_reboot_args),
	    linux_sys_reboot },			/* 88 = reboot */
	{ 3, s(struct linux_sys_readdir_args),
	    linux_sys_readdir },		/* 89 = readdir */
	{ 1, s(struct linux_sys_old_mmap_args),
	    linux_sys_old_mmap },		/* 90 = old_mmap */
	{ 2, s(struct sys_munmap_args),
	    sys_munmap },			/* 91 = munmap */
	{ 2, s(struct linux_sys_truncate_args),
	    linux_sys_truncate },		/* 92 = truncate */
#if !defined(_KERNEL) || defined(COMPAT_43)
	{ 2, s(struct compat_43_sys_ftruncate_args),
	    compat_43_sys_ftruncate },		/* 93 = ftruncate */
#else
	{ 0, 0,
	    sys_nosys },			/* 93 = unimplemented compat_43_sys_ftruncate */
#endif
	{ 2, s(struct sys_fchmod_args),
	    sys_fchmod },			/* 94 = fchmod */
	{ 3, s(struct linux_sys_fchown16_args),
	    linux_sys_fchown16 },		/* 95 = fchown16 */
	{ 2, s(struct sys_getpriority_args),
	    sys_getpriority },			/* 96 = getpriority */
	{ 3, s(struct sys_setpriority_args),
	    sys_setpriority },			/* 97 = setpriority */
	{ 4, s(struct sys_profil_args),
	    sys_profil },			/* 98 = profil */
	{ 2, s(struct linux_sys_statfs_args),
	    linux_sys_statfs },			/* 99 = statfs */
	{ 2, s(struct linux_sys_fstatfs_args),
	    linux_sys_fstatfs },		/* 100 = fstatfs */
	{ 0, 0,
	    sys_nosys },			/* 101 = unimplemented ioperm */
	{ 2, s(struct linux_sys_socketcall_args),
	    linux_sys_socketcall },		/* 102 = socketcall */
	{ 0, 0,
	    sys_nosys },			/* 103 = unimplemented syslog */
	{ 3, s(struct sys_setitimer_args),
	    sys_setitimer },			/* 104 = setitimer */
	{ 2, s(struct sys_getitimer_args),
	    sys_getitimer },			/* 105 = getitimer */
	{ 2, s(struct linux_sys_stat_args),
	    linux_sys_stat },			/* 106 = stat */
	{ 2, s(struct linux_sys_lstat_args),
	    linux_sys_lstat },			/* 107 = lstat */
	{ 2, s(struct linux_sys_fstat_args),
	    linux_sys_fstat },			/* 108 = fstat */
	{ 0, 0,
	    sys_nosys },			/* 109 = unimplemented olduname */
	{ 0, 0,
	    sys_nosys },			/* 110 = unimplemented iopl */
	{ 0, 0,
	    sys_nosys },			/* 111 = unimplemented vhangup */
	{ 0, 0,
	    sys_nosys },			/* 112 = unimplemented idle */
	{ 0, 0,
	    sys_nosys },			/* 113 = unimplemented vm86old */
	{ 4, s(struct linux_sys_wait4_args),
	    linux_sys_wait4 },			/* 114 = wait4 */
	{ 1, s(struct linux_sys_swapoff_args),
	    linux_sys_swapoff },		/* 115 = swapoff */
	{ 1, s(struct linux_sys_sysinfo_args),
	    linux_sys_sysinfo },		/* 116 = sysinfo */
	{ 5, s(struct linux_sys_ipc_args),
	    linux_sys_ipc },			/* 117 = ipc */
	{ 1, s(struct sys_fsync_args),
	    sys_fsync },			/* 118 = fsync */
	{ 0, 0,
	    linux_sys_sigreturn },		/* 119 = sigreturn */
	{ 2, s(struct linux_sys_clone_args),
	    linux_sys_clone },			/* 120 = clone */
	{ 2, s(struct linux_sys_setdomainname_args),
	    linux_sys_setdomainname },		/* 121 = setdomainname */
	{ 1, s(struct linux_sys_uname_args),
	    linux_sys_uname },			/* 122 = uname */
	{ 4, s(struct linux_sys_cacheflush_args),
	    linux_sys_cacheflush },		/* 123 = cacheflush */
	{ 0, 0,
	    sys_nosys },			/* 124 = unimplemented adjtimex */
	{ 3, s(struct sys_mprotect_args),
	    sys_mprotect },			/* 125 = mprotect */
	{ 3, s(struct linux_sys_sigprocmask_args),
	    linux_sys_sigprocmask },		/* 126 = sigprocmask */
	{ 0, 0,
	    sys_nosys },			/* 127 = unimplemented create_module */
	{ 0, 0,
	    sys_nosys },			/* 128 = unimplemented init_module */
	{ 0, 0,
	    sys_nosys },			/* 129 = unimplemented delete_module */
	{ 0, 0,
	    sys_nosys },			/* 130 = unimplemented get_kernel_syms */
	{ 0, 0,
	    sys_nosys },			/* 131 = unimplemented quotactl */
	{ 1, s(struct linux_sys_getpgid_args),
	    linux_sys_getpgid },		/* 132 = getpgid */
	{ 1, s(struct sys_fchdir_args),
	    sys_fchdir },			/* 133 = fchdir */
	{ 0, 0,
	    sys_nosys },			/* 134 = unimplemented bdflush */
	{ 0, 0,
	    sys_nosys },			/* 135 = unimplemented sysfs */
	{ 1, s(struct linux_sys_personality_args),
	    linux_sys_personality },		/* 136 = personality */
	{ 0, 0,
	    sys_nosys },			/* 137 = unimplemented afs_syscall */
	{ 1, s(struct linux_sys_setfsuid_args),
	    linux_sys_setfsuid },		/* 138 = setfsuid */
	{ 0, 0,
	    linux_sys_getfsuid },		/* 139 = getfsuid */
	{ 5, s(struct linux_sys_llseek_args),
	    linux_sys_llseek },			/* 140 = llseek */
	{ 3, s(struct linux_sys_getdents_args),
	    linux_sys_getdents },		/* 141 = getdents */
	{ 5, s(struct linux_sys_select_args),
	    linux_sys_select },			/* 142 = select */
	{ 2, s(struct sys_flock_args),
	    sys_flock },			/* 143 = flock */
	{ 3, s(struct linux_sys_msync_args),
	    linux_sys_msync },			/* 144 = msync */
	{ 3, s(struct sys_readv_args),
	    sys_readv },			/* 145 = readv */
	{ 3, s(struct sys_writev_args),
	    sys_writev },			/* 146 = writev */
	{ 1, s(struct sys_getsid_args),
	    sys_getsid },			/* 147 = getsid */
	{ 1, s(struct linux_sys_fdatasync_args),
	    linux_sys_fdatasync },		/* 148 = fdatasync */
	{ 1, s(struct linux_sys___sysctl_args),
	    linux_sys___sysctl },		/* 149 = __sysctl */
	{ 2, s(struct sys_mlock_args),
	    sys_mlock },			/* 150 = mlock */
	{ 2, s(struct sys_munlock_args),
	    sys_munlock },			/* 151 = munlock */
	{ 1, s(struct sys_mlockall_args),
	    sys_mlockall },			/* 152 = mlockall */
	{ 0, 0,
	    sys_munlockall },			/* 153 = munlockall */
	{ 2, s(struct linux_sys_sched_setparam_args),
	    linux_sys_sched_setparam },		/* 154 = sched_setparam */
	{ 2, s(struct linux_sys_sched_getparam_args),
	    linux_sys_sched_getparam },		/* 155 = sched_getparam */
	{ 3, s(struct linux_sys_sched_setscheduler_args),
	    linux_sys_sched_setscheduler },	/* 156 = sched_setscheduler */
	{ 1, s(struct linux_sys_sched_getscheduler_args),
	    linux_sys_sched_getscheduler },	/* 157 = sched_getscheduler */
	{ 0, 0,
	    linux_sys_sched_yield },		/* 158 = sched_yield */
	{ 1, s(struct linux_sys_sched_get_priority_max_args),
	    linux_sys_sched_get_priority_max },	/* 159 = sched_get_priority_max */
	{ 1, s(struct linux_sys_sched_get_priority_min_args),
	    linux_sys_sched_get_priority_min },	/* 160 = sched_get_priority_min */
	{ 0, 0,
	    sys_nosys },			/* 161 = unimplemented sched_rr_get_interval */
	{ 2, s(struct sys_nanosleep_args),
	    sys_nanosleep },			/* 162 = nanosleep */
	{ 4, s(struct linux_sys_mremap_args),
	    linux_sys_mremap },			/* 163 = mremap */
	{ 3, s(struct linux_sys_setresuid_args),
	    linux_sys_setresuid },		/* 164 = setresuid */
	{ 3, s(struct linux_sys_getresuid_args),
	    linux_sys_getresuid },		/* 165 = getresuid */
	{ 0, 0,
	    sys_nosys },			/* 166 = unimplemented vm86 */
	{ 0, 0,
	    sys_nosys },			/* 167 = unimplemented query_module */
	{ 3, s(struct sys_poll_args),
	    sys_poll },				/* 168 = poll */
	{ 0, 0,
	    sys_nosys },			/* 169 = unimplemented nfsservctl */
	{ 3, s(struct linux_sys_setresgid_args),
	    linux_sys_setresgid },		/* 170 = setresgid */
	{ 3, s(struct linux_sys_getresgid_args),
	    linux_sys_getresgid },		/* 171 = getresgid */
	{ 0, 0,
	    sys_nosys },			/* 172 = unimplemented prctl */
	{ 0, 0,
	    linux_sys_rt_sigreturn },		/* 173 = rt_sigreturn */
	{ 4, s(struct linux_sys_rt_sigaction_args),
	    linux_sys_rt_sigaction },		/* 174 = rt_sigaction */
	{ 4, s(struct linux_sys_rt_sigprocmask_args),
	    linux_sys_rt_sigprocmask },		/* 175 = rt_sigprocmask */
	{ 2, s(struct linux_sys_rt_sigpending_args),
	    linux_sys_rt_sigpending },		/* 176 = rt_sigpending */
	{ 0, 0,
	    sys_nosys },			/* 177 = unimplemented rt_sigtimedwait */
	{ 3, s(struct linux_sys_rt_queueinfo_args),
	    linux_sys_rt_queueinfo },		/* 178 = rt_queueinfo */
	{ 2, s(struct linux_sys_rt_sigsuspend_args),
	    linux_sys_rt_sigsuspend },		/* 179 = rt_sigsuspend */
	{ 4, s(struct linux_sys_pread_args),
	    linux_sys_pread },			/* 180 = pread */
	{ 4, s(struct linux_sys_pwrite_args),
	    linux_sys_pwrite },			/* 181 = pwrite */
	{ 3, s(struct linux_sys_lchown16_args),
	    linux_sys_lchown16 },		/* 182 = lchown16 */
	{ 2, s(struct sys___getcwd_args),
	    sys___getcwd },			/* 183 = __getcwd */
	{ 0, 0,
	    sys_nosys },			/* 184 = unimplemented capget */
	{ 0, 0,
	    sys_nosys },			/* 185 = unimplemented capset */
	{ 2, s(struct linux_sys_sigaltstack_args),
	    linux_sys_sigaltstack },		/* 186 = sigaltstack */
	{ 0, 0,
	    sys_nosys },			/* 187 = unimplemented sendfile */
	{ 0, 0,
	    sys_nosys },			/* 188 = unimplemented getpmsg */
	{ 0, 0,
	    sys_nosys },			/* 189 = unimplemented putpmsg */
	{ 0, 0,
	    sys___vfork14 },			/* 190 = __vfork14 */
	{ 0, 0,
	    sys_nosys },			/* 191 = unimplemented getrlimit */
	{ 0, 0,
	    sys_nosys },			/* 192 = unimplemented mmap2 */
	{ 2, s(struct linux_sys_truncate64_args),
	    linux_sys_truncate64 },		/* 193 = truncate64 */
	{ 2, s(struct sys_ftruncate_args),
	    sys_ftruncate },			/* 194 = ftruncate64 */
	{ 2, s(struct linux_sys_stat64_args),
	    linux_sys_stat64 },			/* 195 = stat64 */
	{ 2, s(struct linux_sys_lstat64_args),
	    linux_sys_lstat64 },		/* 196 = lstat64 */
	{ 2, s(struct linux_sys_fstat64_args),
	    linux_sys_fstat64 },		/* 197 = fstat64 */
	{ 3, s(struct sys___posix_chown_args),
	    sys___posix_chown },		/* 198 = __posix_chown */
	{ 0, 0,
	    sys_getuid },			/* 199 = getuid */
	{ 0, 0,
	    sys_getgid },			/* 200 = getgid */
	{ 0, 0,
	    sys_geteuid },			/* 201 = geteuid */
	{ 0, 0,
	    sys_getegid },			/* 202 = getegid */
	{ 2, s(struct sys_setreuid_args),
	    sys_setreuid },			/* 203 = setreuid */
	{ 2, s(struct sys_setregid_args),
	    sys_setregid },			/* 204 = setregid */
	{ 0, 0,
	    sys_nosys },			/* 205 = unimplemented getgroups */
	{ 0, 0,
	    sys_nosys },			/* 206 = unimplemented setgroups */
	{ 3, s(struct sys___posix_fchown_args),
	    sys___posix_fchown },		/* 207 = __posix_fchown */
	{ 0, 0,
	    sys_nosys },			/* 208 = unimplemented setresuid */
	{ 0, 0,
	    sys_nosys },			/* 209 = unimplemented getresuid */
	{ 0, 0,
	    sys_nosys },			/* 210 = unimplemented setresgid */
	{ 0, 0,
	    sys_nosys },			/* 211 = unimplemented getresgid */
	{ 3, s(struct sys___posix_lchown_args),
	    sys___posix_lchown },		/* 212 = __posix_lchown */
	{ 1, s(struct sys_setuid_args),
	    sys_setuid },			/* 213 = setuid */
	{ 1, s(struct sys_setgid_args),
	    sys_setgid },			/* 214 = setgid */
	{ 0, 0,
	    sys_nosys },			/* 215 = unimplemented setfsuid */
	{ 0, 0,
	    sys_nosys },			/* 216 = unimplemented setfsgid */
	{ 0, 0,
	    sys_nosys },			/* 217 = unimplemented pivot_root */
};

