/* This file is automatically generated.  DO NOT EDIT! */
/* Generated from: 	NetBSD: mknative-gcc,v 1.1 2003/07/25 16:26:53 mrg Exp  */

/* Generated automatically. */
static const char configuration_arguments[] = "/home/mrg/src/netbsd/src/tools/gcc/../../gnu/dist/gcc/configure --disable-multilib --build=i386-unknown-netbsdelf --host=shle--netbsdelf --target=shle--netbsdelf";
static const char thread_model[] = "single";
