#	$NetBSD: Makefile,v 1.1 2001/04/26 02:26:18 garbled Exp $

FILES=	form help
FILESDIR=${BINDIR}/sushi/procs/restartallprocs
SCRIPTS= script script1
SCRIPTSDIR=${BINDIR}/sushi/procs/restartallprocs
MKOBJ=	no

.include "../../../Makefile.inc"
.include <bsd.prog.mk>
