# $NetBSD: Makefile,v 1.2 2001/08/03 14:14:10 drochner Exp $

LIB    = dhcpctl
SRCS   = dhcpctl.c callback.c remote.c

MKLINT=	no
MKPIC=	no
MKPROFILE=no

DHCPSRCDIR=	dhcpctl

# only needed during build
libinstall::

.include <bsd.lib.mk>
