#	$NetBSD: Makefile,v 1.8 2011/07/16 23:07:50 mrg Exp $

#Uncomment the next line to enable the new .init fallthru
CPPFLAGS+=	-I${.CURDIR}/../sparc_elf

ELFSIZE=64

.include "${.CURDIR}/../common_elf/Makefile.inc"
