#	$NetBSD: Makefile.cc1,v 1.6 1998/08/17 02:25:44 tv Exp $

.include <bsd.own.mk>

C_OBJC_SRCS=	c-lex.c c-pragma.c c-decl.c c-typeck.c c-convert.c \
		c-aux-info.c c-common.c c-iterate.c
BINDIR=		/usr/libexec
NOMAN=

LDADD+=		-L${COMMONOBJ} -lcc1
.if defined(NOPIC)
DPADD+=		${COMMONOBJ}/libcc1.a
.else
DPADD+=		${COMMONOBJ}/libcc1_pic.a
.endif

.include <bsd.prog.mk>
