#	$NetBSD: Makefile,v 1.4 1998/04/01 21:45:05 mrg Exp $

SUBDIR+=	common cc1 cc1plus cc1obj f771 libgcc libobjc
SUBDIR+=	cc cpp g++ g77

all-cc1 all-cc1plus all-cc1obj: all-common

.include <bsd.subdir.mk>
