#	$NetBSD: Makefile,v 1.1 2001/01/05 07:32:33 garbled Exp $

SUBDIR= basics execapi formapi helpapi i18n indexapi scriptapi searchpaths

FILES=	index help
FILESDIR=${BINDIR}/sushi/info/programming
MKOBJ=	no

.include "../../../Makefile.inc"
.include <bsd.prog.mk>
.include <bsd.subdir.mk>
