# $NetBSD: Makefile,v 1.3 2007/02/08 02:59:51 elad Exp $

PROG=	paxctl
MAN=	paxctl.8

# This program is set 0550 because, as security(8) states, it has the potential
# to deplete kernel memory, under certain conditions.
BINMODE=0550

.include <bsd.prog.mk>
