/* syscalls */
#define accept		_accept
#define access		_access
#define acct		_acct
#define adjtime		_adjtime
#define bind		_bind
#define chdir		_chdir
#define chflags		_chflags
#define chmod		_chmod
#define chown		_chown
#define chroot		_chroot
#define close		_close
#define connect		_connect
#define dup		_dup
#define dup2		_dup2
#define execve		_execve
#define fchdir		_fchdir
#define fchflags	_fchflags
#define fchmod		_fchmod
#define fchown		_fchown
#define fcntl		_fcntl
#define flock		_flock
#define fpathconf	_fpathconf
#define fstat		_fstat
#define fstatfs		_fstatfs
#define fsync		_fsync
#define getdirentries	_getdirentries
#define getegid		_getegid
#define geteuid		_geteuid
#define getfh		_getfh
#define getfsstat	_getfsstat
#define getgid		_getgid
#define getgroups	_getgroups
#define getitimer	_getitimer
#define getpeername	_getpeername
#define getpgrp		_getpgrp
#define getpid		_getpid
#define getppid		_getppid
#define getpriority	_getpriority
#define getrlimit	_getrlimit
#define getrusage	_getrusage
#define getsockname	_getsockname
#define getsockopt	_getsockopt
#define gettimeofday	_gettimeofday
#define getuid		_getuid
#define ioctl		_ioctl
#define kill		_kill
#define ktrace		_ktrace
#define lfs_bmapv	_lfs_bmapv
#define lfs_markv	_lfs_markv
#define lfs_segclean	_lfs_segclean
#define lfs_segwait	_lfs_segwait
#define link		_link
#define listen		_listen
#define lseek		_lseek
#define lstat		_lstat
#define madvise		_madvise
#define mincore		_mincore
#define mkdir		_mkdir
#define mkfifo		_mkfifo
#define mknod		_mknod
#define mlock		_mlock
#define mount		_mount
#define mprotect	_mprotect
#define msgctl		_msgctl
#define msgget		_msgget
#define msgrcv		_msgrcv
#define msgsnd		_msgsnd
#define msync		_msync
#define munlock		_munlock
#define munmap		_munmap
#define nfssvc		_nfssvc
#define open		_open
#define pathconf	_pathconf
#define profil		_profil
#define quotactl	_quotactl
#define read		_read
#define readlink	_readlink
#define readv		_readv
#define recvfrom	_recvfrom
#define recvmsg		_recvmsg
#define rename		_rename
#define revoke		_revoke
#define rmdir		_rmdir
#define sbrk		_sbrk
#define select		_select
#define semconfig	_semconfig
#define semget		_semget
#define semop		_semop
#define sendmsg		_sendmsg
#define sendto		_sendto
#define setegid		_setegid
#define seteuid		_seteuid
#define setgid		_setgid
#define setgroups	_setgroups
#define setitimer	_setitimer
#define setpgid		_setpgid
#define setpriority	_setpriority
#define setrlimit	_setrlimit
#define setsid		_setsid
#define setsockopt	_setsockopt
#define settimeofday	_settimeofday
#define setuid		_setuid
#define shmat		_shmat
#define shmctl		_shmctl
#define shmdt		_shmdt
#define shmget		_shmget
#define shutdown	_shutdown
#define sigaction	_sigaction
#define sigaltstack	_sigaltstack
#define socket		_socket
#define socketpair	_socketpair
#define stat		_stat
#define statfs		_statfs
#define swapon		_swapon
#define symlink		_symlink
#define sync		_sync
#define sysarch		_sysarch
#define umask		_umask
#define undelete	_undelete
#define unlink		_unlink
#define unmount		_unmount
#define utimes		_utimes
#define vadvise		_vadvise
#define wait4		_wait4
#define write		_write
#define writev		_writev

/* time and date functions */
#define offtime		_offtime
#define posix2time	_posix2time
#define time2posix	_time2posix
#define timegm		_timegm
#define timelocal	_timelocal
#define timeoff		_timeoff
#define tzsetwall	_tzsetwall
#define altzone		_altzone
#define tzname		_tzname
#define daylight	_daylight
#define timezone	_timezone

/* misc */
#define catclose	_catclose
#define catgets		_catgets
#define catopen		_catopen
#define err		_err
#define errx		_errx
#define strtoq		_strtoq
#define strtouq		_strtouq
#define sys_errlist	_sys_errlist
#define sys_nerr	_sys_nerr
#define sys_siglist	_sys_siglist
#define verr		_verr
#define verrx		_verrx
#define vwarn		_vwarn
#define vwarnx		_vwarnx
#define warn		_warn
#define warnx		_warnx
