/*	$NetBSD: namespace.h,v 1.2.4.2 1996/09/16 23:44:14 jtc Exp $	*/

#ifndef NAMESPACE_H
#define NAMESPACE_H

#include <sys/cdefs.h>

#ifdef __weak_alias

#define alphasort	_alphasort
#define authnone_create	_authnone_create
#define authunix_create	_authunix_create
#define authunix_create_default	_authunix_create_default
#define bindresvport	_bindresvport
#define callrpc		_callrpc
#define catclose	_catclose
#define catgets		_catgets
#define catopen		_catopen
#define clnt_broadcast	_clnt_broadcast
#define clnt_create	_clnt_create
#define clnt_pcreateerror	_clnt_pcreateerror
#define clnt_perrno	_clnt_perrno
#define clnt_perror	_clnt_perror
#define clnt_spcreateerror	_clnt_spcreateerror
#define clnt_sperrno	_clnt_sperrno
#define clnt_sperror	_clnt_sperror
#define clntraw_create	_clntraw_create
#define clnttcp_create	_clnttcp_create
#define clntudp_bufcreate	_clntudp_bufcreate
#define clntudp_create	_clntudp_create
#define closedir	_closedir
#define dbm_clearerr	_dbm_clearerr 
#define dbm_close	_dbm_close
#define dbm_delete	_dbm_delete
#define dbm_dirfno	_dbm_dirfno
#define dbm_error	_dbm_error
#define dbm_fetch	_dbm_fetch
#define dbm_firstkey	_dbm_fetchkey
#define dbm_nextkey	_dbm_nextkey
#define dbm_open	_dbm_open
#define dbm_store	_dbm_store
#define dbopen		_dbopen
#define endrpcent	_endrpcent
#define err		_err
#define errx		_errx
#define fts_children	_fts_children
#define fts_close	_fts_close
#define fts_open	_fts_open
#define fts_read	_fts_read
#define fts_set		_fts_set
#define get_myaddress	_get_myaddress
#define getrpcbyname	_getrpcbyname
#define getrpcbynumber	_getrpcbynumber
#define getrpcent	_getrpcent
#define getrpcport	_getrpcport
#define hcreate		_hcreate
#define hdestroy	_hdestroy
#define hsearch		_hsearch
#define mpool_close	_mpool_close
#define mpool_filter	_mpool_filter
#define mpool_get	_mpool_get
#define mpool_new	_mpool_new
#define mpool_open	_mpool_open
#define mpool_put	_mpool_put
#define mpool_sync	_mpool_sync
#define opendir		_opendir
#define pmap_getmaps	_pmap_getmaps
#define pmap_getport	_pmap_getport
#define pmap_rmtcall	_pmap_rmtcall
#define pmap_set	_pmap_set
#define pmap_unset	_pmap_unset
#define readdir		_readdir
#define registerrpc	_registerrpc
#define rewinddir	_rewinddir
#define scandir		_scandir
#define seekdir		_seekdir
#define setrpcent	_setrpcent
#define strtoq		_strtoq
#define strtouq		_strtouq
#define svc_getreq	_svc_getreq
#define svc_getreqset	_svc_getreqset
#define svc_register	_svc_register
#define svc_run		_svc_run
#define svc_sendreply	_svc_sendreply
#define svc_unregister	_svc_unregister
#define svcerr_auth	_svcerr_auth
#define svcerr_decode	_svcerr_decode
#define svcerr_noproc	_svcerr_noproc
#define svcerr_noprog	_svcerr_noprog
#define svcerr_progvers	_svcerr_progvers
#define svcerr_systemerr	_svcerr_systemerr
#define svcerr_weakauth	_svcerr_weakauth
#define svcfd_create	_svcfd_create
#define svcraw_create	_svcraw_create
#define svctcp_create	_svctcp_create
#define svcudp_bufcreate	_svcudp_bufcreate
#define svcudp_create	_svcudp_create
#define svcudp_enablecache	_svcudp_enablecache
#define sys_errlist	_sys_errlist
#define sys_nerr	_sys_nerr
#define sys_siglist	_sys_siglist
#define telldir		_telldir
#define verr		_verr
#define verrx		_verrx
#define vwarn		_vwarn
#define vwarnx		_vwarnx
#define warn		_warn
#define warnx		_warnx
#define xdr_accepted_reply	_xdr_accepted_reply
#define xdr_array	_xdr_array
#define xdr_authunix_parms	_xdr_authunix_parms
#define xdr_bool	_xdr_bool
#define xdr_bytes	_xdr_bytes
#define xdr_callhdr	_xdr_callhdr
#define xdr_callmsg	_xdr_callmsg
#define xdr_char	_xdr_char
#define xdr_des_block	_xdr_des_block
#define xdr_double	_xdr_double
#define xdr_enum	_xdr_enum
#define xdr_float	_xdr_float
#define xdr_free	_xdr_free
#define xdr_int		_xdr_int
#define xdr_int16_t	_xdr_int16_t
#define xdr_int32_t	_xdr_int32_t
#define xdr_long	_xdr_long
#define xdr_netobj	_xdr_netobj
#define xdr_opaque	_xdr_opaque
#define xdr_opaque_auth	_xdr_opaque_auth
#define xdr_pmap	_xdr_pmap
#define xdr_pmaplist	_xdr_pmaplist
#define xdr_pointer	_xdr_pointer
#define xdr_reference	_xdr_reference
#define xdr_rejected_reply	_xdr_rejected_reply
#define xdr_replymsg	_xdr_replymsg
#define xdr_rmtcall_args	_xdr_rmtcall_args
#define xdr_rmtcallres		_xdr_rmtcallres
#define xdr_short	_xdr_short
#define xdr_string	_xdr_string
#define xdr_u_char	_xdr_u_char
#define xdr_u_int	_xdr_u_int
#define xdr_u_int16_t	_xdr_u_int16_t
#define xdr_u_int32_t	_xdr_u_int32_t
#define xdr_u_long	_xdr_u_long
#define xdr_u_short	_xdr_u_short
#define xdr_union	_xdr_union
#define xdr_vector	_xdr_vector
#define xdr_void	_xdr_void
#define xdr_wrapstring	_xdr_wrapstring
#define xdrmem_create	_xdrmem_create
#define xdrrec_create	_xdrrec_create
#define xdrrec_endofrecord	_xdrrec_endofrecord
#define xdrrec_eof	_xdrrec_eof
#define xdrrec_skiprecord	_xdrrec_skiprecord
#define xdrstdio_create	_xdrstdio_create
#define xprt_register	_xprt_register
#define xprt_unregister	_xprt_unregister

#endif

#endif
