/*	$NetBSD: namespace.h,v 1.2.4.7 1996/09/19 20:04:36 jtc Exp $	*/

#ifndef NAMESPACE_H
#define NAMESPACE_H

#include <sys/cdefs.h>

#ifdef __weak_alias

#define alarm			_alarm
#define alphasort		_alphasort
#define authnone_create		_authnone_create
#define authunix_create		_authunix_create
#define authunix_create_default _authunix_create_default
#define bindresvport		_bindresvport
#define callrpc			_callrpc
#define catclose		_catclose
#define catgets			_catgets
#define catopen			_catopen
#define cfgetispeed		_cfgetispeed
#define cfgetospeed		_cfgetospeed
#define cfmakeraw		_cfmakeraw
#define cfsetispeed		_cfsetispeed
#define cfsetospeed		_cfsetospeed
#define cgetcap			_cgetcap
#define cgetclose		_cgetclose
#define cgetent			_cgetent
#define cgetfirst		_cgetfirst
#define cgetmatch		_cgetmatch
#define cgetnext		_cgetnext
#define cgetnum			_cgetnum
#define cgetset			_cgetset
#define cgetstr			_cgetstr
#define cgetustr		_cgetustr
#define clnt_broadcast		_clnt_broadcast
#define clnt_create		_clnt_create
#define clnt_pcreateerror	_clnt_pcreateerror
#define clnt_perrno		_clnt_perrno
#define clnt_perror		_clnt_perror
#define clnt_spcreateerror	_clnt_spcreateerror
#define clnt_sperrno		_clnt_sperrno
#define clnt_sperror		_clnt_sperror
#define clntraw_create		_clntraw_create
#define clnttcp_create		_clnttcp_create
#define clntudp_bufcreate	_clntudp_bufcreate
#define clntudp_create		_clntudp_create
#define closedir		_closedir
#define closelog		_closelog
#define confstr			_confstr
#define ctermid			_ctermid
#define daemon			_daemon
#define daylight		_daylight
#define devname			_devname
#define drand48			_drand48
#define endfsent		_endfsent
#define endgrent		_endgrent
#define endnetgrent		_endnetgrent
#define endpwent		_endpwent
#define endrpcent		_endrpcent
#define endttyent		_endttyent
#define endusershell		_endusershell
#define erand48			_erand48
#define err			_err
#define errx			_errx
#define execl			_execl
#define execle			_execle
#define execlp			_execlp
#define execv			_execv
#define execvp			_execvp
#define fnmatch			_fnmatch
#define ftok			_ftok
#define fts_children		_fts_children
#define fts_close		_fts_close
#define fts_open		_fts_open
#define fts_read		_fts_read
#define fts_set			_fts_set
#define get_myaddress		_get_myaddress
#define getbsize		_getbsize
#define getcwd			_getcwd
#define getdiskbyname		_getdiskbyname
#define getdomainname		_getdomainname
#define getfsent		_getfsent
#define getfsfile		_getfsfile
#define getfsspec		_getfsspec
#define getgrent		_getgrent
#define getgrgid		_getgrgid
#define getgrnam		_getgrnam
#define getgrouplist		_getgrouplist
#define gethostname		_gethostname
#define getloadavg		_getloadavg
#define getlogin		_getlogin
#define getmntinfo		_getmntinfo
#define getmode			_getmode
#define getnetgrent		_getnetgrent
#define getpagesize		_getpagesize
#define getpass			_getpass
#define getpwent		_getpwent
#define getpwnam		_getpwnam
#define getpwuid		_getpwuid
#define getrpcbyname		_getrpcbyname
#define getrpcbynumber		_getrpcbynumber
#define getrpcent		_getrpcent
#define getrpcport		_getrpcport
#define getsubopt		_getsubopt
#define getttyent		_getttyent
#define getttynam		_getttynam
#define getusershell		_getusershell
#define glob			_glob
#define globfree		_globfree
#define group_from_gid		_group_from_gid
#define heapsort		_heapsort
#define initgroups		_initgroups
#define initstate		_initstate
#define innetgr			_innetgr
#define isatty			_isatty
#define jrand48			_jrand48
#define lcong48			_lcong48
#define llabs			_qabs
#define lldiv			_qdiv
#define lrand48			_lrand48
#define mergesort		_mergesort
#define mrand48			_mrand48
#define nice			_nice
#define nlist			_nlist
#define nrand48			_nrand48
#define offtime			_offtime
#define opendir			_opendir
#define openlog			_openlog
#define pause			_pause
#define pclose			_pclose
#define pmap_getmaps		_pmap_getmaps
#define pmap_getport		_pmap_getport
#define pmap_rmtcall		_pmap_rmtcall
#define pmap_set		_pmap_set
#define pmap_unset		_pmap_unset
#define popen			_popen
#define posix2time		_posix2time
#define putenv			_putenv
#define qabs			_qabs
#define qdiv			_qdiv
#define radixsort		_radixsort
#define random			_random
#define readdir			_readdir
#define realpath		_realpath
#define registerrpc		_registerrpc
#define rewinddir		_rewinddir
#define scandir			_scandir
#define seed48			_seed48
#define seekdir			_seekdir
#define setdomainname		_setdomainname
#define setenv			_setenv
#define setfsent		_setfsent
#define setgrent		_setgrent
#define setgroupent		_setgroupent
#define sethostname		_sethostname
#define setlogmask		_setlogmask
#define setmode			_setmode
#define setnetgrent		_setnetgrent
#define setpassent		_setpassent
#define setproctitle		_setproctitle
#define setpwent		_setpwent
#define setrpcent		_setrpcent
#define setstate		_setstate
#define setttyent		_setttyent
#define setusershell		_setusershell
#define siginterrupt		_siginterrupt
#define sradixsort		_sradixsort
#define srand48			_srand48
#define srandom			_srandom
#define strtoll			_strtoq
#define strtoq			_strtoq
#define strtoull		_strtouq
#define strtouq			_strtouq
#define strunvis		_strunvis
#define strvis			_strvis
#define strvisx			_strvisx
#define suboptarg		_suboptarg
#define svc_getreq		_svc_getreq
#define svc_getreqset		_svc_getreqset
#define svc_register		_svc_register
#define svc_run			_svc_run
#define svc_sendreply		_svc_sendreply
#define svc_unregister		_svc_unregister
#define svcerr_auth		_svcerr_auth
#define svcerr_decode		_svcerr_decode
#define svcerr_noproc		_svcerr_noproc
#define svcerr_noprog		_svcerr_noprog
#define svcerr_progvers		_svcerr_progvers
#define svcerr_systemerr	_svcerr_systemerr
#define svcerr_weakauth		_svcerr_weakauth
#define svcfd_create		_svcfd_create
#define svcraw_create		_svcraw_create
#define svctcp_create		_svctcp_create
#define svcudp_bufcreate	_svcudp_bufcreate
#define svcudp_create		_svcudp_create
#define svcudp_enablecache	_svcudp_enablecache
#define sys_errlist		_sys_errlist
#define sys_nerr		_sys_nerr
#define sys_siglist		_sys_siglist
#define sys_signame		_sys_signame
#define sysconf			_sysconf
#define sysctl			_sysctl
#define syslog			_syslog
#define tcdrain			_tcdrain
#define tcflow			_tcflow
#define tcflush			_tcflush
#define tcgetattr		_tcgetattr
#define tcgetpgrp		_tcgetpgrp
#define tcsendbreak		_tcsendbreak
#define tcsetattr		_tcsetattr
#define tcsetpgrp		_tcsetpgrp
#define telldir			_telldir
#define time2posix		_time2posix
#define timegm			_timegm
#define timelocal		_timelocal
#define timeoff			_timeoff
#define timezone		_timezone
#define timezone		_timezone
#define ttyname			_ttyname
#define ttyslot			_ttyslot
#define tzname			_tzname
#define tzset			_tzset
#define tzsetwall		_tzsetwall
#define ualarm			_ualarm
#define uname			_uname
#define unsetenv		_unsetenv
#define unvis			_unvis
#define user_from_uid		_user_from_uid
#define usleep			_usleep
#define utime			_utime
#define valloc			_valloc
#define verr			_verr
#define verrx			_verrx
#define vis			_vis
#define vwarn			_vwarn
#define vwarnx			_vwarnx
#define waidpid			_waitpid
#define wait			_wait
#define wait3			_wait3
#define warn			_warn
#define warnx			_warnx
#define xdr_accepted_reply	_xdr_accepted_reply
#define xdr_array		_xdr_array
#define xdr_authunix_parms	_xdr_authunix_parms
#define xdr_bool		_xdr_bool
#define xdr_bytes		_xdr_bytes
#define xdr_callhdr		_xdr_callhdr
#define xdr_callmsg		_xdr_callmsg
#define xdr_char		_xdr_char
#define xdr_datum		_xdr_datum
#define xdr_des_block		_xdr_des_block
#define xdr_double		_xdr_double
#define xdr_enum		_xdr_enum
#define xdr_float		_xdr_float
#define xdr_free		_xdr_free
#define xdr_int			_xdr_int
#define xdr_int16_t		_xdr_int16_t
#define xdr_int32_t		_xdr_int32_t
#define xdr_long		_xdr_long
#define xdr_netobj		_xdr_netobj
#define xdr_opaque		_xdr_opaque
#define xdr_opaque_auth		_xdr_opaque_auth
#define xdr_pmap		_xdr_pmap
#define xdr_pmaplist		_xdr_pmaplist
#define xdr_pointer		_xdr_pointer
#define xdr_reference		_xdr_reference
#define xdr_rejected_reply	_xdr_rejected_reply
#define xdr_replymsg		_xdr_replymsg
#define xdr_rmtcall_args	_xdr_rmtcall_args
#define xdr_rmtcallres		_xdr_rmtcallres
#define xdr_short		_xdr_short
#define xdr_string		_xdr_string
#define xdr_u_char		_xdr_u_char
#define xdr_u_int		_xdr_u_int
#define xdr_u_int16_t		_xdr_u_int16_t
#define xdr_u_int32_t		_xdr_u_int32_t
#define xdr_u_long		_xdr_u_long
#define xdr_u_short		_xdr_u_short
#define xdr_union		_xdr_union
#define xdr_vector		_xdr_vector
#define xdr_void		_xdr_void
#define xdr_wrapstring		_xdr_wrapstring
#define xdr_yp_inaddr		_xdr_yp_inaddr
#define xdr_ypall		_xdr_ypall
#define xdr_ypbind_resp		_xdr_ypbind_resp
#define xdr_ypbind_setdom	_xdr_ypbind_setdom
#define xdr_ypdomain_wrap_string _xdr_ypdomain_wrap_string
#define xdr_ypmap_parms		_xdr_ypmap_parms
#define xdr_ypmap_wrap_string	_xdr_ypmap_wrap_string
#define xdr_ypmaplist		_xdr_ypmaplist
#define xdr_ypowner_wrap_string _xdr_ypowner_wrap_string
#define xdr_yppushresp_xfr	_xdr_yppushresp_xfr
#define xdr_ypreq_key		_xdr_ypreq_key
#define xdr_ypreq_nokey		_xdr_ypreq_nokey
#define xdr_ypreq_xfr		_xdr_ypreq_xfr
#define xdr_ypresp_key_val	_xdr_ypresp_key_val
#define xdr_ypresp_maplist	_xdr_ypresp_maplist
#define xdr_ypresp_master	_xdr_ypresp_master
#define xdr_ypresp_order	_xdr_ypresp_order
#define xdr_ypresp_val		_xdr_ypresp_val
#define xdrmem_create		_xdrmem_create
#define xdrrec_create		_xdrrec_create
#define xdrrec_endofrecord	_xdrrec_endofrecord
#define xdrrec_eof		_xdrrec_eof
#define xdrrec_skiprecord	_xdrrec_skiprecord
#define xdrstdio_create		_xdrstdio_create
#define xprt_register		_xprt_register
#define xprt_unregister		_xprt_unregister
#define yp_all			_yp_all
#define yp_bind			_yp_bind
#define yp_first		_yp_first
#define yp_get_default_domain	_yp_get_default_domain
#define yp_maplist		_yp_maplist
#define yp_master		_yp_master
#define yp_match		_yp_match
#define yp_next			_yp_next
#define yp_order		_yp_order
#define yp_unbind		_yp_unbind
#define yperr_string		_yperr_string
#define ypprot_err		_ypprot_err

#endif

#endif
