#	$NetBSD: Makefile,v 1.5.30.1 2017/04/21 16:54:13 bouyer Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}asn1_compile
HOST_SRCDIR=	crypto/external/bsd/heimdal/lib/libasn1/asn1_compile

.include "${.CURDIR}/../Makefile.host"
