#	from: @(#)Makefile	8.5 (Berkeley) 3/27/94
#	$Id: Makefile,v 1.8 1994/12/22 10:45:46 cgd Exp $

PROG=	mount
SRCS=	mount.c mount_ufs.c getmntopts.c
MAN=	mount.8
# We do NOT install the getmntopts.3 man page.

.include <bsd.prog.mk>
