#	$NetBSD: Makefile,v 1.14 2002/04/16 05:23:39 lukem Exp $

FLOPPYBASE=	boot-small
FLOPPYSIZE=	2400
FLOPPYKERNDIR=	kernel-ramdisk
FLOPPYKERNEL=	netbsd.INSTALL_SMALL.gz

.include "${.CURDIR}/../common/Makefile.bootfloppy"
