#!/bin/sh
#
# $NetBSD: amd,v 1.14.12.1 2008/04/03 13:54:12 mjf Exp $
#

# PROVIDE: amd
# REQUIRE: rpcbind mountall ypbind
# BEFORE:  DAEMON

$_rc_subr_loaded . /etc/rc.subr

name="amd"
rcvar=$name
command="/usr/sbin/${name}"
reload_cmd="/usr/sbin/amq -f"
extra_commands="reload"

load_rc_config $name

command_args='-p -a '$amd_dir' -F /etc/amd.conf >/var/run/amd.pid'
required_files="/etc/amd.conf"
required_dirs="$amd_dir"
required_vars="rpcbind"

load_rc_config_var rpcbind rpcbind

run_rc_command "$1"
