#!/bin/sh
#
# $NetBSD: autounmountd,v 1.1.6.2 2020/01/31 11:19:58 martin Exp $
#

# PROVIDE: autounmountd
# REQUIRE: DAEMON
# KEYWORD: nojail

$_rc_subr_loaded . /etc/rc.subr

name="autounmountd"
rcvar="autofs"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
