#!/bin/sh
#
# $NetBSD: cgd,v 1.1 2002/10/09 14:55:55 elric Exp $
#

# PROVIDE: disks

. /etc/rc.subr

name="cgd"
start_cmd="cgd_start"
stop_cmd=":"

cgd_start()
{
	if [ -f /etc/cgd/cgd.conf ]; then
		echo "Configuring CGD devices."
		cgdconfig -C
	fi
}

load_rc_config $name
run_rc_command "$1"
