#!/bin/sh
#
# $NetBSD: cleartmp,v 1.6 2006/10/07 07:01:21 elad Exp $
#

# PROVIDE: cleartmp
# REQUIRE: mountall
# BEFORE:  DAEMON

$_rc_subr_loaded . /etc/rc.subr

name="cleartmp"
rcvar="clear_tmp"
start_cmd="cleartmp_start"
stop_cmd=":"

cleartmp_start()
{
	echo "Clearing /tmp."
	#
	#	Prune quickly with one rm, then use find to clean up
	#	/tmp/[iq]* (this is not needed with mfs /tmp, but
	#	doesn't hurt anything).
	#
	(cd /tmp && rm -rf [a-hm-pr-zA-Z]* &&
	    find -x . ! -name . ! -name lost+found ! -name quota.user \
		! -name quota.group ! -name ifile \
		-exec rm -rf -- {} \; -type -d -prune)
}

load_rc_config $name
run_rc_command "$1"
