#!/bin/sh
#
# $NetBSD: cron,v 1.3.4.2 2000/10/02 01:09:23 lukem Exp $
#

# PROVIDE: cron
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="cron"
rcvar=$name
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"

load_rc_config $name
run_rc_command "$1"
