#!/bin/sh
#
# $NetBSD: DAEMON,v 1.7 2002/01/31 01:26:05 lukem Exp $
#

# PROVIDE: DAEMON
# REQUIRE: NETWORKING SERVERS
# REQUIRE: accounting aftermountlkm amd cleartmp dmesg ipmon
# REQUIRE: ipnat ipsec ldconfig named nonlocalswap nfslocking
# REQUIRE: pwcheck quota savecore securelevel sysctl sysdb virecover ypbind

#	This is a dummy dependency, to ensure that general purpose daemons
#	are run _after_ the above are.
