#!/bin/sh
#
# $NetBSD: dhcrelay,v 1.2 2000/03/13 04:03:57 lukem Exp $
#

# PROVIDE: dhcrelay
# REQUIRE: DAEMON

. /etc/rc.subr
. /etc/rc.conf

name="dhcrelay"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"

run_rc_command "$1"
