#!/bin/sh
#
# $NetBSD: dmesg,v 1.3.4.1 2000/08/09 19:09:39 lukem Exp $
#

# PROVIDE: dmesg
# REQUIRE: mountcritremote

. /etc/rc.subr

name="dmesg"
start_precmd="checkyesno dmesg"
start_cmd="do_dmesg"
stop_cmd=":"

do_dmesg()
{
	rm -f /var/run/dmesg.boot
	dmesg $dmesg_flags > /var/run/dmesg.boot
}

load_rc_config $name
run_rc_command "$1"
