#!/bin/sh
#
# $NetBSD: ip6addrctl,v 1.6 2020/07/22 16:50:41 martin Exp $
# FreeBSD: head/etc/rc.d/ip6addrctl 270836 2014-08-30 07:08:10Z hrs
#

# PROVIDE: ip6addrctl
# REQUIRE: root bootconf MOUNTCRITLOCAL tty

$_rc_subr_loaded . /etc/rc.subr

name="ip6addrctl"
rcvar="ip6addrctl"
start_cmd="ip6addrctl_start"
stop_cmd="ip6addrctl_stop"
extra_commands="status prefer_ipv6 prefer_ipv4"
status_cmd="ip6addrctl"
prefer_ipv6_cmd="ip6addrctl_prefer_ipv6"
prefer_ipv4_cmd="ip6addrctl_prefer_ipv4"
config_file="/etc/ip6addrctl.conf"

IP6ADDRCTL_CMD="/usr/sbin/ip6addrctl"

ip6addrctl_prefer_ipv6()
{
	${IP6ADDRCTL_CMD} flush >/dev/null 2>&1
	cat <<EOT | ${IP6ADDRCTL_CMD} install /dev/stdin
	::1/128		 50	 0
	::/0		 40	 1
	::ffff:0:0/96	 35	 4
	2002::/16	 30	 2
	2001::/32	  5	 5
	fc00::/7	  3	13
	::/96		  1	 3
	fec0::/10	  1	11
	3ffe::/16	  1	12
EOT
}

ip6addrctl_prefer_ipv4()
{
	${IP6ADDRCTL_CMD} flush >/dev/null 2>&1
	cat <<EOT | ${IP6ADDRCTL_CMD} install /dev/stdin
	::1/128		 50	 0
	::/0		 40	 1
	::ffff:0:0/96	100	 4
	2002::/16	 30	 2
	2001::/32	  5	 5
	fc00::/7	  3	13
	::/96		  1	 3
	fec0::/10	  1	11
	3ffe::/16	  1	12
EOT
}

ip6addrctl_start()
{
	# install the policy of the address selection algorithm.
	case "${ip6addrctl_policy}" in
	[Aa][Uu][Tt][Oo])
		if [ -r "${config_file}" -a -s "${config_file}" ]; then
			${IP6ADDRCTL_CMD} flush >/dev/null 2>&1
			${IP6ADDRCTL_CMD} install "${config_file}"
		else
			ip6addrctl_prefer_ipv6
		fi
	;;
	ipv4_prefer)
		ip6addrctl_prefer_ipv4
	;;
	ipv6_prefer)
		ip6addrctl_prefer_ipv6
	;;
	*)
		warn "\$ip6addrctl_policy is invalid: ${ip6addrctl_policy}. " \
		    " \"ipv4_prefer\" is used instead."
		ip6addrctl_prefer_ipv4
	;;
	esac

	if checkyesno ip6addrctl_verbose; then
		echo 'Address selection policy table for IPv4 and IPv6:'
		${IP6ADDRCTL_CMD}
	fi
}

ip6addrctl_stop()
{
	${IP6ADDRCTL_CMD} flush >/dev/null 2>&1
}

load_rc_config $name
run_rc_command "$1"
