#!/bin/sh
#
# $NetBSD: ipmon,v 1.2.4.1 2000/10/02 01:07:17 lukem Exp $
#

# PROVIDE: ipmon
# REQUIRE: syslogd

. /etc/rc.subr

name="ipmon"
rcvar=$name
command="/usr/sbin/${name}"
command_args="&"

load_rc_config $name
run_rc_command "$1"
