#!/bin/sh
#
# $NetBSD: ipnat,v 1.3 2000/04/30 13:23:33 lukem Exp $
#

# PROVIDE: ipnat
# REQUIRE: ipfilter

. /etc/rc.subr
. /etc/rc.conf

name="ipnat"
config="/etc/ipnat.conf"

start_precmd="checkyesno ipnat"
start_cmd="ipnat_start"

stop_precmd=$start_precmd
stop_cmd="/usr/sbin/ipnat -F -C"

reload_precmd=$start_precmd
reload_cmd="/usr/sbin/ipnat -F -C -f ${config}"

extra_commands="reload"

ipnat_start()
{
	if [ ! -f ${config} ]; then
		return 0
	fi
	if ! checkyesno ipfilter || [ ! -f /etc/ipf.conf ]; then
		echo "Enabling ipfilter for NAT."
		/sbin/ipf -E -Fa
	fi
	echo -n "Installing NAT rules ... "
	/usr/sbin/ipnat -F -f ${config}
}

run_rc_command "$1"
