#!/bin/sh
#
# $NetBSD: kdc,v 1.1 2000/08/06 21:32:56 thorpej Exp $
#

# PROVIDE: kdc
# REQUIRE: mountcritremote

. /etc/rc.subr

name="kdc"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/krb5.conf"

load_rc_config $name
run_rc_command "$1"
