#!/bin/sh
#
# $NetBSD: local,v 1.2 2000/03/13 04:03:58 lukem Exp $
#

# REQUIRE: DAEMON
# PROVIDE: local
# BEFORE: LOGIN

. /etc/rc.subr
. /etc/rc.conf

name="local"
start_cmd="do_local start"
stop_cmd="do_local stop"

do_local()
{
	if [ -f /etc/rc.local ]; then
		set $1 ; . /etc/rc.local
	fi
}

run_rc_command "$1"
