#!/bin/sh
#
# $NetBSD: mdnsd,v 1.5 2020/07/22 16:50:41 martin Exp $
#

# PROVIDE: mdnsd
# REQUIRE: network MOUNTCRITLOCAL staticroute
# BEFORE:  NETWORKING

$_rc_subr_loaded . /etc/rc.subr

name="mdnsd"
rcvar=$name
command="/usr/sbin/$name"
pidfile="/var/run/mdnsd/${name}.pid"
start_precmd="mdnsd_precmd"

mdnsd_precmd()
{
    if [ ! -d /var/run/mdnsd ]; then
        mkdir -p -m 755 /var/run/mdnsd
    fi
    chown _mdnsd:_mdnsd /var/run/mdnsd
}

load_rc_config $name
run_rc_command "$1"
