#!/bin/sh
#
# $NetBSD: mountall,v 1.5 2008/11/12 12:35:52 ad Exp $
#

# PROVIDE: mountall

$_rc_subr_loaded . /etc/rc.subr

name="mountall"
start_cmd="echo 'Mounting all filesystems...'; mount -a"
stop_cmd="echo 'Unmounting all filesystems...'; umount -a"

load_rc_config $name
run_rc_command "$1"
