#!/bin/sh
#
# $NetBSD: mountcritremote,v 1.5 2002/01/31 01:26:06 lukem Exp $
#

# PROVIDE: mountcritremote
# REQUIRE: NETWORKING root mountcritlocal

. /etc/rc.subr

#	Mount critical filesystems that may be remote.
#	(as specified in $critical_filesystems)
#	This usually includes /usr.
#
name="mountcritremote"
start_cmd="mount_critical_filesystems remote"
stop_cmd=":"

load_rc_config $name
run_rc_command "$1"
