#!/bin/sh
#
# $NetBSD: nfsd,v 1.4.6.1 2005/05/09 22:42:12 riz Exp $
#

# PROVIDE: nfsd
# REQUIRE: mountd

. /etc/rc.subr

name="nfsd"
rcvar="nfs_server"
command="/usr/sbin/${name}"
required_vars="mountd rpcbind"

load_rc_config $name
load_rc_config_var rpcbind rpcbind
load_rc_config_var mountd mountd
run_rc_command "$1"
