#!/bin/sh
#
# $NetBSD: npfd,v 1.1.2.2 2017/01/07 08:53:48 pgoyette Exp $
#

# PROVIDE: npfd
# REQUIRE: npf
# BEFORE:  SERVERS

$_rc_subr_loaded . /etc/rc.subr

name="npfd"
rcvar=$name
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"

load_rc_config $name
run_rc_command "$1"
