#!/bin/sh
#
# $NetBSD: ntpdate,v 1.21 2020/12/25 13:42:02 martin Exp $
#

# PROVIDE: ntpdate
# REQUIRE: NETWORKING mountcritremote syslogd named
# BEFORE: ntpd

$_rc_subr_loaded . /etc/rc.subr

name="ntpdate"
rcvar=$name
command="/usr/sbin/${name}"
start_cmd="ntpdate_start"
stop_cmd=":"

ntpdate_start()
{
	if [ -z "$ntpdate_hosts" ]; then
		ntpdate_hosts=$(awk '
			/^#/				{ next }
			/^(server|peer)[ \t]*127.127/	{ next }
			/^(server|peer|pool)/		{ if ($2 ~ /^-[46]/)
							    print $3
							  else
							    print $2 }
		' </etc/ntp.conf)
	fi
	if [ -n "$ntpdate_hosts"  ]; then
		echo "Setting date via ntp."
		$command $rc_flags $ntpdate_hosts
	fi
}

load_rc_config $name
run_rc_command "$1"
