#!/bin/sh
#
# $NetBSD: ntpdate,v 1.3.4.1 2000/08/09 19:09:44 lukem Exp $
#

# PROVIDE: ntpdate
# REQUIRE: NETWORK syslogd

. /etc/rc.subr

name="ntpdate"
start_precmd="checkyesno ntpdate"
start_cmd="ntpdate_start"
stop_cmd=":"

ntpdate_start()
{
	if [ -z "$ntpdate_hosts" ]; then
		ntpdate_hosts=`awk '
		    /^server[ \t]*127.127/	{next}
		    /^(server|peer)/		{print $2}
		' </etc/ntp.conf`
	fi
	if [ -n "$ntpdate_hosts"  ]; then
		echo "Setting date via ntp."
		ntpdate -b -s $ntpdate_hosts
	fi
}

load_rc_config $name
run_rc_command "$1"
