#!/bin/sh
#
# $NetBSD: pf,v 1.3.2.1 2005/08/15 19:02:49 tron Exp $
#

# PROVIDE: pf
# REQUIRE: NETWORKING
# BEFORE: SERVERS

$_rc_subr_loaded . /etc/rc.subr

name="pf"
rcvar=$name
start_cmd="pf_start"
stop_cmd="pf_stop"
reload_cmd="pf_reload"
status_cmd="pf_status"
extra_commands="reload status"

pf_start()
{
	echo "Enabling pf firewall."
	/sbin/pfctl -q -e 
	if [ -f ${pf_rules} ]; then
		/sbin/pfctl -q -f ${pf_rules}
	else
		warn "${pf_rules} not found; no pf rules loaded."
	fi
}

pf_stop()
{
	echo "Disabling pf firewall."
	/sbin/pfctl -q -Fa -d
}

pf_reload()
{
	echo "Reloading pf rules."
	if [ -f ${pf_rules} ]; then
		/sbin/pfctl -q -f ${pf_rules}
	else
		warn "${pf_rules} not found; no pf rules loaded."
	fi
}

pf_status()
{
	/sbin/pfctl -s info
}

load_rc_config $name
run_rc_command "$1"
