#!/bin/sh
#
# $NetBSD: postfix,v 1.2 2000/04/27 20:58:26 veego Exp $
#

# PROVIDE: mail
# REQUIRE: LOGIN

#	we could do this, but make mail start late, so that things like
#	.forward's are not processed until the system is fully operational
## REQUIRE: DAEMON

. /etc/rc.subr
. /etc/rc.conf

postfix_start_precmd() {
	postfix start
	return 1
}
start_precmd="postfix_start_precmd"

stop_precmd="checkyesno postfix"
stop_cmd="postfix stop"

reload_precmd="checkyesno postfix"
reload_cmd="postfix reload"

name="postfix"
required_files="/etc/${name}/main.cf"

run_rc_command "$1" "reload"
