#!/bin/sh
#
# $NetBSD: quota,v 1.1.1.1 2000/03/10 11:53:24 lukem Exp $
#

# PROVIDE: quota
# REQUIRE: mountall

. /etc/rc.subr
. /etc/rc.conf

name="quota"
start_cmd="quota_start"
stop_cmd="/usr/sbin/quotaoff -a"

quota_start()
{
	echo -n "Checking quotas:"
	/usr/sbin/quotacheck -a
	echo " done."
	/usr/sbin/quotaon -a
}

run_rc_command "$1"
