#!/bin/sh
#
# $NetBSD: racoon,v 1.5.92.1 2018/09/30 01:45:10 pgoyette Exp $
#

# PROVIDE: ike
# REQUIRE: kdc ppp
# BEFORE:  SERVERS
# KEYWORD: shutdown

$_rc_subr_loaded . /etc/rc.subr

name="racoon"
rcvar=$name
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/racoon/racoon.conf"

load_rc_config $name
run_rc_command "$1"
