#!/bin/sh
#
# $NetBSD: raidframe,v 1.11 2021/08/03 05:15:20 mlelstv Exp $
#

# PROVIDE: raidframe
# REQUIRE: devpubd
# BEFORE:  DISKS

$_rc_subr_loaded . /etc/rc.subr

name="raidframe"
rcvar=$name
start_cmd="raidframe_start"
stop_cmd=":"

raidframe_start()
{
	# Configure non-auto-configured raid devices.
	# Ensure order by globbing raid[0-9].conf before raid[1-9][0-9].conf.
	#
	for cfg in /etc/raid[0-9].conf /etc/raid[1-9][0-9].conf ; do
		[ ! -f $cfg ] && continue
		dev=${cfg##*/}
		dev=${dev%%.conf}
		raidctl -c $cfg $dev
	done
}

load_rc_config $name
run_rc_command "$1"
