#!/bin/sh
#
# $NetBSD: rarpd,v 1.6 2004/08/13 18:08:03 mycroft Exp $
#

# PROVIDE: rarpd
# REQUIRE: DAEMON
# BEFORE:  LOGIN

$_rc_subr_loaded . /etc/rc.subr

name="rarpd"
rcvar=$name
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/ethers"

load_rc_config $name
run_rc_command "$1"
