#!/bin/sh
#
# $NetBSD: routed,v 1.7 2002/03/22 04:34:00 thorpej Exp $
#

# PROVIDE: routed
# REQUIRE: DAEMON
# BEFORE:  LOGIN

. /etc/rc.subr

name="routed"
rcvar=$name
command="/sbin/${name}"
start_precmd="routed_precmd"

routed_precmd()
{
	if checkyesno gated && checkyesno routed; then
		warn "gated and routed both requested to be run: only running gated."
		return 1
	fi
}

load_rc_config $name
run_rc_command "$1"
