#!/bin/sh
#
# $NetBSD: routed,v 1.10 2007/04/21 15:20:07 tron Exp $
#

# PROVIDE: routed
# REQUIRE: network
# BEFORE:  NETWORKING

$_rc_subr_loaded . /etc/rc.subr

name="routed"
rcvar=$name
command="/sbin/${name}"
start_precmd="routed_precmd"

routed_precmd()
{
	if checkyesno gated && checkyesno routed; then
		warn "gated and routed both requested to be run: only running gated."
		return 1
	fi
}

load_rc_config $name
load_rc_config_var gated gated
run_rc_command "$1"
