#!/bin/sh
#
# $NetBSD: route6d,v 1.7 2007/04/21 15:20:07 tron Exp $
#

# PROVIDE: route6d
# REQUIRE: network mountcritlocal
# BEFORE:  NETWORKING

$_rc_subr_loaded . /etc/rc.subr

name="route6d"
rcvar=$name
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
