#!/bin/sh
#
# $NetBSD: rpcbind,v 1.7 2004/08/13 18:08:03 mycroft Exp $
#

# PROVIDE: rpcbind
# REQUIRE: NETWORKING ntpdate syslogd named ppp

$_rc_subr_loaded . /etc/rc.subr

name="rpcbind"
rcvar=$name
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"

load_rc_config $name
run_rc_command "$1"
