#!/bin/sh
#
# $NetBSD: rtadvd,v 1.2 2000/03/13 04:04:03 lukem Exp $
#

# PROVIDE: rtadvd
# REQUIRE: DAEMON

. /etc/rc.subr
. /etc/rc.conf

name="rtadvd"
command="/usr/sbin/${name}"
start_precmd="rtadvd_precmd"

rtadvd_precmd()
{
	if [ "$ip6mode" != "router" ]; then
		warn \
	"${name} cannot be used on IPv6 host, only on an IPv6 router."
		return 1
	fi
}

run_rc_command "$1"
