#!/bin/sh
#
# $NetBSD: sdpd,v 1.1 2006/06/19 15:44:36 gdamore Exp $
#

# PROVIDE: sdpd
# REQUIRE: bluetooth
# BEFORE: LOGIN

$rc_subr_loaded . /etc/rc.subr

name="sdpd"
rcvar=$name
command="/usr/sbin/${name}"

load_rc_config $name
control="${sdpd_control:-/var/run/sdp}"
group="${sdpd_groupname:-nobody}"
user="${sdpd_username:-nobody}"
command_args="-c ${control} -g ${group} -u ${user}"

run_rc_command "$1"
