#!/bin/sh
#
# $NetBSD: sdpd,v 1.2 2007/03/18 15:53:54 plunky Exp $
#

# PROVIDE: sdpd
# REQUIRE: bluetooth
# BEFORE: LOGIN

$rc_subr_loaded . /etc/rc.subr

name="sdpd"
rcvar=$name
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
