#!/bin/sh
#
# $NetBSD: sshd,v 1.29.4.1 2023/06/21 16:06:14 martin Exp $
#

# PROVIDE: sshd
# REQUIRE: LOGIN

$_rc_subr_loaded . /etc/rc.subr

name="sshd"
rcvar=$name
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/ssh/sshd_config"
extra_commands="check keygen reload"

sshd_keygen()
{
(
	keygen="/usr/bin/ssh-keygen"
	umask 022
	while read type bits filename;  do
		f="/etc/ssh/$filename"
		if [ -f "$f" ]; then
			continue
		fi
		case "${bits}" in
		-1)	bitarg=;;
		0)	bitarg="${ssh_keygen_flags}";;
		*)	bitarg="-b ${bits}";;
		esac
		"${keygen}" -t "${type}" ${bitarg} -f "${f}" -N '' -q && \
		    printf "ssh-keygen: " && "${keygen}" -f "${f}" -l
	done << _EOF
ecdsa	-1	ssh_host_ecdsa_key
ed25519	-1	ssh_host_ed25519_key
rsa	0	ssh_host_rsa_key
_EOF
)
}

sshd_precmd()
{
	run_rc_command keygen
}

sshd_check()
{
	sshd -t
}

sshd_reload_precmd()
{
	run_rc_command check
}

check_cmd=sshd_check
keygen_cmd=sshd_keygen
reload_precmd=sshd_reload_precmd
start_precmd=sshd_precmd

load_rc_config $name
run_rc_command "$1"
