#!/bin/sh
#
# $NetBSD: syslogd,v 1.3 2000/05/13 08:45:09 lukem Exp $
#

# PROVIDE: syslogd
# REQUIRE: systemfs

. /etc/rc.subr

name="syslogd"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/syslog.conf"
start_precmd="syslogd_precmd"
extra_commands="reload"

syslogd_precmd()
{
	#	Transitional symlink for old binaries
	#
	if [ ! -h /dev/log ]; then
		ln -sf /var/run/log /dev/log
	fi
	rm -f /var/run/log
	return 0
}

load_rc_config $name
run_rc_command "$1"
