#!/bin/sh
#
#	$NetBSD: veriexec,v 1.2 2004/01/15 11:20:19 uebayasi Exp $
#

# PROVIDE: veriexec
# REQUIRE: mountcritlocal
# BEFORE:  securelevel

. /etc/rc.subr

name="veriexec"
rcvar=$name
start_cmd="veriexec_start"

veriexec_start()
{
	echo -n "Loading fingerprints..."
	/sbin/veriexecctl /etc/signatures
	echo " done."
}

load_rc_config $name
run_rc_command "$1"
