#!/bin/sh
#
# $NetBSD: virecover,v 1.8 2004/08/13 18:08:03 mycroft Exp $
#

# PROVIDE: virecover
# REQUIRE: mountcritremote
# BEFORE:  DAEMON
#
# XXX: should require `mail'!

$_rc_subr_loaded . /etc/rc.subr

name="virecover"
rcvar=$name
command="/usr/libexec/${name}"
stop_cmd=":"
reload_cmd=":"

load_rc_config $name
run_rc_command "$1"
