#!/bin/sh
#
# $NetBSD: wdogctl,v 1.2.36.1 2009/05/13 19:18:03 jym Exp $
#

# PROVIDE: wdogctl
# BEFORE:  fsck_root

# The watchdog is configured VERY early, so that any problems that
# occur during the bootstrap process are protected by the watchdog.

$_rc_subr_loaded . /etc/rc.subr

name="wdogctl"
rcvar=$name

start_cmd="watchdog_start"
stop_cmd="watchdog_stop"
status_cmd="watchdog_status"

extra_commands="status"

watchdog_start()
{
	if [ x"${wdogctl_flags}" = "x" ]; then
		warn "\${wdogctl_flags} is not set, watchdog not started"
	else
		echo "Starting watchdog timer."
		/sbin/wdogctl ${wdogctl_flags}
	fi
}

watchdog_stop()
{
	echo "Stopping watchdog timer."
	/sbin/wdogctl -d
}

watchdog_status()
{
	/sbin/wdogctl
}

load_rc_config $name
run_rc_command "$1"
