#!/bin/sh
#
# $NetBSD: wscons,v 1.2 2000/03/11 20:11:16 veego Exp $
#

# PROVIDE: wscons
# REQUIRE: systemfs

. /etc/rc.subr
. /etc/rc.conf

name="wscons"
start_precmd="checkyesno wscons"
start_cmd="do_wscons"
stop_cmd=":"

do_wscons()
{
	if [ -f /etc/rc.wscons ]; then
		. /etc/rc.wscons
	fi
}

run_rc_command "$1"
