#!/bin/sh
#
# $NetBSD: yppasswdd,v 1.3 2000/05/13 08:45:10 lukem Exp $
#

# PROVIDE: yppasswdd
# REQUIRE: ypserv ypbind

. /etc/rc.subr

name="yppasswdd"
command="/usr/sbin/rpc.${name}"
required_vars="portmap ypserv"
start_precmd="yppasswdd_precmd"

yppasswdd_precmd()
{
	_domain=`domainname`
	if [ -z "$_domain" ]; then
		warn "domainname(1) is not set; ${name} not started"
		return 1
	fi
}

load_rc_config $name
run_rc_command "$1"
