#!/bin/sh
#
# $NetBSD: zfs,v 1.1 2019/09/15 19:38:09 brad Exp $
#

# PROVIDE: zfs
# REQUIRE: root
# BEFORE:  DISKS

$_rc_subr_loaded . /etc/rc.subr

name="zfs"
start_cmd="zfs_start"
stop_cmd="zfs_stop"

zfs_start()
{
	if [ -x /sbin/zfs -a -f /etc/zfs/zpool.cache ]; then
		# Get ZFS module loaded (and thereby, zvols created).
		/sbin/zfs list > /dev/null 2>&1
		if [ $? -ne 0 ]; then
			warn "zfs module may not have loaded, may not be present in the kernel, or /dev/zfs may be missing"
			return 1;
		fi
	fi
}

zfs_stop()
{
	if [ -x /sbin/zfs -a -f /etc/zfs/zpool.cache ]; then
		zfs unmount -a
		modunload zfs
	fi
	return 0;
}

load_rc_config $name
run_rc_command "$1"
