#	$NetBSD: Makefile,v 1.6.2.6 2002/12/11 06:37:47 thorpej Exp $

SUBDIR=	apm ata dec hpc i2o ic ieee1394 ir isa ofw pci pckbc pcmcia raidframe \
	sbus scsipi sun tc usb vme wscons 

INCSDIR= /usr/include/dev

# Only install includes which are used by userland
INCS=	ccdvar.h cgdvar.h kttcpio.h md.h vndvar.h

.include <bsd.kinc.mk>
