#	$NetBSD: Makefile,v 1.1.10.3 2017/12/03 11:39:11 jdolecek Exp $
#

.PATH:  ${.CURDIR}/../../../../kern

LIB=	rumpvfs_aio
COMMENT=POSIX asynchronous I/O system calls

SRCS=	sys_aio.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
