#	$NetBSD: Makefile,v 1.2 2015/10/19 16:16:35 pooka Exp $
#

.PATH:  ${.CURDIR}/../../../../kern

LIB=	rumpvfs_aio
COMMENT=POSIX asynchronous I/O system calls

SRCS=	sys_aio.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
