#	$NetBSD: Makefile,v 1.2.54.1 2019/06/10 22:09:20 christos Exp $

.include "../Makefile.inc"

.PATH:	${S}/dev/pci

KMOD=	coram
IOCONF=	coram.ioconf
SRCS=	coram.c

WARNS=	3

.include <bsd.kmodule.mk>
