#	$NetBSD: Makefile,v 1.2 2001/12/12 01:49:26 tv Exp $

SUBDIR= restartallprocs restartprocs showallprocs showprocs startallprocs
SUBDIR+= startprocs stopallprocs stopprocs topcpu topmem toptime

FILES=	help index
FILESDIR=${BINDIR}/sushi/procs
NOOBJ=	# defined

.include "../../Makefile.inc"
.include <bsd.prog.mk>
.include <bsd.subdir.mk>
