#	$NetBSD: bsd.i386.mk,v 1.4 2011/07/21 03:13:30 mrg Exp $

LD+=			-m elf_i386
MLIBDIR=		i386
LIBC_MACHINE_ARCH=	${MLIBDIR}
COMMON_MACHINE_ARCH=	${MLIBDIR}
KVM_MACHINE_ARCH=	${MLIBDIR}
PTHREAD_MACHINE_ARCH=	${MLIBDIR}
BFD_MACHINE_ARCH=	${MLIBDIR}
CSU_MACHINE_ARCH=	${MLIBDIR}
CRYPTO_MACHINE_CPU=	${MLIBDIR}
LDELFSO_MACHINE_CPU=	${MLIBDIR}

.include "${.PARSEDIR}/../../m32.mk"
