# $NetBSD: armv5.conf,v 1.1 2026/09/10 20:19:55 yurix Exp $
# ARMv5 customization script used by mkimage
#
board=armv5
resize=true

. ${DIR}/conf/evbarm.conf

kernels_generic="GENERIC_V5"

make_label() {
	make_label_evbarm
}

make_fstab() {
	make_fstab_evbarm
}

customize() {
	customize_evbarm
	cat >> "${mnt}/etc/rc.conf" << EOF
mdnsd=YES
devpubd=YES
wscons=\$(dev_exists wsdisplay0)
EOF
}

populate_common() {
	# Boot command
	cp ${DIR}/files/armv5_boot.cmd ${mnt}/boot/boot.cmd

	# Install boot script
	[ -n "${MKREPRO_TIMESTAMP}" ] && \
	    MKUBOOTIMAGEARGS="-t ${MKREPRO_TIMESTAMP}"
	"${MKUBOOTIMAGE}" -A arm -C none -O netbsd -T script \
	    ${MKUBOOTIMAGEARGS} -a 0 -n "NetBSD/armv5 boot" \
	    "${mnt}/boot/boot.cmd" "${mnt}/boot/boot.scr"
}

populate() {
	echo "${bar} looking for kernels in ${kernel} ${bar}"
	kernels=""
	# .ub kernels
	for k in $kernels_generic; do
		f="${kernel}/netbsd-${k}.ub.gz"
		test -f "${f}" && kernels="${kernels} ${f}"
	done
	# .img kernels
	for k in $kernels_generic; do
		f="${kernel}/netbsd-${k}.img.gz"
		test -f "${f}" && kernels="${kernels} ${f}"
	done

	# install kernels to /boot partition
	for k in ${kernels}; do
		tgt="$(basename ${k} | sed 's/\.gz$//')"
		echo "${bar} installing ${k} to /boot/${tgt} ${bar}"
		case "${k}" in
		*.gz)
			${GZIP_CMD} -dc "${k}" > "${mnt}/boot/${tgt}"
			;;
		*)
			cp "${k}" "${mnt}/boot/${tgt}"
			;;
		esac ||
			fail "Copy of ${k} to ${mnt}/boot/${tgt} failed"
	done

	# common configuration
	populate_common
}
