#	$NetBSD: Makefile,v 1.3.4.1 1997/11/08 06:10:35 lukem Exp $
#	@(#)Makefile	8.1 (Berkeley) 5/31/93

PROG=	snscore
CPPFLAGS+=-I${.CURDIR}/../snake
NOMAN=	noman
HIDEGAME=hidegame

.include "../../Makefile.inc"
.include <bsd.prog.mk>
