#	$NetBSD: Makefile,v 1.3.2.3 2002/05/04 19:44:57 thorpej Exp $

INCSDIR= /usr/include/dev/sun

# Only install includes which are used by userland
INCS=	disklabel.h fbio.h kbd_reg.h kbio.h sun_boot.h vuid_event.h

.include <bsd.kinc.mk>
