.\"	$NetBSD: audiocfg.1,v 1.1 2010/08/31 14:57:26 wiz Exp $
.\"
.\" Copyright (c) 2010 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Thomas Klausner.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd August 31, 2010
.Dt AUDIOCFG 1
.Os
.Sh NAME
.Nm audiocfg
.Nd configure default audio device
.Sh SYNOPSIS
.Nm
.Op index
.Sh DESCRIPTION
The
.Nm
utility helps maintaining a
.Pa /dev/audio
symlink.
Run without arguments, it lists the available audio devices and shows
the current default audio device.
If given an
.Ar index
argument, that device is set as default audio device.
.Nm
needs access to
.Pa /dev/drvctl
and write access to
.Pa /dev
(when given an
.Ar index )
to work.
.Sh FILES
.Bl -tag -width 10n
.It Pa /dev/audio
Symlink to default audio device.
.It Pa /dev/audio[0-9]*
Available audio devices.
.It Pa /dev/drvctl
Used for finding the correlating audio driver to an audio device.
.El
.Sh SEE ALSO
.Xr audioplay 1 ,
.Xr audiorecord 1 ,
.Xr audio 4 ,
.Xr drvctl 8
