#	$NetBSD: Makefile,v 1.1.1.1 1996/10/03 06:33:26 mrg Exp $

SRCS=	dhclient.c options.c errwarn.c convert.c tree.c memory.c alloc.c \
	print.c hash.c tables.c inet.c dispatch.c bpf.c packet.c raw.c nit.c \
	socket.c
PROG=	dhclient
NOMAN=	1
.PATH:	${.CURDIR}/..

.include <bsd.prog.mk>
