#	$NetBSD: Makefile,v 1.2.34.1 2009/05/04 08:14:26 yamt Exp $
#

.PATH:  ${.CURDIR}/../../../../fs/efs

LIB=	rumpfs_efs

SRCS=	efs_genfs.c efs_ihash.c efs_subr.c efs_vfsops.c efs_vnops.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
