#	$NetBSD: Makefile,v 1.23 2001/06/13 06:01:48 simonb Exp $

KDIR=	/sys/arch/powerpc/include
INCSDIR= /usr/include/powerpc

INCS=	ansi.h aout_machdep.h asm.h \
	bat.h bswap.h byte_swap.h \
	cdefs.h cpu.h \
	db_machdep.h \
	elf_machdep.h endian.h endian_machdep.h \
	float.h fpu.h frame.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	ipkdb.h \
	kcore.h \
	limits.h lock.h \
	math.h \
	param.h pcb.h pio.h pmap.h proc.h profile.h psl.h pte.h ptrace.h \
	reg.h reloc.h \
	setjmp.h signal.h stdarg.h \
	trap.h types.h \
	varargs.h

.include <bsd.kinc.mk>
