$set 1 errors
1 log_do arguments must be on or off
2 script_do arguments must be on or off
3 ftp_start failed
4 nlist failed
5 function not found
6 empty endpoint
7 select failed but no child died
8 failed to allocate status window
9 failed to allocate status box
10 failed to allocate output window
11 invalid data type
12 description too long
13 no files
14 invalid field type
15 error return from new form
16 cannot allocate scroll widget
17 select failure
18 can't stat
19 No menu hierchy found.
20 Bad keybinding
21 Bad keyword in config file
22 Null filename in escript argument
$set 2 labels
1 F1=Help
2 F2=Refresh
3 F3=Cancel
4 F4=List
5 F5=Reset
6 F6=Command
7 F7=Edit
8 F8=Image
9 F9=Shell
10 F10=Exit
11 </5><OK><!5>
12 Help
13 Script:
14 Log:
15 ON 
16 OFF
$set 3 run.c stuff
1 executing
2 Status
3 Running
4 Command
5 Lines
6 Failed
7 Finished
8 Press any key to continue
9 Use HOME,END,PGUP,PDGN,UP/DOWN Arrow keys to scroll ESC, F3 exits, F10 quits.
10 The current field is a list field, and selections can only be made from
11 the pre-defined list.  Please use TAB or the List(F4) command to edit.
12 Press the ENTER key to return from the list popup.
13 The current field is a multiple-selection list field.  The field can only
14 be edited by issuing the List(F4) command, and toggling desired options
15 with the spacebar.  Press the ENTER key to return from the list popup.
16 No help is available for this screen.
17 Are you sure? (Y/n)
$set 4 menu titles and stuff
1 Select choice
2 Generating form data, please wait
3 Log started at
4 Script started at
5 <C></5>Sushi\n\n
6 Enter the field data below, and hit enter to return to the form.
7 Data Entry: 
8 Form Page:
9 PGUP/PGDN to change page, UP/DOWN switch field, ENTER submit.
10 Log ended at
11 Script ended at
