#	$NetBSD: Makefile,v 1.1.28.1 2020/04/13 08:06:05 martin Exp $
#
# Makefile for prep
#

MENUS_MD=	menus.md.${SYSINSTLANG}
MSG_MD=		msg.md.${SYSINSTLANG} msg.mbr.${SYSINSTLANG}
LANGUAGES=	en pl de
NO_MBR=no

.include "../../Makefile.inc"
