#! /bin/sh --
#
#	$NetBSD: checkflist,v 1.8 1998/06/30 20:25:14 ross Exp $
#
# Verify output of makeflist against contents of $DESTDIR.

[ "$DESTDIR" ] || {
	echo DESTDIR must be set
	exit 1
}

if [ "$1" = "-x11" ]; then
	sh makeflist -x > /tmp/_CHECK.$$
elif [ "$1" = "-both" ]; then
	sh makeflist -b > /tmp/_CHECK.$$
else
	sh makeflist > /tmp/_CHECK.$$
fi
( cd $DESTDIR ; find . \( -type d -o -type f -o -type l \) ) | sort | \
    diff /tmp/_CHECK.$$ -
/bin/rm -f /tmp/_CHECK.$$
