#!/bin/sh
#
# $NetBSD: listpkgs,v 1.7 2003/12/29 03:13:25 lukem Exp $
#
# List all packages in the given pkgset by parsing the list files.
#

. ./sets.subr

prefix=/

usage()
{
	cat 1>&2 <<USAGE
Usage: ${0##*/} [-a arch] [-m machine] [-s setsdir] [-p prefix] setname
	-a arch		set arch (e.g, m68k, mips, powerpc)	[$machine_arch]
	-m machine	set machine (e.g, amiga, i386, macppc)	[$machine]
	-s setsdir	directory to find sets			[$setsdir]
	setname set to list packages for
USAGE
	exit 1
}

# handle args
while getopts a:m:s: ch; do
	case ${ch} in
	a)
		machine_arch=${OPTARG}
		machine_cpu=$(arch_to_cpu ${OPTARG})
		;;
	m)
		machine=${OPTARG}
		;;
	s)
		setsdir=${OPTARG}
		;;
	*)
		usage
		;;
	esac
done
shift $((${OPTIND} - 1))
if [ $# -ne 1 ]; then
	usage
fi
setname="$1"

list_set_files $setname | awk '{print $2}' | sort -u
