/* This file is automatically generated.  DO NOT EDIT! */
/* Generated from: 	NetBSD: mknative-gcc,v 1.7 2003/08/22 00:24:46 mrg Exp  */

/* Generated automatically. */
static const char configuration_arguments[] = "/usr/src/tools/gcc/../../gnu/dist/gcc/configure --enable-long-long --disable-multilib --enable-threads --build=alpha-unknown-netbsd --host=alpha--netbsd --target=alpha--netbsd";
static const char thread_model[] = "posix";
