# This file is automatically generated.  DO NOT EDIT!
# Generated from: 	NetBSD: mknative,v 1.9 2003/02/07 01:52:54 lukem Exp 
#
G_archdefs=-DARCH_vax
G_BFD_MACHINES=vax-dis.lo
G_libopcodes_la_SOURCES=dis-buf.c disassemble.c
