.\"	$NetBSD: catclose.3,v 1.9 2003/02/05 05:05:50 gmcgarry Exp $
.\"
.\" Written by J.T. Conklin <jtc@netbsd.org>.
.\" Public domain.
.\"
.Dd May 29, 1994
.Dt CATCLOSE 3
.Os
.Sh NAME
.Nm catclose
.Nd close message catalog
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.Fd #include \*[Lt]nl_types.h\*[Gt]
.Ft int
.Fn catclose "nl_catd catd"
.Sh DESCRIPTION
The
.Fn catclose
function closes the message catalog specified by the argument
.Fa catd .
.Sh SEE ALSO
.Xr gencat 1 ,
.Xr catgets 3 ,
.Xr catopen 3
.Sh STANDARDS
The
.Fn catclose
function conforms to
.St -xpg3 .
