# $NetBSD: Makefile,v 1.2 2025/11/29 00:07:26 nia Exp $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/usr.bin/diff3

TESTS_SH=	t_diff3

FILESDIR=	${TESTSDIR}
FILES+=		1.out
FILES+=		1t.out
FILES+=		2.out
FILES+=		5.out
FILES+=		6.out
FILES+=		7.out
FILES+=		8.out
FILES+=		9.out
FILES+=		long-A.out
FILES+=		long-ed.out
FILES+=		long-merge.out
FILES+=		1.txt
FILES+=		2.txt
FILES+=		3.txt
FILES+=		long-m.txt
FILES+=		long-o.txt
FILES+=		long-y.txt

.include <bsd.test.mk>
