#	$NetBSD: Makefile,v 1.1.4.2 2009/05/04 08:14:33 yamt Exp $
#

LIB=	rumpnet_shmif

SRCS=	if_shmem.c

CPPFLAGS+=	-I${.CURDIR}/../../../librump/rumpkern

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
