# $NetBSD: Makefile,v 1.8.24.1 2008/05/18 12:36:15 yamt Exp $

LIBISPRIVATE=	yes

LIB    = omapi
SRCS   = protocol.c buffer.c alloc.c result.c connection.c errwarn.c \
         listener.c dispatch.c generic.c support.c handle.c message.c \
	 auth.c convert.c hash.c array.c inet_addr.c mrtrace.c trace.c \
	 toisc.c

DHCPSRCDIR=	omapip

.include <bsd.lib.mk>
