#	$NetBSD: Makefile,v 1.1 2001/12/10 17:22:09 martin Exp $

PROG=	pppoectl
MAN=	pppoectl.8

LINKS=  ${BINDIR}/pppoectl ${BINDIR}/ispppcontrol
MLINKS= pppoectl.8 ispppcontrol.8

.include <bsd.prog.mk>
