#	$NetBSD: Makefile,v 1.5.72.1 2014/08/10 06:53:13 tls Exp $
#
#	@(#)Makefile	8.1 (Berkeley) 6/10/93

SECTION=reference/ref9
ARTICLE=net
SRCS=	0.t 1.t 2.t 3.t 4.t 5.t 6.t 7.t 8.t 9.t a.t b.t c.t d.t e.t f.t
MACROS=	-ms
ROFF_TBL=yes
EXTRAHTMLFILES=net1.png net2.png net3.png net4.png

.include <bsd.doc.mk>
