#	$NetBSD: Makefile.rumpnet,v 1.5.2.4 2010/08/11 22:55:08 yamt Exp $
#

RUMPNETLIST=	net net80211 netbt netinet local sockin shmif virtif

.for var in ${RUMPNETLIST}
RUMPNETLIBS+=lib${var}
RUMPNETLDADD+=-lrumpnet_${var}
.endfor
