#	$NetBSD: Makefile,v 1.16.42.1 2009/06/06 22:10:49 bouyer Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/5/93

# Missing: connectives, words

NOOBJ=	# defined

FILES=	README propernames web2 web2a
FILESDIR=${BINDIR}/dict
LINKS=	${FILESDIR}/web2 ${FILESDIR}/words
LINKSMODE= ${FILESMODE}

.include <bsd.prog.mk>
