#	$NetBSD: Makefile,v 1.16 2002/09/18 08:12:29 lukem Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/5/93

# Missing: connectives, words

NOOBJ=	# defined

FILES=	README propernames web2 web2a
FILESDIR=${BINDIR}/dict
LINKS=	${FILESDIR}/web2 ${FILESDIR}/words

.include <bsd.prog.mk>
