/* This file is automatically generated.  DO NOT EDIT! */
/* Generated from: 	NetBSD: toolchain2netbsd,v 1.11 2001/08/14 05:11:50 tv Exp  */

#ifdef IN_GCC
#include "auto-host.h"
#endif
#ifdef IN_GCC
#include "gansidecl.h"
#endif
#ifdef IN_GCC
#include "i386/xm-i386.h"
#endif
#ifdef IN_GCC
#include "xm-netbsdh"
#endif
#ifdef IN_GCC
#include "hwint.h"
#endif
