#	$NetBSD: Makefile,v 1.10 2007/01/25 23:25:20 cbiere Exp $
#	from: @(#)Makefile	5.4 (Berkeley) 5/11/93

PROG=	timedc
SRCS=	cmds.c cmdtab.c timedc.c byteorder.c measure.c cksum.c tspname.c
MAN=	timedc.8
BINOWN=	root
BINMODE=4555
.PATH:	${.CURDIR}/../timed

.include <bsd.prog.mk>
