#	$NetBSD: Makefile,v 1.4 2001/11/14 22:13:41 tv Exp $

HOSTPROGNAME=	nbmenuc
HOST_SRCDIR=	usr.bin/menuc
HOSTFILES=	menu_sys.def
HOST_FILESDIR=	${TOOLDIR}/share/misc
MKSHARE=no

.include "${.CURDIR}/../Makefile.host"
