#	$NetBSD: Makefile,v 1.1 2001/10/13 06:10:32 jmc Exp $

HOSTPROGNAME=	menuc
HOST_SRCDIR=	usr.bin/menuc
HOSTFILES=menu_sys.def
HOST_FILESDIR= ${TOOLDIR}/share/misc

.include "${.CURDIR}/../Makefile.host"


${TIMESTAMP}: ${SRCS}
