# This file is automatically generated.  DO NOT EDIT!
# Generated from: 	NetBSD: mknative-binutils,v 1.3 2003/12/04 14:38:00 mrg Exp 
#
G_DEFS=-DHAVE_CONFIG_H -I. -I/usr/src/tools/binutils/../../gnu/dist/binutils/gprof -I.
G_gprof_OBJECTS=basic_blocks.o call_graph.o  cg_arcs.o cg_dfn.o cg_print.o  corefile.o gmon_io.o gprof.o hertz.o  hist.o source.o search_list.o symtab.o  sym_ids.o utils.o i386.o alpha.o  vax.o tahoe.o sparc.o mips.o  flat_bl.o bsd_callg_bl.o fsf_callg_bl.o
G_INCLUDES=-D_GNU_SOURCE -DDEBUG -I../bfd -I/usr/src/tools/binutils/../../gnu/dist/binutils/gprof/../include -I/usr/src/tools/binutils/../../gnu/dist/binutils/gprof/../bfd -I/usr/src/tools/binutils/../../gnu/dist/binutils/gprof/../intl -I../intl -I. -DLOCALEDIR="\"/usr/local/share/locale\""
G_TEXINFOS=gprof.texi
