.\"	$NetBSD: ffb.4,v 1.2.42.1 2018/03/30 06:20:10 pgoyette Exp $
.\"
.\" Copyright (c) 2011 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Julian Coleman
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd April 1, 2011
.Dt FFB 4 sparc64
.Os
.Sh NAME
.Nm ffb
.Nd Sun accelerated 24-bit color frame buffer
.Sh SYNOPSIS
.Cd "ffb* at mainbus0 addr 0xff8de000: Creator3D, model SUNW,501-4790, dac 10"
.Pq UltraSPARC II horizontal
.Cd "ffb* at mainbus0 addr 0xfeb80000: Creator3D, model SUNW,501-4788, dac 10"
.Pq UltraSPARC II vertical
.Cd "ffb* at mainbus0: Elite3D, model SUNW,540-3623, dac 10"
.Pq UltraSPARC II vertical
.Cd "ffb* at upa0: Creator3D, model SUNW,501-4788, dac 10"
.Pq UltraSPARC III vertical
.Cd "ffb* at upa0: Elite3D, model SUNW,540-3623, dac 10"
.Pq UltraSPARC III vertical
.Sh DESCRIPTION
The
.Nm
is a UPA based color frame buffer, found in some Sun SBus and PCI systems.
The
.Nm
driver supports both the Creator/Creator3D, and the Elite3D frame buffers.
.Pp
There are several versions of the
.Nm
board.
The Sun part numbers and board types are:
.Pp
.Bl -tag -offset indent -compact
.It 501-2634
Creator Series 1 (FFB)
.It " "
Ultra1, Ultra2
.It 501-4127
Creator Series 1 (FFB)
.It " "
Ultra1, Ultra2, Enterprisexx00
.It 501-2633
Creator 3D Series 1 (FFB)
.It " "
Ultra1, Ultra2
.It 501-3129
Creator 3D Series 1 (FFB)
.It " "
Ultra1, Ultra2, Enterprisexx00
.It 501-4126
Creator 3D Series 1 (FFB)
.It " "
Ultra1, Ultra2
.It 501-4174
Creator Series 2 (FFB2)
.It " "
Ultra 30, Ultra 60
.It 501-4173
Creator3D Series 2 (FFB2)
.It " "
Ultra1, Ultra2, Enterprisexx00
.It 501-4172
Creator3D Series 2 (FFB2)
.It " "
Ultra30, Ultra60
.It 501-4789
Creator Series 3 (FFB2+)
.It " "
Ultra10, Ultra30, Ultra60
.It 501-4790
Creator 3D Series 3 (FFB2+)
.It " "
Ultra2, Enterprisexx00
.It 501-4788, 501-5690
Creator 3D Series 3 (FFB2+)
.It " "
Ultra10, Ultra30, Ultra60, Blade1000, Blade2000
.It 501-4860, 501-5268, 501-5201, 501-5484
Elite3D-m3 Series 1 (AFB)
.It " "
Ultra10, Ultra30, Ultra60, Ultra80
.It 540-3623, 540-3902
Elite3D-m6 Series 1 (AFB)
.It " "
Ultra10, Ultra30, Ultra60, Ultra80
.It 501-5574, 501-5575
Elite3D-m3 Series 2 (AFB)
.It " "
Ultra10, Ultra30, Ultra60, Ultra80, Blade1000, Blade2000
.It 540-4313
Elite3D-m6 Series 2 (AFB)
.It " "
Ultra10, Ultra30, Ultra60, Ultra80, Blade1000, Blade2000
.It 540-3058, 540-3979, 540-4335
Elite3D-m6 (AFB)
.It " "
Ultra2, Ultra450, Enterprisexx00
.El
.Pp
The
.Sq Creator
cards have 5MB of on-board memory, support a maximum graphics resolution
of 1280x1024, and are single-buffered.
.Pp
The
.Sq Creator3D
cards have 15MB of on-board memory support a maximum resolution of
1280x1024 double-buffered, and 1920x1360 single-buffered.
.Pp
The
.Sq Elite3D
cards have 15MB of on-board memory, support a maximum resolution of
1280x1024, and are always double-buffered.
The
.Sq Elite3D-m3
cards have one hardware geometry engine, whereas the
.Sq Elite3D-m6
cards have two.
.Pp
The
.Sq Series 3
cards are considerably faster than the
.Sq Series 1
and
.Sq Series 2
cards.
.Pp
The
.Nm
driver supports reading
.Dv EDID
data from connected monitors on
.Sq Series 2
and
.Sq Series 3
cards, and will automatically set a resolution that is supported by both the
card and the monitor if the
.Dv EDID
data can be read.
This can be overridden for the console frame buffer, by setting the
.Dv output-device
openprom variable.
For example, the following openprom command will set the console resolution
to 1280x1024 @ 60Hz, which will not be altered by the
.Nm
driver.
.Bd -literal -offset indent
setenv output-device screen:r1280x1024x60
.Ed
.Sh SEE ALSO
.Xr eeprom 8
.Sh BUGS
It is necessary to blank the video output when reading
.Dv EDID
data.
.Pp
The
.Nm
driver does not support 3D acceleration.
.Pp
Not all
.Dv 13W3
to
.Dv VGA
converters connect
.Dv 13W3
pin 2 to
.Dv VGA
pin 9.
This pin supplies +5V DC to power the monitor
.Dv EEPROM ,
even when the monitor
is powered off, and is necessary in order to obtain
.Dv EDID
data on some monitors.
.Pp
Adapters that are known to connect these pins are:
.Pp
.Bl -tag -offset indent -compact
.It 530-2917
.Dv 13W3
cable
.It 130-3034
.Dv VGA
cable
.El
.Pp
Adapters that are known not to connect these pins are:
.Pp
.Bl -tag -offset indent -compact
.It 530-2357
.Dv 13W3
cable
.El
