.\"	$NetBSD: skeyaudit.1,v 1.6 2001/04/09 12:34:14 wiz Exp $
.\"
.Dd June 9, 1994
.Dt SKEYAUDIT 1
.Os
.Sh NAME
.Nm skeyaudit
.Nd warn users if their S/Key will soon expire
.Sh SYNOPSIS
.Nm
.Op Ar limit
.Sh DESCRIPTION
.Nm
searches through the file
.Dq Pa /etc/skeykeys
for users whose S/Key sequence number is less than
.Ar limit ,
and sends them a reminder to run
.Xr skeyinit 1
soon. If no limit is specified a default of 12 is used.
.Sh FILES
.Bl -tag -width /etc/skeykeys -compact
.It Pa /etc/skeykeys
The S/Key key information database
.El
.Sh SEE ALSO
.Xr skey 1 ,
.Xr skeyinfo 1 ,
.Xr skeyinit 1
