# This file is automatically generated.  DO NOT EDIT!
# Generated from: 	NetBSD: mknative-binutils,v 1.2 2003/11/27 10:52:53 mrg Exp 
#
G_archdefs=-DARCH_rs6000 -DARCH_powerpc
G_BFD_MACHINES=ppc-dis.lo ppc-opc.lo
G_libopcodes_la_SOURCES=dis-buf.c disassemble.c
