#	$NetBSD: Makefile,v 1.5 1997/10/16 05:24:23 lukem Exp $
#	@(#)Makefile	8.1 (Berkeley) 5/31/93

SUBDIR=	common_source backgammon teachgammon

all-backgammon all-teachgammon: all-common_source 

.include <bsd.subdir.mk>
