#	$Id: Makefile,v 1.6 1993/10/15 13:52:26 cgd Exp $

LIB=	netboot
SRCS+=	arp.c bootinfo.c bootp.c exec.c globals.c in_cksum.c \
	net.c netif.c rpc.c util.c

SRCS+=	boot_nfs.c boot_tftp.c

NOPROFILE=
NOPIC=

install:

.include <bsd.lib.mk>
