#	$NetBSD: Makefile,v 1.9 2001/11/22 19:19:49 thorpej Exp $

KDIR=	/sys/arch/cats/include
INCSDIR= /usr/include/arm/cats

INCS=	bootconfig.h \
	frame.h \
	intr.h irqhandler.h \
	joystick.h \
	param.h pci_machdep.h pmap.h psl.h \
	rtc.h \
	types.h \
	vmparam.h

.include <bsd.kinc.mk>
