#	$Id: Makefile.src,v 1.4 1993/11/21 18:57:11 brezak Exp $

RPCSRCS=        bootparam_prot.x klm_prot.x mount.x nfs_prot.x nlm_prot.x \
		rex.x rnusers.x rusers.x rquota.x rstat.x rwall.x sm_inter.x \
		spray.x yp.x yppasswd.x
