/*
 * System call numbers.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from	NetBSD: syscalls.master,v 1.7 1995/05/10 16:45:47 christos Exp 
 */

#define	HPUX_SYS_syscall	0
#define	HPUX_SYS_exit	1
#define	HPUX_SYS_hpux_fork	2
#define	HPUX_SYS_hpux_read	3
#define	HPUX_SYS_hpux_write	4
#define	HPUX_SYS_hpux_open	5
#define	HPUX_SYS_close	6
#define	HPUX_SYS_hpux_wait	7
#define	HPUX_SYS_hpux_creat	8
#define	HPUX_SYS_link	9
#define	HPUX_SYS_unlink	10
#define	HPUX_SYS_hpux_execv	11
#define	HPUX_SYS_chdir	12
				/* 13 is compat_hpux_6x time */
#define	HPUX_SYS_mknod	14
#define	HPUX_SYS_chmod	15
#define	HPUX_SYS_chown	16
#define	HPUX_SYS_obreak	17
				/* 18 is compat_hpux_6x stat */
#define	HPUX_SYS_compat_43_lseek	19
#define	HPUX_SYS_getpid	20
#define	HPUX_SYS_setuid	23
#define	HPUX_SYS_getuid	24
				/* 25 is compat_hpux_6x stime */
#define	HPUX_SYS_hpux_ptrace	26
				/* 27 is compat_hpux_6x alarm */
				/* 28 is compat_hpux_6x fstat */
				/* 29 is compat_hpux_6x pause */
				/* 30 is compat_hpux_6x utime */
				/* 31 is compat_hpux_6x stty */
				/* 32 is compat_hpux_6x gtty */
#define	HPUX_SYS_access	33
				/* 34 is compat_hpux_6x nice */
				/* 35 is compat_hpux_6x ftime */
#define	HPUX_SYS_sync	36
#define	HPUX_SYS_hpux_kill	37
#define	HPUX_SYS_hpux_stat	38
				/* 39 is compat_hpux_6x setpgrp */
#define	HPUX_SYS_hpux_lstat	40
#define	HPUX_SYS_hpux_dup	41
#define	HPUX_SYS_pipe	42
				/* 43 is compat_hpux_6x times */
#define	HPUX_SYS_profil	44
#define	HPUX_SYS_setgid	46
#define	HPUX_SYS_getgid	47
				/* 48 is compat_hpux_6x ssig */
#define	HPUX_SYS_hpux_ioctl	54
#define	HPUX_SYS_symlink	56
#define	HPUX_SYS_hpux_utssys	57
#define	HPUX_SYS_readlink	58
#define	HPUX_SYS_execve	59
#define	HPUX_SYS_umask	60
#define	HPUX_SYS_chroot	61
#define	HPUX_SYS_hpux_fcntl	62
#define	HPUX_SYS_hpux_ulimit	63
#define	HPUX_SYS_hpux_vfork	66
#define	HPUX_SYS_vread	67
#define	HPUX_SYS_vwrite	68
#define	HPUX_SYS_hpux_mmap	71
#define	HPUX_SYS_munmap	73
#define	HPUX_SYS_mprotect	74
#define	HPUX_SYS_getgroups	79
#define	HPUX_SYS_setgroups	80
#define	HPUX_SYS_hpux_getpgrp2	81
#define	HPUX_SYS_hpux_setpgrp2	82
#define	HPUX_SYS_setitimer	83
#define	HPUX_SYS_hpux_wait3	84
#define	HPUX_SYS_getitimer	86
#define	HPUX_SYS_dup2	90
#define	HPUX_SYS_hpux_fstat	92
#define	HPUX_SYS_select	93
#define	HPUX_SYS_fsync	95
#define	HPUX_SYS_sigreturn	103
#define	HPUX_SYS_hpux_sigvec	108
#define	HPUX_SYS_hpux_sigblock	109
#define	HPUX_SYS_hpux_sigsetmask	110
#define	HPUX_SYS_hpux_sigpause	111
#define	HPUX_SYS_compat_43_sigstack	112
#define	HPUX_SYS_gettimeofday	116
#define	HPUX_SYS_hpux_readv	120
#define	HPUX_SYS_hpux_writev	121
#define	HPUX_SYS_settimeofday	122
#define	HPUX_SYS_fchown	123
#define	HPUX_SYS_fchmod	124
#define	HPUX_SYS_hpux_setresuid	126
#define	HPUX_SYS_hpux_setresgid	127
#define	HPUX_SYS_rename	128
#define	HPUX_SYS_compat_43_truncate	129
#define	HPUX_SYS_compat_43_ftruncate	130
#define	HPUX_SYS_hpux_sysconf	132
#define	HPUX_SYS_mkdir	136
#define	HPUX_SYS_rmdir	137
#define	HPUX_SYS_hpux_getrlimit	144
#define	HPUX_SYS_hpux_setrlimit	145
#define	HPUX_SYS_hpux_rtprio	152
#define	HPUX_SYS_hpux_netioctl	154
#define	HPUX_SYS_hpux_lockf	155
#define	HPUX_SYS_semget	156
#define	HPUX_SYS___semctl	157
#define	HPUX_SYS_semop	158
#define	HPUX_SYS_msgget	159
#define	HPUX_SYS_msgctl	160
#define	HPUX_SYS_msgsnd	161
#define	HPUX_SYS_msgrcv	162
#define	HPUX_SYS_shmget	163
#define	HPUX_SYS_hpux_shmctl	164
#define	HPUX_SYS_shmat	165
#define	HPUX_SYS_shmdt	166
#define	HPUX_SYS_hpux_advise	167
#define	HPUX_SYS_hpux_getcontext	174
#define	HPUX_SYS_hpux_getaccess	190
#define	HPUX_SYS_hpux_waitpid	200
#define	HPUX_SYS_pathconf	225
#define	HPUX_SYS_fpathconf	226
#define	HPUX_SYS_compat_43_getdirentries	231
#define	HPUX_SYS_compat_09_getdomainname	232
#define	HPUX_SYS_compat_09_setdomainname	236
#define	HPUX_SYS_hpux_sigaction	239
#define	HPUX_SYS_hpux_sigprocmask	240
#define	HPUX_SYS_hpux_sigpending	241
#define	HPUX_SYS_hpux_sigsuspend	242
#define	HPUX_SYS_compat_43_getdtablesize	268
#define	HPUX_SYS_fchdir	272
#define	HPUX_SYS_compat_43_accept	275
#define	HPUX_SYS_bind	276
#define	HPUX_SYS_connect	277
#define	HPUX_SYS_compat_43_getpeername	278
#define	HPUX_SYS_compat_43_getsockname	279
#define	HPUX_SYS_getsockopt	280
#define	HPUX_SYS_listen	281
#define	HPUX_SYS_compat_43_recv	282
#define	HPUX_SYS_compat_43_recvfrom	283
#define	HPUX_SYS_compat_43_recvmsg	284
#define	HPUX_SYS_compat_43_send	285
#define	HPUX_SYS_compat_43_sendmsg	286
#define	HPUX_SYS_sendto	287
#define	HPUX_SYS_hpux_setsockopt2	288
#define	HPUX_SYS_shutdown	289
#define	HPUX_SYS_socket	290
#define	HPUX_SYS_socketpair	291
#define	HPUX_SYS_nsemctl	312
#define	HPUX_SYS_nmsgctl	313
#define	HPUX_SYS_hpux_nshmctl	314
#define	HPUX_SYS_MAXSYSCALL	315
