# $NetBSD: Makefile,v 1.5 2010/12/16 22:54:22 joerg Exp $

# $FreeBSD: src/gnu/usr.bin/groff/src/utils/addftinfo/Makefile,v 1.4 2003/05/01 13:22:20 ru Exp $

DIST_SUBDIR=	src/utils/addftinfo

PROG=		addftinfo
SRCS=		addftinfo.cpp guess.cpp
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
