#	$NetBSD: Makefile,v 1.4.2.2 2001/09/13 01:13:33 thorpej Exp $

KDIR=	/sys/arch/dnard/include
INCSDIR= /usr/include/arm/dnard

INCS=	bootconfig.h \
	conf.h \
	db_machdep.h \
	frame.h \
	intr.h irqhandler.h \
	joystick.h \
	katelib.h kerndebug.h \
	ofisa_machdep.h \
	param.h pmap.h psl.h \
	scrio.h \
	types.h \
	vmparam.h

.include <bsd.kinc.mk>
