#	$NetBSD: Makefile,v 1.1 2010/03/30 00:59:07 pooka Exp $
#

.PATH:  ${.CURDIR}/../../../../miscfs/nullfs

LIB=	rumpfs_nullfs

SRCS=	null_vfsops.c null_vnops.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
