.\"     $NetBSD: pthread_attr_setname_np.3,v 1.1 2007/12/14 21:51:21 yamt Exp $
.\"
.\" Copyright (c)2007 YAMAMOTO Takashi,
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" ------------------------------------------------------------
.Dd December 15, 2007
.Dt PTHREAD_ATTR_SETNAME_NP 3
.Os
.Sh NAME
.Nm pthread_attr_setname_np
.Nd set descriptive name of an attribute
.\" ------------------------------------------------------------
.Sh LIBRARY
.Lb libc
.\" ------------------------------------------------------------
.Sh SYNOPSIS
.In pthread.h
.Ft int
.Fn pthread_attr_setname_np "pthread_attr_t attr" "const char *name" \
    "void *arg"
.\" ------------------------------------------------------------
.Sh DESCRIPTION
.Fn pthread_attr_setname_np
sets the descriptive name of the attribute.
It takes the following arguments.
.Bl -tag -width attr
.It Fa attr
The attribute whose descriptive name will be set.
.It Fa name
The 
.Xr printf 3
format string to be used to construct the descriptive name of the attribute.
The resulted descriptive name should be shorter than
.Dv PTHREAD_MAX_NAMELEN_NP .
.It Fa arg
The
.Xr printf 3
argument used with
.Fa name .
.El
.\" ------------------------------------------------------------
.Sh RETURN VALUES
.Fn pthread_attr_setname_np
returns 0 on success.
Otherwise,
.Fn pthread_attr_setname_np
returns an error number described in
.Xr errno 2 .
.\" ------------------------------------------------------------
.\".Sh ERRORS
.\" ------------------------------------------------------------
.Sh SEE ALSO
.Xr errno 2 ,
.Xr pthread_attr_getname_np 3
