#	$NetBSD: Makefile,v 1.8.36.2 2008/01/08 22:09:18 bouyer Exp $

INCSDIR= /usr/include/amd64

INCS=	ansi.h aout_machdep.h asm.h \
	bootinfo.h bswap.h bus.h byte_swap.h \
	cdefs.h cpu.h cpufunc.h \
	disklabel.h \
	elf_machdep.h endian.h endian_machdep.h \
	float.h fpu.h frame.h frame_regs.h \
	gdt.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intr.h intrdefs.h \
	joystick.h \
	kcore.h \
	limits.h linux32_machdep.h lock.h \
	math.h mcontext.h mutex.h mtrr.h \
	netbsd32_machdep.h \
	param.h pcb.h pci_machdep.h pio.h pmap.h pmc.h proc.h \
	profile.h psl.h pte.h ptrace.h \
	reg.h rwlock.h \
	segments.h setjmp.h signal.h specialreg.h stdarg.h sysarch.h \
	trap.h tss.h types.h \
	userret.h \
	varargs.h vmparam.h \
	wchar_limits.h

.include <bsd.kinc.mk>
