#	$NetBSD: Makefile,v 1.1.1.1.4.1 1999/11/15 00:37:50 fvdl Exp $

KDIR=	/sys/arch/hpcmips/include
INCSDIR= /usr/include/hpcmips

INCS= ansi.h aout_machdep.h asm.h autoconf.h bootinfo.h bswap.h bus.h \
	cdefs.h clock_machdep.h cpu.h db_machdep.h disklabel.h \
	ecoff_machdep.h elf_machdep.h endian.h intr.h kcore.h \
	limits.h locore.h param.h pcb.h pmap.h proc.h psl.h pte.h ptrace.h \
	reg.h regdef.h regnum.h reloc.h signal.h stdarg.h sysconf.h \
	types.h vmparam.h setjmp.h float.h ieeefp.h ieee.h \
	bsd-aout.h kdbparam.h mips_opcode.h profile.h trap.h varargs.h

.include <bsd.kinc.mk>
