#	$NetBSD: Makefile,v 1.8 1997/10/24 09:01:16 lukem Exp $

.PATH:	${.CURDIR}/../lint1

PROG=	xlint
PROGNAME= lint
SRCS=	xlint.c mem.c
MAN=	lint.1

CPPFLAGS+=-I${.CURDIR}/../lint1

.include <bsd.prog.mk>
