#	$NetBSD: Makefile,v 1.6 2002/04/11 12:17:14 lukem Exp $

IMAGE=		boot-ps2.fs
KERNELDIR=	kernel-ramdisk
KERNEL=		netbsd.INSTALL_PS2.gz
DISKSIZE=	2880

.include "${.CURDIR}/../common/Makefile.bootfloppy"
