#	$NetBSD: Makefile,v 1.7.8.1 2000/11/20 20:27:55 bouyer Exp $

.include <bsd.own.mk>

PROG=	installboot
MKMAN= no
NOMAN= yes
BINDIR=/usr/mdec

# Need this to work in the miniroot
LDSTATIC?=	-static

.include <bsd.prog.mk>
