#	from: @(#)Makefile	5.1 (Berkeley) 2/12/91
#	$NetBSD: Makefile,v 1.2 2000/07/22 23:14:38 bjh21 Exp $

MAN=	arckbd.4 cpu.4 dtide.4 ea.4 ei.4

MLINKS=	arckbd.4 arcwskbd.4 arckbd.4 arcwsmouse.4
MANSUBDIR=/arm26

.include <bsd.man.mk>
