#!/bin/sh -
#
#	$NetBSD: reset_button,v 1.2 2003/10/30 17:32:45 mycroft Exp $
#
# Generic script for reset button events.  We simply attempt to
# reboot the system gracefully.
#
# Arguments passed by powerd(8):
#
#	device event

case "${2}" in
pressed)
	/sbin/shutdown -r now
	exit 0
	;;

*)
	logger -p warning "${0}: unsupported event ${2} on device ${1}" >&1
	exit 1
	;;
esac
