#	$NetBSD: Makefile,v 1.1 2011/01/26 01:18:48 pooka Exp $
#	from: @(#)Makefile	8.2 (Berkeley) 2/16/94

MAN=	ace.4 autoconf.4 dz.4 ebus.4 eclock.4 enic.4 intro.4
MANSUBDIR=/emips

.include <bsd.man.mk>
