#	$NetBSD: Makefile.inc,v 1.4 2002/12/02 13:18:14 lukem Exp $
#
#	etc.walnut/Makefile.inc -- walnut-specific etc Makefile targets
#

KERNEL_SETS=		WALNUT
KERNEL_SUFFIXES=	img

BUILD_KERNELS=		INSTALL
