# $NetBSD: Makefile.sendmail,v 1.5 2003/10/22 06:04:03 lukem Exp $

CFDIR?=		${.CURDIR}/..
CHMOD=		chmod
TOOL_M4?=	/usr/bin/m4
ROMODE=		444
RM=		rm -f

.if !defined(FILES)
.SUFFIXES: .cf .mc
.mc.cf:
.else
__makemc: .USE
	${_MKTARGET_CREATE}
.endif
	${RM} $@
	(cd ${CFDIR}/cf && \
	    ${TOOL_M4} ${CFDIR}/m4/cf.m4 ${.CURDIR}/${@:R}.mc > ${.OBJDIR}/$@)
	${CHMOD} ${ROMODE} $@

.for F in ${FILES:M*.mc}
${F:S/.mc/.cf/}: ${F} __makemc
.endfor
