#	$NetBSD: Makefile,v 1.7 1997/10/08 19:13:39 christos Exp $
#	from: @(#)Makefile	5.11 (Berkeley) 3/12/91

PROG=	rdist
SRCS=	docmd.c expand.c lookup.c main.c server.c
OBJS+=	gram.o
CLEANFILES=y.tab.h

.include <bsd.prog.mk>
