#	$NetBSD: Makefile,v 1.141 2016/01/12 22:59:53 christos Exp $

.include <bsd.own.mk>

SUBDIR+=	bc
SUBDIR+=	c89 c99
SUBDIR+=	dc diffutils
SUBDIR+=	rcs send-pr texinfo

.if ${MKGROFF} != "no"
SUBDIR+=	groff
.endif

.include <bsd.subdir.mk>
