# $Header: /cvsroot/src/gnu/usr.bin/Attic/Makefile,v 1.11 1993/07/09 13:32:33 paul Exp $

SUBDIR+= bc-1.02 gzip-1.1.1 tar-1.11.2 gawk-2.15.2
SUBDIR+= diff diff3 sdiff gas gcc gdb lex pr sort
SUBDIR+= ld groff grep 
SUBDIR+= rcs

.include <bsd.subdir.mk>
