#	$NetBSD: Makefile,v 1.2.26.1 2011/01/06 21:42:50 riz Exp $

SUBDIR= dnssec-dsfromkey dnssec-keyfromlabel dnssec-keygen dnssec-signzone \
	dnssec-settime dnssec-revoke

.include "Makefile.inc"

.include <bsd.subdir.mk>
