#	$NetBSD: Makefile,v 1.1 2002/03/16 15:47:56 tsutsui Exp $
#
# Makefile for newsmips
#

# have to have all of them here for crunch ...

SRCS=	menu_defs.c msg_defs.c main.c install.c upgrade.c \
	txtwalk.c run.c factor.c net.c disks.c disks_lfs.c util.c geom.c \
	label.c target.c md.c

md.o:	menu_defs.h msg_defs.h

.include "../../Makefile.inc"
