#	$NetBSD: Makefile,v 1.3 2010/07/24 07:46:52 jruoho Exp $

INCSDIR= /usr/include/ia64

INCS=	_regset.h acpi_func.h acpi_machdep.h ansi.h \
	aout_machdep.h asm.h atomic.h bootinfo.h bswap.h cdefs.h \
	cpu.h cpufunc.h dig64.h disklabel.h efi.h \
	elf_machdep.h endian.h endian_machdep.h float.h fpu.h frame.h \
	ia64_cpu.h int_const.h int_fmtio.h int_limits.h \
	int_mwgwtypes.h int_types.h intr.h intrcnt.h limits.h \
	loadfile_machdep.h lock.h mca_machdep.h mcontext.h md_var.h \
	pal.h param.h pcb.h pmap.h proc.h pte.h ptrace.h reg.h sal.h \
	setjmp.h signal.h smp.h ssc.h stdarg.h types.h varargs.h \
	vmparam.h wchar_limits.h

.include <bsd.kinc.mk>
