#!/bin/sh -
#
#	$NetBSD: monthly,v 1.6 1997/02/15 10:02:18 mikel Exp $
#	from: @(#)monthly	8.1 (Berkeley) 6/9/93
#

host=`hostname`
echo "Subject: $host monthly run output"

umask 077

if [ -s /etc/monthly.conf ]; then
	. /etc/monthly.conf
fi

# echo ""
# echo "Doing login accounting:"
# ac -p | sort -nr +1

echo "Nothing to do!"
#echo "."
