#!/bin/sh -
#
#	$NetBSD: monthly,v 1.9 2004/04/02 13:13:47 jmmv Exp $
#	from: @(#)monthly	8.1 (Berkeley) 6/9/93
#

export PATH=/bin:/usr/bin:/sbin:/usr/sbin
umask 077

if [ -s /etc/monthly.conf ]; then
	. /etc/monthly.conf
fi

host=`hostname`
date=`date`
rcvar_manpage='monthly.conf(5)'

echo "To: ${MAILTO:-root}"
echo "Subject: $host monthly output for $date"
echo ""

# echo ""
# echo "Doing login accounting:"
# ac -p | sort -nr +1

if [ -f /etc/monthly.local ]; then
	echo ""
	echo "Running /etc/monthly.local:"
	. /etc/monthly.local
fi
