#!/bin/sh -
#
#	$NetBSD: weekly,v 1.10 1998/01/26 12:02:58 lukem Exp $
#	from: @(#)weekly	8.2 (Berkeley) 1/2/94
#

PATH=/bin:/sbin:/usr/sbin:/usr/bin:/usr/libexec
export PATH
host=`hostname`
echo "Subject: $host weekly run output"

umask 077

if [ -f /etc/rc.subr ]; then
	. /etc/rc.subr
else
	echo "Can't read /etc/rc.subr; aborting."
	exit 1;
fi

if [ -s /etc/weekly.conf ]; then
	. /etc/weekly.conf
fi

#echo ""
#echo "Removing old .o files:"
#find /usr/src -name '*.o' -atime +21 -print -a -exec rm -f {} \;

# see if /usr/src exists and is local
# before looking there for checked-out files

#if [ -d /usr/src -a \
#  -n "`find -f /usr/src ! -fstype local -prune -or -type d -print -prune`" ];
#then
#	echo "looking for checked out files:"
#	TDIR=/tmp/_checkout$$
#
#	mkdir $TDIR
#	for file in `find -f /usr/src ! -fstype local -prune -or \
#	    -name 'p.*' -print | egrep 'SCCS/p\.'`; do
#		owner=`awk '{ print $3 }' $file`
#		echo "$owner	$file"
#		echo $file >> $TDIR/$owner
#	done | sed -e 's,SCCS/p.,,'
#	if test -n "`ls $TDIR`"; then
#		for file in $TDIR/*; do
#			sed -e 's,SCCS/p.,,' $file | \
#			    Mail -s 'checked out files' `basename $file`
#		done
#	fi
#	rm -rf $TDIR
#fi

if checkyesno clean_uucp && [ -f /usr/libexec/uucp/clean.weekly ]; then
	echo ""
	echo "Cleaning up UUCP:"
	su daemon -c /usr/libexec/uucp/clean.weekly
fi
echo ""

echo ""
if checkyesno rebuild_locatedb && [ -f /var/db/locate.database ]; then
	echo "Rebuilding locate database:"
	chmod 644 /var/db/locate.database
	chown nobody.nobody /var/db/locate.database
	nice -5 su -m nobody -c /usr/libexec/locate.updatedb 2>/dev/null
	chown root.wheel /var/db/locate.database
else
	echo "Not rebuilding locate database; no /var/db/locate.database"
fi
