#	$NetBSD: Makefile,v 1.1.2.1 2012/08/17 20:50:50 martin Exp $

LIVEIMGBASE=	NetBSD-${DISTRIBVER}-amd64-live-wd0root	# gives ${IMGBASE}.img

BOOTDISK=	wd0			# for QEMU etc.

.include "${.CURDIR}/../Makefile.liveimage"
