#	$NetBSD: Makefile,v 1.1 2010/03/31 14:18:33 pooka Exp $
#

.PATH:  ${.CURDIR}/../../../../miscfs/kernfs

LIB=	rumpfs_kernfs

SRCS=	kernfs_subr.c kernfs_vfsops.c kernfs_vnops.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
