#	$NetBSD: Makefile,v 1.1.6.2 2010/08/11 22:55:03 yamt Exp $
#

.PATH:  ${.CURDIR}/../../../../miscfs/kernfs

LIB=	rumpfs_kernfs

SRCS=	kernfs_subr.c kernfs_vfsops.c kernfs_vnops.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
