#	$NetBSD: Makefile,v 1.1.108.1 2010/03/11 15:02:51 yamt Exp $

INCSDIR= /usr/include/powerpc/oea

INCS=	bat.h \
	hid.h hid_601.h \
	pmap.h pte.h \
	spr.h sr_601.h \
	vmparam.h

.include <bsd.kinc.mk>
