.\"	$NetBSD: td_thr_info.3,v 1.2 2016/11/24 12:18:02 wiz Exp $
.\"
.\" Copyright (c) 2016 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd November 21, 2016
.Dt TD_THR_INFO 3
.Os
.Sh NAME
.Nm td_thr_info
.Nd get information on a thread
.Sh LIBRARY
.Lb libpthread_dbg
.Sh SYNOPSIS
.In pthread_dbg.h
.Ft int
.Fn td_thr_info "td_thread_t *thread" "td_thread_info_t *info"
.Sh DESCRIPTION
The
.Fn td_thr_info
function retrieves information on a thread specified in the
.Fa thread
argument and saves the result in
.Fa info .
.Pp
The following members are defined in the
.Dv td_thread_info_t
structure:
.Bl -column "thread_state" "caddr_t" "Pointer to underlaying Dv pthread_t object"
.It Sy Name      Ta Sy Type     Ta Sy Description
.It thread_addr  Ta Dv caddr_t  Ta Points to underlaying Dv pthread_t object
.It thread_state Ta Dv int      Ta Defines Dv TD_STATE of the thread
.\" TODO: Add ATF tests, verify and document:
.\" thread_type
.\" thread_id
.\" thread_stack
.\" thread_hasjoiners
.\" thread_tls
.\" thread_errno
.\" thread_sigmask
.\" thread_sigpending
.El
.Ss Thread State types
The following state types are possible in
.Dv thread_state :
.Pp
.Bl -column ".Sy TD_STATE_RUNNING" "Thread is alive" -compact
.It Dv TD_STATE_UNKNOWN Ta "Unknown state"
.It Dv TD_STATE_RUNNING Ta "Thread is alive"
.It Dv TD_STATE_ZOMBIE  Ta "Thread is in the zombie state"
.It Dv TD_STATE_DEAD    Ta "Thread is dead"
.El
.Pp
It is not possible to retrieve information whether a thread
is suspended or resumed using this interface,
as this data is stored only inside the kernel and not in the
.Dv pthread_t
object.
The
.Dv TD_STATE_RUNNING
name is kept for backwards compatibility with old Scheduler Activation threads.
The
.Dv TD_STATE_RUNNING
state might only be returned for a mismatch between the versions of
.Xr pthread 3
and
.Xr pthread_dbg 3 .
.Sh RETURN VALUES
If successful, the
.Nm
function will return
.Dv TD_ERR_OK .
Otherwise an error number will be returned to indicate failure as described in
.Xr pthread_dbg 3 .
.Sh SEE ALSO
.Xr pthread 3 ,
.Xr pthread_dbg 3
.Sh HISTORY
The
.Nm
function first appeared in
.Nx 2.0 .
.Sh AUTHORS
.An -nosplit
.An Nathan J. Williams Aq Mt nathanw@NetBSD.org
.Pp
This manual page was written by
.An Kamil Rytarowski Aq Mt kamil@NetBSD.org .
