/* msg system definitions. */

#ifndef MSG_DEFS_H
#define MSG_DEFS_H
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <stdarg.h>
#include <curses.h>

typedef const char *msg;

/* Prototypes */
int  msg_window(WINDOW *window);
const char *msg_string (msg msg_no);
void msg_clear(void);
void msg_standout(void);
void msg_standend(void);
void msg_display(msg msg_no,...);
void msg_display_add(msg msg_no,...);
void msg_prompt (msg msg_no, const char *def, char *val, int max_chars, ...);
void msg_prompt_add (msg msg_no, const char *def, char *val, int max_chars, ...);
void msg_prompt_noecho (msg msg_no, const char *def, char *val, int max_chars, ...);
void msg_table_add(msg msg_no,...);

/* Message names */
#define MSG_NONE	NULL
#define MSG_usage	((msg)(long)0)
#define MSG_newline	((msg)(long)1)
#define MSG_yes	((msg)(long)2)
#define MSG_no	((msg)(long)3)
#define MSG_install	((msg)(long)4)
#define MSG_reinstall	((msg)(long)5)
#define MSG_upgrade	((msg)(long)6)
#define MSG_hello	((msg)(long)7)
#define MSG_thanks	((msg)(long)8)
#define MSG_installusure	((msg)(long)9)
#define MSG_upgradeusure	((msg)(long)10)
#define MSG_reinstallusure	((msg)(long)11)
#define MSG_nodisk	((msg)(long)12)
#define MSG_onedisk	((msg)(long)13)
#define MSG_askdisk	((msg)(long)14)
#define MSG_badname	((msg)(long)15)
#define MSG_disktoosmall	((msg)(long)16)
#define MSG_pleasemountroot	((msg)(long)17)
#define MSG_cylinders	((msg)(long)18)
#define MSG_heads	((msg)(long)19)
#define MSG_sectors	((msg)(long)20)
#define MSG_size	((msg)(long)21)
#define MSG_start	((msg)(long)22)
#define MSG_offset	((msg)(long)23)
#define MSG_bsize	((msg)(long)24)
#define MSG_fsize	((msg)(long)25)
#define MSG_mountpoint	((msg)(long)26)
#define MSG_cylname	((msg)(long)27)
#define MSG_secname	((msg)(long)28)
#define MSG_megname	((msg)(long)29)
#define MSG_layout	((msg)(long)30)
#define MSG_sizechoice	((msg)(long)31)
#define MSG_defaultunit	((msg)(long)32)
#define MSG_startoutsidedisk	((msg)(long)33)
#define MSG_endoutsidedisk	((msg)(long)34)
#define MSG_fspart	((msg)(long)35)
#define MSG_fspart_header	((msg)(long)36)
#define MSG_fspart_row_start	((msg)(long)37)
#define MSG_fspart_row_end_bsd	((msg)(long)38)
#define MSG_fspart_row_end_msdos	((msg)(long)39)
#define MSG_fspart_row_end_other	((msg)(long)40)
#define MSG_edfspart	((msg)(long)41)
#define MSG_not42bsd	((msg)(long)42)
#define MSG_packname	((msg)(long)43)
#define MSG_lastchance	((msg)(long)44)
#define MSG_disksetupdone	((msg)(long)45)
#define MSG_disksetupdoneupdate	((msg)(long)46)
#define MSG_openfail	((msg)(long)47)
#define MSG_statfail	((msg)(long)48)
#define MSG_unlink_fail	((msg)(long)49)
#define MSG_rename_fail	((msg)(long)50)
#define MSG_deleting_files	((msg)(long)51)
#define MSG_deleting_dirs	((msg)(long)52)
#define MSG_renamed_dir	((msg)(long)53)
#define MSG_cleanup_warn	((msg)(long)54)
#define MSG_nomount	((msg)(long)55)
#define MSG_mountfail	((msg)(long)56)
#define MSG_dotar	((msg)(long)57)
#define MSG_dotarfail	((msg)(long)58)
#define MSG_extractcomplete	((msg)(long)59)
#define MSG_instcomplete	((msg)(long)60)
#define MSG_upgrcomplete	((msg)(long)61)
#define MSG_unpackcomplete	((msg)(long)62)
#define MSG_distmedium	((msg)(long)63)
#define MSG_distset	((msg)(long)64)
#define MSG_ftpsource	((msg)(long)65)
#define MSG_host	((msg)(long)66)
#define MSG_dir	((msg)(long)67)
#define MSG_user	((msg)(long)68)
#define MSG_passwd	((msg)(long)69)
#define MSG_proxy	((msg)(long)70)
#define MSG_email	((msg)(long)71)
#define MSG_dev	((msg)(long)72)
#define MSG_nfssource	((msg)(long)73)
#define MSG_nfsbadmount	((msg)(long)74)
#define MSG_cdromsource	((msg)(long)75)
#define MSG_localfssource	((msg)(long)76)
#define MSG_localdir	((msg)(long)77)
#define MSG_filesys	((msg)(long)78)
#define MSG_cdrombadmount	((msg)(long)79)
#define MSG_localfsbadmount	((msg)(long)80)
#define MSG_badlocalsetdir	((msg)(long)81)
#define MSG_badsetdir	((msg)(long)82)
#define MSG_nonet	((msg)(long)83)
#define MSG_asknetdev	((msg)(long)84)
#define MSG_badnet	((msg)(long)85)
#define MSG_netinfo	((msg)(long)86)
#define MSG_net_domain	((msg)(long)87)
#define MSG_net_host	((msg)(long)88)
#define MSG_net_ip	((msg)(long)89)
#define MSG_net_mask	((msg)(long)90)
#define MSG_net_namesrv6	((msg)(long)91)
#define MSG_net_namesrv	((msg)(long)92)
#define MSG_net_defroute	((msg)(long)93)
#define MSG_net_media	((msg)(long)94)
#define MSG_netok	((msg)(long)95)
#define MSG_netokv6	((msg)(long)96)
#define MSG_netagain	((msg)(long)97)
#define MSG_resolv	((msg)(long)98)
#define MSG_realdir	((msg)(long)99)
#define MSG_ftperror_cont	((msg)(long)100)
#define MSG_ftperror	((msg)(long)101)
#define MSG_distdir	((msg)(long)102)
#define MSG_verboseextract	((msg)(long)103)
#define MSG_badls	((msg)(long)104)
#define MSG_notarfile	((msg)(long)105)
#define MSG_endtarok	((msg)(long)106)
#define MSG_endtar	((msg)(long)107)
#define MSG_abort	((msg)(long)108)
#define MSG_abortinst	((msg)(long)109)
#define MSG_abortupgr	((msg)(long)110)
#define MSG_abortunpack	((msg)(long)111)
#define MSG_anonprog	((msg)(long)112)
#define MSG_anonprogfailed	((msg)(long)113)
#define MSG_progdie	((msg)(long)114)
#define MSG_createfstab	((msg)(long)115)
#define MSG_noetcfstab	((msg)(long)116)
#define MSG_badetcfstab	((msg)(long)117)
#define MSG_etc_oldexists	((msg)(long)118)
#define MSG_X_oldexists	((msg)(long)119)
#define MSG_netnotup	((msg)(long)120)
#define MSG_makedev	((msg)(long)121)
#define MSG_badfs	((msg)(long)122)
#define MSG_badmount	((msg)(long)123)
#define MSG_upgrinode	((msg)(long)124)
#define MSG_rootmissing	((msg)(long)125)
#define MSG_badroot	((msg)(long)126)
#define MSG_fddev	((msg)(long)127)
#define MSG_fdmount	((msg)(long)128)
#define MSG_fdnotfound	((msg)(long)129)
#define MSG_fdremount	((msg)(long)130)
#define MSG_mntnetconfig	((msg)(long)131)
#define MSG_cur_distsets	((msg)(long)132)
#define MSG_cur_distsets_header	((msg)(long)133)
#define MSG_cur_distsets_row	((msg)(long)134)
#define MSG_tarerror	((msg)(long)135)
#define MSG_partitions_overlap	((msg)(long)136)
#define MSG_edit_partitions_again	((msg)(long)137)
#define MSG_not_regular_file	((msg)(long)138)
#define MSG_out_of_memory	((msg)(long)139)
#define MSG_config_open_error	((msg)(long)140)
#define MSG_config_read_error	((msg)(long)141)
#define MSG_nobiosgeom	((msg)(long)142)
#define MSG_biosguess	((msg)(long)143)
#define MSG_cmdfail	((msg)(long)144)
#define MSG_aoutfail	((msg)(long)145)
#define MSG_noactivepart	((msg)(long)146)
#define MSG_upgradeparttype	((msg)(long)147)
#define MSG_continue	((msg)(long)148)
#define MSG_choose_timezone	((msg)(long)149)
#define MSG_swapactive	((msg)(long)150)
#define MSG_swapdelfailed	((msg)(long)151)
#define MSG_rootpw	((msg)(long)152)
#define MSG_label_size_special	((msg)(long)153)
#define MSG_label_offset_special	((msg)(long)154)
#define MSG_postuseexisting	((msg)(long)155)
#define MSG_cur_fs	((msg)(long)156)
#define MSG_cur_fs_header	((msg)(long)157)
#define MSG_cur_fs_row	((msg)(long)158)
#define MSG_no_root_fs	((msg)(long)159)
#define MSG_md_hello	((msg)(long)160)
#define MSG_fullpart	((msg)(long)161)
#define MSG_badreadbb	((msg)(long)162)
#define MSG_badreadriscix	((msg)(long)163)
#define MSG_notnetbsdriscix	((msg)(long)164)
#define MSG_notnetbsd	((msg)(long)165)
#define MSG_dobootblks	((msg)(long)166)
#define MSG_askfsroot	((msg)(long)167)
#define MSG_askfsswap	((msg)(long)168)
#define MSG_askfsusr	((msg)(long)169)
#define MSG_otherparts	((msg)(long)170)
#define MSG_askfspart	((msg)(long)171)
#define MSG_arm32fspart	((msg)(long)172)

#endif
