#	$NetBSD: Makefile,v 1.6 2004/11/11 01:40:32 christos Exp $

SUBDIR=	fdesc fifofs genfs kernfs nullfs overlay portal
SUBDIR+= procfs ptyfs specfs syncfs umapfs

INCSDIR= /usr/include/miscfs

.include <bsd.kinc.mk>
