#	$NetBSD: Makefile,v 1.2 2002/05/20 16:21:32 wiz Exp $

MAN=	apecs.4 asc.4 autoconf.4 cia.4 dwlpx.4 gbus.4 \
	intro.4 irongate.4 jensenio.4 kft.4 lca.4 mcbus.4 \
	mcpcia.4 sableio.4 tcasic.4 tlsb.4 tsc.4 tsp.4 \
	ttwoga.4 ttwopci.4

MANSUBDIR=/alpha

MLINKS=		tlsb.4 tlsbmem.4
MLINKS+=	mcbus.4 mcmem.4

.include <bsd.man.mk>
