#	$NetBSD: Makefile,v 1.1.8.2 2014/08/20 00:04:54 tls Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}hppa-mkboot
HOST_SRCDIR=	sys/arch/hppa/stand/mkboot

HOST_CPPFLAGS+= -I${.CURDIR}

.include "${.CURDIR}/../Makefile.host"
