#	$NetBSD: Makefile,v 1.1 2014/02/24 07:23:44 skrll Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}hppa-mkboot
HOST_SRCDIR=	sys/arch/hppa/stand/mkboot

HOST_CPPFLAGS+= -I${.CURDIR}

.include "${.CURDIR}/../Makefile.host"
