# This file is automatically generated.  DO NOT EDIT!
# Generated from: 	NetBSD: mknative,v 1.6 2002/02/27 17:02:04 tv Exp 
#
G_ALLOCA=
G_EXTRA_OFILES=
G_LIBOBJS=insque.o mkstemps.o strncmp.o
G_REQUIRED_OFILES=argv.o choose-temp.o concat.o cplus-dem.o cp-demangle.o      dyn-string.o fdmatch.o fnmatch.o getopt.o getopt1.o getpwd.o           getruntime.o hashtab.o hex.o floatformat.o md5.o objalloc.o obstack.o  partition.o pexecute.o safe-ctype.o sort.o spaces.o splay-tree.o       strerror.o strsignal.o xatexit.o xexit.o xmalloc.o xmemdup.o           xstrdup.o xstrerror.o
