#!/bin/sh -
#
#	$NetBSD: MAKEDEV,v 1.2 2001/09/10 21:23:56 augustss Exp $
#
# Copyright (c) 1990 The Regents of the University of California.
# All rights reserved.
#
# Updated by Mark Brinicombe
# Created by Scott Stevens
#
# Redistribution and use in source and binary forms are permitted provided
# that: (1) source distributions retain this entire copyright notice and
# comment, and (2) distributions including binaries display the following
# acknowledgement:  ``This product includes software developed by the
# University of California, Berkeley and its contributors'' in the
# documentation or other materials provided with the distribution and in
# all advertising materials mentioning features or use of this software.
# Neither the name of the University nor the names of its contributors may
# be used to endorse or promote products derived from this software without
# specific prior written permission.
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
#	@(#)MAKEDEV	5.2 (Berkeley) 6/22/90
#
###########################################################################
#
#   PLEASE RUN "cd ../share/man/man8 ; perl5 MAKEDEV2manpage.pl"
#   AFTER CHANGING THIS FILE, AND COMMIT THE UPDATED MANPAGE!
#
###########################################################################
#       
# Device "make" file.  Valid arguments:
#	all	makes all known devices, including local devices.
#		Tries to make the 'standard' number of each type.
#	floppy	devices to be put on install floppies
#	std	standard devices
#	local	configuration specific devices which are created by running
#		the MAKEDEV.local shell script with the argument "all".
#	isdn	make ISDN devices
#
# Tapes:
#	st*	SCSI tapes
#
# Disks:
#	wd*	"winchester" disk drives (ST506,IDE,ESDI,RLL,...)
#	fd*	"floppy" disk drives (3 1/2", 5 1/4")
#	sd*	SCSI disks
#	cd*	SCSI CD-ROM
#	vnd*	"file" pseudo-disks
#	md*	memory pseudo-disk devices
#	ccd*	contatenated disk devices
#	raid*	RAIDframe disk driver
#
# Console ports:
#	ttyv0	pccons console
#	ttyE*	wscons
#
# Pointing devices:
#	quadmouse*	"quadrature mouse"
#	pms*		"PS/2 mouse"
#	wsmouse* wscons mouse events
# 
# Keyboard devices:
#	wskbd*	wscons keyboard events
# 
# Terminal ports:
#	tty*	serial ports
#	fcom	DC21285 COM port
#
# Pseudo terminals:
#	pty*	set of 16 master and slave pseudo terminals
#
# Printers:
#	lpt*	stock lp
#	lpa*	interruptless lp
#
# USB devices:
#	usb*	Bus control devices used by usbd for attach/detach
#	uhid*	Generic HID devices
#	ulpt*	Printer devices
#	ugen*	Generic device
#	urio*	Diamond Rio 500
#	uscanner*	Scanners
#	ttyU*	Modem
#
# ISDN devices:
#	i4b	comunication between userland isdnd and kernel
#	i4bctl	control device
#	i4brbch* raw b-channel access
#	i4btel*	telephonie device
#	i4btrc*	trace device
#
# Special purpose devices:
#	md	memory disk
#	kbd	raw keyboard
#	kbdctl	keyboard control
#	fd	file descriptors
#	bpf*	packet filter
#	beep	riscpc speaker
#	ipl	IP filter control
#	openfirm OpenFirmware accessor
#	random	Random number generator
#	lkm	loadable kernel modules interface
#	tun*	network tunnel driver
#	ch*	SCSI Auto changer
#	uk*	SCSI Unknown device
#	scsibus* SCSI busses, see scsi(4), scsictl(8)
#	ss*	SCSI scanner device
#	iic*	IIC bus device
#	rtc*	RTC device
#	cfs*	Coda file system device
#	wsmux*	wscons event multiplexor
#

dialin=0
dialout=524288		# high bit of the minor number
callunit=262144

PATH=/sbin:/usr/sbin:/bin:/usr/bin
umask 77
for i
do
case $i in

all)
	sh $0 std fd fd0 fd1 wd0 wd1 wd2 wd3 md0 md1 sd0 sd1 sd2 sd3
	sh $0 tty0 tty1 pty0 pty1 pty2 pty3 st0 st1 ch0 cd0 cd1 vnd0 vnd1
	sh $0 ccd0 ccd1 uk0 uk1 ss0
	sh $0 raid0 raid1 raid2 raid3
	sh $0 ttyv0
	sh $0 bpf0 bpf1 bpf2 bpf3 bpf4 bpf5 bpf6 bpf7
	sh $0 lpa0 lpt0 tun0 tun1 tun2 ipl
	sh $0 beep lkm qms0 pms0 local
	sh $0 usbs wscons isdn
	sh $0 mouse-qms0 random openfirm
	sh $0 music rmidi0 rmidi1 rmidi2 rmidi3 rmidi4 rmidi5 rmidi6 rmidi7
	sh $0 scsibus0 scsibus1 scsibus2 scsibus3
	;;

ramdisk|floppy)
	sh $0 std fd0 fd1 wd0 wd1 wd2 wd3 md0 md1 sd0 sd1 sd2 sd3
	sh $0 tty0 tty1 pty0 ttyv0
	sh $0 st0 st1 cd0 cd1
	;;

usbs)
	sh $0 usb usb0 usb1 
	sh $0 uhid0 uhid1 uhid2 uhid3
	sh $0 ulpt0 ulpt1 
	sh $0 ttyU0 ttyU1
	sh $0 urio0
	sh $0 uscanner0 uscanner1
	;;

isdn)
	sh $0 i4b i4bctl i4brbch0 i4brbch1 i4btel0 i4btel1 i4btrc0 i4btrc1
	;;

std)
	rm -f console drum mem kmem null zero tty klog stdin stdout stderr kbd
	rm -f kbdctl vidcvideo0 vidcconsole0 vidc iic rtc0
	mknod mem		c 0 0	; chmod 640 mem	; chgrp kmem mem
	mknod kmem		c 0 1	; chmod 640 kmem ; chgrp kmem kmem
	mknod null		c 0 2	; chmod 666 null
	mknod zero		c 0 3	; chmod 666 zero
	mknod drum		c 1 0	; chmod 640 drum ; chgrp kmem drum
	mknod console		c 2 0
	mknod tty		c 3 0	; chmod 666 tty
	mknod klog		c 5 0	; chmod 600 klog
	mknod kbd		c 11 0	; chmod 666 kbd
	mknod kbdctl		c 11 1	; chmod 666 kbdctl
	mknod stdin		c 34 0	; chmod 666 stdin
	mknod stdout		c 34 1	; chmod 666 stdout
	mknod stderr		c 34 2	; chmod 666 stderr
	mknod vidcconsole0	c 37 0	; chmod 640 vidcconsole0
	ln -s vidcconsole0 vidc
	ln -s vidcconsole0 vidcvideo0	; # backwards compatible for X (XXX)
	mknod iic		c 42 0	; chmod 600 iic
	mknod rtc0		c 43 0	; chmod 644 rtc0
	;;

ttyv*)
	chr=4; unit=${i#ttyv}
	rm -f ttyv$unit
	mknod ttyv$unit c $chr $unit
	chown root.wheel ttyv$unit
	;;

wscons)
	sh $0 ttyE0 ttyE1 ttyE2 ttyE3 ttyE4 ttyE5 ttyE6 ttyE7
	sh $0 wsmouse0 wsmouse1 wsmouse2 wsmouse3
	sh $0 wskbd0 wskbd1 wskbd2 wskbd3
	sh $0 ttyEcfg
	sh $0 wsmux
	;;

wsmux|wsmouse|wskbd)
	rm -f wsmouse wskbd
	mknod wsmouse c 73 0
	mknod wskbd c 73 1
	chown root.wheel wsmouse wskbd
	chmod 600 wsmouse wskbd
	;;

wsmux*)
	unit=${i#wsmux}
	wsmux=wsmux$unit
	major=73
	rm -f $wsmux
	mknod $wsmux c $major $unit
	chown root.wheel $wsmux
	chmod 600 $wsmux
	;;

ttyEcfg)
	chr=60
	rm -f ttyEcfg
	mknod ttyEcfg c $chr 255
	chown root.wheel ttyEcfg
	chmod 600 ttyEcfg
	;;

ttyE*)
	chr=60; unit=${i#ttyE}
	rm -f ttyE$unit
	mknod ttyE$unit c $chr $unit
	chown root.wheel ttyE$unit
	;;

wsmouse*)
	unit=${i#wsmouse}
	wsmouse=wsmouse$unit
	major=62
	rm -f $wsmouse
	mknod $wsmouse c $major $unit
	chown root.wheel $wsmouse
	chmod 600 $wsmouse
	;;

wskbd*)
	unit=${i#wskbd}
	wskbd=wskbd$unit
	major=61
	rm -f $wskbd
	mknod $wskbd c $major $unit
	chown root.wheel $wskbd
	chmod 600 $wskbd
	;;

fd)
	rm -f fd/*
	mkdir fd > /dev/null 2>&1
	n=0
	while [ $n -lt 64 ]; do
		mknod fd/$n c 34 $n
		n=$(($n + 1))
	done
	chown -R root.wheel fd
	chmod 755 fd
	chmod 666 fd/*
	;;

md*)
	unit=${i#md}; blk=18; chr=18;
	rm -f md${unit}? rmd${unit}?
	mknod md${unit}a  b $blk $(($unit * 8 + 0))
	mknod md${unit}c  b $blk $(($unit * 8 + 2))
#	mknod rmd${unit}a c $chr $(($unit * 8 + 0))
#	mknod rmd${unit}c c $chr $(($unit * 8 + 2))
	chgrp operator md${unit}? #rmd${unit}?
	chmod 640 md${unit}? #rmd${unit}?
	;;

ccd*|fd*|raid*|sd*|vnd*|wd*)
	case $i in
	ccd*) name=ccd;	unit=${i#ccd};	blk=21;	chr=21;;
	fd*) name=fd;	unit=${i#fd};	blk=17;	chr=17;;
	raid*) name=raid;	unit=${i#raid};	blk=71;	chr=71;;
	sd*) name=sd;	unit=${i#sd};	blk=24;	chr=24;;
	vnd*) name=vnd;	unit=${i#vnd};	blk=19;	chr=19;;
	wd*) name=wd;	unit=${i#wd};	blk=16;	chr=16;;
	esac
	rm -f $name$unit? r$name$unit?
	mknod ${name}${unit}a	b $blk $(($unit * 8 + 0))
	mknod ${name}${unit}b	b $blk $(($unit * 8 + 1))
	mknod ${name}${unit}c	b $blk $(($unit * 8 + 2))
	mknod ${name}${unit}d	b $blk $(($unit * 8 + 3))
	mknod ${name}${unit}e	b $blk $(($unit * 8 + 4))
	mknod ${name}${unit}f	b $blk $(($unit * 8 + 5))
	mknod ${name}${unit}g	b $blk $(($unit * 8 + 6))
	mknod ${name}${unit}h	b $blk $(($unit * 8 + 7))
	mknod r${name}${unit}a	c $chr $(($unit * 8 + 0))
	mknod r${name}${unit}b	c $chr $(($unit * 8 + 1))
	mknod r${name}${unit}c	c $chr $(($unit * 8 + 2))
	mknod r${name}${unit}d	c $chr $(($unit * 8 + 3))
	mknod r${name}${unit}e	c $chr $(($unit * 8 + 4))
	mknod r${name}${unit}f	c $chr $(($unit * 8 + 5))
	mknod r${name}${unit}g	c $chr $(($unit * 8 + 6))
	mknod r${name}${unit}h	c $chr $(($unit * 8 + 7))
	chgrp operator $name$unit? r$name$unit?
	chmod 640 $name$unit? r$name$unit?
	;;

ttyU*)
	unit=${i#ttyU}
	ttyU=ttyU$unit
	dtyU=dtyU$unit
	ctyU=ctyU$unit
	major=74
	rm -f $ttyU $dtyU $ctyU
	mknod $ttyU c $major $(($unit + $dialin  ))
	mknod $dtyU c $major $(($unit + $dialout ))
	mknod $ctyU c $major $(($unit + $callunit))
	chown uucp.wheel $ttyU $dtyU $ctyU
	chmod 600 $ttyU $dtyU $ctyU
	;;

urio*)
	unit=${i#urio}
	urio=urio$unit
	major=75
	rm -f $urio
	mknod $urio c $major $unit
	chown root.wheel $urio
	chmod 600 $urio
	;;

uscanner*)
	unit=${i#uscanner}
	uscanner=uscanner$unit
	major=76
	rm -f $uscanner
	mknod $uscanner c $major $unit
	chown root.wheel $uscanner
	chmod 600 $uscanner
	;;

tty*)
	unit=${i#???}
	rm -f tty0$unit dty0$unit
	mknod tty0$unit c 12 $(($unit + $dialin ))
	mknod dty0$unit c 12 $(($unit + $dialout))
	chown uucp.wheel tty0$unit dty0$unit
	;;

fcom*)
	unit=${i#fcom}
	fcom=fcom$unit
	rm -f $fcom
	mknod $fcom c 54 $unit
	chown uucp.wheel $fcom
	chmod 600 $fcom
	;;

pty*)
	class=${i#pty}
	case $class in
	0)      name=p;;
	1)      name=q;;
	2)      name=r;;
	3)      name=s;;
	4)      name=t;;
	5)      name=u;;
	6)      name=v
		echo "$0: $i: pty unit conflicts with console ttyv* devices."
		continue;;
	7)      name=w;;
	8)      name=x;;
	9)      name=y;;
	10)     name=z;;
	11)     name=P;;
	12)     name=Q;;
	13)     name=R;;
	14)     name=S;;
	15)     name=T;;
	*)      echo "$0: $i: pty unit must be between 0 and 15"
	        continue ;;
	esac
	rm -f tty$name[0-9a-f] pty$name[0-9a-f]
	for j in 0 1 2 3 4 5 6 7 8 9 a b c d e f
	do
		case $j in
		[0-9])  jn=$j ;;
		a)      jn=10 ;;
		b)      jn=11 ;;
		c)      jn=12 ;;
		d)      jn=13 ;;
		e)      jn=14 ;;
		f)      jn=15 ;;
		esac
		unit=$(($class * 16 + $jn))
		mknod tty$name$j c 7 $unit
		mknod pty$name$j c 6 $unit
	done
        chgrp wheel tty$name? pty$name?
        chmod 666 tty$name? pty$name?
	;;

st*)
	case $i in
	st*) name=st;	unit=${i#st};	chr=25;	blk=25;;
	esac
	rm -f $name$unit n$name$unit e$name$unit en$name$unit \
		r$name$unit nr$name$unit er$name$unit enr$name$unit 
	mknod $name$unit	b $blk $(($unit * 16 + 0))
	mknod n$name$unit	b $blk $(($unit * 16 + 1))
	mknod e$name$unit	b $blk $(($unit * 16 + 2))
	mknod en$name$unit	b $blk $(($unit * 16 + 3))
	mknod r$name$unit	c $chr $(($unit * 16 + 0))
	mknod nr$name$unit	c $chr $(($unit * 16 + 1))
	mknod er$name$unit	c $chr $(($unit * 16 + 2))
	mknod enr$name$unit	c $chr $(($unit * 16 + 3))
	chgrp operator $name$unit n$name$unit e$name$unit en$name$unit \
		r$name$unit nr$name$unit er$name$unit enr$name$unit 
	chmod 660 $name$unit n$name$unit e$name$unit en$name$unit \
		r$name$unit nr$name$unit er$name$unit enr$name$unit 
	;;

ch*|uk*)
	case $i in
	ch*) name=ch;	unit=${i#ch};	chr=27;;
	uk*) name=uk;	unit=${i#uk};	chr=28;;
	esac
	rm -f $name$unit
	mknod $name$unit	c $chr $unit
	chgrp operator $name$unit
	chmod 640 $name$unit
	;;

ss*)
	case $i in
	ss*) name=ss;	unit=${i#ss};	chr=29;;
	esac
	rm -f $name$unit n$name$unit en$name$unit
	mknod $name$unit	c $chr $(($unit * 16 + 0))
	mknod n$name$unit	c $chr $(($unit * 16 + 1))
	mknod en$name$unit	c $chr $(($unit * 16 + 3))
	chgrp operator $name$unit n$name$unit en$name$unit
	chmod 640 $name$unit n$name$unit en$name$unit
	;;

cd*)
	case $i in
	cd*) name=cd;	unit=${i#cd};	chr=26;	blk=26;;
	esac
	rm -f $name$unit? r$name$unit?
	mknod ${name}${unit}a	b $blk $(($unit * 8 + 0))
	mknod ${name}${unit}c	b $blk $(($unit * 8 + 2))
	mknod r${name}${unit}a	c $chr $(($unit * 8 + 0))
	mknod r${name}${unit}c	c $chr $(($unit * 8 + 2))
	chgrp operator $name$unit? r$name$unit?
	chmod 640 $name$unit? r$name$unit?
	;;

lpt*|lpa*)
	case $i in
	lpt*) name=lpt;	unit=${i#lpt};	chr=8;	flags=0;;
	lpa*) name=lpa;	unit=${i#lpa};	chr=8;	flags=128;;
	esac
	rm -f $name$unit
	mknod $name$unit	c $chr $(($unit + $flags))
	chown root.wheel $name$unit
	;;


bpf*|tun*|pms*|qms*|joy*)
	case $i in
	bpf*) name=bpf;	unit=${i#bpf};	chr=32;;
	tun*) name=tun;	unit=${i#tun};	chr=33;;
	pms*) name=pms;	unit=${i#pms};	chr=40;;
	qms*) name=qms;	unit=${i#qms};	chr=9;;
	joy*) name=joy;	unit=${i#joy};	chr=56;;
	esac
	rm -f $name$unit
	mknod $name$unit	c $chr $unit
	chown root.wheel $name$unit
	;;

ipl)
	rm -f ipl ipnat ipstate ipauth
	mknod ipl c 46 0
	mknod ipnat c 46 1
	mknod ipstate c 46 2
	mknod ipauth c 46 3
	chown root.wheel ipl ipnat ipstate ipauth
	chmod 600 ipl ipnat ipstate ipauth
	;;

beep)
	rm -f beep
	mknod beep c 10 0
	chown root.wheel beep
	;;

lkm)
	rm -f lkm
	mknod lkm c 35 0
	chown root.kmem lkm
	chmod 640 lkm
	;;

mouse-*)
	case $i in
	mouse-pms*) name=pms;	unit=${i#mouse-pms};;
	mouse-qms*) name=qms;	unit=${i#mouse-qms};;
	esac
	rm -f mouse
	ln -s $name$unit mouse
	;;

audio*)
	unit=${i#audio}
	audio=audio$unit
	sound=sound$unit
	mixer=mixer$unit
	major=36
	audioctl=audioctl$unit
	if [ "$unit" = "" ]; then unit=0; fi
	rm -f $audio $sound $mixer $audioctl
	mknod $sound    c $major $(($unit + 0))
	mknod $audio    c $major $(($unit + 128))
	mknod $mixer    c $major $(($unit + 16))
	mknod $audioctl c $major $(($unit + 192))
	chown root.wheel $audio $sound $mixer $audioctl
	chmod 666 $audio $sound $mixer $audioctl
	;;

rmidi*)
	unit=${i#rmidi}
	major=57
	rmidi=rmidi$unit
	rm -f $rmidi
	mknod $rmidi c $major $unit
	chown root.wheel $rmidi
	chmod 666 $rmidi
	;;

music*)
	unit=${i#music}
	music=music$unit
	sequencer=sequencer$unit
	major=58
	if [ "$unit" = "" ]; then unit=0; fi
	rm -f $sequencer $music
	mknod $music     c $major $(($unit + 0))
	mknod $sequencer c $major $(($unit + 128))
	chown root.wheel $music $sequencer
	chmod 666 $music $sequencer
	;;

usb*)
	unit=${i#usb}
	if [ "$unit" = "" ]; then
	    unit=255
	    usb=usb
	else
	    usb=usb$unit
	fi
	major=64
	rm -f $usb
	mknod $usb c $major $unit
	chown root.wheel $usb
	chmod 600 $usb
	;;

uhid*)
	unit=${i#uhid}
	uhid=uhid$unit
	major=65
	rm -f $uhid
	mknod $uhid c $major $unit
	chown root.wheel $uhid
	chmod 666 $uhid
	;;

ulpt*)
	unit=${i#ulpt}
	ulpt=ulpt$unit
	major=66
	rm -f $ulpt
	mknod $ulpt c $major $unit
	chown root.wheel $ulpt
	chmod 600 $ulpt
	;;

ugen*)
	unit=${i#ugen}
	ugen=ugen$unit
	major=72
	for j in 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15
	do
		ugenj=$ugen.$j
		rm -f $ugenj
		mknod $ugenj c $major $(($unit * 16 + $j))
		chown root.wheel $ugenj
		chmod 600 $ugenj
	done
	;;


openfirm)
	rm -f openfirm
	mknod openfirm c 77 0
	chown root.wheel openfirm
	chmod 444 openfirm
	;;

random)
	rm -f random urandom
	mknod random c 52 0
	mknod urandom c 52 1
	chown root.wheel random urandom
	chmod 444 random
	chmod 644 urandom
	;;

cfs*)
	unit=${i#cfs}
	cfs=cfs$unit
	major=59
	rm -f $cfs
	mknod $cfs c $major $unit
	chown root.wheel $cfs
	chmod 600 $cfs
	;;

scsibus*)
	unit=${i#scsibus}; 
	rm -f scsibus$unit
	mknod scsibus$unit c 70 $unit
	chown root:wheel scsibus$unit
	chmod 644 scsibus$unit
	;;

i4b)
	rm -f i4b
	mknod i4b c 78 0
	chmod 600 i4b
	;;

i4bctl)
	rm -f i4bctl
	mknod i4bctl c 79 0
	chmod 600 i4bctl
	;;

i4brbch*)
	unit=${i#i4brbch};
	rm -f i4brbch$unit
	mknod i4brbch$unit c 80 $unit
	chmod 600 i4brbch$unit
	;;

i4btel*)
	unit=${i#i4btel};
	rm -f i4btel$unit
	mknod i4btel$unit c 82 $unit
	chmod 600 i4btel$unit
	;;

i4btrc*)
	unit=${i#i4btrc};
	rm -f i4btrc$unit
	mknod i4btrc$unit c 81 $unit
	chmod 600 i4btrc$unit
	;;

local)
	umask 0
	sh $0.local all
	umask 77
	;;

*)
	echo $i: unknown device
	;;

esac
done
