#	from: @(#)Makefile	6.2 (Berkeley) 2/2/91
#	$NetBSD: Makefile,v 1.2 1996/03/05 00:06:04 jtc Exp $

PROG=		cc1

SRCS=	c-parse.c c-lang.c 

CLEANFILES+=	c-parse.c

.PATH:	${.CURDIR}/../common

.include <../Makefile.cc1>
