.\" $NetBSD: btdevctl.8,v 1.9 2012/12/26 17:57:49 plunky Exp $
.\"
.\" Copyright (c) 2006 Itronix Inc.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of Itronix Inc. may not be used to endorse
.\"    or promote products derived from this software without specific
.\"    prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY ITRONIX INC. ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL ITRONIX INC. BE LIABLE FOR ANY
.\" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.\" Copyright (c) 2004 Maksim Yevmenkin <m_evmenkin@yahoo.com>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd December 26, 2012
.Dt BTDEVCTL 8
.Os
.Sh NAME
.Nm btdevctl
.Nd Bluetooth remote device control utility
.Sh SYNOPSIS
.Nm
.Op Fl A | Fl D
.Op Fl qv
.Op Fl m Ar mode
.Fl a Ar address
.Fl d Ar device
.Fl s Ar service
.Sh DESCRIPTION
The
.Nm
utility is used to configure bluetooth devices in the system.
Normally,
.Nm
will perform an SDP query to the remote device as needed, and
cache the results in the
.Pa /var/db/btdevctl.plist
file for later use.
If neither Attach nor Detach is specified,
.Nm
will display the configuration.
.Pp
The options are:
.Bl -tag
.It Fl A
Attach device
.It Fl a Ar address
Remote device address.
The
.Ar address
may be given as BDADDR or a name.
If a name was specified,
.Nm
attempts to resolve the name via
.Xr bt_gethostbyname 3 .
.It Fl D
Detach device
.It Fl d Ar device
Local device address.
May be given as BDADDR or device name.
.It Fl m Ar mode
Connection link mode.
The following modes are supported:
.Pp
.Bl -tag -width encrypt -compact
.It none
clear previously set mode.
.It auth
require devices be paired, see
.Xr btpin 1 .
.It encrypt
auth, plus enable encryption.
.It secure
encryption, plus change of link key.
.El
.Pp
When configuring the HID service,
.Nm
will set
.Sq auth
by default, or
.Sq encrypt
for keyboard devices.
If the device cannot handle authentication, then the mode will need
to be cleared manually.
.It Fl q
Ignore any cached data and perform a SDP query for the given
.Ar service .
.It Fl s Ar service
Service to configure.
Known services are:
.Pp
.Bl -tag -width HSETXX -compact
.It Dv HID
Human Interface Device.
.It Dv HF
Handsfree.
.It Dv HSET
Headset.
.El
.It Fl v
Be verbose.
.El
.Pp
For device configurations to persist across boots, add entries to the
.Pa /etc/bluetooth/btdevctl.conf
file and
set the
.Xr rc.conf 5
variable
.Sy btdevctl
to YES.
.Sh FILES
.Bl -tag -compact
.It Pa /etc/bluetooth/btdevctl.conf
.It Pa /dev/bthub
.It Pa /var/db/btdevctl.plist
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr btpin 1 ,
.Xr bthidev 4 ,
.Xr bthub 4 ,
.Xr btsco 4 ,
.Xr rc.conf 5
.Pp
See the Bluetooth chapter of
.Qq The NetBSD Guide
for detailed examples of configuring keyboards, mice, and audio headsets.
.Sh HISTORY
Parts of the
.Nm
program originated in the
.Fx
.Nm bthidcontrol
program.
.Sh AUTHORS
.An Iain Hibbert
for Itronix, Inc.
.An Maksim Yevmenkin Aq m_evmenkin@yahoo.com
