#	$NetBSD: Makefile,v 1.2.72.1 2018/09/30 01:45:00 pgoyette Exp $
CDBASE=		acorn32cd		# gives ${CDBASE}.iso
CDRELEASE=	true			# include $RELEASEDIR/$MACHINE
CDRELEASE_NODEBUG=	true

.include "${.CURDIR}/../../../common/Makefile.bootcd"
