#	$NetBSD: Makefile,v 1.10 2001/11/28 13:16:25 kleink Exp $

KDIR=	/sys/arch/amigappc/include
INCSDIR= /usr/include/amigappc

INCS=	ansi.h aout_machdep.h asm.h \
	bswap.h bus.h \
	cdefs.h conf.h cpu.h cpufunc.h \
	db_machdep.h disklabel.h \
	elf_machdep.h endian.h \
	float.h frame.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intr.h \
	kcore.h \
	limits.h \
	math.h mtpr.h \
	param.h pcb.h pmap.h proc.h profile.h psl.h pte.h ptrace.h \
	reg.h \
	setjmp.h signal.h stdarg.h \
	trap.h types.h \
	varargs.h vmparam.h

.include <bsd.kinc.mk>
