#	$NetBSD: Makefile,v 1.1 2000/05/25 22:11:58 is Exp $

KDIR=	/sys/arch/amiga/include
INCSDIR= /usr/include/amiga

INCS=	ansi.h aout_machdep.h asm.h bswap.h bus.h cdefs.h conf.h cpu.h \
	cpufunc.h db_machdep.h disklabel.h elf_machdep.h endian.h fbio.h \
	float.h frame.h ieee.h ieeefp.h intr.h kcore.h limits.h mtpr.h \
	param.h pcb.h pmap.h proc.h profile.h psl.h pte.h ptrace.h reg.h \
	setjmp.h signal.h stdarg.h svr4_machdep.h trap.h types.h varargs.h \
	vmparam.h

.include <bsd.kinc.mk>
