# $NetBSD: Makefile,v 1.1 2007/11/16 18:06:46 jmmv Exp $

.include <bsd.own.mk>

SUBDIR=		libfake

TESTS_SH=	t_groups
TESTS_SH+=	t_id
TESTS_SH+=	t_whoami

.include <bsd.test.mk>
.include <bsd.subdir.mk>
