#	$NetBSD: Makefile,v 1.5 2001/04/11 07:42:38 jdolecek Exp $

# use 'make -f Makefile.pcmciadevs' to make pcmciadevs.h and pcmciadevs_data.h

INCSDIR= /usr/include/dev/pcmcia

# Only install includes which are used by userland
INCS=	if_wi_ieee.h if_cnwioctl.h

.include <bsd.kinc.mk>
