/*	$NetBSD: pcmciadevs_data.h,v 1.64 1999/12/23 19:46:27 augustss Exp $	*/

/*
 * THIS FILE AUTOMATICALLY GENERATED.  DO NOT EDIT.
 *
 * generated from:
 *	NetBSD: pcmciadevs,v 1.63 1999/12/23 19:45:56 augustss Exp 
 */

/*-
 * Copyright (c) 1998 The NetBSD Foundation, Inc.
 * All rights reserved.
 *
 * This code is derived from software contributed to The NetBSD Foundation
 * by Christos Zoulas.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *        This product includes software developed by the NetBSD
 *        Foundation, Inc. and its contributors.
 * 4. Neither the name of The NetBSD Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

struct pcmcia_knowndev pcmcia_knowndevs[] = {
	{
	    PCMCIA_VENDOR_ADAPTEC, PCMCIA_PRODUCT_ADAPTEC_APA1460,
	    PCMCIA_CIS_ADAPTEC_APA1460,
	    0,
	    "Adaptec Corporation",
	    "Adaptec APA-1460 SlimSCSI"	},
	},
	{
	    PCMCIA_VENDOR_ADAPTEC, PCMCIA_PRODUCT_ADAPTEC_APA1460A,
	    PCMCIA_CIS_ADAPTEC_APA1460A,
	    0,
	    "Adaptec Corporation",
	    "Adaptec APA-1460A SlimSCSI"	},
	},
	{
	    PCMCIA_VENDOR_3COM, PCMCIA_PRODUCT_3COM_3C562,
	    PCMCIA_CIS_3COM_3C562,
	    0,
	    "3Com Corporation",
	    "3Com 3c562 33.6 Modem/10Mbps Ethernet"	},
	},
	{
	    PCMCIA_VENDOR_3COM, PCMCIA_PRODUCT_3COM_3C589,
	    PCMCIA_CIS_3COM_3C589,
	    0,
	    "3Com Corporation",
	    "3Com 3c589 10Mbps Ethernet"	},
	},
	{
	    PCMCIA_VENDOR_3COM, PCMCIA_PRODUCT_3COM_3C574,
	    PCMCIA_CIS_3COM_3C574,
	    0,
	    "3Com Corporation",
	    "3Com 3c574-TX 10/100Mbps Ethernet"	},
	},
	{
	    PCMCIA_VENDOR_3COM, PCMCIA_PRODUCT_3COM_3CXM056BNW,
	    PCMCIA_CIS_3COM_3CXM056BNW,
	    0,
	    "3Com Corporation",
	    "3Com/NoteWorthy 3CXM056-BNW 56K Modem"	},
	},
	{
	    PCMCIA_VENDOR_3COM, PCMCIA_PRODUCT_3COM_3CXEM556,
	    PCMCIA_CIS_3COM_3CXEM556,
	    0,
	    "3Com Corporation",
	    "3Com/Megahertz 3CXEM556 Ethernet/Modem"	},
	},
	{
	    PCMCIA_VENDOR_3COM, PCMCIA_PRODUCT_3COM_3CXEM556INT,
	    PCMCIA_CIS_3COM_3CXEM556INT,
	    0,
	    "3Com Corporation",
	    "3Com/Megahertz 3CXEM556-INT Ethernet/Modem"	},
	},
	{
	    PCMCIA_VENDOR_3COM, PCMCIA_PRODUCT_3COM_3CCFEM556BI,
	    PCMCIA_CIS_3COM_3CCFEM556BI,
	    0,
	    "3Com Corporation",
	    "3Com/Megahertz 3CCFEM556BI Ethernet/Modem"	},
	},
	{
	    PCMCIA_VENDOR_COMPEX, PCMCIA_PRODUCT_COMPEX_LINKPORT_ENET_B,
	    PCMCIA_CIS_COMPEX_LINKPORT_ENET_B,
	    0,
	    "Compex Corporation",
	    "Compex Linkport ENET-B Ethernet"	},
	},
	{
	    PCMCIA_VENDOR_LASAT, PCMCIA_PRODUCT_LASAT_CREDIT_288,
	    PCMCIA_CIS_LASAT_CREDIT_288,
	    0,
	    "Lasat Communications A/S",
	    "Lasat Credit 288 Modem"	},
	},
	{
	    PCMCIA_VENDOR_DAYNA, PCMCIA_PRODUCT_DAYNA_COMMUNICARD_E_1,
	    PCMCIA_CIS_DAYNA_COMMUNICARD_E_1,
	    0,
	    "Dayna Corporation",
	    "Dayna CommuniCard E"	},
	},
	{
	    PCMCIA_VENDOR_DAYNA, PCMCIA_PRODUCT_DAYNA_COMMUNICARD_E_2,
	    PCMCIA_CIS_DAYNA_COMMUNICARD_E_2,
	    0,
	    "Dayna Corporation",
	    "Dayna CommuniCard E"	},
	},
	{
	    PCMCIA_VENDOR_DIGITAL, PCMCIA_PRODUCT_DIGITAL_MOBILE_MEDIA_CDROM,
	    PCMCIA_CIS_DIGITAL_MOBILE_MEDIA_CDROM,
	    0,
	    "Digital Equipment Corporation",
	    "Digital Mobile Media CD-ROM"	},
	},
	{
	    PCMCIA_VENDOR_FUJITSU, PCMCIA_PRODUCT_FUJITSU_SCSI600,
	    PCMCIA_CIS_FUJITSU_SCSI600,
	    0,
	    "Fujitsu Corporation",
	    "Fujitsu SCSI 600 Interface"	},
	},
	{
	    PCMCIA_VENDOR_MOTOROLA, PCMCIA_PRODUCT_MOTOROLA_POWER144,
	    PCMCIA_CIS_MOTOROLA_POWER144,
	    0,
	    "Motorola Corporation",
	    "Motorola Power 14.4 Modem"	},
	},
	{
	    PCMCIA_VENDOR_MOTOROLA, PCMCIA_PRODUCT_MOTOROLA_PM100C,
	    PCMCIA_CIS_MOTOROLA_PM100C,
	    0,
	    "Motorola Corporation",
	    "Motorola Personal Messenger 100C CDPD Modem"	},
	},
	{
	    PCMCIA_VENDOR_FUJITSU, PCMCIA_PRODUCT_FUJITSU_LA501,
	    PCMCIA_CIS_FUJITSU_LA501,
	    0,
	    "Fujitsu Corporation",
	    "Fujitsu Towa LA501 Ethernet"	},
	},
	{
	    PCMCIA_VENDOR_FUJITSU, PCMCIA_PRODUCT_FUJITSU_LA10S,
	    PCMCIA_CIS_FUJITSU_LA10S,
	    0,
	    "Fujitsu Corporation",
	    "Fujitsu Compact Flash Ethernet"	},
	},
	{
	    PCMCIA_VENDOR_IBM, PCMCIA_PRODUCT_IBM_3270,
	    PCMCIA_CIS_IBM_3270,
	    0,
	    "IBM Corporation",
	    "3270 Emulation"	},
	},
	{
	    PCMCIA_VENDOR_IBM, PCMCIA_PRODUCT_IBM_INFOMOVER,
	    PCMCIA_CIS_IBM_INFOMOVER,
	    0,
	    "IBM Corporation",
	    "National Semiconductor InfoMover"	},
	},
	{
	    PCMCIA_VENDOR_IBM, PCMCIA_PRODUCT_IBM_5250,
	    PCMCIA_CIS_IBM_5250,
	    0,
	    "IBM Corporation",
	    "5250 Emulation"	},
	},
	{
	    PCMCIA_VENDOR_IBM, PCMCIA_PRODUCT_IBM_TROPIC,
	    PCMCIA_CIS_IBM_TROPIC,
	    0,
	    "IBM Corporation",
	    "Token Ring 4/16"	},
	},
	{
	    PCMCIA_VENDOR_IBM, PCMCIA_PRODUCT_IBM_HOME_AND_AWAY,
	    PCMCIA_CIS_IBM_HOME_AND_AWAY,
	    0,
	    "IBM Corporation",
	    "IBM Home and Away Modem"	},
	},
	{
	    PCMCIA_VENDOR_IBM, PCMCIA_PRODUCT_IBM_WIRELESS_LAN_ENTRY,
	    PCMCIA_CIS_IBM_WIRELESS_LAN_ENTRY,
	    0,
	    "IBM Corporation",
	    "Wireless LAN Entry"	},
	},
	{
	    PCMCIA_VENDOR_IBM, PCMCIA_PRODUCT_IBM_PORTABLE_CDROM,
	    PCMCIA_CIS_IBM_PORTABLE_CDROM,
	    0,
	    "IBM Corporation",
	    "PCMCIA Portable CD-ROM Drive"	},
	},
	{
	    PCMCIA_VENDOR_IBM, PCMCIA_PRODUCT_IBM_ETHERJET,
	    PCMCIA_CIS_IBM_ETHERJET,
	    0,
	    "IBM Corporation",
	    "IBM EtherJet Ethernet"	},
	},
	{
	    PCMCIA_VENDOR_IODATA, PCMCIA_PRODUCT_IODATA_PCLATE,
	    PCMCIA_CIS_IODATA_PCLATE,
	    0,
	    "I-O DATA",
	    "I-O DATA PCLA/TE"	},
	},
	{
	    PCMCIA_VENDOR_LINKSYS, PCMCIA_PRODUCT_LINKSYS_ECARD_1,
	    PCMCIA_CIS_LINKSYS_ECARD_1,
	    0,
	    "Linksys Corporation",
	    "Linksys EthernetCard or D-Link DE-650"	},
	},
	{
	    PCMCIA_VENDOR_LINKSYS, PCMCIA_PRODUCT_LINKSYS_COMBO_ECARD,
	    PCMCIA_CIS_LINKSYS_COMBO_ECARD,
	    0,
	    "Linksys Corporation",
	    "Linksys Combo EthernetCard"	},
	},
	{
	    PCMCIA_VENDOR_LINKSYS, PCMCIA_PRODUCT_LINKSYS_TRUST_COMBO_ECARD,
	    PCMCIA_CIS_LINKSYS_TRUST_COMBO_ECARD,
	    0,
	    "Linksys Corporation",
	    "Trust (Linksys) Combo EthernetCard"	},
	},
	{
	    PCMCIA_VENDOR_MEGAHERTZ, PCMCIA_PRODUCT_MEGAHERTZ_XJ4288,
	    PCMCIA_CIS_MEGAHERTZ_XJ4288,
	    0,
	    "Megahertz Corporation",
	    "Megahertz XJ4288 Modem"	},
	},
	{
	    PCMCIA_VENDOR_MEGAHERTZ, PCMCIA_PRODUCT_MEGAHERTZ_XJ4336,
	    PCMCIA_CIS_MEGAHERTZ_XJ4336,
	    0,
	    "Megahertz Corporation",
	    "Megahertz XJ4336 Modem"	},
	},
	{
	    PCMCIA_VENDOR_MEGAHERTZ, PCMCIA_PRODUCT_MEGAHERTZ_XJ5560,
	    PCMCIA_CIS_MEGAHERTZ_XJ5560,
	    0,
	    "Megahertz Corporation",
	    "Megahertz X-JACK 56kbps Modem"	},
	},
	{
	    PCMCIA_VENDOR_MEGAHERTZ2, PCMCIA_PRODUCT_MEGAHERTZ2_XJACK,
	    PCMCIA_CIS_MEGAHERTZ2_XJACK,
	    0,
	    "Megahertz Corporation",
	    "Megahertz X-JACK Ethernet"	},
	},
	{
	    PCMCIA_VENDOR_MEGAHERTZ, PCMCIA_PRODUCT_MEGAHERTZ_XJEM3336,
	    PCMCIA_CIS_MEGAHERTZ_XJEM3336,
	    0,
	    "Megahertz Corporation",
	    "Megahertz X-JACK Ethernet Modem"	},
	},
	{
	    PCMCIA_VENDOR_USROBOTICS, PCMCIA_PRODUCT_USROBOTICS_WORLDPORT144,
	    PCMCIA_CIS_USROBOTICS_WORLDPORT144,
	    0,
	    "US Robotics Corporation",
	    "US Robotics WorldPort 14.4 Modem"	},
	},
	{
	    PCMCIA_VENDOR_SANDISK, PCMCIA_PRODUCT_SANDISK_SDCFB,
	    PCMCIA_CIS_SANDISK_SDCFB,
	    0,
	    "Sandisk Corporation",
	    "Sandisk CompactFlash Card"	},
	},
	{
	    PCMCIA_VENDOR_SIMPLETECH, PCMCIA_PRODUCT_SIMPLETECH_COMMUNICATOR288,
	    PCMCIA_CIS_SIMPLETECH_COMMUNICATOR288,
	    0,
	    "Simple Technology",
	    "Simple Technology 28.8 Communicator"	},
	},
	{
	    PCMCIA_VENDOR_SIMPLETECH, PCMCIA_PRODUCT_SIMPLETECH_SPECTRUM24,
	    PCMCIA_CIS_SIMPLETECH_SPECTRUM24,
	    0,
	    "Simple Technology",
	    "Symbol Spectrum24 WLAN Adapter"	},
	},
	{
	    PCMCIA_VENDOR_SOCKET, PCMCIA_PRODUCT_SOCKET_PAGECARD,
	    PCMCIA_CIS_SOCKET_PAGECARD,
	    0,
	    "Socket Communications",
	    "Socket Communications PageCard"	},
	},
	{
	    PCMCIA_VENDOR_SOCKET, PCMCIA_PRODUCT_SOCKET_DUAL_RS232,
	    PCMCIA_CIS_SOCKET_DUAL_RS232,
	    0,
	    "Socket Communications",
	    "Socket Communications Dual RS232"	},
	},
	{
	    PCMCIA_VENDOR_SOCEKT, PCMCIA_PRODUCT_SOCEKT_LP_ETHER_CF,
	    PCMCIA_CIS_SOCEKT_LP_ETHER_CF,
	    0,
	    "",
	    "Socket Communications Low Power Ethernet CF"	},
	},
	{
	    PCMCIA_VENDOR_TDK, PCMCIA_PRODUCT_TDK_LAK_CD021BX,
	    PCMCIA_CIS_TDK_LAK_CD021BX,
	    0,
	    "TDK Corporation",
	    "TDK LAK-CD021BX Ethernet"	},
	},
	{
	    PCMCIA_VENDOR_TDK, PCMCIA_PRODUCT_TDK_DFL9610,
	    PCMCIA_CIS_TDK_DFL9610,
	    0,
	    "TDK Corporation",
	    "TDK DFL9610 Ethernet & Digital Cellular"	},
	},
	{
	    PCMCIA_VENDOR_TDK, PCMCIA_PRODUCT_TDK_LAK_CF010,
	    PCMCIA_CIS_TDK_LAK_CF010,
	    0,
	    "TDK Corporation",
	    "TDK LAC-CF010"	},
	},
	{
	    PCMCIA_VENDOR_TDK, PCMCIA_PRODUCT_TDK_XIR_CE_10,
	    PCMCIA_CIS_TDK_XIR_CE_10,
	    0,
	    "TDK Corporation",
	    "Xircom CreditCard Ethernet"	},
	},
	{
	    PCMCIA_VENDOR_TDK, PCMCIA_PRODUCT_TDK_XIR_CEM_10,
	    PCMCIA_CIS_TDK_XIR_CEM_10,
	    0,
	    "TDK Corporation",
	    "Xircom CreditCard Ethernet + Modem"	},
	},
	{
	    PCMCIA_VENDOR_TDK, PCMCIA_PRODUCT_TDK_XIR_PS_CE2_10,
	    PCMCIA_CIS_TDK_XIR_PS_CE2_10,
	    0,
	    "TDK Corporation",
	    "Xircom CreditCard CE2 Ethernet"	},
	},
	{
	    PCMCIA_VENDOR_TDK, PCMCIA_PRODUCT_TDK_XIR_CE3_10_100,
	    PCMCIA_CIS_TDK_XIR_CE3_10_100,
	    0,
	    "TDK Corporation",
	    "Xircom CreditCard CE3 10/100 Ethernet"	},
	},
	{
	    PCMCIA_VENDOR_TDK, PCMCIA_PRODUCT_TDK_XIR_CNW_801,
	    PCMCIA_CIS_TDK_XIR_CNW_801,
	    0,
	    "TDK Corporation",
	    "Xircom CreditCard Netwave (Canada)"	},
	},
	{
	    PCMCIA_VENDOR_TDK, PCMCIA_PRODUCT_TDK_XIR_CNW_802,
	    PCMCIA_CIS_TDK_XIR_CNW_802,
	    0,
	    "TDK Corporation",
	    "Xircom CreditCard Netwave (US)"	},
	},
	{
	    PCMCIA_VENDOR_NEWMEDIA, PCMCIA_PRODUCT_NEWMEDIA_BASICS,
	    PCMCIA_CIS_NEWMEDIA_BASICS,
	    0,
	    "New Media Corporation",
	    "New Media BASICS Ethernet"	},
	},
	{
	    PCMCIA_VENDOR_NEWMEDIA, PCMCIA_PRODUCT_NEWMEDIA_BUSTOASTER,
	    PCMCIA_CIS_NEWMEDIA_BUSTOASTER,
	    0,
	    "New Media Corporation",
	    "New Media BusToaster SCSI Host Adapter"	},
	},
	{
	    PCMCIA_VENDOR_SMC, PCMCIA_PRODUCT_SMC_8016,
	    PCMCIA_CIS_SMC_8016,
	    0,
	    "Standard Microsystems Corporation",
	    "SMC 8016 EtherCard"	},
	},
	{
	    PCMCIA_VENDOR_SMC, PCMCIA_PRODUCT_SMC_EZCARD,
	    PCMCIA_CIS_SMC_EZCARD,
	    0,
	    "Standard Microsystems Corporation",
	    "SMC EXCard 10 PCMCIA"	},
	},
	{
	    PCMCIA_VENDOR_CONTEC, PCMCIA_PRODUCT_CONTEC_CNETPC,
	    PCMCIA_CIS_CONTEC_CNETPC,
	    0,
	    "Contec",
	    "Contec C-NET(PC)C"	},
	},
	{
	    PCMCIA_VENDOR_ALLIEDTELESIS, PCMCIA_PRODUCT_ALLIEDTELESIS_LA_PCM,
	    PCMCIA_CIS_ALLIEDTELESIS_LA_PCM,
	    0,
	    "Allied Telesis K.K.",
	    "Allied Telesis LA-PCM"	},
	},
	{
	    PCMCIA_VENDOR_LUCENT, PCMCIA_PRODUCT_LUCENT_WAVELAN_IEEE,
	    PCMCIA_CIS_LUCENT_WAVELAN_IEEE,
	    0,
	    "Lucent Technologies",
	    "WaveLAN/IEEE"	},
	},
	{
	    PCMCIA_VENDOR_BAY, PCMCIA_PRODUCT_BAY_STACK_650,
	    PCMCIA_CIS_BAY_STACK_650,
	    0,
	    "Bay Networks",
	    "BayStack 650 Wireless LAN"	},
	},
	{
	    PCMCIA_VENDOR_WEBGEAR, PCMCIA_PRODUCT_WEBGEAR_WLAN,
	    PCMCIA_CIS_WEBGEAR_WLAN,
	    0,
	    "WebGear",
	    "WLAN Adapter"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_MEGAHERTZ_XJ2288,
	    PCMCIA_CIS_MEGAHERTZ_XJ2288,
	    0,
	    "Megahertz Corporation",
	    "Megahertz XJ2288 Modem"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_PREMAX_PE200,
	    PCMCIA_CIS_PREMAX_PE200,
	    0,
	    "Premax",
	    "PreMax PE-200"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_PLANET_SMARTCOM2000,
	    PCMCIA_CIS_PLANET_SMARTCOM2000,
	    0,
	    "Planet",
	    "Planet SmartCOM 2000"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_PLANEX_FNW3600T,
	    PCMCIA_CIS_PLANEX_FNW3600T,
	    0,
	    "Planex Communications Inc",
	    "Planex FNW-3600-T"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_DLINK_DE650,
	    PCMCIA_CIS_DLINK_DE650,
	    0,
	    "D-Link",
	    "D-Link DE-650"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_DLINK_DE660,
	    PCMCIA_CIS_DLINK_DE660,
	    0,
	    "D-Link",
	    "D-Link DE-660"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_RPTI_EP401,
	    PCMCIA_CIS_RPTI_EP401,
	    0,
	    "RPTI",
	    "RPTI EP401"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_ACCTON_EN2212,
	    PCMCIA_CIS_ACCTON_EN2212,
	    0,
	    "ACCTON",
	    "Accton EN2212"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_YEDATA_EXTERNAL_FDD,
	    PCMCIA_CIS_YEDATA_EXTERNAL_FDD,
	    0,
	    "Y-E DATA",
	    "Y-E DATA External FDD"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_DIGITAL_DEPCMXX,
	    PCMCIA_CIS_DIGITAL_DEPCMXX,
	    0,
	    "Digital Equipment Corporation",
	    "DEC DEPCM-BA"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_TEAC_IDECARDII,
	    PCMCIA_CIS_TEAC_IDECARDII,
	    0,
	    "TEAC",
	    "TEAC IDE Card/II"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_LINKSYS_ECARD_2,
	    PCMCIA_CIS_LINKSYS_ECARD_2,
	    0,
	    "Linksys Corporation",
	    "Linksys E-Card"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_COREGA_ETHER_PCC_T,
	    PCMCIA_CIS_COREGA_ETHER_PCC_T,
	    0,
	    "Corega K.K.",
	    "Corega"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_COREGA_ETHER_II_PCC_T,
	    PCMCIA_CIS_COREGA_ETHER_II_PCC_T,
	    0,
	    "Corega K.K.",
	    "Corega"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_COREGA_FAST_ETHER_PCC_TX,
	    PCMCIA_CIS_COREGA_FAST_ETHER_PCC_TX,
	    0,
	    "Corega K.K.",
	    "Corega"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_SVEC_COMBOCARD,
	    PCMCIA_CIS_SVEC_COMBOCARD,
	    0,
	    "SVEC/Hawking Technology",
	    "SVEC/Hawking Tech. Combo Card"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_SVEC_LANCARD,
	    PCMCIA_CIS_SVEC_LANCARD,
	    0,
	    "SVEC/Hawking Technology",
	    "SVEC PCMCIA Lan Card"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_AMBICOM_AMB8002T,
	    PCMCIA_CIS_AMBICOM_AMB8002T,
	    0,
	    "AmbiCom Inc",
	    "AmbiCom AMB8002T"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_IODATA_PCLAT,
	    PCMCIA_CIS_IODATA_PCLAT,
	    0,
	    "I-O DATA",
	    "IO-DATA PCLA/T"	},
	},
	{
	    PCMCIA_VENDOR_UNKNOWN, PCMCIA_PRODUCT_EPSON_EEN10B,
	    PCMCIA_CIS_EPSON_EEN10B,
	    0,
	    "Seiko Epson Corporation",
	    "Epson EEN10B"	},
	},
	{
	    PCMCIA_VENDOR_FUJITSU, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Fujitsu Corporation",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_SANDISK, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Sandisk Corporation",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_NEWMEDIA, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "New Media Corporation",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_IBM, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "IBM Corporation",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_MOTOROLA, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Motorola Corporation",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_3COM, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "3Com Corporation",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_MEGAHERTZ, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Megahertz Corporation",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_SOCKET, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Socket Communications",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_TDK, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "TDK Corporation",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_SMC, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Standard Microsystems Corporation",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_USROBOTICS, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "US Robotics Corporation",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_MEGAHERTZ2, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Megahertz Corporation",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_ADAPTEC, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Adaptec Corporation",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_LINKSYS, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Linksys Corporation",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_SIMPLETECH, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Simple Technology",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_LUCENT, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Lucent Technologies",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_DAYNA, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Dayna Corporation",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_WEBGEAR, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "WebGear",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_BAY, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Bay Networks",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_IODATA, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "I-O DATA",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_LASAT, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Lasat Communications A/S",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_COMPEX, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Compex Corporation",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_CONTEC, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Contec",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_COREGA, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Corega K.K.",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_ALLIEDTELESIS, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Allied Telesis K.K.",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_HAGIWARASYSCOM, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Hagiwara SYS-COM",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_PREMAX, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Premax",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_PLANET, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Planet",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_PLANEX, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Planex Communications Inc",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_DLINK, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "D-Link",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_RPTI, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "RPTI",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_ACCTON, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "ACCTON",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_YEDATA, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Y-E DATA",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_DIGITAL, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Digital Equipment Corporation",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_TEAC, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "TEAC",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_SVEC, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "SVEC/Hawking Technology",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_AMBICOM, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "AmbiCom Inc",
	    NULL,
	},
	{
	    PCMCIA_VENDOR_EPSON, 0,
	    PCMCIA_KNOWNDEV_NOPROD,
	    PCMCIA_CIS_INVALID,
	    "Seiko Epson Corporation",
	    NULL,
	},
	{ 0, 0, { NULL, NULL, NULL, NULL }, 0, NULL, NULL, }
};
