#	$NetBSD: Makefile,v 1.14.22.1 2014/08/10 06:58:55 tls Exp $
#	from: @(#)Makefile	8.1 (Berkeley) 6/6/93

.include <bsd.own.mk>
WARNS=6

PROG=	sed
SRCS=	compile.c main.c misc.c process.c

.include <bsd.prog.mk>
