#	$NetBSD: Makefile,v 1.10 2006/12/26 04:43:10 rumble Exp $

MAN=	crime.4 dpclock.4 dsclock.4 gio.4 giopci.4 grtwo.4 haltwo.4 hpc.4 \
	imc.4 intro.4 light.4 mace.4 mec.4 newport.4 pic.4 sq.4 wdsc.4
MANSUBDIR=/sgimips

.include <bsd.man.mk>
