#	$NetBSD: Makefile,v 1.9 2002/05/07 14:08:30 isaki Exp $

SUBDIR=		ramdisk.sysinst instkernel.sysinst bootfloppy.sysinst
SUBDIR+=	bootfloppy.generic inst

.PHONY: release

TARGETS+=	release

.include <bsd.subdir.mk>
