#	$NetBSD: Makefile,v 1.23 2005/01/11 00:57:56 joff Exp $

INCSDIR= /usr/include/dev/ic

# Only install includes which are used by userland
INCS=	athioctl.h bt8xx.h hd44780var.h icpreg.h icp_ioctl.h isp_ioctl.h \
	mlxreg.h mlxio.h rrunnerreg.h rrunnervar.h wdcreg.h wi_ieee.h

.include <bsd.kinc.mk>
