#	$NetBSD: Makefile,v 1.3 2003/09/20 06:20:56 lukem Exp $

.include <bsd.own.mk>

MAN=	DBE.3 XdbeAllocateBackBufferName.3 XdbeBeginIdiom.3 \
	XdbeEndIdiom.3 XdbeDeallocateBackBufferName.3 XdbeFreeVisualInfo.3 \
	XdbeQueryExtension.3 XdbeSwapBuffers.3 \
	XdbeGetBackBufferAttributes.3 XdbeGetVisualInfo.3

BUILDSYMLINKS=\
	XdbeAllo.man XdbeAllocateBackBufferName.man \
	XdbeBegi.man XdbeBeginIdiom.man \
	XdbeEndI.man XdbeEndIdiom.man \
	XdbeDeal.man XdbeDeallocateBackBufferName.man \
	XdbeFree.man XdbeFreeVisualInfo.man \
	XdbeQuer.man XdbeQueryExtension.man \
	XdbeSwap.man XdbeSwapBuffers.man \
	XdbeGetB.man XdbeGetBackBufferAttributes.man \
	XdbeGetV.man XdbeGetVisualInfo.man

.PATH:  ${X11SRCDIR.xc}/doc/man/Xext/dbe

.include <bsd.x11.mk>
.include <bsd.man.mk>
