#	$NetBSD: Makefile,v 1.1.1.1 2003/09/11 18:37:05 lukem Exp $

LIB=		exts
SRCS=		appgroup.c panoramiX.c panoramiXSwap.c panoramiXprocs.c \
		security.c shm.c sleepuntil.c xf86bigfont.c xprint.c \
		xtest.c xtest1dd.c xtest1di.c

.include "../Makefile.ext"
