# $NetBSD: Makefile,v 1.10.8.1 2018/10/20 06:58:46 pgoyette Exp $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/lib/libc/string
DBG=-g

TESTS_C+=	t_bm
TESTS_C+=	t_memchr
TESTS_C+=	t_memcpy
TESTS_C+=	t_memmem
TESTS_C+=	t_memset
TESTS_C+=	t_popcount
TESTS_C+=	t_strcat
TESTS_C+=	t_strchr
TESTS_C+=	t_strcmp
TESTS_C+=	t_strcoll
TESTS_C+=	t_strcpy
TESTS_C+=	t_strcspn
TESTS_C+=	t_strerror
TESTS_C+=	t_stresep
TESTS_C+=	t_strlen
TESTS_C+=	t_strpbrk
TESTS_C+=	t_strrchr
TESTS_C+=	t_strspn
TESTS_C+=	t_swab

WARNS=		4

.include <bsd.test.mk>
