# $NetBSD: Makefile,v 1.3 2010/12/25 21:10:24 pgoyette Exp $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/lib/libc/string

TESTS_C+=	t_string

# EXPENSIVE, REALY, REALY EXPENSIVE test!  Disable for now.
#TESTS_C+=	t_popcount

.include <bsd.test.mk>
