#	$NetBSD: Makefile,v 1.1 2000/12/11 13:48:11 jdolecek Exp $

# directory 'example' is explicitly not included - the module should not be
# built nor installed by default

SUBDIR+=	# empty

.include <bsd.kinc.mk>
