#	$NetBSD: Makefile,v 1.8 1997/03/24 22:15:42 christos Exp $
#	@(#)Makefile	8.1 (Berkeley) 5/31/93

PROG=	fish
MAN=	fish.6
HIDEGAME=hidegame
FILES=fish.instr
FILESDIR=/usr/share/games

.include <bsd.prog.mk>
