#	$NetBSD: Makefile,v 1.2 2018/09/28 15:05:23 martin Exp $
CDBASE=		zauruscd		# gives ${CDBASE}.iso
CDRELEASE=	true			# include $RELEASEDIR/$MACHINE
CDRELEASE_NODEBUG=	true

.include "${.CURDIR}/../../../common/Makefile.bootcd"
