#	$NetBSD: Makefile,v 1.1.46.2 2020/04/13 07:45:37 martin Exp $
CDBASE=		zauruscd		# gives ${CDBASE}.iso
CDRELEASE=	true			# include $RELEASEDIR/$RELEASEMACHINEDIR
CDRELEASE_NODEBUG=	true

.include "${.CURDIR}/../../../common/Makefile.bootcd"
