#	$NetBSD: Makefile,v 1.2 2001/04/29 10:30:41 martin Exp $

PROG	=	ispppcontrol
MAN      =	ispppcontrol.8

LINKS=  ${BINDIR}/ispppcontrol ${BINDIR}/pppoectl
MLINKS= ispppcontrol.8 /pppoectl.8

.include <bsd.prog.mk>
