#	$NetBSD: Makefile,v 1.13 2004/05/23 03:16:40 lukem Exp $

SUBDIR= libbind9 libdns libisc libisccc libisccfg liblwres .WAIT \
	dig host named nslookup nsupdate rndc rndc-confgen

.include "Makefile.inc"

.include <bsd.subdir.mk>
