.\"	$NetBSD: xntpd.8,v 1.1.1.1 1997/04/18 13:29:14 christos Exp $
.\" Converted from HTML to mandoc by Jason R. Thorpe <thorpej@NetBSD.ORG>
.Dd April 17, 1997
.Dt XNTPD 8
.Os NetBSD
.Sh NAME
.Nm xntpd
.Nd Network Time Protocol (NTP) daemon
.Sh SYNOPSIS
.Nm
.Op Fl aAbdm
.Op Fl c Ar conffile
.Op Fl f Ar driftfile
.Op Fl k Ar keyfile
.Op Fl l Ar logfile
.Op Fl p Ar pidfile
.Op Fl r Ar broadcastdelay
.Op Fl s Ar statsdir
.Op Fl t Ar key
.Op Fl v Ar variable
.Op Fl V Ar variable
.Sh DESCRIPTION
.Nm
is an operating system daemon which sets and
maintains the system time-of-day in synchronism with Internet
standard time servers.
.Nm
is a complete
implementation of the Network Time Protocol (NTP) version 3, as
defined by RFC-1305, but also retains compatibility with version 1
and 2 servers as defined by RFC-1059 and RFC-1119,
respectively.
.Nm
does all computations in 64-bit
fixed point arithmetic and requires no floating point
support. While the ultimate precision of this design, about 232
picoseconds, is not achievable with ordinary workstations and
networks of today, it may be required with future nanosecond CPU
clocks and gigabit LANs.
.Pp
The daemon can operate in any of several modes, including
symmetric active/passive, client/server and broadcast/multicast,
as described in RFC-1305. A broadcast/multicast client can
discover remote servers, compute server-client propagation delay
correction factors and configure itself automatically. This makes
it possible to deploy a fleet of workstations without specifying
configuration details specific to the local environment.
.Pp
Ordinarily,
.Nm
reads the
.Pa ntp.conf
configuration file at startup time in order to determine the
synchronization sources and operating modes. It is also possible
to specify a working, although limited, configuration entirely on
the command line, obviating the need for a configuration
file. This may be particularly appropriate when the local host is
to be configured as a broadcast or multicast client, with all
peers being determined by listening to broadcasts at run time.
.Pp
Various internal
.Nm
variables can be displayed
and configuration options altered while the daemon is running
using the
.Xr ntpq 8
and
.Xr xntpdc 8
utility programs.
.Pp
When
.Nm
starts it looks at the value of
.Pa umask ,
and if it's zero
.Nm
will set
.Pa umask
to
.Pa 022 .
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl a
Enable authentication mode. The default is enabled, so this option
is obsolete now.
.It Fl A
Disable authentication mode.
.It Fl b
Synchronize using NTP broadcast messages.
.It Fl c Ar conffile
Specify the name and path of the configuration file.
.It Fl d
Specify debugging mode. This flag may occur multiple times, with
each occurrence indicating greater detail of display.
.It Fl f Ar driftfile
Specify the name and path of the drift file.
.It Fl k Ar keyfile
Specify the name and path of the file containing the NTP
authentication keys.
.It Fl l Ar logfile
Specify the name and path of the log file. The default is the system
log facility.
.It Fl m
Synchronize using NTP multicast messages on the IP multicast group
address 224.0.1.1 (requires multicast kernel).
.It Fl p Ar pidfile
Specify the name and path to record the daemon's process ID.
.It Fl r Ar broadcastdelay
Specify the default propagation delay from the broadcast/multicast
server and this computer. This is used only if the delay cannot be
computed automatically by the protocol.
.It Fl s Ar statsdir
Specify the directory path for files created by the statistics
facility.
.It Fl t Ar key
Add a key number to the trusted key list.
.It Fl v Ar variable
Add a system variable.
.It Fl V Ar variable
Add a system variable listed by default.
.El
.Pp
.Sh THE CONFIGURATION FILE
The
.Nm
configuration file is read at initial startup
in order to specify the synchronization sources, modes and other related
information. Usually, it is installed in the
.Pa /etc
directory, but could be installed elsewhere (see the
.Fl -c Ar conffile
command line option). The file format is similar
to other Unix configuration files - comments begin with a
.Pa #
character and extend to the end of the line; blank lines are ignored.
Configuration commands consist of an initial keyword followed by a list
of arguments, some of which may be optional, separated by whitespace.
Commands may not be continued over multiple lines. Arguments may be host
names, host addresses written in numeric, dotted-quad form, integers,
floating point numbers (when specifying times in seconds) and text
strings. Optional arguments are delimited by
.Pa [ ]
in the
following descriptions, while alternatives are separated by
.Pa | .
The notation [ ... ] means an optional, indefinite
repetition of the last item before the [ ... ].
.Pp
See the following pages for configuration and control options. While
there is a rich set of options available, the only required option is
one or more
.Pa server, peer
or
.Pa broadcast
commands
described in the
.Pa Configuration Options
page. The
.Pa Notes on Configuring NTP and Setting up a NTP Subnet
page contains
an extended discussion of these options.
.\" XXX fuck
.\" <p><a href="confopt.html"> Configuration Options </a>
.\" <br><a href="authopt.html"> Authentication Options </a>
.\" <br><a href="monopt.html"> Monitoring Options </a>
.\" <br><a href="accopt.html"> Access Control Options </a>
.\" <br><a href="clockopt.html"> Reference Clock Options </a>
.\" <br><a href="miscopt.html"> Miscellaneous Options </a>
.\" XXX
.Sh FILES
.Bl -tag -width /etc/ntp.driftXXX -compact
.It Pa /etc/ntp.conf
the default name of the configuration file
.It Pa /etc/ntp.drift
the default name of the drift file
.It Pa /etc/ntp.keys
the default name of the key file
.Sh BUGS
.Nm
has gotten rather fat. While not huge, it has gotten
larger than might be desireable for an elevated-priority daemon running
on a workstation, particularly since many of the fancy features which
consume the space were designed more with a busy primary server, rather
than a high stratum workstation, in mind.
.Sh AUTHOR
David L. Mills (mills@udel.edu)
