.\"	$NetBSD: ethers.5,v 1.5 1999/03/17 20:19:45 garbled Exp $
.\"
.\"     Written by Roland McGrath <roland@frob.com>.  Public domain.
.\"
.Dd December 16, 1993
.Dt ETHERS 5
.Os
.Sh NAME
.Nm ethers
.Nd Ethernet host name data base
.Sh DESCRIPTION
The
.Nm
file maps Ethernet MAC addresses to host names.
Lines consist of an address and a host name, separated by any number
of blanks and/or tab characters.
A ``#'' character indicates the beginning of a comment;
characters up to the end of
the line are not interpreted by routines which search the file.
.Pp
Ethernet MAC addresses are expressed as six hexadecimal numbers separated
by colons, e.g. "08:00:20:00:5a:bc".
The functions described in 
.Xr ethers 3
and
.Xr ether_aton 3
can read and produce this format.
.Sh FILES
.Bl -tag -width /etc/ethers -compact
.It Pa /etc/ethers
The
.Nm
file resides in
.Pa /etc .
.El
.Sh SEE ALSO
.Xr ethers 3
.Sh BUGS
A name server should be used instead of a static file.
.Sh HISTORY
The
.Nm ethers
file format was adopted from
.Tn SunOS
and appeared in
.Nx 1.0 .
