.\"	$NetBSD: mk.conf.5,v 1.28 2005/12/21 04:25:54 hubertf Exp $
.\"
.\"  Copyright (c) 1999-2003 The NetBSD Foundation, Inc.
.\"  All rights reserved.
.\"
.\"  This code is derived from software contributed to The NetBSD Foundation
.\"  by Luke Mewburn.
.\"
.\"  Redistribution and use in source and binary forms, with or without
.\"  modification, are permitted provided that the following conditions
.\"  are met:
.\"  1. Redistributions of source code must retain the above copyright
.\"     notice, this list of conditions and the following disclaimer.
.\"  2. Redistributions in binary form must reproduce the above copyright
.\"     notice, this list of conditions and the following disclaimer in the
.\"     documentation and/or other materials provided with the distribution.
.\"  3. All advertising materials mentioning features or use of this software
.\"     must display the following acknowledgement:
.\"  	This product includes software developed by Luke Mewburn.
.\"  4. The name of the author may not be used to endorse or promote products
.\"     derived from this software without specific prior written permission.
.\"
.\"  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\"  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\"  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\"  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\"  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\"  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
.\"  OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\"  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
.\"  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
.\"  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd December 20, 2005
.Dt MK.CONF 5
.Os
.\" turn off hyphenation
.hym 999
.
.Sh NAME
.Nm mk.conf
.Nd make configuration file
.
.Sh DESCRIPTION
The
.Nm
file overrides various parameters used during the build of the system.
.Pp
Listed below are the
.Nm
variables that may be set, the values to which each may be set,
a brief description of what each variable does, and a reference to
relevant manual pages.
.
.Ss NetBSD System variables
.
.de YorN
Can be set to
.Dq yes
or
.Dq no .
..
.de DFLT
.Pp
.Em Default :
..
.de DFLTu
.DFLT
Unset.
..
.de DFLTy
.DFLT
.Dq yes
..
.de DFLTn
.DFLT
.Dq no
..
The basic rule for the variable naming scheme is as follows:
.Bl -tag -width USE_XXX
.
.It Sy MKxxx
Can be set to
.Dq no
to disable functionality, or
.Dq yes 
to enable it.
Usually defaults to 
.Dq yes ,
although some variables
default to
.Dq no .
.Pp
Due to
.Xr make 1
implementation issues, if a temporary command-line override of a
.Pa mk.conf or
\*[Lt]bsd.own.mk\*[Gt]
setting is required whilst still honouring a particular
Makefile's setting of
MKxxx ,
use
.Dl Ic env MKxxx=value make
instead of
.Dl Ic make MKxxx=value
.Pp
.It Sy NOxxx
If defined, disables a feature.
Not intended for users.
This is to allow Makefiles to disable functionality
that they don't support (such as missing man pages).
NOxxx variables must be defined before \*[Lt]bsd.own.mk\*[Gt]
is included.
.Pp
.El
The following variables that control how things are made/installed that
are not set by default. These should not be set by Makefiles; they're for
the user to define in
.It Sy MAKECONF
(see \*[Lt]bsd.own.mk\*[Gt], below) or on the
.Xr make 1
command line:
.Bl -tag -width CXXFLAGS.lib\*[Lt]lib\*[Gt]
.It Sy BSDOBJDIR
The real path to the
.Sq obj
tree for the
.Nx
source tree.
.DFLT
.Pa /usr/obj
.
.It Sy BSDSRCDIR
The real path to the
.Nx
source tree.
.DFLT
.Pa /usr/src
.
.It Sy BUILD
If defined,
.Sq "make install"
checks that the targets in the source directories are up-to-date and
re-makes them if they are out of date, instead of blindly trying to install
out of date or non-existent targets.
.DFLTu
.
.It Sy BUILDID
Identifier for the build.
The identifier will be appended to
object directory names, and can be consulted in the
.Xr make 1
configuration file in order to set additional build parameters,
such as compiler flags.
.DFLTu
.
.It Sy COPTS
Extra options for the C compiler.
Should be appended to (e.g.,
.Sy COPTS+=-g ) ,
rather than explicitly set.
.
.It Sy DESTDIR
Directory to contain the built
.Nx
system.
If set, special options are passed to the compilation tools to
prevent their default use of the host system's
.Sy /usr/include , /usr/lib ,
and so forth.
This pathname should
.Em not
end with a slash
.Pq /
character (for installation into the system's root directory, set
.Sy DESTDIR
to an empty string).
The directory must reside on a file system which supports long file
names and hard links.
.DFLT
Empty string if
.Sy USETOOLS
is
.Dq yes ;
unset otherwise.
.Pp
.Em Note :
.Sy build.sh
will provide a default of
.Pa destdir. Ns Sy MACHINE
(in the top-level
.Sy .OBJDIR )
unless run in
.Sq expert
mode
.
.It Sy MAKEVERBOSE
Control how "verbose" the standard make(1) rules are.
Default: 2, supported values:
.Bl -tag -width M
.It Dv 0
Minimal output
.Pq Dq quiet
.It Dv 1
Describe what is occurring
.It Dv 2
Describe what is occurring and echo the actual command
.El
.Pp
.It Sy MKBFD
.YorN
Indicates whether
.Sy libbfd ,
.Sy libiberty ,
or any of the things that depend
upon them (such as the binutils,
.Xr as 1 ,
.Xr gdb 1 ,
.Xr ld 1 ,
.Xr dbsym 8 ,
or
.Xr mdsetimage 8 )
should be built.
.DFLTy
.
.It Sy MKCATPAGES
.YorN
Indicates whether preformatted plaintext manual pages will be created
and installed during a build.
.DFLTy
.
.It Sy MKCRYPTO
.YorN
Indicates whether cryptographic code will be included in a build;
provided for the benefit of countries that do not allow strong
cryptography.
Will not affect use of the standard low-security password encryption system,
.Xr crypt 3 .
.DFLTy
.Pp
If
.Dq no ,
acts as
.Sy MKKERBEROS=no MKKERBEROS4=no .
.
.It Sy MKCRYPTO_IDEA
.YorN
Indicates whether IDEA support will be built into
.Sy libcrypto_idea.a .
.DFLTn
.
.It Sy MKCRYPTO_MDC2
.YorN
Indicates whether MDC2 support will be built into
.Sy libcrypto_mdc2.a .
.DFLTn
.
.It Sy MKCRYPTO_RC5
.YorN
Indicates whether RC5 support will be built into
.Sy libcrypto_rc5.a .
.DFLTn
.
.It Sy MKCVS
.YorN
Indicates whether
.Xr cvs 1
is built.
.DFLTy
.
.It Sy MKDOC
.YorN
Indicates whether system documentation destined for
.Sy DESTDIR Ns Pa /usr/share/doc
will be installed during a build.
.DFLTy
.
.It Sy MKDYNAMICROOT
.YorN
Indicates whether all programs should be dynamically linked,
and to install shared libraries required by
.Pa /bin
and
.Pa /sbin
and the shared linker
.Xr ld.elf_so 1
into
.Pa /lib .
If
.Sq no ,
link programs in
.Pa /bin
and
.Pa /sbin
statically.
.DFLTy
.
.It Sy MKGCC
.YorN
Indicates whether
.Xr gcc 1
or any related libraries
.Pq Sy libg2c , libgcc , libobjc , libstdc+
are built.
.DFLTy
.
.It Sy MKGCCCMDS
.YorN
Indicates whether
.Xr gcc 1
is built. 
.DFLTy
.It Sy MKGDB
.YorN
Indicates whether
.Xr gdb 1
is built.
.DFLTy
.
.It Sy MKHESIOD
.YorN
Indicates whether the Hesiod infrastructure
(libraries and support programs) is built.
.DFLTy
.
.It Sy MKHOSTOBJ
.YorN
If set to
.Dq yes ,
then for programs intended to be run on the compile host,
the name, release, and architecture of the host operating system
will be suffixed to the name of the object directory created by
.Dq make obj .
(This allows multiple host systems to compile
.Nx
for a single target.)
If set to
.Dq no ,
then programs built to be run on the compile host will use the same
object directory names as programs built to be run on the target.
.DFLTn
.
.It Sy MKHTML
.YorN
Indicates whether the html manual pages are built and installed.
.DFLTy
.
.It Sy MKIEEEFP
.YorN
Indicates whether code for IEEE754/IEC60559 conformance is built.
Has no effect on most platforms.
.DFLTy
.
.It Sy MKINET6
.YorN
Indicates if the IPv6 infrastructure
(libraries and support programs) is built.
.DFLTy
.
.It Sy MKINFO
.YorN
Indicates whether GNU Info files, used for the documentation for
most of the compilation tools, will be created and installed during a
build.
.DFLTy
.
.It Sy MKIPFILTER
.YorN
Indicates whether the
.Xr ipf 4
programs, headers and LKM will be compiled and installed during a build.
.DFLTy
.
.It Sy MKKERBEROS4
.YorN
Indicates whether the Kerberos v4 infrastructure
(libraries and support programs) is built.
.DFLTy
.
.It Sy MKKERBEROS
.YorN
Indicates whether the Kerberos v5 infrastructure
(libraries and support programs) is built.
.DFLTy
.
.It Sy MKLINKLIB
.YorN
Indicates whether all of the library infrastructure is built.
If
.Sq no ,
prevents:
.Bl -dash
.It
installation of the
.Sy *.a
libraries,
.It
installation of the
.Sy *_pic.a
.It
libraries on PIC systems,
building of
.Sy *.a
libraries on PIC systems,
.It
installation of
.Sy .so
symlinks on ELF systems
.El
i.e., only install the shared library (and the .so.major symlink on ELF).
If 
.Sq no 
acts as
.Sy MKPICINSTALL=no MKPROFILE=no .
.DFLTy
.Pp
.
.It Sy MKLINT
.YorN
Indicates whether
.Xr lint 1
will be run against portions of the
.Nx
source code during the build, and whether lint libraries will be
installed into
.Sy DESTDIR Ns Pa /usr/libdata/lint .
.DFLTy
.
.It Sy MKMAN
.YorN
Indicates whether manual pages will be installed during a build.
.DFLTy
.Pp
If
.Dq no ,
acts as
.Sy MKCATPAGES=no MKHTML=no .
.
.It Sy MKMANZ
.YorN
Indicates whether manual pages should be compressed with
.Xr gzip 1
at installation time.
.DFLTn
.
.It Sy MKNLS
.YorN
Indicates whether Native Language System (NLS) locale zone files will be
compiled and installed during a build.
.DFLTy
.
.It Sy MKOBJ
.YorN
Indicates whether object directories will be created when running
.Dq make obj .
If set to
.Dq no ,
then all built files will be located inside the regular source tree.
.DFLTy
.Pp
If
.Dq no ,
acts as
.Sy MKOBJDIRS=no .
.
.It Sy MKOBJDIRS
.YorN
Indicates whether object directories will be created automatically
(via a
.Dq make obj
pass) at the start of a build.
.DFLTn
.
.It Sy MKPAM
.YorN
Indicates whether the
.Xr pam 8
framework (libraries and support files) is built.
.DFLTy
.
.It Sy MKPF
.YorN
Indicates whether the
.Xr pf 4
programs, headers and LKM will be compiled and installed during a build.
.DFLTy
.
.It Sy MKPIC
.YorN
Indicates whether shared objects and libraries will be created and
installed during a build.
If set to
.Dq no ,
the entire built system will be statically linked.
.DFLTy
(for most platforms)
.Pp
If
.Dq no ,
acts as
.Sy MKPICLIB=no .
.
.It Sy MKPICINSTALL
.YorN
Indicates whether the
.Xr ar 1
format libraries
.Sy ( lib*_pic.a ) ,
used to generate shared libraries, are installed during a build.
.DFLTy
.
.It Sy MKPICLIB
.YorN
If
.Sq no ,
don't build
.Sy *_pic.a
libraries, and build the shared object libraries from the
.Sy *.a
libraries instead.
A symlink is installed in
.Pa ${DESTDIR}/usr/lib
for the
.Sy _pic.a
library pointing to the
.Sy .a
library.
.DFLTy
.
.It Sy MKPOSTFIX
.YorN
Indicates whether 
.Xr postfix 1
is built.
.DFLTy
.
.It Sy MKPROFILE
.YorN
Indicates whether profiled libraries
.Sy ( lib*_p.a )
will be built and installed during a build.
.DFLT
.Dq yes ;
however, some platforms turn off
.Sy MKPROFILE
by default at times due to toolchain problems with profiled code.
.
.It Sy MKSENDMAIL
.YorN
Indicates whether
.Xr sendmail 8
is built.
.DFLTy
.
.It Sy MKSHARE
.YorN
Indicates whether 
pages, documentation, Info documentation, man pages, NLS files, ...
destined to reside in
.Sy DESTDIR Ns Pa /usr/share
will be built and installed during a build.
.DFLTy
.Pp
If
.Dq no ,
acts as
.Sy MKCATPAGES=no MKDOC=no MKHTML=no MKINFO=no MKMAN=no MKNLS=no .
.
.It Sy MKSKEY
.YorN
Indicates whether the S/key infrastructure
(libraries and support programs) is built.
.DFLTy
.
.It Sy MKSOFTFLOAT
.YorN
Indicates whether the compiler generates output containing
library calls for floating point and possibly soft-float library
support.
.DFLTn
.
.It Sy MKSTATICLIB
.YorN
Indicates if the normal static libraries
.Sy ( *.a )
will be built and installed.
.DFLTy
.
.It Sy MKUNPRIVED
.YorN
Indicates whether an unprivileged install will occur.
The user, group, permissions, and file flags, will not be set on
the installed item; instead the information will be appended to
a file called
.Pa METALOG
in
.Sy DESTDIR .
The contents of
.Pa METALOG
is used during the generation of the distribution tar files to ensure
that the appropriate file ownership is stored.
.DFLTn
.
.It Sy MKUPDATE
.YorN
If 
.Sq yes ,
.Sq make install
only installs targets that are more recently modified in the source
directories that their installed counterparts
.DFLTn
.
.It Sy MKUUCP
.YorN
Indicates whether
.Xr uucp 1
and related programs are built.
.DFLTy
.
.It Sy MKX11
.YorN
If set to
Indicates if building the system also
descends into
.Pa src/x11
to cross build X11R6 and automatically enables creation
of X sets.
.DFLTn
.
.It Sy MKYP
.YorN
Indicates whether the YP (NIS) infrastructure
(libraries and support programs) is built.
.DFLTy
.
.It Sy NETBSDSRCDIR
The path to the top level of the
.Nx
sources.
If
.Xr make 1
is run from within the
.Nx
source tree, the default is the top
level of that tree (as determined by the presence of
.Pa build.sh
and
.Pa tools/ ) ,
otherwise
.Sy BSDSRCDIR
will be used.
.
.It Sy OBJMACHINE
If defined, creates objdirs of the form
.Pa obj. Ns Sy MACHINE ,
where
.Sy MACHINE
is the current architecture (as per
.Sq "uname -m" ) .
.
.It Sy RELEASEDIR
If set, specifies the directory to which a
.Xr release 7
layout will be written at the end of a
.Dq make release .
.DFLTu
.Pp
.Em Note :
.Sy build.sh
will provide a default of
.Pa releasedir
(in the top-level
.Sy .OBJDIR )
unless run in
.Sq expert
mode
.
.It Sy TOOLDIR
Directory to hold the host tools, once built.
This directory should be unique to a given host system and
.Nx
source tree.
(However, multiple targets may share the same
.Sy TOOLDIR ;
the target-dependent files have unique names.)
If unset, a default based
on the
.Xr uname 1
information of the host platform will be created in the
.Sy .OBJDIR
of
.Pa src .
.DFLTu
.
.It Sy USETOOLS
Indicates whether the tools specified by
.Sy TOOLDIR
should be used as part of a build in progress.
Must be set to
.Dq yes
if cross-compiling.
.Bl -tag -width "never"
.It Sy yes
Use the tools from
.Sy TOOLDIR .
.It Sy no
Do not use the tools from
.Sy TOOLDIR ,
but refuse to build native compilation tool components that are
version-specific for that tool.
.It Sy never
Do not use the tools from
.Sy TOOLDIR ,
even when building native tool components.
This is similar to the traditional
.Nx
build method, but does
.Em not
verify that the compilation tools in use are up-to-date enough in order
to build the tree successfully.
This may cause build or runtime problems when building the whole
.Nx
source tree.
.El
.DFLT
.Dq yes
if building all or part of a whole
.Nx
source tree (detected automatically);
.Dq no
otherwise (to preserve traditional semantics of the
.Aq bsd.*.mk
.Xr make 1
include files).
.
.It Sy USE_HESIOD
.YorN
If 
.Dq no ,
disables building Hesiod support into various system utilities/libraries
that support it.
If
.Sy ${MKHESIOD}
is
.Dq no ,
.Sy USE_HESIOD 
will also be forced to
.Dq no .
.
.It Sy USE_INET6
.YorN
If 
.Sq no ,
disables building INET6 (IPv6) support into
various system utilities/libraries that support it.
If
.Sy ${MKINET6}
is
.Dq no ,
.Sy USE_INET6 
will also be forced to
.Dq no .
.
.It Sy USE_KERBEROS4
.YorN
If 
.Sq no ,
disables building Kerberos v4 support into various system utilities/libraries
that support it.
If
.Sy ${MKKERBEROS4} 
is
.Dq no ,
.Sy USE_KERBEROS4 
will also be forced to
.Dq no .
.
.It Sy USE_KERBEROS
.YorN
If 
.Sq no ,
disables building Kerberos v4 and v5 support into various system
utilities/libraries that support it.
If
.Sy ${MKKERBEROS} 
is
.Dq no ,
.Sy USE_KERBEROS 
will also be forced to
.Dq no .
.
.It Sy USE_PAM
.YorN
If
.Sq no ,
disables building PAM authentication support into various system
utilities/libraries that support it.
If
.Sy ${MKPAM}
is
.Dq no ,
.Sy USE_PAM
will also be forced to
.Dq no .
.
.It Sy USE_SKEY
.YorN
If
.Sq no ,
disables building S/key authentication support into various system
utilities/libraries that support it.
If
.Sy ${MKSKEY}
is
.Dq no ,
.Sy USE_SKEY
will also be forced to
.Dq no .
.
.It Sy USE_YP
.YorN
If
.Sq no ,
disables building YP (NIS) support into various system utilities/libraries
that support it.
If
.Sy ${MKYP}
is
.Dq no ,
.Sy USE_YP
will also be forced to
.Dq no .
.
.It Sy COPTS.lib\*[Lt]lib\*[Gt]
.It Sy LDADD.lib\*[Lt]lib\*[Gt]
.It Sy CPPFLAGS.lib\*[Lt]lib\*[Gt]
.It Sy CXXFLAGS.lib\*[Lt]lib\*[Gt]
.It Sy COPTS.\*[Lt]prog\*[Gt]
.It Sy LDADD.\*[Lt]prog\*[Gt]
.It Sy CPPFLAGS.\*[Lt]prog\*[Gt]
.It Sy CXXFLAGS.\*[Lt]prog\*[Gt]
These provide a way to specify additions to the associated
variables in a way that applies only to a particular library
or program. 
\*[Lt]lib\*[Gt] corresponds to the
.Sy LIB
variable set in
the library's
.Pa Makefile . 
\*[Lt]prog\*[Gt] corresponds to either
.Sy PROG
or
.Sy PROG_CXX
(if set). 
For example, if
.Sy COPTS.libcrypto
is set to
.Dq -g ,
.Dq -g
will be added to
.Sy COPTS
only when compiling the crypto library.
.
.El
.
.Ss pkgsrc system variables
.
Please see
.Xr packages 7
for more variables used internally by the package system and
.Pa ${PKGSRCDIR}/mk/defaults/mk.conf
for package-specific examples.
.
.Sh FILES
.Bl -tag -width /etc/mk.conf
.
.It Pa /etc/mk.conf
This file.
.
.It Pa ${PKGSRCDIR}/mk/defaults/mk.conf
Examples for settings regarding the pkgsrc collection.
.El
.
.Sh SEE ALSO
.Xr make 1 ,
.Xr packages 7 ,
.Pa /usr/share/mk/bsd.README
.Sh HISTORY
The
.Nm
file appeared in
.Nx 1.2 .
