.\"	$NetBSD: rc.conf.5,v 1.6 1997/04/01 20:17:43 perry Exp $
.\"
.\" Copyright (c) 1996 Matthew R. Green
.\" Copyright (c) 1997 Curt J. Sampson
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"      This product includes software developed by Matthew R. Green for
.\"      the NetBSD Project.
.\" 4. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd March 22, 1997
.Dt RC.CONF 5
.Os NetBSD 1.3
.\" turn off hyphenation
.hym 999
.Sh NAME
.Nm rc.conf
.Nd system startup configuration file
.Sh DESCRIPTION
The
.Nm
file specifies which services are enabled during system startup by
the startup script
.Pa /etc/rc .
The
.Nm
file is a shell script that is sourced by
.Pa /etc/rc
if it exists, meaning
that
.Nm
must be valid shell commands.
.Pp
Listed below are the
.Sy daemon_flags
variables that may be set, the values that each may be set to,
a brief description of what each daemon does, and a reference to
each daemon's manual page. Most 
.Sy daemon_flags
variables have three values: a list of parameters to pass on the
command line, "DEFAULT" for a reasonable default set of parameters,
or "NO" if the daemon is not to be run at all. Some programs don't
take a set of flags, and may only be set to "YES" or "NO". A few are
always run, and will not take "NO."
The arguments passed if "DEFAULT" is chosen are listed in
.Nm
itself.
.Pp
Interface boot-up configuration:
.Bl -tag -width bootparamd_flags
.It Sy net_interfaces
Parameters, DEFAULT, or NO.
Lists a set of interfaces to be configured with
.Xr ifconfig 8
at boot time.
If DEFAULT, the interfaces are found by running
.Xr ifconfig 8
with the
.Ar -l
flag. Usually, the parameters for the subsequent
.Xr ifconfig 8
commands are found in files named
.Pa /etc/ifconfig.* ,
where
.Dq *
is the name of each interface (e.g.
.Pa /etc/ifconfig_le0 ) .
However, parameters may alternatively be found in an
.Em ifconfig_*
variable (see below).
.It Sy ifconfig_*
Parameters only.
Supplies a set of parameters for configuring the given interface
.Dq *
(e.g.
.Em ifconfig_le0 ) .
See
.Em net_interfaces ,
above.
.El
Programs run on boot-up:
.Bl -tag -width bootparamd_flags
.It Sy savecore_flags
Parameters, DEFAULT or NO.
Saves a copy of the kernel and crash dump when the system comes up
after a crash.  The
.Ar -z
parameter will compress the kernel and crash dump.  See
.Xr savecore 8 .
.It Sy lkm_init
YES or NO. Loads
.Xr lkm 4
modules based on information in
.Pa /etc/lkm.conf .
See
.Xr lkm.conf 5 .
.It Sy ipfilter
YES or NO.  Runs 
.Xr ipf 8
to load in packet filter specifications from
.Pa /etc/ipf.conf
at network boot time, before any interfaces are configured.  See
.Xr ipf 5 .
.El
Daemons required for other daemons:
.Bl -tag -width bootparamd_flags
.It Sy inetd_flags
Parameters, DEFAULT or NO.
Starts other internet programs (as listed in
.Pa /etc/inetd.conf )
as necessary.  The
.Ar -l
option turns on libwrap connection logging.  See
.Xr inetd 8 .
.It Sy portmap
YES or NO.  The
.Xr portmap 8
daemon is required for any Sun RPC based services.  These include NFS, YP,
.Xr bootparamd 8 ,
.Xr rstatd 8 ,
.Xr rusersd 8 ,
and
.Xr rwalld 8 .
.El
Commonly used daemons:
.Bl -tag -width bootparamd_flags
.It Sy update_flags
Parameters or DEFAULT.  The
.Xr update 8
daemon flushes cached disk pages that are dirty to disk at regular intervals.
.It Sy syslog_flags
Parameters, DEFAULT or NO.
Syslog daemon; logs messages to logfiles.  See
.Xr syslogd 8 .
.It Sy timed_flags
Parameters, DEFAULT or NO.
Local area network time synchronisation daemon.  The
.Ar -M
parameter allows this host to be a master, as well as a slave. See
.Xr timed 8 .
.It Sy xntpd_flags
Parameters, DEFAULT or NO.
Local and wide area network time synchronisation daemon.  If this is used,
.Sy timed_flags
should be set to
.Ar -M -F localhost
on one xntp-using host on the network, and to "NO"
on any other xntp-using host.
.Xr xntpd 8
is not included with
.Nx .
.It Sy sendmail_flags
Parameters, DEFAULT or NO.
Sendmail SMTP mail transport agent.  See
.Xr sendmail 8 .
.It Sy named_flags
Parameters, DEFAULT or NO.
BIND domain name resolver and server.  See
.Xr named 8 .
.It Sy lpd_flags
Parameters, DEFAULT or NO.
Line printer daemon; allows other hosts to print to the local host's printer.
The
.Ar -l
option turns on extra logging.  See
.Xr lpd 8 .
.El
Routing daemons:
.Bl -tag -width bootparamd_flags
.It Sy routed_flags
Parameters, DEFAULT or NO.
RIP routing protocol daemon.  This should be NO if
.Sy gated_flags
is anything but NO.  See
.Xr routed 8 .
.It Sy gated_flags
Parameters, DEFAULT or NO.
Routing daemon for many IP routing protocols.
This should be NO if
.Sy routed_flags
is anything but NO.
.Xr gated 8
is not included with
.Nx .
.It Sy mrouted_flags
Parameters, DEFAULT or NO.
DVMRP multicast routing protocol daemon.  See
.Xr mrouted 8 .
.El
Daemons used to boot other hosts over a network:
.Bl -tag -width bootparamd_flags
.It Sy rarpd_flags
Parameters, DEFAULT or NO.
Reverse ARP daemon; used to boot NetBSD and Sun workstations.  See
.Xr rarpd 8 .
.It Sy bootparamd_flags
Parameters, DEFAULT or NO.
Boot parameter server; used for booting NetBSD and SunOS 4.x systems.  See
.Xr bootparamd 8 .
.It Sy dhcpd_flags
Parameters, DEFAULT or NO.
Dynamic Host Configuration Protocol daemon, for assigning IP addresses to
hosts and passing boot information.  See
.Xr dhcpd 8 .
.It Sy rbootd_flags
Parameters, DEFAULT or NO.
HP boot protocol daemon; used for booting HP workstations.  See
.Xr rbootd 8 .
.It Sy mopd_flags
Parameters, DEFAULT or NO.
DEC MOP protocol daemon; used for booting VAX and other DEC machines.  See
.Xr mopd 8 .
.El
YP (NIS) daemons:
.Bl -tag -width bootparamd_flags
.It Sy ypbind_flags
Parameters, DEFAULT or NO.
Run on YP (NIS) clients to use information from a YP server.  See
.Xr ypbind 8 .
.It Sy ypserv_flags
Parameters, DEFAULT or NO.
YP (NIS) server for distributing information from certain files in
.Pa /etc .
See
.Xr ypserv 8 .
.It Sy yppasswdd_flags
Parameters, DEFAULT or NO.
Allows remote YP users to update password on master server.  See
.Xr yppasswdd 8 .
.El
Network file system daemons:
.Bl -tag -width bootparamd_flags
.It Sy nfs_client
YES or NO.  Runs 
.Xr nfsiod 8
to increase performance of an NFS client host.
.It Sy nfsiod_flags
Parameters or DEFAULT.  Flags passed to
.Xr nfsiod 8
if
.Sy nfs_client
is set to YES.
.It Sy nfs_server
YES or NO.  Sets up a host to be a NFS server by running
.Xr mountd 8
and
.Xr nfsd 8 .
.It Sy mountd_flags
Parameters or DEFAULT. These are passed to
.Xr mountd 8
if
.Sy nfs_server
is set to YES.
.It Sy nfsd_flags
Parameters or DEFAULT. These are passed to
.Xr nfsd 8
if
.Sy nfs_server
is set to YES.
.It Sy lockd_flags
Parameters, DEFAULT or NO.  Provides locking for NFS.  Ignored if
.Sy nfs_server
and
.Sy nfs_client
are both set to NO.  See
.Xr rpc.lockd 8 .
.It Sy statd_flags
Parameters, DEFAULT or NO.  Ignored if
.Sy nfs_server
and
.Sy nfs_client
are both set to NO.  Status monitoring daemon used when
.Xr rpc.lockd 8
is running.  See
.Xr rpc.statd 8 .
.It Sy amd_flags
Parameters, DEFAULT or NO.  
The automounter daemon,
.Xr amd 8 ,
automatically mounts NFS file systems whenever a file or directory within
that filesystem is accessed.
.It Sy amd_dir
The
.Xr amd 8 
mount directory.  Used only if
.Sy amd_flags
is not set to NO.
.It Sy amd_master
The
.Xr amd 8 
automounter master map.
Used only if
.Sy amd_flags
is not set to NO.
.El
Other daemons:
.Bl -tag -width bootparamd_flags
.It Sy rwhod
YES or NO.  Daemon to support
.Xr rwho 8
command.  See
.Xr rwhod 8 .
.It Sy kerberos
YES or NO.  Runs the kerberos server
.Xr kerberos 8
and the kerberos admininstration server,
.Xr kadmind 8 .
This should only be run on the kerberos master server.
The kerberos server is only available with the domestic distribution of
.Nx .
.El
.Sh FILES
.Pa /etc/rc.conf
.Sh SEE ALSO
.Xr boot 8
.Sh BUGS
The
.Sy kerberos_server
variable is actually used by the default
.Pa /etc/rc.local
script, not the
.Pa /etc/rc
script.
.Sh HISTORY
The
.Nm
file appeared in
.Nx 1.3 .
