.\"	$NetBSD: rc.conf.5,v 1.32.2.3 2000/08/09 19:15:32 lukem Exp $
.\"
.\" Copyright (c) 1996 Matthew R. Green
.\" Copyright (c) 1997 Curt J. Sampson
.\" Copyright (c) 1997 Michael W. Long
.\" Copyright (c) 1998-2000 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This document is derived from works contributed to The NetBSD Foundation
.\" by Luke Mewburn.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd August 9, 2000
.Dt RC.CONF 5
.Os
.\" turn off hyphenation
.hym 999
.Sh NAME
.Nm rc.conf
.Nd system startup configuration file
.Sh DESCRIPTION
The
.Nm
file specifies which services are enabled during system startup by
the startup scripts invoked by
.Pa /etc/rc .
The
.Nm
file is a shell script that is sourced by
.Pa /etc/rc
if it exists, meaning that
.Nm
must contain valid shell commands.
.Pp
Listed below are the
.Nm
variables that may be set, the values to which each may be set,
a brief description of what each variable does, and a reference to
relevant manual pages.
.Pp
Most variables are one of two types: enabling variables or flags
variables.
Enabling variables, such as
.Sy inetd ,
are generally named after the program or the system they enable,
and are set to
.Sq YES
or
.Sq NO .
Flags variables, such as
.Sy inetd_flags
have the same name with "_flags" appended, and determine what
arguments are passed to the program if it is enabled.
.Pp
If a variable that
.Pa /etc/rc
expects to be set is not set, or the value is not one of the allowed
values, a warning will be printed.
.Ss Overall control:
.Bl -tag -width net_interfaces
.It Sy rc_configured
If this is not set to
.Sq YES
then the system will drop into single-user mode during boot.
.It Sy do_rcshutdown
If set to
.Sq NO ,
.Xr shutdown 8
will not run
.Pa /etc/rc.shutdown .
.El
.Ss Basic network configuration:
.Bl -tag -width net_interfaces
.It Sy hostname
Name of host.
If empty or not set, then the contents of
.Pa /etc/myname
(if it exists) are used.
.It Sy domainname
.Tn NIS
(YP) domain of host.
If empty or not set, then the contents of
.Pa /etc/defaultdomain
(if it exists) are used.
.It Sy defaultroute
Default network route.
If empty or not set, then the contents of
.Pa /etc/mygate
(if it exists) are used.
.El
.Ss Boottime file-system and swap configuration:
.Bl -tag -width net_interfaces
.It Sy critical_filesystems_beforenet
File systems mounted very early in the system boot before networking
services are available.
Usually
.Pa /var
is part of this, because it is needed by services such as
.Xr dhclient 1
which may be required to get the network operational.
.It Sy critical_filesystems
File systems such as
.Pa /usr
that may require network services to be available to mount,
that must be available early in the system boot for general services to use.
.It Sy no_swap
Set the
.Sy no_swap
variable to
.Sq YES
if you have configured your system with no swap on purpose.
If not set, or set to anything other than
.Sq YES ,
and no swap devices
are configured, the system will warn you.
.El
.Ss One-time actions to perform or programs to run on boot-up:
.Bl -tag -width net_interfaces
.It Sy lkm
.Sq YES
or
.Sq NO .
Runs
.Pa /etc/rc.lkm .
.It Sy savecore
.Sq YES
or
.Sq NO .
Runs the
.Xr savecore 8
utility.
Passes
.Sy savecore_flags .
.It Sy clear_tmp
.Sq YES
or
.Sq NO .
Clear /tmp after reboot.
.It Sy update_motd
.Sq YES
or
.Sq NO .
Updates the
.Nx
version string in the
.Pa /etc/motd
file to reflect the version of the running kernel.
See
.Xr motd 5 .
.It Sy dmesg
.Sq YES
or
.Sq NO .
Create
.Pa /var/run/dmesg.boot
from the output of
.Xr dmesg 8 .
Passes
.Sy dmesg_flags .
.It Sy accounting
.Sq YES
or
.Sq NO .
Enables process accounting with
.Xr accton 8 .
Requires
.Pa /var/account/acct
to exist.
.El
.Ss System security setting:
.Bl -tag -width net_interfaces
.It Sy securelevel
A number.
The system securelevel is set to the specified value early
in the boot process, before any external logins, or other programs
that run users job, are started.
If set to nothing, the default action is taken, as described
.Xr init 8 ,
which contains definative information about the system securelevel.
.El
.Ss Networking startup:
.Bl -tag -width net_interfaces
.It Sy ipfilter
.Sq YES
or
.Sq NO .
Runs
.Xr ipf 8
to load in packet filter specifications from
.Pa /etc/ipf.conf
at network boot time, before any interfaces are configured.
See
.Xr ipf.conf 5 .
.It Sy ipnat
Runs
.Xr ipnat 8
to load in the IP network address translation (NAT) rules from
.Pa /etc/ipnat.conf
at network boot time, before any interfaces are configured.
See
.Xr ipnat.conf 5 .
.It Sy ipsec
.Sq YES
or
.Sq NO .
Runs
.Xr setkey 8
to load in IPsec manual keys and policies from
.Pa /etc/ipsec.conf
at network boot time, before any interfaces are configured.
.It Sy ipmon
.Sq YES
or
.Sq NO .
Runs
.Xr ipmon 8
to read
.Xr ipf 8
packet log information and log it to a file or the system log.
Passes
.Sy ipmon_flags .
.It Sy auto_ifconfig
.Sq YES
or
.Sq NO .
Sets the
.Sy net_interfaces
variable (see below) to the output of
.Xr ifconfig 8
with the
.Ar -l
flag and suppresses warnings about interfaces in this list that
do not have an ifconfig file or variable.
.It Sy net_interfaces
The list of network interfaces to be configured at boot time.
For each interface "xxn", the system first looks for ifconfig
parameters in
.Pa /etc/ifconfig.xxn
and then in the variable
.Sy ifconfig_xxn .
The contents of the file or the variable are handed to ifconfig
after the interface name.
If
.Sy auto_ifconfig
is set to "NO" and neither the file nor the variable is found,
a warning is printed.
.It Sy ifaliases_*
List of
.Sq Ar "address netmask"
pairs to configure additional network addresses for the given
configured interface
.Dq *
(e.g.
.Sy ifaliases_le0 ) .
If
.Ar netmask
is
.Dq - ,
then use the default netmask for the interface.
.Pp
.Sy ifaliases_*
covers limited cases only and considered unrecommended.
We recommend using
.Pa /etc/ifconfig.xxN
with multiple lines instead.
.It Sy flushroutes
.Sq YES
or
.Sq NO .
Flushes the route table on networking startup.
Useful when coming up to multiuser mode after going down to
single-user mode.
.It Sy dhclient
.Sq YES
or
.Sq NO .
Set to
.Sq YES
to configure some or all network interfaces using
the DHCP client.
If you set
.Sy dhclient
to
.Sq YES ,
you must either have
.Pa /var
in
.Sy critical_filesystems_beforenet ,
as part of
.Pa / ,
or direct the DHCP client to store the leases file on the root
filesystem by modifying the
.Sy dhclient_flags
variable.
You must not provide ifconfig information or ifaliases
information for any interface that is to be configured using the DHCP client.
Interface aliases can be set up in the DHCP client configuration
file if needed - see
.Xr dhclient.conf 5
for details.
.Pp
Passes
.Sy dhclient_flags
to the DHCP client.
See
.Xr dhclient 8
for complete documentation.
If you wish to configure all broadcast
network interfaces using the DHCP client, you can leave this blank.
To configure only specific interfaces, name the interfaces to be configured
on the command line.
.Pp
If you must run the DHCP client before mounting critical filesystems,
then you should specify an alternate location for the DHCP client's lease
file in the
.Sy dhclient_flags
variable - for example, "-lf /tmp/dhclient.leases".
.It Sy ntpdate
.Sq YES
or
.Sq NO .
Runs
.Xr ntpdate 8
to set the system time from one of the hosts in
.Sy ntpdate_hosts .
If
.Sy ntpdate_hosts
is empty, it will attempt to find a list of hosts in
.Pa /etc/ntp.conf .
.It Sy ppp_peers
If
.Sy ppp_peers
is not empty, then
.Pa /etc/netstart
will check each word in
.Sy ppp_peers
for a coresponding ppp configuration file in
.Pa /etc/ppp/peers
and will call
.Xr pppd 8
with the
.Dq call Sy peer
option.
.It Sy ip6mode
An IPv6 node can be a router
.Pq nodes that forward packet for others
or host
.Pq nodes that do not forward .
A host can be autoconfigured
based on the information advertised by adjacent IPv6 router.
By setting
.Sy ip6mode
to
.Dq Li router ,
.Dq Li host ,
or
.Dq Li autohost ,
you can configure your node as a router,
a non-autoconfigured host, or an autoconfigured host.
Invalid values will be ignored, and the node will be configured as
a non-autoconfigured host.
You may want to check
.Sy rtsol
and
.Sy rtsold
as well, if you set the variable to
.Li autohost .
.It Sy rtsol
.Sq YES
or
.Sq NO .
Run
.Xr rtsol 8 ,
router solicitation command for IPv6 host.
On nomadic host like notebook computers, you may want to enable
.Sy rtsold
as well.
Passes
.Sy rtsol_flags .
This is only for autoconfigured IPv6 host, so set
.Sy ip6mode
to autohost if you use it.
.El
.Ss Daemons required by other daemons:
.Bl -tag -width net_interfaces
.It Sy inetd
.Sq YES
or
.Sq NO .
Runs the
.Xr inetd 8
daemon to start network server processes (as listed in
.Pa /etc/inetd.conf )
as necessary.
Passes
.Sy inetd_flags .
The
.Ar -l
flag turns on libwrap connection logging.
.It Sy rpcbind
.Sq YES
or
.Sq NO .
The
.Xr rpcbind 8
daemon is required for any
.Xr rpc 3
services.
These include NFS,
.Tn NIS ,
.Xr bootparamd 8 ,
.Xr rstatd 8 ,
.Xr rusersd 8 ,
and
.Xr rwalld 8 .
.El
.Ss Commonly used daemons:
.Bl -tag -width net_interfaces
.It Sy syslogd
.Sq YES
or
.Sq NO .
Runs
.Xr syslogd 8
and passes
.Sy syslogd_flags .
.It Sy cron
.Sq YES
or
.Sq NO .
Run
.Xr cron 8 .
.It Sy named
.Sq YES
or
.Sq NO .
Runs
.Xr named 8
and passes
.Sy named_flags .
.It Sy timed
.Sq YES
or
.Sq NO .
Runs
.Xr timed 8
and passes
.Sy timed_flags .
The
.Ar -M
option allows
.Xr timed 8
to be a master time source as well as a slave.
If you are also running
.Xr ntpd 8 ,
only one machine running both should have the
.Ar -M
flag given to
.Xr timed 8 .
.It Sy ntpd
.Sq YES
or
.Sq NO .
Runs
.Xr ntpd 8
and passes
.Sy ntpd_flags .
.It Sy sendmail
.Sq YES
or
.Sq NO .
Runs
.Xr sendmail 8
and passes
.Sy sendmail_flags .
.It Sy postfix
.Sq YES
or
.Sq NO .
Starts
.Xr postfix 8
mail system.
.It Sy lpd
.Sq YES
or
.Sq NO .
Runs
.Xr lpd 8
and passes
.Sy lpd_flags .
The
.Ar -l
flag will turn on extra logging.
.It Sy sshd
.Sq YES
or
.Sq NO .
Runs
.Xr sshd 8
and passes
.Sy sshd_flags .
.Xr sshd 8
is not included with the standard
.Nx
installation, although it is part of the optional
.Nx
package collection.
.El
.Ss Routing daemons:
.Bl -tag -width net_interfaces
.It Sy routed
.Sq YES
or
.Sq NO .
Runs
.Xr routed 8 ,
the RIP routing protocol daemon.
Passes
.Sy routed_flags .
This should be
.Sq NO
if
.Sy gated
is
.Sq YES .
.It Sy gated
.Sq YES
or
.Sq NO .
Runs
.Xr gated 8 ,
the multiprotocol routing daemon.
Passes
.Sy gated_flags .
This should be
.Sq NO
if
.Sy routed
is
.Sq YES .
.Xr gated 8
is not included with the standard
.Nx
installation, although it is part of the optional
.Nx
package collection.
.It Sy mrouted
.Sq YES
or
.Sq NO .
Runs
.Xr mrouted 8 ,
the DVMRP multicast routing protocol daemon.
Passes
.Sy mrouted_flags .
.It Sy route6d
.Sq YES
or
.Sq NO .
Runs
.Xr route6d 8 ,
the RIPng routing protocol daemon for IPv6.
Passes
.Sy route6d_flags .
.It Sy rtsold
.Sq YES
or
.Sq NO .
Runs
.Xr rtsold 8 ,
the IPv6 router solicitation daemon.
.Xr rtsold 8
periodically transmits router solicitation packet
to find IPv6 router on the network.
This configuration is mainly for nomadic host like notebook computers.
Stationary host should work fine with
.Sy rtsol
only.
Passes
.Sy rtsold_flags .
This is only for autoconfigured IPv6 host, so set
.Sy ip6mode
to autohost if you use it.
.El
.Ss Daemons used to boot other hosts over a network:
.Bl -tag -width net_interfaces
.It Sy rarpd
.Sq YES
or
.Sq NO .
Runs
.Xr rarpd 8 ,
the reverse ARP daemon, often used to boot
.Nx
and Sun workstations.
Passes
.Sy rarpd_flags .
.It Sy bootparamd
.Sq YES
or
.Sq NO .
Runs
.Xr bootparamd 8 ,
the boot parameter server, with
.Sy bootparamd_flags
as options.
Used to boot
.Nx
and
.Tn "SunOS 4.x"
systems.
.It Sy dhcpd
.Sq YES
or
.Sq NO .
Runs
.Xr dhcpd 8 ,
the Dynamic Host Configuration Protocol (DHCP) daemon,
for assigning IP addresses to hosts and passing boot information.
Passes
.Sy dhcpd_flags .
.It Sy dhcrelay
.Sq YES
or
.Sq NO .
Runs
.Xr dhcrelay 8 .
Passes
.Sy dhcrelay_flags .
.It Sy rbootd
.Sq YES
or
.Sq NO .
Runs
.Xr rbootd 8 ,
the
.Tn HP
boot protocol daemon; used for booting
.Tn HP
workstations.
Passes
.Sy rbootd_flags .
.It Sy mopd
.Sq YES
or
.Sq NO .
Runs
.Xr mopd 8 ,
the
.Tn DEC
.Tn MOP
protocol daemon; used for booting
.Tn VAX
and other
.Tn DEC
machines.
Passes
.Sy mopd_flags .
.It Sy rtadvd
.Sq YES
or
.Sq NO .
Runs
.Xr rtadvd 8 ,
the IPv6 router advertisement daemon, which is used to advertise
information about the subnet to IPv6 end hosts.
Passes
.Sy rtadvd_flags .
This is only for IPv6 router, so set
.Sy ip6forwarding
to
.Sq YES
if you use it.
.El
.Ss X Window System daemons:
.Bl -tag -width net_interfaces
.It Sy xfs
.Sq YES
or
.Sq NO .
Runs the
.Xr xfs 1
X11 font server, which supplies local X font files to X terminals.
.It Sy xdm
.Sq YES
or
.Sq NO .
Runs the
.Xr xdm 1
X display manager.
These X daemons are available only with the optional X distribution of
.Nx .
.El
.Ss NIS (YP) daemons:
.Bl -tag -width net_interfaces
.It Sy ypbind
.Sq YES
or
.Sq NO .
Runs
.Xr ypbind 8 ,
which lets
.Tn NIS
(YP) clients use information from a
.Tn NIS
server.
Passes
.Sy ypbind_flags .
.It Sy ypserv
.Sq YES
or
.Sq NO .
Runs
.Xr ypserv 8 ,
the
.Tn NIS
(YP) server for distributing information from certain files in
.Pa /etc .
Passes
.Sy ypserv_flags .
The
.Ar -d
flag causes it to use DNS for lookups in
.Pa /etc/hosts
that fail.
.It Sy yppasswdd
.Sq YES
or
.Sq NO .
Runs
.Xr yppasswdd 8 ,
which allows remote
.Tn NIS
users to update password on master server.
Passes
.Sy yppasswdd_flags .
.El
.Ss NFS daemons and parameters:
.Bl -tag -width net_interfaces
.It Sy nfs_client
.Sq YES
or
.Sq NO .
The number of local NFS asynchronous I/O server is now controlled via
.Xr sysctl 8 .
.It Sy nfs_server
.Sq YES
or
.Sq NO .
Sets up a host to be a NFS server by running
.Xr mountd 8
and
.Xr nfsd 8 ,
and passing
.Sy mountd_flags
and
.Sy nfsd_flags
to them, respectively.
.It Sy lockd
.Sq YES
or
.Sq NO .
Runs
.Xr rpc.lockd 8
if either
.Sy nfs_server
or
.Sy nfs_client
is (or both are) set to
.Sq YES .
Passes
.Sy lockd_flags .
.It Sy statd
.Sq YES
or
.Sq NO .
Runs
.Xr rpc.statd 8 ,
a status monitoring daemon used when
.Xr rpc.lockd 8
is running, if either
.Sy nfs_server
or
.Sy nfs_client
is (or both are) set to
.Sq YES .
Passes
.Sy statd_flags .
.It Sy amd
.Sq YES
or
.Sq NO .
Runs
.Xr amd 8 ,
the automounter daemon, which automatically mounts NFS file systems
whenever a file or directory within that filesystem is accessed.
Passes
.Sy amd_flags .
.It Sy amd_dir
The
.Xr amd 8
mount directory.
Used only if
.Sy amd
is set to
.Sq YES .
.It Sy amd_master
The
.Xr amd 8
automounter master map.
Used only if
.Sy amd
is set to
.Sq YES .
.El
.Ss Other daemons:
.Bl -tag -width net_interfaces
.It Sy rwhod
.Sq YES
or
.Sq NO .
Runs
.Xr rwhod 8
to support the
.Xr rwho 1
and
.Xr ruptime 1
commands.
.It Sy kerberos
.Sq YES
or
.Sq NO .
Runs the kerberos server
.Xr kerberos 8
and the kerberos admininstration server,
.Xr kadmind 8 .
This should only be run on the kerberos master server.
Both servers implement version IV of the Kerberos protocol, not the
newer Kerberos version 5.
.El
.Ss Hardware daemons:
.Bl -tag -width net_interfaces
.It Sy apmd
.Sq YES
or
.Sq NO .
Runs
.Xr apmd 8
and passes
.Sy apmd_flags .
.It Sy screenblank
.Sq YES
or
.Sq NO .
Runs
.Xr screenblank 1
and passes
.Sy screenblank_flags .
.It Sy wscons
.Sq YES
or
.Sq NO .
Configures the
.Xr wscons 4
console driver, from the configuration file
.Pa /etc/wscons.conf .
.El
.Sh FILES
.Pa /etc/rc.conf
.Sh SEE ALSO
.Xr boot 8 ,
.Xr rc 8 ,
.Xr sysctl 8
.Sh HISTORY
The
.Nm
file appeared in
.Nx 1.3 .
