#	$NetBSD: Makefile,v 1.25.12.1 2017/12/03 11:35:48 jdolecek Exp $

INCSDIR= /usr/include/amiga

INCS=	ansi.h aout_machdep.h asm.h \
	bswap.h bus.h \
	cdefs.h cpu.h cpufunc.h \
	disklabel.h \
	elf_machdep.h endian.h endian_machdep.h \
	fenv.h float.h frame.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intr.h \
	kcore.h \
	limits.h lock.h \
	math.h mcontext.h mutex.h \
	param.h pcb.h pmap.h pmc.h proc.h profile.h psl.h pte.h ptrace.h \
	reg.h rwlock.h \
	setjmp.h signal.h \
	trap.h types.h \
	vmparam.h \
	wchar_limits.h

.include <bsd.kinc.mk>
