# $NetBSD: Makefile,v 1.6 2020/06/27 05:07:07 jruoho Exp $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/sbin/ifconfig

TESTS_SH=	t_bridge \
		t_nonexistent \
		t_repeated_scan \
		t_repeated_updown \
		t_tap \
		t_woptions

.include <bsd.test.mk>
