#	$NetBSD: Makefile,v 1.9 2014/07/23 18:19:44 alnsn Exp $

INCSDIR= /usr/include/mvmeppc

INCS=   bootinfo.h \
	disklabel.h \
	intr.h \
	sljit_machdep.h \
	vmparam.h

.include "../../powerpc/include/Makefile"
