#	$NetBSD: Makefile,v 1.7.128.1 2014/05/18 17:45:19 rmind Exp $

INCSDIR= /usr/include/mvmeppc

INCS=   bootinfo.h \
	disklabel.h \
	intr.h \
	sljitarch.h \
	vmparam.h

.include "../../powerpc/include/Makefile"
