#	$NetBSD: Makefile,v 1.2 2001/04/25 18:32:03 garbled Exp $

FILES=	form help preform
FILESDIR=${BINDIR}/sushi/network/interfaces/interface
SCRIPTS= script script1 script2
SCRIPTSDIR=${BINDIR}/sushi/network/interfaces/interface
MKOBJ=	no

.include "../../../../Makefile.inc"
.include <bsd.prog.mk>
