#	$NetBSD: Makefile,v 1.3 2001/07/14 06:51:27 garbled Exp $

FILES=	form help preform nwid.sed
FILESDIR=${BINDIR}/sushi/network/interfaces/interface
SCRIPTS= script script1 script2
SCRIPTSDIR=${BINDIR}/sushi/network/interfaces/interface
MKOBJ=	no

.include "../../../../Makefile.inc"
.include <bsd.prog.mk>
