#	$NetBSD: Makefile,v 1.4 2001/12/12 01:49:24 tv Exp $

FILES=	form help preform nwid.sed
FILESDIR=${BINDIR}/sushi/network/interfaces/interface
SCRIPTS= script script1 script2
SCRIPTSDIR=${BINDIR}/sushi/network/interfaces/interface
NOOBJ=	# defined

.include "../../../../Makefile.inc"
.include <bsd.prog.mk>
