.\" $NetBSD: utoppya.1,v 1.3.26.1 2014/08/20 00:05:05 tls Exp $
.\"
.\" Copyright (c) 2006 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Steve C. Woodford.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd April 3, 2006
.Dt UTOPPYA 1
.Os
.Sh NAME
.Nm utoppya
.Nd Topfield TF5000PVR file manipulation program
.Sh SYNOPSIS
.Nm
.Op Fl f Ar device
.Ar command ...
.Sh DESCRIPTION
.Nm
is the userland interface to the
.Xr utoppy 4
device driver.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl f
Communicate with
.Ar device
instead of the default
.Pa /dev/utoppy0 .
.El
.Pp
Using the services of the
.Xr utoppy 4
driver,
.Nm
can perform the following operations, specified by the
.Ar command
operand:
.Bl -tag -width Ds
.It Cm df
Display disk size and free space
.It Cm ls Op Ar directory
List the files in the specified
.Ar directory .
Default is the Toppy's root directory.
.It Cm mkdir Ao Ar directory Ac
Make the specified
.Ar directory .
You must supply the full pathname to
.Ar directory .
.It Cm rm Ao Ar pathname Ac
Delete the file or directory specified by
.Ar pathname .
.It Cm rename Ao Ar source Ac Ao Ar target Ac
Rename the file or directory specified by the
.Ar source
operand to the destination file or directory specified by the
.Ar target
operand.
.It Cm get Oo Fl prt Oc Ao Ar toppyfile Ac Oo Ar localfile Oc
Copy
.Ar toppyfile
from the Toppy to
.Ar localfile
on the local filesystem.
If
.Ar localfile
is omitted, the file will be copied into the current directory and will be
named using the last component of the
.Ar toppyfile
operand.
If
.Ar localfile
is
.Sq - ,
then
.Ar toppyfile
will be copied to the standard output.
.Pp
The following options are available for the
.Nm get
command:
.Bl -tag -width Ds
.It Fl p
Display a progress bar.
.It Fl r
This option is useful if you wish to resume a previously interrupted
.Nm get
command.
Instead of restarting from the beginning of the file, the transfer will
resume where it left off.
.It Fl t
Enable
.Ql Turbo
mode.
This instructs the Toppy to drop everything and concentrate on transferring
the file as quickly as possible.
You will be able to watch live TV, but all other functions, including
changing channel via the remote control, will be inoperative.
.El
.It Cm put Oo Fl prt Oc Ao Ar localfile Ac Ao Ar toppyfile Ac
Copy
.Ar localfile
on the local filesystem to
.Ar toppyfile
on the Toppy.
If
.Ar toppyfile
specifies a directory on the Toppy, the last component of the
.Ar localfile
operand will be appended to the
.Ar toppyfile
operand.
.Pp
The options described for the
.Nm get
command (above) also apply to the
.Nm put
command.
.El
.Sh FILES
.Pa /dev/utoppy0
The default Topfield TF5000PVR instance.
.Sh SEE ALSO
.Xr usb 4 ,
.Xr utoppy 4
.Sh HISTORY
The
.Nm
command first appeared in
.Nx 4.0
and was inspired by
.Ql ftpd-topfield
written by Steve Bennett
.Aq msteveb at ozemail.com.au
and
.Ql puppy
written by Peter Urbanec
.Aq toppy at urbanec.net .
.Sh AUTHORS
.An Steve C. Woodford Aq Mt scw@netbsd.org
