#	$NetBSD: Makefile,v 1.4 2005/06/22 06:16:02 dyoung Exp $

INCSDIR= /usr/include/net80211

INCS=	_ieee80211.h ieee80211.h \
	ieee80211_crypto.h ieee80211_ioctl.h ieee80211_netbsd.h \
	ieee80211_node.h ieee80211_proto.h ieee80211_radiotap.h \
	ieee80211_rssadapt.h ieee80211_sysctl.h ieee80211_var.h

.include <bsd.kinc.mk>
