# $NetBSD: Makefile,v 1.1 2009/02/13 05:19:51 jmmv Exp $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/util/config

NOATFFILE=	# defined

FILESDIR=	${TESTSDIR}/support/arch/regress/conf
FILES=		Makefile.regress
FILES+=		files.regress
FILES+=		std.regress

.include <bsd.test.mk>
.include <bsd.files.mk>
.include <bsd.prog.mk>
