# $NetBSD: Makefile,v 1.2 2003/05/23 21:56:38 leo Exp $

BTYPE=MILAN

.include <../Makefile.sdb00t>
# $NetBSD: Makefile,v 1.2 2003/05/23 21:56:38 leo Exp $

BTYPE=MILAN

.include <../Makefile.sdb00t>
