#	$NetBSD: Makefile,v 1.13 2019/05/03 11:29:06 sevan Exp $

NOOBJ=	# defined

.include <bsd.own.mk>

.if ${MKSHARE} != "no"
FILES=	sup.jp.netbsd.org sup2.fr.netbsd.org
FILESDIR=/usr/share/examples/supfiles
.endif

.include <bsd.prog.mk>
