#	$NetBSD: Makefile,v 1.2 1998/09/27 17:22:09 lukem Exp $

.if !defined(NOSHARE)
FILES=	ftp.cs.umn.edu skarven.itea.unit.no sup.au.netbsd.org \
	sup.de.netbsd.org sup.netbsd.org sup.uk.netbsd.org
FILESDIR=/usr/share/examples/supfiles
.endif
NOOBJ=	noobj

.include <bsd.prog.mk>
