.\" $NetBSD: bmd.4,v 1.3 2003/01/19 21:25:41 atatat Exp $
.\"
.\" Copyright (c) 2002 Tetsuya Isaki. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"      This product includes software developed by Tetsuya Isaki.
.\" 4. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\" BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\" AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd December 1, 2002
.Os
.Dt BMD 4 x68k
.Sh NAME
.Nm bmd
.Nd Nereid bank memory disk driver
.Sh SYNOPSIS
.Cd bmd* at intio0 addr 0xece3f0
.Cd bmd* at intio0 addr 0xecebf0
.Sh DESCRIPTION
The
.Nm
driver provides a memory disk for the Nereid bank memory space.
There is no special command to configure it, because
.Nm
is not a logical disk as
.Xr md 4 .
.Sh FILES
.Bl -tag -width /dev/rbmdXX -compact
.It Pa "/dev/bmd??"
block mode bank memory disk
.It Pa "/dev/rbmd??"
raw mode bank memory disk
.El
.Sh EXAMPLES
In order to use it, do as follows:
.Dl newfs /dev/bmd0c
.Dl mount /dev/bmd0c /mnt
.Sh SEE ALSO
.Xr intio 4
.Sh HISTORY
.Nm
appeared in
.Nx 2.0 .
