.\" This software is in the Public Domain.
.\" Author: Masaru Oki
.\"
.Dd May 5, 1995
.Dt LOADFONT 1
.Os BSD 4
.Sh NAME
.Nm loadfont
.Nd load and set font for the NetBSD/x68k console.
.Sh SYNOPSIS
.Nm loadfont
.Ar fontfile
.Sh DESCRIPTION
.Nm Loadfont
command reads font data from
.Ar fontfile
and replaces the x68k console font with it.
.Pp
.Ar Fontfile
format is compatible with that of
.Nm Human68k IOCS font .
.Sh BUGS
Replacing kanji fonts is not supported, 
because current NetBSD/x68k kernel has no ability to use
one other than in the ROM.

Font data in
.Ar fontfile
must be a full set of JIS X0201 (must contain hankaku-katakana part).
