.\"	$NetBSD: loadkmap.1,v 1.7 2019/09/01 14:32:04 sevan Exp $
.\"
.\" This software is in the Public Domain.
.\" Author: Masaru Oki
.\"
.Dd September 1, 2019
.Dt LOADKMAP 1 x68k
.Os
.Sh NAME
.Nm loadkmap
.Nd load and set the x68k console keyboard map
.Sh SYNOPSIS
.Nm loadkmap
.Ar keymapfile
.Sh DESCRIPTION
.Nm
command reads
.Ar keymapfile
and replaces the x68k console keyboard map.
.Sh HISTORY
A
.Nm
utility first appeared in
.Nx 1.4 .
