.\"	$NetBSD: loadkmap.1,v 1.4 1999/03/15 08:22:21 garbled Exp $
.\"
.\" This software is in the Public Domain.
.\" Author: Masaru Oki
.\"
.Dd May 5, 1995
.Dt LOADKMAP 1
.Os
.Sh NAME
.Nm loadkmap
.Nd load and set the x68k console keyboard map.
.Sh SYNOPSIS
.Nm loadkmap
.Ar keymapfile
.Sh DESCRIPTION
.Nm Loadkmap
command reads 
.Ar keymapfile
and replaces the x68k console keyboard map.
