.\"	$NetBSD: palette.1,v 1.6 2001/04/21 14:30:18 wiz Exp $
.\"
.\" This software is in the Public Domain.
.\" Author: Masaru Oki
.\"
.Dd March 5, 1995
.Dt PALETTE 1 x68k
.Os
.Sh NAME
.Nm palette
.Nd manipulate the text screen colormap
.Sh SYNOPSIS
.Nm palette
.Op Ar red green blue Op Ar code
.Sh DESCRIPTION
The
.Nm
utility manipulates the colormap of x68k's console.
The value of the color cell number
.Ar code
is replaced according to the arguments
.Ar red, green, blue
.Po
each value is an integer from
.Li 0
to
.Li 31
.Pc .
.Pp
Each part of the console corresponds to the
.Ar code :
.Bl -tag -width "foreground (default)" -compact
.It background
.Li 0
.It cursor
.Li 1
.It foreground (default)
.Li 7
.El
.Pp
If no arguments are supplied,
.Nm
resets the colormap to the default.
.Sh BUGS
Quite a few.
