.\"	$NetBSD: tvctrl.1,v 1.6 2019/09/01 14:40:07 sevan Exp $
.\"
.\" This software is in the Public Domain.
.\" Author: Masaru Oki
.\"
.Dd September 1, 2019
.Dt TVCTRL 1 x68k
.Os
.Sh NAME
.Nm tvctrl
.Nd control display-TV for X680x0
.Sh SYNOPSIS
.Nm tvctrl
.Ar control_number
.Sh DESCRIPTION
.Nm tvctrl
is a display-TV control program for X680x0.
.Sh HISTORY
A
.Nm
utility first appeared in
.Nx 1.4 .
.Sh BUGS
Errors are not checked.
