#	$NetBSD: Makefile,v 1.3 1999/02/13 02:54:35 lukem Exp $

.include <bsd.own.mk>

.if ${MKSHARE} != "no"
FILES=	svc.conf
FILESDIR=/usr/share/examples/emul/ultrix/etc
.endif
MKOBJ=	no

.include <bsd.prog.mk>
