#	$NetBSD: Makefile,v 1.25 2003/05/15 18:51:18 wiz Exp $

INCSDIR= /usr/include/i386

INCS=	ansi.h aout_machdep.h apmvar.h asm.h atomic.h \
	bioscall.h bootinfo.h bswap.h byte_swap.h bus.h \
	cdefs.h cpu.h cpufunc.h cputypes.h \
	db_machdep.h disklabel.h \
	elf_machdep.h endian.h endian_machdep.h \
	float.h frame.h freebsd_machdep.h \
	gdt.h \
	ibcs2_machdep.h ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intr.h intrdefs.h \
	joystick.h \
	kcore.h \
	limits.h lock.h \
	math.h mcontext.h mtrr.h \
	npx.h \
	param.h pcb.h pccons.h pio.h pmap.h pmc.h proc.h profile.h psl.h \
	pte.h ptrace.h \
	reg.h \
	segments.h setjmp.h signal.h specialreg.h spkr.h stdarg.h \
	svr4_machdep.h sysarch.h \
	trap.h tss.h types.h \
	varargs.h vm86.h vmparam.h

.include <bsd.kinc.mk>
