#	$NetBSD: Makefile,v 1.1.218.1 2016/07/09 20:25:24 skrll Exp $

INCSDIR= /usr/include/ufs/ext2fs

INCS=	ext2fs.h ext2fs_dinode.h ext2fs_dir.h ext2fs_extents.h ext2fs_extern.h

.include <bsd.kinc.mk>
