#	$NetBSD: Makefile,v 1.8 1997/10/19 13:04:24 mrg Exp $
#	from: @(#)Makefile	8.1 (Berkeley) 6/5/93

MAN=	MAKEDEV.8 boot.8 crash.8 drtest.8 format.8 installboot.8
MLINKS=	MAKEDEV.8 makedev.8
MANSUBDIR=/vax

.include <bsd.man.mk>
