#	$NetBSD: Makefile.booters,v 1.3.20.4 2004/11/29 07:24:02 skrll Exp $

.include <bsd.own.mk>

.if ${OBJECT_FMT} == "ELF"

RELOC2BB=	${TOOL_AMIGAELF2BB}

.else

RELOC2BB=	${TOOL_AMIGAAOUT2BB}

.endif

TXLT=		${TOOL_AMIGATXLT}
