#	$NetBSD: Makefile.booters,v 1.6 2005/12/11 12:16:36 christos Exp $

.include <bsd.own.mk>

.if ${OBJECT_FMT} == "ELF"

RELOC2BB=	${TOOL_AMIGAELF2BB}

.else

RELOC2BB=	${TOOL_AMIGAAOUT2BB}

.endif

TXLT=		${TOOL_AMIGATXLT}
