#	$NetBSD: Makefile,v 1.2.8.2 2002/10/18 02:35:18 nathanw Exp $

SUBDIR=	include include/arm26 include/arm32

# XXX VIDC includes are needed by Xarm32vidc
SUBDIR+= iomd
# install footbridge headers.
SUBDIR+= footbridge

.include <bsd.kinc.mk>
