# $NetBSD: Makefile,v 1.3 2003/06/30 18:47:54 wiz Exp $

# $FreeBSD: src/gnu/usr.bin/groff/src/roff/nroff/Makefile,v 1.1 2001/04/17 12:37:13 ru Exp $

DIST_SUBDIR=	src/roff/nroff

SCRIPTS=	nroff
MAN=		nroff.1
CLEANFILES=	${SCRIPTS} ${MAN}

.include <bsd.prog.mk>
