#	$NetBSD: Makefile.xkbcomp,v 1.1 2004/02/09 04:30:05 lukem Exp $

XKBCOMPDIR!=	cd ${NETBSDSRCDIR}/x11/tools/xkbcomp && ${PRINTOBJDIR}
XKBCOMP=	${XKBCOMPDIR}/xkbcomp

${XKBCOMP}:
	(cd ${NETBSDSRCDIR}/x11/tools/xkbcomp && ${MAKE})
