#	$NetBSD: Makefile,v 1.1.1.1.4.2 2004/08/03 10:51:59 skrll Exp $

INCSDIR= /usr/include/dev/vinum

# Only install includes which are used by userland

INCS=	request.h vinumext.h vinumio.h vinumobj.h vinumutil.h \
        statetexts.h vinumhdr.h vinumkw.h vinumstate.h vinumvar.h

.include <bsd.kinc.mk>
