#	$NetBSD: Makefile,v 1.7 2019/01/17 20:47:42 kamil Exp $

.include <bsd.own.mk>

SUBDIR+=	executor
SUBDIR+=	hello
#SUBDIR+=	luahello		# Nothing to build here, only text files
SUBDIR+=	luareadhappy		# Needs an additional Lua script
SUBDIR+=	mapper			# Needs an additional helper program
SUBDIR+=	panic_string		# Crashes the system
SUBDIR+=	ping			# Needs an additional helper program
SUBDIR+=	properties
SUBDIR+=	readhappy
SUBDIR+=	readhappy_mpsafe	# Contains an additional helper program
SUBDIR+=	sysctl

.include <bsd.subdir.mk>
