#	$NetBSD: Makefile,v 1.3 2018/04/13 01:20:27 kamil Exp $

.include <bsd.own.mk>

SUBDIR+=	hello
#SUBDIR+=	luahello	# Nothing to build here, only text files
SUBDIR+=	luareadhappy	# Needs an additional Lua script
SUBDIR+=	ping		# Needs an additional helper program
SUBDIR+=	properties
SUBDIR+=	readhappy
SUBDIR+=	sysctl

.include <bsd.subdir.mk>
