#	$NetBSD: Makefile,v 1.5 2018/04/20 00:06:45 kamil Exp $

.include <bsd.own.mk>

SUBDIR+=	executor
SUBDIR+=	hello
#SUBDIR+=	luahello		# Nothing to build here, only text files
SUBDIR+=	luareadhappy		# Needs an additional Lua script
SUBDIR+=	ping			# Needs an additional helper program
SUBDIR+=	properties
SUBDIR+=	readhappy
SUBDIR+=	readhappy_mpsafe	# Contains an additional helper program
SUBDIR+=	sysctl

.include <bsd.subdir.mk>
