#	$NetBSD: Makefile,v 1.1.1.1 1997/03/14 02:40:32 perry Exp $

BINDIR=	/usr/mdec
PROG=	installboot

MAN=	installboot.8
MANSUBDIR=/i386

CPPFLAGS= -I${.CURDIR}/../lib/crt/bootsect
CFLAGS+= -Wall
#LDSTATIC=-static

.include <bsd.prog.mk>
