#	$NetBSD: bsd.oabi.mk,v 1.2 2013/12/15 18:08:37 joerg Exp $

MLIBDIR=		oabi
.if ${MACHINE_ARCH:M*eb} != ""
ARM_MACHINE_ARCH=	armeb
LD+=			-m armelfb
.else
ARM_MACHINE_ARCH=	arm
LD+=			-m armelf
.endif
LIBC_MACHINE_ARCH=	${ARM_MACHINE_ARCH}
LIBGCC_MACHINE_ARCH=	${ARM_MACHINE_ARCH}
LIBEXECINFO_MACHINE_ARCH=	${ARM_MACHINE_ARCH}
COMMON_MACHINE_ARCH=	${ARM_MACHINE_ARCH}
KVM_MACHINE_ARCH=	${ARM_MACHINE_ARCH}
PTHREAD_MACHINE_ARCH=	${ARM_MACHINE_ARCH}
BFD_MACHINE_ARCH=	${ARM_MACHINE_ARCH}
CSU_MACHINE_ARCH=	${ARM_MACHINE_ARCH}
CRYPTO_MACHINE_CPU=	${ARM_MACHINE_ARCH}
LDELFSO_MACHINE_CPU=	${ARM_MACHINE_ARCH}
GOMP_MACHINE_ARCH=	${ARM_MACHINE_ARCH}

COPTS+=		${ARM_APCS_FLAGS}
CPUFLAGS+=	${ARM_APCS_FLAGS}
LDADD+=		${ARM_APCS_FLAGS}
LDFLAGS+=	${ARM_APCS_FLAGS}
MKDEPFLAGS+=	${ARM_APCS_FLAGS}

.include "${.PARSEDIR}/../../Makefile.compat"
