/* $NetBSD: namespace.h,v 1.24 2024/07/16 14:52:50 riastradh Exp $ */

#define acos _acos
#define acosf _acosf
#define acoshl _acoshl
#define acosl _acosl
#define asin _asin
#define asinf _asinf
#define asinhl _asinhl
#define asinl _asinl
#define atan _atan
#define atan2 _atan2
#define atan2f _atan2f
#define atan2l _atan2l
#define atanf _atanf
#define atanhl _atanhl
#define atanl _atanl
#define casin _casin
#define casinf _casinf
#define casinl _casinl
#define catan _catan
#define catanf _catanf
#define catanl _catanl
#define cbrtl _cbrtl
#define ceill _ceill
#define copysignl _copysignl
#define cos _cos
#define cosf _cosf
#define cosh _cosh
#define coshf _coshf
#define coshl _coshl
#define cosl _cosl
#define cospi _cospi
#define cospif _cospif
#define cospil _cospil
#define erfcl _erfcl
#define erfl _erfl
#define exp _exp
#define exp2l _exp2l
#define expf _expf
#define expl _expl
#define expm1l _expm1l
#define feclearexcept _feclearexcept
#define fedisableexcept _fedisableexcept
#define feenableexcept _feenableexcept
#define fegetenv _fegetenv
#define fegetexcept _fegetexcept
#define fegetexceptflag _fegetexceptflag
#define fegetround _fegetround
#define feholdexcept _feholdexcept
#define feraiseexcept _feraiseexcept
#define fesetenv _fesetenv
#define fesetexceptflag _fesetexceptflag
#define fesetround _fesetround
#define fetestexcept _fetestexcept
#define feupdateenv _feupdateenv
#define finite _finite
#define finitef _finitef
#define floorl _floorl
#define fmodl _fmodl
#define hypot _hypot
#define hypotf _hypotf
#define hypotl _hypotl
#define lgammal _lgammal
#define lgammal_r _lgammal_r
#define log _log
#define log10 _log10
#define log10l _log10l
#define log10f _log10f
#define log1p _log1p
#define log1pl _log1pl
#define log1pf _log1pf
#define log2 _log2
#define log2l _log2l
#define log2f _log2f
#define logf _logf
#define logl _logl
#define modfl _modfl
#define powl _powl
#define remquo _remquo
#define remquof _remquof
#define remquol _remquol
#define roundl _roundl
#define scalbln _scalbln
#define scalblnf _scalblnf
#define scalblnl _scalblnl
#define scalbn _scalbn
#define scalbnf _scalbnf
#define scalbnl _scalbnl
#define sin _sin
#define sincos _sincos
#define sincosf _sincosf
#define sincosl _sincosl
#define sinf _sinf
#define sinh _sinh
#define sinhf _sinhf
#define sinhl _sinhl
#define sinl _sinl
#define sinpi _sinpi
#define sinpif _sinpif
#define sinpil _sinpil
#define sqrtl _sqrtl
#define tan _tan
#define tanf _tanf
#define tanhl _tanhl
#define tanl _tanl
#define tanpi _tanpi
#define tanpif _tanpif
#define tanpil _tanpil
#define tgammal _tgammal
#define truncl _truncl
