#	$NetBSD: Makefile,v 1.1 1996/08/22 20:18:27 explorer Exp $

# MISSING:  fifo (prolly needs a syscall layer as well)
#           deadfs
SUBDIR=	fdesc kernfs nullfs portal procfs umapfs union

.include <bsd.subdir.mk>
