.\"	$NetBSD: worms.6,v 1.18 2023/04/26 22:58:09 kre Exp $
.\"
.\" Copyright (c) 1989, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)worms.6	8.1 (Berkeley) 5/31/93
.\"
.Dd April 26, 2023
.Dt WORMS 6
.Os
.Sh NAME
.Nm worms
.Nd animate worms on a display terminal
.Sh SYNOPSIS
.Nm
.Op Fl CfHrt
.Op Fl d Ar delay
.Op Fl l Ar length
.Op Fl n Ar number
.Op Fl S Ar seed
.Sh DESCRIPTION
.Nm
is a
.Ux
version of the DEC-2136 program
.Dq worms .
.Pp
The options are as follows:
.Bl -compact -tag -width Fl
.Pp
.It Fl C
Use colours, if available, to make the worms easier to distinguish.
.Pp
.It Fl d Ar delay
Specifies a
.Ar delay ,
in milliseconds, between each update.
This is useful for fast terminals.
Reasonable values are around 20-200;
the default is 20.
.Pp
.It Fl f
Makes a
.Dq field
for the worm(s) to eat.
.Pp
.It Fl H
Display the head of the worm differently than its body.
.Pp
.It Fl l Ar length
.It Fl l Ar min Ns \(mi Ns Ar max
Specifies the
.Ar length
of each worm; the default is 16, the minimum is 2.
In the second form, worm lengths are randomly chosen
between
.Ar min
.Pq which must be at least 2
and
.Ar max .
The
.Ar max
worm length will be reduced if required by the screen
size and the
.Ar number
of worms selected.
This option overrides any earlier
.Fl r .
.Pp
.It Fl n Ar number
Specifies the
.Ar number
of worms; the default is 3.
There must be at least one.
.Pp
.It Fl r
Use random lengths for the worms, within a range of
sizes chosen to suit the screen size.
Note this option overrides any earlier
.Fl l .
.Pp
.It Fl S Ar seed
Provide an integer
.Ar seed
for the random number generator.
Specifying zero (0, the default) causes a random seed to be used.
.Pp
.It Fl t
Makes each worm leave a trail behind it.
.El
.Pp
The maximum
.Ar length ,
and
.Ar number ,
of worms depends upon the screen size, though the
.Ar length
can never exceed 1024.
If the screen is particularly small, even the defaults
for those may be too large.
Screens with less than 3 rows or columns cannot be handled,
nor can ones with insufficient total space.
