# $NetBSD: MAKEDEV.conf,v 1.1 2026/07/19 01:48:20 thorpej Exp $

all_md)
	makedev wd0 wd1 wd2 wd3 wd4 wd5 wd6 wd7
	makedev dk0 dk1 dk2 dk3 dk4 dk5 dk6 dk7
	makedev openfirm
	;;

ramdisk)
	makedev std bpf md0 md1 wd0 wd1 wd2 wd3
	makedev dk0 dk1 dk2 dk3 dk4 dk5 dk6 dk7
	makedev opty
	makedev drvctl random
	;;
