#	$NetBSD: Makefile,v 1.1.28.1 2020/04/13 08:06:02 martin Exp $
#
# Makefile for evbarm
#

MENUS_MD= menus.md.${SYSINSTLANG}
MSG_MD= msg.md.${SYSINSTLANG} msg.mbr.${SYSINSTLANG}
MD_OPTIONS=	AOUT2ELF
NO_MBR=no

.include "../../Makefile.inc"
