#	$NetBSD: Makefile,v 1.1.36.1 2009/05/13 19:19:49 jym Exp $

PROG=	getextattr

LINKS+=	${BINDIR}/getextattr ${BINDIR}/setextattr
LINKS+=	${BINDIR}/getextattr ${BINDIR}/rmextattr
LINKS+=	${BINDIR}/getextattr ${BINDIR}/lsextattr

MLINKS+= getextattr.1 setextattr.1
MLINKS+= getextattr.1 rmextattr.1
MLINKS+= getextattr.1 lsextattr.1

.include <bsd.prog.mk>
