#	$NetBSD: Makefile,v 1.6.2.1 2002/11/03 19:50:27 he Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

PROG=	whatis
SRCS=	whatis.c manconf.c
.PATH:	${.CURDIR}/../man
CPPFLAGS+=-I${.CURDIR}/..

.include <bsd.prog.mk>
