#	$NetBSD: Makefile.inc,v 1.5.2.1 1999/04/09 21:31:09 fair Exp $
#
#	etc.arm32/Makefile.inc -- arm32-specific etc Makefile targets
#

# Set this for any kernels beyond GENERIC you want to include
# in the distribution.
EXTRA_KERNELS+= A7000 CATS EBSA285 RISCPC SHARK
