#	$NetBSD: Makefile,v 1.3.16.2 2017/12/03 11:39:15 jdolecek Exp $
#

LIB=	rumpkern_sysproxy
COMMENT=Remote system call support (rump kernel as a server)

SRCS=	sysproxy.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
