#	$NetBSD: Makefile,v 1.1.1.2 2001/04/19 14:33:07 wiz Exp $

.include "../../Makefile.path"

.PATH:		${IIDIST}/font/devX100

DEVICE=		X100
FONTFILES=	CB CBI CI CR HB HBI HI HR NB NBI NI NR S TB TBI TI TR DESC

MKOBJ=		no

clean cleandir distclean:

.include "../Makefile.dev"
