#	$NetBSD: Makefile,v 1.9 2002/09/19 03:09:38 lukem Exp $

NOOBJ=		# defined

.include "../../Makefile.path"

.PATH:		${IDIST}/font/devX100

DEVICE=		X100
FONTFILES=	CB CBI CI CR HB HBI HI HR NB NBI NI NR S TB TBI TI TR DESC

clean cleandir distclean:

.include "../Makefile.dev"
