#	$NetBSD: Makefile,v 1.6 1999/09/07 21:52:06 soren Exp $

INCSDIR= /usr/include/dev/mii

INCS=	icsphyreg.h inphyreg.h iophyreg.h lxtphyreg.h mii.h miivar.h \
	nsphyreg.h qsphyreg.h tlphyreg.h tlphyvar.h tqphyreg.h

.include <bsd.kinc.mk>
