#	$NetBSD: Makefile.miidevs,v 1.4 2021/06/29 21:03:36 pgoyette Exp $
#
# As per tron@NetBSD.org, the proper procedure is (adapted from dev/hdaudio)
#
# 1.) Change "src/sys/dev/mii/miidevs".
# 2.) Commit "src/sys/dev/mii/miidevs".
# 3.) Execute "make -f Makefile.miidevs" in "src/sys/dev/mii".
# 4.) Ensure that the value of MII_MAX_DESCR_LEN is at least as large as
#     the values reported.  If necessary, update "src/sys/dev/mii/miivar.h"
#     and bump the kernel version in "src/sys/sys/param/h".
# 5.) Commit "src/sys/dev/mii/miidevs.h" and
#     "src/sys/dev/mii/miidevs_data.h"; if you changed them, also
#     commit "src/sys/dev/mii/miivar.h" and "src/sys/sys/param.h".

.include <bsd.own.mk>

miidevs.h miidevs_data.h: ${.CURDIR}/../devlist2h.awk miidevs
	/bin/rm -f miidevs.h miidevs_data.h
	${TOOL_AWK} -f ${.ALLSRC}
