#	$NetBSD: Makefile,v 1.1.2.2 2014/08/10 07:00:27 tls Exp $
#
# Makefile for luna68k
#

MD_OPTIONS=	AOUT2ELF	# Who will update from NetBSD/luna68k 1.5!?

LANGUAGES=	# won't bother to prepare translations

.include "../../Makefile.inc"
