# $NetBSD: Makefile,v 1.2 2003/06/30 18:47:51 wiz Exp $

# $FreeBSD: src/gnu/usr.bin/groff/src/preproc/Makefile,v 1.2 2002/10/29 14:56:06 ru Exp $

SUBDIR=		eqn grn html pic refer soelim tbl

.include <bsd.subdir.mk>
