#	$NetBSD: Makefile,v 1.1 2007/03/06 21:57:06 bouyer Exp $
CDBASE=		ibmnwscd		# gives ${CDBASE}.iso
CDRELEASE=	true			# include $RELEASEDIR/$MACHINE

.include "${.CURDIR}/../../../common/Makefile.bootcd"
