#	$NetBSD: Makefile,v 1.4.32.1 2009/01/15 03:24:09 snj Exp $

.include <bsd.own.mk>

NOOBJ=	# defined
NOMAN=	# defined

SUBDIR=	ctype monetary numeric time messages

FILES=		locale.alias
FILESOWN=	${LOCALEOWN}
FILESGRP=	${LOCALEGRP}
FILESMODE=	${LOCALEMODE}
FILESDIR=	${LOCALEDIR}

.include <bsd.prog.mk>
.include <bsd.subdir.mk>
