#	$NetBSD: Makefile,v 1.4 1999/01/21 08:20:25 mycroft Exp $

KDIR=	/sys/arch/arm32/include
INCSDIR= /usr/include/arm32

INCS=	ansi.h aout_machdep.h asm.h beep.h bootconfig.h bswap.h bus.h cdefs.h \
	conf.h cpu.h cpufunc.h cpus.h db_machdep.h disklabel.h \
	disklabel_acorn.h disklabel_mbr.h endian.h float.h fp.h frame.h \
	ieee.h ieeefp.h iic.h intr.h io.h ipkdb.h irqhandler.h joystick.h \
	katelib.h kbd.h limits.h mouse.h \
	param.h pcb.h pmap.h proc.h profile.h psl.h pte.h ptrace.h reg.h \
	rtc.h setjmp.h signal.h stdarg.h sysarch.h trap.h types.h undefined.h \
	varargs.h vconsole.h vidc.h vmparam.h

.include <bsd.kinc.mk>
