#	$NetBSD: Makefile,v 1.1.6.2 2010/08/17 06:48:00 uebayasi Exp $
#

# zlib.c is logically in sys/net
.PATH:	${.CURDIR}/../../../../net

LIB=	rumpkern_z

SRCS=	zlib.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
