#	$NetBSD: Makefile,v 1.2.12.2 2001/04/21 17:46:13 bouyer Exp $

#SUBDIR= common freebsd hpux ibcs2 linux m68k4k osf1 ossaudio sunos svr2 \
#	ultrix netbsd32 sunos32

KDIR=	/sys/compat
#INCSDIR= /usr/include/compat

.include <bsd.kinc.mk>
