#	$NetBSD: Makefile,v 1.3.2.1 2001/04/09 01:55:28 nathanw Exp $

#SUBDIR= common freebsd hpux ibcs2 linux m68k4k osf1 ossaudio sunos svr2 \
#	ultrix netbsd32 sunos32

KDIR=	/sys/compat
#INCSDIR= /usr/include/compat

.include <bsd.kinc.mk>
