#	$NetBSD: Makefile,v 1.4 2024/04/24 11:29:34 nia Exp $

SUBDIR=
SUBDIR+=	bootcd
SUBDIR+=	bootcd-com
SUBDIR+=	installdvd
SUBDIR+=	installcd

TARGETS+=       release iso_image

.include <bsd.subdir.mk>
