#	from: @(#)Makefile	5.16.1.1 (Berkeley) 5/7/91
#	$Id: Makefile,v 1.4 1993/10/30 13:01:18 mycroft Exp $

MAN3=	assert.0 bitstring.0 end.0 intro.0 stdarg.0
MLINKS+=end.3 edata.3 end.3 etext.3
MLINKS+=stdarg.3 varargs.3 stdarg.3 va_arg.3 stdarg.3 va_end.3 \
	stdarg.3 va_start.3

.include <bsd.prog.mk>
