#	$NetBSD: Makefile,v 1.2 2008/05/10 19:22:17 skrll Exp $

.include "${.CURDIR}/../Makefile.cdrom"

CDBASE=		hp700cd			# gives ${CDBASE}.iso
CDRELEASE=	true			# include $RELEASEDIR/$MACHINE

.include "${.CURDIR}/../../../common/Makefile.bootcd"
