/* This file is automatically generated.  DO NOT EDIT! */
/* Generated from: 	NetBSD: mknative-gcc,v 1.17 2006/05/15 22:03:03 mrg Exp  */
/* and from: NetBSD: mknative.common,v 1.6 2006/05/15 21:01:42 mrg Exp  */

#ifndef GCC_BCONFIG_H
#define GCC_BCONFIG_H
#include "auto-build.h"
#ifdef IN_GCC
# include "ansidecl.h"
#endif
#endif /* GCC_BCONFIG_H */
