#	$NetBSD: Makefile,v 1.34 1999/03/15 23:32:56 thorpej Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/4/93

SUBDIR=	atrun comsat fingerd ftpd getNAME getty identd ld.aout_so \
	ld.elf_so lfs_cleanerd mail.local makekey makewhatis rexecd \
	rlogind rmail rshd rpc.rquotad rpc.rstatd rpc.rusersd rpc.rwalld \
	rpc.sprayd talkd telnetd tftpd uucpd

.include <bsd.subdir.mk>
