#	from: @(#)Makefile	5.7 (Berkeley) 4/1/91
#	$Id: Makefile,v 1.7 1993/11/23 04:32:01 cgd Exp $

SUBDIR=	comsat crond elvispreserve fingerd ftpd getNAME \
	getty mail.local makekey rarpd rexecd rlogind rshd rpc.rstatd \
	rpc.rusersd rpc.rwalld talkd telnetd tftpd uucpd

.include <bsd.subdir.mk>
