#	$NetBSD: Makefile,v 1.1 2001/10/13 06:10:52 jmc Exp $

HOSTPROGNAME=	msgc
HOST_SRCDIR=	usr.bin/msgc
HOSTFILES=msg_sys.def
HOST_FILESDIR=${TOOLDIR}/share/misc

.include "${.CURDIR}/../Makefile.host"

${TIMESTAMP}: ${SRCS}
