#	$NetBSD: Makefile,v 1.32 1997/10/11 08:22:37 mycroft Exp $
#	from: @(#)Makefile	5.1 (Berkeley) 2/12/91

MAN=	apm.4 autoconf.4 busmouse.4 com.4 console.4 ed.4 fdc.4	\
	ie.4 intro.4 joy.4 le.4 lms.4 lpt.4 mem.4 mms.4 npx.4 \
	pms.4 pcvt.4 speaker.4 wd.4 
MLINKS=	mem.4 kmem.4
MANSUBDIR=/i386

.include <bsd.man.mk>
