#	from: @(#)Makefile	5.1 (Berkeley) 2/12/91
#	$Id: Makefile,v 1.8 1994/02/20 09:41:41 cgd Exp $

MAN4=	intro.0 autoconf.0
MAN4+=	com.0 cy.0 ed.0 lms.0 lpt.0 mem.0 mms.0 npx.0 pms.0 
MAN4+=	speaker.0 ep.0
MLINKS=	mem.4 kmem.4
MANSUBDIR=/i386

.include <bsd.prog.mk>
