#	@(#)Makefile	5.1 (Berkeley) 3/22/91
#	$NetBSD: Makefile,v 1.9 2002/01/06 07:44:11 mrg Exp $

MAN=	MAKEDEV.8 boot.8 installboot.8 binstall.8
MLINKS=	MAKEDEV.8 makedev.8
MANSUBDIR=/sparc

.include <bsd.man.mk>
