/* $NetBSD: omap2_spireg.h,v 1.1.2.1 2013/05/11 17:19:41 khorben Exp $ */

/*
 * Texas Instruments OMAP2/3 Multichannel SPI driver.
 *
 * Copyright (c) 2013 The NetBSD Foundation, Inc.
 * All rights reserved.
 *
 * This code is derived from software contributed to The NetBSD Foundation
 * by Pierre Pronchery (khorben@defora.org).
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef _OMAP2_SPIREG_H
#define _OMAP2_SPIREG_H

/*
 * Multichannel SPI Controller registers
 */

#define OMAP2_MCSPI_REVISION			0x00
#define  OMAP2_MCSPI_REV_MAJ_MASK		__BITS(4,7)
#define  OMAP2_MCSPI_REV_MAJ_SHIFT		4
#define  OMAP2_MCSPI_REV_MIN_MASK		__BITS(0,3)
#define  OMAP2_MCSPI_REV_MIN_SHIFT		0

#define OMAP2_MCSPI_SYSCONFIG			0x10
#define  OMAP2_MCSPI_SYSCONFIG_CLOCKACTIVITY	__BITS(8,9)
#define  OMAP2_MCSPI_SYSCONFIG_SIDLEMODE	__BITS(3,4)
#define  OMAP2_MCSPI_SYSCONFIG_ENAWAKEUP	__BIT(2)
#define  OMAP2_MCSPI_SYSCONFIG_SOFTRESET	__BIT(1)
#define  OMAP2_MCSPI_SYSCONFIG_AUTOIDLE		__BIT(0)

#define OMAP2_MCSPI_SYSSTATUS			0x14
#define  OMAP2_MCSPI_SYSSTATUS_RESETDONE	__BIT(0)

#define OMAP2_MCSPI_IRQSTATUS			0x18
#define  OMAP2_MCSPI_IRQSTATUS_EOW		__BIT(16)
#define  OMAP2_MCSPI_IRQSTATUS_RX3_FULL		__BIT(14)
#define  OMAP2_MCSPI_IRQSTATUS_TX3_UNDERFLOW	__BIT(13)
#define  OMAP2_MCSPI_IRQSTATUS_TX3_EMPTY	__BIT(12)
#define  OMAP2_MCSPI_IRQSTATUS_RX2_FULL		__BIT(10)
#define  OMAP2_MCSPI_IRQSTATUS_TX2_UNDERFLOW	__BIT(9)
#define  OMAP2_MCSPI_IRQSTATUS_TX2_EMPTY	__BIT(8)
#define  OMAP2_MCSPI_IRQSTATUS_RX1_FULL		__BIT(6)
#define  OMAP2_MCSPI_IRQSTATUS_TX1_UNDERFLOW	__BIT(5)
#define  OMAP2_MCSPI_IRQSTATUS_TX1_EMPTY	__BIT(4)
#define  OMAP2_MCSPI_IRQSTATUS_RX0_OVERFLOW	__BIT(3)
#define  OMAP2_MCSPI_IRQSTATUS_RX0_FULL		__BIT(2)
#define  OMAP2_MCSPI_IRQSTATUS_TX0_UNDERFLOW	__BIT(1)
#define  OMAP2_MCSPI_IRQSTATUS_TX0_EMPTY	__BIT(0)

#define OMAP2_MCSPI_IRQENABLE			0x1c
#define  OMAP2_MCSPI_IRQENABLE_EOWKE		__BIT(17)
#define  OMAP2_MCSPI_IRQENABLE_WKE		__BIT(16)
#define  OMAP2_MCSPI_IRQENABLE_RX3_FULL		__BIT(14)
#define  OMAP2_MCSPI_IRQENABLE_TX3_UNDERFLOW	__BIT(13)
#define  OMAP2_MCSPI_IRQENABLE_TX3_EMPTY	__BIT(12)
#define  OMAP2_MCSPI_IRQENABLE_RX2_FULL		__BIT(10)
#define  OMAP2_MCSPI_IRQENABLE_TX2_UNDERFLOW	__BIT(9)
#define  OMAP2_MCSPI_IRQENABLE_TX2_EMPTY	__BIT(8)
#define  OMAP2_MCSPI_IRQENABLE_RX1_FULL		__BIT(6)
#define  OMAP2_MCSPI_IRQENABLE_TX1_UNDERFLOW	__BIT(5)
#define  OMAP2_MCSPI_IRQENABLE_TX1_EMPTY	__BIT(4)
#define  OMAP2_MCSPI_IRQENABLE_RX0_OVERFLOW	__BIT(3)
#define  OMAP2_MCSPI_IRQENABLE_RX0_FULL		__BIT(2)
#define  OMAP2_MCSPI_IRQENABLE_TX0_UNDERFLOW	__BIT(1)
#define  OMAP2_MCSPI_IRQENABLE_TX0_EMPTY	__BIT(0)

#define OMAP2_MCSPI_WAKEUPENABLE		0x20

#define OMAP2_MCSPI_SYST			0x24
#define  OMAP2_MCSPI_SYST_SSB			__BIT(11)
#define  OMAP2_MCSPI_SYST_SPIENDIR		__BIT(10)
#define  OMAP2_MCSPI_SYST_SPIDATDIR1		__BIT(9)
#define  OMAP2_MCSPI_SYST_SPIDATDIR0		__BIT(8)
#define  OMAP2_MCSPI_SYST_WAKD			__BIT(7)
#define  OMAP2_MCSPI_SYST_SPICLK		__BIT(6)
#define  OMAP2_MCSPI_SYST_SPIDAT_1		__BIT(5)
#define  OMAP2_MCSPI_SYST_SPIDAT_0		__BIT(4)
#define  OMAP2_MCSPI_SYST_SPIEN_3		__BIT(3)
#define  OMAP2_MCSPI_SYST_SPIEN_2		__BIT(2)
#define  OMAP2_MCSPI_SYST_SPIEN_1		__BIT(1)
#define  OMAP2_MCSPI_SYST_SPIEN_0		__BIT(0)

#define OMAP2_MCSPI_MODULCTRL			0x28
#define  OMAP2_MCSPI_MODULCTRL_SYSTEM_TEST	__BIT(3)
#define  OMAP2_MCSPI_MODULCTRL_MS		__BIT(2)
#define  OMAP2_MCSPI_MODULCTRL_SINGLE		__BIT(0)

#define OMAP2_MCSPI_CHXCONF(channel)		(0x2c + (channel * 0x14))
#define OMAP2_MCSPI_CH0CONF			OMAP2_MCSPI_CHXCONF(0)
#define OMAP2_MCSPI_CH1CONF			OMAP2_MCSPI_CHXCONF(1)
#define OMAP2_MCSPI_CH2CONF			OMAP2_MCSPI_CHXCONF(2)
#define OMAP2_MCSPI_CH3CONF			OMAP2_MCSPI_CH0CONF(3)
#define  OMAP2_MCSPI_CHXCONF_FFER		__BIT(28)
#define  OMAP2_MCSPI_CHXCONF_FFEW		__BIT(27)
#define  OMAP2_MCSPI_CHXCONF_TCS		__BITS(25,26)
#define  OMAP2_MCSPI_CHXCONF_SBE		__BIT(23)
#define  OMAP2_MCSPI_CHXCONF_TRM		__BITS(12,13)
#define  OMAP2_MCSPI_CHXCONF_TRM_SHIFT		12
#define  OMAP2_MCSPI_CHXCONF_WL			__BITS(7,11)
#define  OMAP2_MCSPI_CHXCONF_WL_SHIFT		7
#define  OMAP2_MCSPI_CHXCONF_EPOL		__BIT(6)
#define  OMAP2_MCSPI_CHXCONF_CLKD		__BITS(2,5)
#define  OMAP2_MCSPI_CHXCONF_CLKD_SHIFT		2
#define  OMAP2_MCSPI_CHXCONF_POL		__BIT(1)
#define  OMAP2_MCSPI_CHXCONF_PHA		__BIT(0)

#define OMAP2_MCSPI_CHXSTAT(channel)		(0x30 + ((channel) * 0x14))
#define OMAP2_MCSPI_CH0STAT			OMAP2_MCSPI_CHXSTAT(0)
#define OMAP2_MCSPI_CH1STAT			OMAP2_MCSPI_CHXSTAT(1)
#define OMAP2_MCSPI_CH2STAT			OMAP2_MCSPI_CHXSTAT(2)
#define OMAP2_MCSPI_CH3STAT			OMAP2_MCSPI_CHXSTAT(3)
# define OMAP2_MCSPI_CHXSTAT_EOT		__BIT(2)
# define OMAP2_MCSPI_CHXSTAT_TXS		__BIT(1)
# define OMAP2_MCSPI_CHXSTAT_RXS		__BIT(0)

#define OMAP2_MCSPI_CHXCTRL(channel)		(0x34 + ((channel) * 0x14))
#define OMAP2_MCSPI_CH0CTRL			OMAP2_MCSPI_CHXCTRL(0)
#define OMAP2_MCSPI_CH1CTRL			OMAP2_MCSPI_CHXCTRL(1)
#define OMAP2_MCSPI_CH2CTRL			OMAP2_MCSPI_CHXCTRL(2)
#define OMAP2_MCSPI_CH3CTRL			OMAP2_MCSPI_CHXCTRL(3)
#define  OMAP2_MCSPI_CHXCTRL_EN			__BIT(0)

#define OMAP2_MCSPI_TX(channel)			(0x38 + ((channel) * 0x14))
#define OMAP2_MCSPI_TX0				OMAP2_MCSPI_TX(0)
#define OMAP2_MCSPI_TX1				OMAP2_MCSPI_TX(1)
#define OMAP2_MCSPI_TX2				OMAP2_MCSPI_TX(2)
#define OMAP2_MCSPI_TX3				OMAP2_MCSPI_TX(3)

#define OMAP2_MCSPI_RX(channel)			(0x3c + (channel * 0x14))
#define OMAP2_MCSPI_RX0				OMAP2_MCSPI_RX(0)
#define OMAP2_MCSPI_RX1				OMAP2_MCSPI_RX(1)
#define OMAP2_MCSPI_RX2				OMAP2_MCSPI_RX(2)
#define OMAP2_MCSPI_RX3				OMAP2_MCSPI_RX(3)

#define OMAP2_MCSPI_XFERLEVEL			0x7c
#define  OMAP2_MCSPI_XFERLEVEL_WCNT		__BITS(16,31)
#define  OMAP2_MCSPI_XFERLEVEL_AFL		__BITS(8,13)
#define  OMAP2_MCSPI_XFERLEVEL_AEL		__BITS(0,5)

#endif /* !_OMAP2_SPIREG_H */
