#	$NetBSD: Makefile,v 1.2 1998/09/27 17:22:08 lukem Exp $

.if !defined(NOSHARE)
FILES=	SVR4_MAKEDEV netconfig nsswitch.conf
FILESDIR=/usr/share/examples/emul/svr4/etc
.endif
NOOBJ=	noobj

.include <bsd.prog.mk>
