#	$NetBSD: Makefile,v 1.13 1997/09/26 19:53:30 christos Exp $

WARNS?=	1
PROG=	pppstats
SRCS=	pppstats.c
MAN=	pppstats.8
BINDIR=	/usr/sbin
CFLAGS+=	-Wall -Wstrict-prototypes -Wmissing-prototypes

.include "../../Makefile.inc"
.include <bsd.prog.mk>
