#	$NetBSD: Makefile,v 1.1.1.2 1997/05/17 21:27:53 christos Exp $

PROG=	pppstats
SRCS=	pppstats.c
MAN=	pppstats.8
BINDIR=	/usr/sbin
CFLAGS+=	-Wall -Wstrict-prototypes -Wmissing-prototypes -Dlint

.include <bsd.prog.mk>
