#	$NetBSD: Makefile,v 1.1 2010/12/05 16:11:16 pooka Exp $
#

.PATH:  ${.CURDIR}/../../../../miscfs/nullfs

LIB=	rumpfs_null

SRCS=	null_vfsops.c null_vnops.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
