# $NetBSD: Makefile,v 1.3 2003/06/30 18:47:56 wiz Exp $

# $FreeBSD: src/gnu/usr.bin/groff/src/utils/pfbtops/Makefile,v 1.1 2001/04/17 12:37:17 ru Exp $

DIST_SUBDIR=	src/utils/pfbtops

PROG=		pfbtops
DPADD+=		${LIBGROFF}
LDADD+=		${LIBGROFF}
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
