#	$NetBSD: Makefile,v 1.1.6.2 2014/05/22 11:41:14 yamt Exp $
#
# Public Domain.
#

.PATH:	${.CURDIR}/../../../../external/bsd/sljit/sljit \
	${.CURDIR}/../../../../external/bsd/sljit/dist/sljit_src

LIB=	rumpkern_sljit

SRCS=	sljitLir.c sljit_mod.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
