#	$NetBSD: Makefile,v 1.1.32.1 2017/12/03 11:38:48 jdolecek Exp $

.include "../Makefile.inc"

.PATH:	${S}/netinet

KMOD=	accf_dataready
IOCONF=	accf_data.ioconf
SRCS=	accf_data.c

.include <bsd.kmodule.mk>
