/* $NetBSD: byte_swap.h,v 1.11 2013/11/10 19:52:01 jmcneill Exp $ */

/*
 * Automatically generated by genheaders.sh on Sun Nov 10 15:47:57 AST 2013
 * Do not modify directly!
 */
#ifndef _USERMODE_BYTE_SWAP_H
#define _USERMODE_BYTE_SWAP_H

#if defined(__i386__)
#include "../../i386/include/byte_swap.h"
#elif defined(__x86_64__)
#include "../../amd64/include/byte_swap.h"
#elif defined(__arm__)
#include "../../arm/include/byte_swap.h"
#else
#error port me
#endif

#endif
