/* $NetBSD: cdefs.h,v 1.5.10.1 2014/05/18 17:45:28 rmind Exp $ */

/*
 * Automatically generated by genheaders.sh on Sun Nov 10 15:47:58 AST 2013
 * Do not modify directly!
 */
#ifndef _USERMODE_CDEFS_H
#define _USERMODE_CDEFS_H

#if defined(__i386__)
#include "../../i386/include/cdefs.h"
#elif defined(__x86_64__)
#include "../../amd64/include/cdefs.h"
#elif defined(__arm__)
#include "../../arm/include/cdefs.h"
#else
#error port me
#endif

#endif
