/* $NetBSD: elf_machdep.h,v 1.11 2013/11/10 19:52:01 jmcneill Exp $ */

/*
 * Automatically generated by genheaders.sh on Sun Nov 10 15:47:57 AST 2013
 * Do not modify directly!
 */
#ifndef _USERMODE_ELF_MACHDEP_H
#define _USERMODE_ELF_MACHDEP_H

#if defined(__i386__)
#include "../../i386/include/elf_machdep.h"
#elif defined(__x86_64__)
#include "../../amd64/include/elf_machdep.h"
#elif defined(__arm__)
#include "../../arm/include/elf_machdep.h"
#else
#error port me
#endif
#ifdef ELF_MD_PROBE_FUNC
#undef ELF_MD_PROBE_FUNC
#endif

#endif
