/* $NetBSD: endian_machdep.h,v 1.8 2012/02/02 11:12:40 reinoud Exp $ */

/*
 * Automatically generated by genheaders.sh on Fri Jan 27 08:34:26 CET 2012
 * Do not modify directly!
 */
#ifndef _USERMODE_ENDIAN_MACHDEP_H
#define _USERMODE_ENDIAN_MACHDEP_H

#if defined(__i386__)
#include "../../i386/include/endian_machdep.h"
#elif defined(__x86_64__)
#include "../../amd64/include/endian_machdep.h"
#else
#error port me
#endif

#endif
