/* $NetBSD: endian_machdep.h,v 1.4.2.1 2012/04/17 00:06:59 yamt Exp $ */

/*
 * Automatically generated by genheaders.sh on Sun Feb  5 18:39:34 CET 2012
 * Do not modify directly!
 */
#ifndef _USERMODE_ENDIAN_MACHDEP_H
#define _USERMODE_ENDIAN_MACHDEP_H

#if defined(__i386__)
#include "../../i386/include/endian_machdep.h"
#elif defined(__x86_64__)
#include "../../amd64/include/endian_machdep.h"
#else
#error port me
#endif

#endif
