/* $NetBSD: int_limits.h,v 1.7 2012/01/14 21:21:48 reinoud Exp $ */

/*
 * Automatically generated by ./genheaders.sh on Sat Jan 14 22:20:59 CET 2012
 * Do not modify directly!
 */
#ifndef _USERMODE_INT_LIMITS_H
#define _USERMODE_INT_LIMITS_H

#if defined(__i386__)
#include "../../i386/include/int_limits.h"
#elif defined(__x86_64__)
#include "../../amd64/include/int_limits.h"
#else
#error port me
#endif

#endif
