/* $NetBSD: int_types.h,v 1.4 2011/09/08 10:49:57 jmcneill Exp $ */

/*
 * Automatically generated by genheaders.sh on Thu Sep  8 06:50:17 EDT 2011
 * Do not modify directly!
 */
#ifndef _USERMODE_INT_TYPES_H
#define _USERMODE_INT_TYPES_H

#if defined(__i386__)
#include "../../i386/include/int_types.h"
#elif defined(__x86_64__)
#include "../../amd64/include/int_types.h"
#else
#error port me
#endif

#endif
