/* $NetBSD: param.h,v 1.6 2012/01/08 18:05:43 jmcneill Exp $ */

/*
 * Automatically generated by genheaders.sh on Sat Jan  7 19:13:27 EST 2012
 * Do not modify directly!
 */
#ifndef _USERMODE_PARAM_H
#define _USERMODE_PARAM_H

#if defined(__i386__)
#include "../../i386/include/param.h"
#elif defined(__x86_64__)
#include "../../amd64/include/param.h"
#else
#error port me
#endif
#undef UPAGES
#define UPAGES 6
#undef USPACE
#define USPACE (PAGE_SIZE*UPAGES)

#endif
