/* $NetBSD: param.h,v 1.7 2012/01/14 17:36:32 reinoud Exp $ */

/*
 * Automatically generated by ./genheaders.sh on Sat Jan 14 12:29:09 CET 2012
 * Do not modify directly!
 */
#ifndef _USERMODE_PARAM_H
#define _USERMODE_PARAM_H

#if defined(__i386__)
#include "../../i386/include/param.h"
#elif defined(__x86_64__)
#include "../../amd64/include/param.h"
#else
#error port me
#endif
#undef UPAGES
#define UPAGES 7
#undef USPACE
#define USPACE (PAGE_SIZE*UPAGES)

#endif
