/* $NetBSD: ptrace.h,v 1.5 2011/09/03 14:23:50 jmcneill Exp $ */

/*
 * Automatically generated by genheaders.sh on Sat Sep  3 10:13:14 EDT 2011
 * Do not modify directly!
 */
#ifndef _USERMODE_PTRACE_H
#define _USERMODE_PTRACE_H

#if defined(__i386__)
#include "../../i386/include/ptrace.h"
#elif defined(__x86_64__)
#include "../../amd64/include/ptrace.h"
#else
#error port me
#endif
#undef __HAVE_PTRACE_MACHDEP
#undef __HAVE_PROCFS_MACHDEP

#endif
