# $NetBSD: Makefile,v 1.8 2005/02/27 22:34:18 christos Exp $

CONFIGFILES=	README display_manager ftpd gdm imap kde login other passwd \
		pop3 ppp rexecd rsh sshd su system telnetd xdm
FILESDIR=	/etc/pam.d
FILESMODE=	644
FILESMODE_README=444

.include <bsd.prog.mk>
