#	$NetBSD: Makefile,v 1.1.20.2 2009/05/04 08:14:06 yamt Exp $

.include "../Makefile.inc"

.PATH:	${S}/fs/adosfs

KMOD=	adosfs
SRCS=	adlookup.c adutil.c advfsops.c advnops.c

.include <bsd.kmodule.mk>
