#	$NetBSD: Makefile,v 1.1.4.2 2008/07/03 18:38:19 simonb Exp $

.include "../Makefile.inc"

.PATH:	${S}/fs/adosfs

KMOD=	adosfs
SRCS=	adlookup.c adutil.c advfsops.c advnops.c

.include <bsd.kmodule.mk>
