#	$NetBSD: Makefile.rumpdev,v 1.13.14.1 2021/08/01 22:42:43 thorpej Exp $
#

LIB=	rumpdev
COMMENT=Rump kernel device faction

.PATH:	${RUMPTOP}/librump/rumpdev				\
	${RUMPTOP}/../kern					\
	${RUMPTOP}/../dev

SRCS=	rump_dev.c

# sys/kern
SRCS+=	kern_pmf.c

# sys/dev
SRCS+=	dev_verbose.c
COPTS.dev_verbose.c+= -Wno-error=format-nonliteral

CPPFLAGS+=	-I${RUMPTOP}/librump/rumpkern

.include "${RUMPTOP}/Makefile.rump"

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
