# 	from: @(#)Makefile	8.2 (Berkeley) 2/16/94
#	$NetBSD: Makefile,v 1.3.8.1 1999/12/27 18:30:55 wrstuden Exp $

MAN=	 intro.4 asc.4 ioasic.4 dc.4 lk201.4 scc.4 sii.4 tc.4
#MLINKS=	mem.4 kmem.4
MANSUBDIR=/pmax

.include <bsd.man.mk>
