#	from: @(#)Makefile	5.13 (Berkeley) 5/7/91
#	$Id: Makefile,v 1.9 1997/03/24 21:57:08 christos Exp $

FILES=	airport ascii birthtoken eqnchar getopt inter.phone man.template \
	mdoc.template na.phone operator style zipcodes
NOOBJ=	noobj

all clean cleandir depend lint tags:

.include <bsd.prog.mk>
