#	$NetBSD: Makefile,v 1.19.2.1 2004/08/03 10:33:36 skrll Exp $

INCSDIR= /usr/include/bebox

INCS=   bootinfo.h \
	disklabel.h \
	intr.h \
	mouse.h \
	pccons.h \
	spkr.h \
	vmparam.h

.include "../../powerpc/include/Makefile"
