#	$NetBSD: Makefile,v 1.19.2.2 2004/09/18 14:33:21 skrll Exp $

INCSDIR= /usr/include/bebox

INCS=   bootinfo.h \
	disklabel.h \
	intr.h \
	mouse.h \
	pccons.h \
	spkr.h \
	vmparam.h

.include "../../powerpc/include/Makefile"
