#	$NetBSD: Makefile,v 1.8 2000/06/26 15:42:27 kleink Exp $

KDIR=	/sys/arch/bebox/include
INCSDIR= /usr/include/bebox

INCS=   ansi.h aout_machdep.h asm.h bat.h bootinfo.h bswap.h bus.h cdefs.h \
	conf.h cpu.h cpufunc.h db_machdep.h disklabel.h elf_machdep.h \
	endian.h endian_machdep.h float.h fpu.h frame.h ieee.h ieeefp.h \
	int_types.h intr.h ipkdb.h kcore.h kgdb.h limits.h lock.h \
	machine_type.h math.h mouse.h param.h pcb.h pccons.h pio.h pmap.h \
	powerpc.h proc.h profile.h psl.h pte.h ptrace.h reg.h reloc.h \
	setjmp.h signal.h spkr.h stdarg.h trap.h types.h varargs.h vmparam.h

.include <bsd.kinc.mk>
