#	$NetBSD: Makefile,v 1.1 2002/05/02 23:02:50 bjh21 Exp $
#
# Makefile for acorn32
#

# have to have all of them here for crunch ...

SRCS=	menu_defs.c msg_defs.c main.c install.c upgrade.c \
	txtwalk.c run.c factor.c net.c disks.c disks_lfs.c util.c  geom.c \
	label.c target.c md.c aout2elf.c

md.o:	menu_defs.h msg_defs.h

.include "../../Makefile.inc"
