#	$NetBSD: Makefile,v 1.4.22.1 2014/05/18 17:46:17 rmind Exp $
#

.include "${.CURDIR}/../Makefile.rumpkerncomp"

SUBDIR+=	${RUMPKERNLIBS}

# obsolete and going away soon
SUBDIR+=	libtime

.include <bsd.subdir.mk>
