#	$NetBSD: Makefile,v 1.15 2003/05/15 18:51:18 wiz Exp $

INCSDIR= /usr/include/prep

INCS=   ansi.h aout_machdep.h asm.h \
	bat.h bootinfo.h bswap.h bus.h \
	cdefs.h cpu.h cpufunc.h \
	db_machdep.h disklabel.h \
	elf_machdep.h endian.h endian_machdep.h \
	float.h fpu.h frame.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intr.h ipkdb.h \
	kcore.h kgdb.h \
	limits.h lock.h \
	math.h mcontext.h \
	param.h pcb.h pio.h pmap.h pmc.h powerpc.h proc.h profile.h \
	psl.h pte.h ptrace.h \
	reg.h reloc.h \
	setjmp.h signal.h spkr.h stdarg.h \
	trap.h types.h \
	varargs.h vmparam.h

.include <bsd.kinc.mk>
