#	$NetBSD: Makefile,v 1.6 1995/11/15 22:55:41 pk Exp $
#	from: @(#)Makefile	8.1 (Berkeley) 6/6/93

SUBDIR=	lpc lpd lpq lpr lprm lptest pac filters

.if make(install)
SUBDIR+= SMM.doc
.endif

.include <bsd.subdir.mk>
