#	$NetBSD: Makefile,v 1.12 2018/06/10 17:55:11 christos Exp $
#	from: @(#)Makefile	8.1 (Berkeley) 6/6/93

SUBDIR=	common_source .WAIT lp lpc lpd lpq lpr lprm lptest pac filters
SUBDIR.roff+= SMM.doc

.include <bsd.subdir.mk>
