#      $NetBSD: Makefile.sdmmcdevs,v 1.1.6.2 2009/05/13 17:21:29 jym Exp $
#      $OpenBSD: Makefile,v 1.1 2006/06/01 21:15:40 uwe Exp $
#
# 1.) Change "src/sys/dev/sdmmc/sdmmcdevs".
# 2.) Commit "src/sys/dev/sdmmc/sdmmcdevs".
# 3.) Execute "make -f Makefile.sdmmcdevs" in "src/sys/dev/sdmmc".
# 4.) Commit "src/sys/dev/sdmmc/sdmmcdevs.h".

.include <bsd.own.mk>

sdmmcdevs.h: sdmmcdevs devlist2h.awk
	/bin/rm -f sdmmcdevs.h
	${TOOL_AWK} -f devlist2h.awk sdmmcdevs
