# $NetBSD: Makefile,v 1.2 2003/06/30 18:47:47 wiz Exp $

# $FreeBSD: src/gnu/usr.bin/groff/src/devices/Makefile,v 1.1 2001/04/17 12:37:02 ru Exp $

SUBDIR=		grodvi grohtml grolbp grolj4 grops grotty

.include <bsd.subdir.mk>
