#	$NetBSD: Makefile,v 1.4.8.1 2000/11/20 20:05:33 bouyer Exp $

PROG=	xxboot.ahdi
SRCS=	xxboot.ahdi.s
MKMAN=	no
LIBCRT0=
INCL=	-I${.CURDIR} -I${.CURDIR}/..

CPPFLAGS+= ${INCL}

.include <bsd.prog.mk>
