#	$NetBSD: Makefile.xxb,v 1.4 2014/01/12 15:26:28 tsutsui Exp $

PROG=	xxboot.ahdi
SRCS=	xxboot.ahdi.S
NOMAN=	# defined
LIBCRT0=
LIBCRTI=
.PATH: ${.CURDIR}/..

.include <../../Makefile.xxboot>
.include <bsd.prog.mk>
