#	$NetBSD: Makefile.xxb,v 1.3 2005/12/11 12:17:02 christos Exp $

PROG=	xxboot.ahdi
SRCS=	xxboot.ahdi.S
NOMAN=	# defined
LIBCRT0=
.PATH: ${.CURDIR}/..

.include <../../Makefile.xxboot>
.include <bsd.prog.mk>
