#	$NetBSD: Makefile,v 1.2.2.1 2004/09/13 17:28:37 tron Exp $

FLOPPYBASE=	boot-com
FLOPPYMAX=	3
FLOPPYKERNEL=	netbsd-INSTALL.gz
FLOPPYBOOTOPTIONS=	-o console=com0

.include "${.CURDIR}/../common/Makefile.bootfloppy"
