#	$NetBSD: Makefile,v 1.1 2003/12/21 03:07:01 rtr Exp $

XMODULEDIR=	${X11ROOTDIR}/lib/modules/extensions

.include "../../../Makefile.serverlib"

.include <bsd.own.mk>

.PATH:		${X11SRCDIR.xc}/programs/Xserver/GL/mesa/GLcore
SRCS=		GLcoremodule.c

.include "../Makefile.GLcore"
