#	$NetBSD: Makefile,v 1.5 1996/11/06 15:35:47 leo Exp $

#
# Note that the directory 'tostools' should never show up...
#
SUBDIR=	binpatch bootxx edahdi installboot keymaps libsa loadkmap msconfig \
	xxboot

.include <bsd.subdir.mk>
