.\"
.\" $NetBSD: pvcsif.8,v 1.4 2002/02/02 01:37:13 wiz Exp $
.\"
.Dd December 29, 1997
.Dt PVCSIF 8
.Os
.Sh NAME
.Nm pvcsif
.Nd configure ATM PVC sub interfaces
.Sh SYNOPSIS
.Nm pvcsif
.Ar interface
.Op Fl s
.Nm pvcsif
.Fl a
.Sh DESCRIPTION
.Nm
creates a sub interface for an ATM PVC.
A sub interface
.Xr pvc 4
is dynamically created.
The created interface is bound to
.Ar interface
but at this point no VC is assigned.  To assign a VC,
.Xr pvctxctl 8
should be used later.
.Pp
A PVC sub interface is intended to use an ATM PVC as an alternative
serial connection, and to be allocated per PVC basis.
A PVC sub interface looks as a point-to-point interface
and is multicast capable, as opposed to the NBMA
(NonBroadcast Multiple Access) model that requires a MARS server.
A point-to-point interface is useful to run MBone or protocols
requiring multicast, such as RSVP and IPv6, over a PVC WAN
connection.
.Pp
Note that a sub interface is not a full-fledged interface but just
an indirect reference to the real interface.
.Pp
The options are as follows:
.Bl -tag -width Fl
.It Fl s
For use with a shell, it prints the created interface name.
.It Fl a
Lists the existing sub interfaces.
.El
.Sh SEE ALSO
.Xr en 4 ,
.Xr pvc 4 ,
.Xr ifconfig 8 ,
.Xr pvctxctl 8
.Sh BUGS
Currently, there is no way to remove a sub interface.
