#	$NetBSD: Makefile.common,v 1.4.4.2 2017/04/21 16:53:13 bouyer Exp $

# shared stuff with src/distrib/utils/x_ifconfig for install media.
# stuff not required by install media should be into Makefile.

.ifdef SMALLPROG
CPPFLAGS+=	-DSMALL
.endif

DPADD+=		${LIBUTIL} ${LIBPROP}
LDADD+=		-lutil -lprop

INCS+=		af_inetany.h env.h extern.h media.h parse.h util.h
SRCS+=		af_inet.c af_inetany.c agr.c env.c ether.c ieee80211.c \
		ifconfig.c l2tp.c media.c parse.c tunnel.c util.c vlan.c
