#	$NetBSD: Makefile,v 1.17.2.3 2001/04/21 17:53:08 bouyer Exp $

KDIR=	/sys/arch/arc/include
INCSDIR= /usr/include/arc

# Header files which are needed from userland.

INCS=	ansi.h aout_machdep.h asm.h autoconf.h \
	bswap.h bsd-aout.h \
	cdefs.h cpu.h \
	disklabel.h display.h \
	ecoff_machdep.h elf_machdep.h endian.h endian_machdep.h \
	float.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	kcore.h kdbparam.h \
	limits.h lock.h \
	math.h mips_opcode.h mouse.h \
	param.h pcb.h pccons.h pmap.h proc.h profile.h psl.h pte.h ptrace.h \
	reg.h regdef.h regnum.h reloc.h \
	setjmp.h signal.h stdarg.h \
	trap.h types.h \
	varargs.h vmparam.h

.include <bsd.kinc.mk>
