#	$NetBSD: Makefile,v 1.7.12.1 2006/05/24 15:50:30 tron Exp $

# use 'make -f Makefile.usbdevs' to make usbdevs.h and usbdevs_data.h
# _after_ you committed usbdevs. See comment in Makefile.usbdevs

INCSDIR= /usr/include/dev/usb

# Only install includes which are used by userland
INCS=	ukyopon.h urio.h usb.h usbhid.h utoppy.h

.include <bsd.kinc.mk>
