#	$NetBSD: Makefile.usbdevs,v 1.4.114.2 2010/03/11 15:04:04 yamt Exp $

#	The header files depend on the correct version of usbdevs.
#
#	Thus, the procedure is:
#	  1) change usbdevs
#	  2) commit usbdevs
#	  3) _then_ generate header files
#	  4) commit them

.include <bsd.own.mk>

UNAME=	uname
RM=	rm

usbdevs.h usbdevs_data.h: usbdevs devlist2h.awk
	${RM} -f usbdevs.h usbdevs_data.h
	${TOOL_AWK} -v os=`${UNAME} -s` -f devlist2h.awk usbdevs
