#	$NetBSD: Makefile,v 1.11 2001/06/30 21:16:52 tron Exp $

# use 'make -f Makefile.tcdevs' to make tcdevs.h and tcdevs_data.h

INCSDIR= /usr/include/dev/tc

# Only install includes which are used by userland
INCS=	sfbreg.h sticreg.h sticvar.h

.include <bsd.kinc.mk>
