#	$NetBSD: Makefile,v 1.10 2001/05/16 13:48:52 ad Exp $

# use 'make -f Makefile.tcdevs' to make tcdevs.h and tcdevs_data.h

INCSDIR= /usr/include/dev/tc

# Only install includes which are used by userland
INCS=	sticreg.h sticvar.h

.include <bsd.kinc.mk>
