#	$NetBSD: Makefile.inc,v 1.2 2003/12/04 09:29:33 mrg Exp $

.if !defined(__COMMON_MAKEFILE_INC_INCLUDED__)
__COMMON_MAKEFILE_INC_INCLUDED__=1

DIST=		${.CURDIR}/../../../dist/binutils
BFDSUBDIR=	lib

.endif
