#	$NetBSD: Makefile,v 1.24.10.1 2002/05/19 08:31:26 gehenna Exp $

KDIR=	/sys/arch/pmax/include
INCSDIR= /usr/include/pmax

INCS=	ansi.h aout_machdep.h asm.h autoconf.h \
	bswap.h bsd-aout.h bus.h \
	cdefs.h cpu.h \
	db_machdep.h dc7085cons.h disklabel.h \
	ecoff_machdep.h elf_machdep.h endian.h endian_machdep.h \
	fbvar.h float.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intr.h \
	kcore.h kdbparam.h \
	limits.h lock.h locore.h \
	math.h mips_opcode.h \
	param.h pcb.h pmap.h pmioctl.h proc.h profile.h psl.h pte.h ptrace.h \
	reg.h regdef.h regnum.h reloc.h \
	setjmp.h signal.h stdarg.h \
	tc_machdep.h trap.h types.h \
	varargs.h vmparam.h

.include <bsd.kinc.mk>
