#	$NetBSD: Makefile.booters,v 1.14 1999/01/22 14:05:05 simonb Exp $
#	@(#)Makefile	8.3 (Berkeley) 2/16/94

# RELOC=80200000 allows for boot prog up to 1D0000 (1900544) bytes long
RELOC=	80200000

BOOTDEFS=-D_STANDALONE -DSMALL
AINC+=	 -D_LOCORE
CFLAGS+= ${DEFS}
AFLAGS+= ${DEFS}

# not yet: need to write libsa/Makefile.inc first
LIBSADIR != cd ${.CURDIR}/../libsa ; make print-objdir
LIBSA=	${LIBSADIR}/libsa.a
LIBS=	${LIBSA}

includes:

.include <bsd.dep.mk>
.include <bsd.obj.mk>
