.\"	$NetBSD: boot.8,v 1.1 2004/04/03 04:13:49 uwe Exp $
.Dd April 3, 2004
.Dt BOOT 8 hpcsh
.Os
.Sh NAME
.Nm boot
.Nd system bootstrapping procedures
.Sh DESCRIPTION
Windows\ CE machines with
.Tn SuperH
CPU use
.Xr hpcboot 8
program to boot
.Nx .
Once running,
.Nx
can reboot itself if
.Xr kloader 4
is configured in the kernel.
.Ss Power fail and crash recovery
.\"
Unfortunately, 
.Nx
can't reboot itself at power-up or after crashes.
The machine will go through the cold reset and boot into Windows\ CE.
You will have to restart
.Nx
manually using
.Xr hpcboot 8 .
.Pp
Once
.Nx
starts, an automatic consistency check of the file systems will be
performed, and unless this fails, the system will resume multi-user
operations.
.\"
.Ss Cold starts
.\"
On cold reset Windows\ CE handheld machines attempt to boot Windows\ CE
operating system from the boot ROM.
The boot ROM is usually not rewritable, so you cannot erase or damage
Windows\ CE image.
.Pp
You can't boot
.Nx
directly, skipping Windows\ CE.
The
.Nx
bootloader,
.Xr hpcboot 8 ,
is provided as a Windows\ CE application program instead.
Though the bootloader is an application program, it blows the entire
running Windows\ CE, its data, and its settings away from RAM (but not
ROM!\&) when the kernel boots successfully.
If
.Nx
is halted the machine will go throught the cold reset and will reboot
into Windows\ CE.
.\"
.Ss Normal Operation
.\"
Please, refer to the
.Xr hpcboot 8
manual page.
.Sh FILES
.\"
.Bl -tag -width hpcboot.exe -compact
.It Pa hpcboot.exe
bootloader program for Windows\ CE
.El
.\"
.Sh SEE ALSO
.\"
.Xr kloader 4 ,
.Xr hpcboot 8
.\"
.Sh BUGS
.\"
There is no general way to launch the bootloader automatically, as
only a few Windows\ CE machines provide an
.Dq auto run
mechanism.
