# $NetBSD: Makefile,v 1.9 2024/10/18 23:22:52 christos Exp $
.include <bsd.own.mk>

TESTSDIR=       ${TESTSBASE}/usr.sbin

TESTS_SUBDIRS+= certctl
TESTS_SUBDIRS+= cpuctl
TESTS_SUBDIRS+= execsnoop
TESTS_SUBDIRS+= inetd
TESTS_SUBDIRS+= makefs
TESTS_SUBDIRS+= mtree
TESTS_SUBDIRS+= opensnoop
TESTS_SUBDIRS+= stdethers
TESTS_SUBDIRS+= stdhosts
TESTS_SUBDIRS+= tcpdump
TESTS_SUBDIRS+= traceroute
TESTS_SUBDIRS+= useradd

.include <bsd.test.mk>
