#	$NetBSD: Makefile,v 1.4 2002/09/19 03:09:53 lukem Exp $
#	install these sources in /usr/share/sendmail/m4

.include <bsd.own.mk>

DIST=		${NETBSDSRCDIR}/gnu/dist
.PATH: ${DIST}/sendmail/cf/m4

FILESDIR=	/usr/share/sendmail/m4
FILES=		cf.m4 cfhead.m4 proto.m4 version.m4

all:

.include <bsd.prog.mk>
