#	$NetBSD: Makefile,v 1.5 1997/02/17 15:10:53 mrg Exp $
#	from: @(#)Makefile	8.1 (Berkeley) 7/19/93

PROG=	rsh
#CFLAGS+=-DKERBEROS -DCRYPT
#SRCS=	rsh.c krcmd.c kcmd.c des_rw.c
#DPADD=	${LIBKRB} ${LIBDES}
#LDADD=	-lkrb -ldes
#INSTALLFLAGS=-fschg
.PATH:	${.CURDIR}/../rlogin

.include <bsd.prog.mk>
