#	$NetBSD: Makefile.elf,v 1.5.30.1 2019/11/26 08:12:27 martin Exp $

# Makefile fragment to build a (32 or 64 bit) libldd_elfxx.a.
# Expects CPPFLAGS to have ELFSIZE set, and LIB to be set.

SRCS=	ldd_elfxx.c
SRCS+=	xmalloc.c debug.c expand.c map_object.c load.c search.c \
	headers.c paths.c tls.c symver.c

CPPFLAGS.tls.c+=	-std=gnu11

.include "Makefile.common"
