#	$NetBSD: Makefile,v 1.8 2004/01/08 04:20:27 lukem Exp $

XTODO=	xf1bpp

SUBDIR=	ddc doc drivers dummy etc fbdevhw \
	i2c input int10 loader pcidata \
	rac ramdac scanpci shadowfb vbe vgahw \
	xaa xf1bpp xf24_32bpp xf4bpp xf86 xf86_os \
	xf86config xf8_16bpp xf8_32bpp xloader \
	.WAIT \
	bin

.include <bsd.subdir.mk>
