#	$NetBSD: Makefile,v 1.4 2004/01/05 05:18:08 rtr Exp $

XTODO=	rac shadowfb vgahw xf24_32bpp xf1bpp xf4bpp xf8_16bpp xf8_32bpp

SUBDIR=	ddc doc drivers dummy i2c input int10 loader pcidata ramdac \
	scanpci vbe vgahw xaa xf86 xf86_os xf86config xloader \
	.WAIT \
	bin

.include <bsd.subdir.mk>
