# $NetBSD: Makefile,v 1.13 2006/03/12 15:06:13 rpaulo Exp $

NOOBJ=	# defined

FILES=	pckbd.be.azerty pckbd.br.abnt2 pckbd.hu.iso8859-2 pckbd.pl.iso8859-2 \
	pckbd.sv.svascii pckbd.ru.koi8-r amikbd.pl.qwertz.iso8859-2 \
	mkbd.pt.iso8859-1 pckbd.de_CH.iso8859-1 pckbd.fr_CH.iso8859-1

FILESDIR= /usr/share/wscons/keymaps

.include <bsd.prog.mk>
