#	$Id: Makefile,v 1.2 1993/05/28 12:30:03 cgd Exp $

PROG=	yacc
SRCS=	closure.c error.c lalr.c lr0.c main.c mkpar.c output.c reader.c \
	skeleton.c symtab.c verbose.c warshall.c
MAN1=	yacc.0

.include <bsd.prog.mk>
