#! /bin/sh
# $NetBSD: test-simple,v 1.3 2016/12/27 12:09:19 schmonz Exp $

test="$1"
bozohttpd="$2"
datadir="$3"
verbose="$4"

if [ "yes" = "$verbose" ]; then
	echo "Running test $test"
else
	exec 2>tmp.$test.err
fi

bozotestport=11111

${bozohttpd} ${datadir} < $test.in > tmp.$test.out
if ./html_cmp cmp $test.out tmp.$test.out; then
	exit 0
else
	[ "yes" = "$verbose" ] || echo "Failed test $test: `cat tmp.$test.err; echo; ./html_cmp diff $test.out tmp.$test.out`"
	exit 1
fi
