#	$NetBSD: Makefile,v 1.2.16.2 2009/05/04 08:14:33 yamt Exp $
#

LIB=	rumpnet_virtif

SRCS=	if_virt.c

CPPFLAGS+=	-I${.CURDIR}/../../../librump/rumpkern

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
