#	$NetBSD: Makefile,v 1.11 2021/02/26 10:33:46 nia Exp $

MAN=	awge.4 bcmgpio.4 cpsw.4 epgpio.4 gxio.4 intro.4 iopaau.4 iopwdog.4 \
	rktsadc.4 vcaudio.4 vchiq.4

MANSUBDIR=/evbarm

.include <bsd.man.mk>
