#	$NetBSD: Makefile,v 1.5 2001/12/12 01:49:20 tv Exp $

SUBDIR= info install system users procs util network

FILES=	help index
FILESDIR=${BINDIR}/sushi
NOOBJ=	# defined

.include "../Makefile.inc"
.include <bsd.prog.mk>
.include <bsd.subdir.mk>
