$NetBSD: To.Do,v 1.11 2003/01/06 20:30:33 wiz Exp $

This is the "To Do" list for NetBSD/pc532
  (Order is not in order of importance.)
  (Last updated, May 17, 2001)

- write an aic scsi driver

- man4 man pages

- man8 man pages

- mods to better support ffs boot loader

- improve bim (detect a non-writable disklabel, ...)

- find or write a "usable" comm package to replace kermit for
	initial downloading.

- switch from a.out to ELF
