$NetBSD: To.Do,v 1.9 1997/11/10 01:58:10 phil Exp $

This is the "To Do" list for NetBSD/pc532
  (Order is not in order of importance.)
  (Last updated, 11/9/97)

- write an aic scsi driver

- man4 man pages

- man8 man pages

- mods to better support ffs boot loader

- improve bim (detect a non-writeable disklabel, ...)

- find or write a "usable" comm package to replace kermit for
	initial downloading.
