#	$NetBSD: Makefile,v 1.1.72.1 2018/09/30 01:45:01 pgoyette Exp $
CDBASE=		cobaltcd		# gives ${CDBASE}.iso
CDRELEASE=	true			# include $RELEASEDIR/$MACHINE
CDRELEASE_NODEBUG=	true

.include "${.CURDIR}/../../../common/Makefile.bootcd"
