#	$NetBSD: Makefile,v 1.14 2001/05/02 13:43:10 jdolecek Exp $

SUBDIR=		biosboot installboot
SUBDIR+=	dosboot
SUBDIR+=	biosboot_com0
SUBDIR+=	biosboot_resetvideo
#SUBDIR+=	genprom netboot

.include <bsd.subdir.mk>
