#!/bin/sh
# $NetBSD: Showsyms,v 1.3 1996/10/09 00:13:36 jtc Exp $
# Small helper to print out symbols in a useful order.

tf=_tmp$$

nm -n rd_bin.syms | egrep -v ' (gcc2|___gnu)_compiled' > $tf

grep -i ' u ' $tf
grep -i ' a ' $tf
grep -i ' t ' $tf
grep -i ' d ' $tf
grep -i ' b ' $tf
rm -f $tf

nm -p rd_bin.syms | grep -i ' c '
