#	$NetBSD: Makefile,v 1.7 1997/05/08 21:11:56 gwr Exp $

CFLAGS += -I${.CURDIR}/.. -I.

NOMAN = I mean it!

SRCS = mkdctype.c ebc_disp.c ectype.c
PROG = mkdctype

.include <bsd.prog.mk>

.PATH: ${.CURDIR}/../../api
