#	$Id: Makefile,v 1.4 1993/08/02 17:56:09 mycroft Exp $

CFLAGS += -I${.CURDIR}/.. -I.

NOMAN = I mean it!

SRCS = mkdctype.c ebc_disp.c ectype.c
PROG = mkdctype

.include <bsd.prog.mk>

.PATH: ${.CURDIR}/../../api
