#	$NetBSD: Makefile,v 1.5.80.1 2008/10/19 22:18:10 haad Exp $

INCSDIR= /usr/include/ufs/ufs

INCS=	dinode.h dir.h extattr.h inode.h quota.h ufs_bswap.h ufs_extern.h \
	ufs_wapbl.h ufsmount.h

.include <bsd.kinc.mk>
