#	$NetBSD: Makefile,v 1.5.74.1 2009/05/04 08:14:38 yamt Exp $

INCSDIR= /usr/include/ufs/ufs

INCS=	dinode.h dir.h extattr.h inode.h quota.h ufs_bswap.h ufs_extern.h \
	ufs_wapbl.h ufsmount.h

.include <bsd.kinc.mk>
