#	$NetBSD: Makefile,v 1.5.76.1 2008/09/18 04:37:06 wrstuden Exp $

INCSDIR= /usr/include/ufs/ufs

INCS=	dinode.h dir.h extattr.h inode.h quota.h ufs_bswap.h ufs_extern.h \
	ufs_wapbl.h ufsmount.h

.include <bsd.kinc.mk>
