#	$NetBSD: Makefile,v 1.5.2.3 2001/04/21 17:53:27 bouyer Exp $

KDIR=	/sys/arch/cobalt/include
INCSDIR= /usr/include/cobalt

INCS=	ansi.h aout_machdep.h asm.h autoconf.h \
	bsd-aout.h bswap.h \
	cdefs.h conf.h cpu.h \
	db_machdep.h disklabel.h \
	ecoff_machdep.h elf_machdep.h endian.h endian_machdep.h \
	float.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intr.h \
	kcore.h kdbparam.h \
	leds.h limits.h lock.h locore.h \
	math.h mips_opcode.h \
	nvram.h \
	param.h pcb.h pmap.h proc.h profile.h psl.h pte.h ptrace.h \
	reg.h regdef.h regnum.h reloc.h \
	setjmp.h signal.h stdarg.h \
	trap.h types.h \
	varargs.h vmparam.h

.include <bsd.kinc.mk>
