#	$NetBSD: Makefile,v 1.2.16.1 2004/08/03 10:42:21 skrll Exp $

SA_PROG= tapeboot
SRCS=   boot.c conf.c rawfs.c dev_tape.c

PROG=	${SA_PROG}
NOMAN= # defined

.include <bsd.prog.mk>
.PATH: ${S}/lib/libsa
