# $NetBSD: Makefile.inc,v 1.2 2006/02/06 18:34:58 wiz Exp $

# $FreeBSD: src/gnu/usr.bin/groff/contrib/Makefile.inc,v 1.1 2001/04/17 12:36:32 ru Exp $

#DIST_SUBDIR=	contrib/mom

.include "../Makefile.inc"
