# $NetBSD: Makefile,v 1.3 2020/06/24 15:05:45 martin Exp $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/usr.sbin/stdhosts

TESTS_SH=	t_stdhosts

FILESDIR=	${TESTSDIR}
FILES+= 	d_ipv6.in

.include <bsd.test.mk>
