#	$NetBSD: Makefile,v 1.5 2001/10/04 16:33:05 tv Exp $

.include <bsd.own.mk>

# XXX this should use real dependencies
SUBDIR=		binstall .WAIT gencat mkdep rpcgen tsort \
		yacc .WAIT lex .WAIT \
		compile_et config lint lint1 lint2 lorder \
		toolchain .WAIT texinfo

TARGETS+=	build

.include <bsd.subdir.mk>
