.\"	$NetBSD: ofctl.8,v 1.1 2006/09/29 19:03:11 macallan Exp $
.\"
.\" Copyright (c) 2006 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Matt Thomas.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of The NetBSD Foundation nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd September 29, 2006
.Dt OFCTL 8
.Os
.Sh NAME
.Nm ofctl
.Nd display the OpenPROM or OpenFirmware device tree
.Sh SYNOPSIS
.Nm
.Op Fl f Ar file
.Op Fl p
.Oo
.Ar node
.Oc
.Sh DESCRIPTION
.Nm
provides an interface for displaying the OpenPROM or OpenFirmware device tree
and node properties.  Without any arguments,
.Nm
will dump the full tree.
When given the name of a specific node,
.Nm
will display that node and its child nodes.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl f Ar file
On systems with OpenPROM, use
.Ar file
instead of the default
.Pa /dev/openprom .
On systems with OpenFirmware, use
.Ar file
instead of the default
.Pa /dev/openfirm .
.It Fl p
.Nm
will display each node's properties.
.El
.Pp
.Sh FILES
.Bl -tag -width "/dev/openprom "
.It /dev/openprom
The openprom device on systems with OpenPROM.
.It /dev/openfirm
The openfirm device on systems with OpenFirmware.
.El
.Sh SEE ALSO
.Xr eeprom 8
