.\"	$NetBSD: ofctl.8,v 1.4.58.1 2018/06/25 07:26:12 pgoyette Exp $
.\"
.\" Copyright (c) 2006 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Matt Thomas.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd May 28, 2018
.Dt OFCTL 8
.Os
.Sh NAME
.Nm ofctl
.Nd display the OpenPROM or OpenFirmware device tree
.Sh SYNOPSIS
.Nm
.Op Fl lpv
.Op Fl f Ar file
.Op Fl r Ar propfile
.Op Fl w Ar propfile
.Op Ar node
.Sh DESCRIPTION
.Nm
provides an interface for displaying the OpenPROM or OpenFirmware
device tree and node properties.
The
.Nm
program is only installed on supported platforms.
.Pp
Without any arguments,
.Nm
will dump the full tree.
When given the name of a specific node,
.Nm
will display that node and its child nodes.
.Pp
The options are as follows:
.Bl -tag -offset indent -width 12n
.It Fl f Ar file
On systems with OpenPROM, use
.Ar file
instead of the default
.Pa /dev/openprom .
On systems with OpenFirmware, use
.Ar file
instead of the default
.Pa /dev/openfirm .
.It Fl l
Dump a partial tree starting from
.Ar node .
.It Fl p
Display each node's properties.
.It Fl r Ar propfile
Instead of reading from the openprom or openfirm device,
use the proplib file
.Ar propfile
as input.
See also
.Fl w .
.It Fl v
Display the full path name for each node.
.It Fl w Ar propfile
Write the device tree to the proplib file
.Ar propfile .
See also
.Fl r .
.El
.Sh FILES
.Bl -tag -width "/dev/openprom "
.It Pa /dev/openprom
The openprom device on systems with OpenPROM.
.It Pa /dev/openfirm
The openfirm device on systems with OpenFirmware.
.El
.Sh SEE ALSO
.Xr eeprom 8
