.\" $NetBSD: acpi.4,v 1.31 2010/01/15 19:24:49 joerg Exp $
.\"
.\" Copyright (c) 2002, 2004 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd May 16, 2009
.Dt ACPI 4
.Os
.Sh NAME
.Nm acpi
.Nd Advanced Configuration and Power Interface
.Sh SYNOPSIS
.Cd "acpi0     at mainbus0"
.Cd "acpiacad* at acpi?"
.Cd "acpibat*  at acpi?"
.Cd "acpibut*  at acpi?"
.Cd "acpiec*   at acpi?"
.Cd "acpilid*  at acpi?"
.Cd "acpitz*   at acpi?"
.Cd "attimer*  at acpi?"
.Cd "aiboost*  at acpi?"
.Cd "com*      at acpi?"
.Cd "fdc*      at acpi?"
.Cd "hpet*     at acpi?"
.Cd "joy*      at acpi?"
.Cd "lpt*      at acpi?"
.Cd "mpu*      at acpi?"
.Cd "npx*      at acpi?"
.Cd "pckbc*    at acpi?"
.Cd "pcppi*    at acpi?"
.Cd "sony*     at acpi?"
.Cd "spic*     at acpi?"
.Cd "ug*       at acpi?"
.Cd "vald*     at acpi?"
.Cd "wss*      at acpi?"
.Cd "ym*       at acpi?"
.Pp
.Cd "options   ACPI_DEBUG"
.Cd "options   ACPIVERBOSE"
.Cd "options   ACPI_ACTIVATE_DEV"
.Cd "options   ACPICA_PEDANTIC"
.Cd "options   ACPI_DSDT_OVERRIDE"
.Sh DESCRIPTION
.Nx
provides machine-independent bus support for
Advanced Configuration and Power Interface
.Pq Tn ACPI
devices and includes several
.Tn ACPI
device drivers.
.Pp
The
.Nx
implementation of
.Tn ACPI
integrates Intel's ACPI Component Architecture
.Pq Tn ACPI-CA
for the OS-independent part.
The
.Tn ACPI-CA
provides OS-neutral
.Tn ACPI
functionalities such as
.Tn ACPI
.Tn BIOS
table support,
an
.Tn ACPI
event framework and an ACPI Machine Language
.Pq Tn AML
interpreter.
.Pp
Options:
.Bl -tag -width ACPI_DSDT_FILE__filename_XX -offset 3n
.It Dv ACPI_DEBUG
Enable
.Tn ACPI
debugging message outputs.
.It Dv ACPI_ACTIVATE_DEV
Determine if the
.Tn ACPI
driver should attempt to activate inactive devices.
The default is off.
.It Dv ACPICA_PEDANTIC
Force strict conformance to the
.Tn ACPI
specification in the
.Tn ACPI-CA .
Do not enable this option unless you are debugging.
.It Dv ACPI_DSDT_OVERRIDE
Force a given Differentiated System Description Table
.Pq Tn DSDT
instead of the BIOS-supplied version.
Use
.Dv ACPI_DSDT_FILE
to specify a
.Tn DSDT .
.It Dv ACPI_DSDT_FILE="filename"
If
.Dv ACPI_DSDT_FILE
is not specified, default to
.Dq dsdt.hex
in the build directory.
.El
.Ss sysctl support
These
.Xr sysctl 8
variables are directly relevant for
.Nm :
.Bl -inset -width hw.acpi.supported_states
.It Li hw.acpi.root
is the
.Tn ACPI
root pointer.
.It Li hw.acpi.supported_states
is a list of the supported
.Tn ACPI
states (see
.Xr sysctl 7 ) .
.It Li machdep.acpi_vbios_reset
defines the handling of the graphics card.
The supported values are:
.Bl -tag -width '2' -offset indent
.It 0
No attempt to reset the
.Tn VGA
controller will be made.
.It 1
Call the
.Tn VGA
.Tn BIOS
when still in real mode.
This can result in direct reboots.
In that case, use
.Sq 2
or
.Ic vbetool post
from the
.Pa pkgsrc/sysutils/vbetool
package.
.It 2
Call the
.Tn VGA
.Tn BIOS
using the in-kernel x86 emulator.
.El
.El
.Sh SUPPORTED DEVICES
.Nx
.Tn ACPI
supports several machine-dependent and machine-independent devices:
.Ss machine-independent devices
.Bl -tag -width pcdisplay -offset indent
.It acpiacad
.Tn ACPI
AC adapters.
.It acpibat
.Tn ACPI
Control Method Batteries.
.It acpibut
.Tn ACPI
power and sleep buttons.
.It acpiec
.Tn ACPI
Embedded Controllers.
.It acpilid
.Tn ACPI
lid switches.
.It acpitz
.Tn ACPI
thermal zones.
.It attimer
AT Timer.
.It aiboost
ASUS AI Booster Hardware monitor.
.It com
NS8250-, NS16450-, and NS16550-based serial ports.
.It fdc
Floppy disk controllers.
.It hpet
High Precision Event Timer.
.It joy
Joystick/Game port interface.
.It lpt
Standard ISA parallel port interface.
.It mpu
Roland MPU-401 (compatible) MIDI UART.
.It pcppi
AT-style speaker sound.
.It ug
Abit uGuru Hardware monitor.
.It wss
Windows Sound System-compatible sound cards based on the AD1848 and compatible chips.
.It ym
Yamaha OPL3-SA2 and OPL3-SA3 audio device driver.
.El
.Ss i386-dependent devices
.Bl -tag -width pcdisplay -offset indent
.It npx
i386 numeric processing extension coprocessor.
.It pckbc
PC keyboard controllers.
.It sony
Sony Miscellaneous Controller
.It spic
Sony programmable I/O controller.
.It vald
Toshiba Libretto device.
.El
.Sh SEE ALSO
.Xr acpiacad 4 ,
.Xr acpibat 4 ,
.Xr acpibut 4 ,
.Xr acpiec 4 ,
.Xr acpilid 4 ,
.Xr acpitz 4 ,
.Xr aiboost 4 ,
.Xr apm 4 ,
.Xr attimer 4 ,
.Xr com 4 ,
.Xr fdc 4 ,
.Xr joy 4 ,
.Xr lpt 4 ,
.Xr mpu 4 ,
.Xr npx 4 ,
.Xr pci 4 ,
.Xr pckbc 4 ,
.Xr pcppi 4 ,
.Xr sony 4 ,
.Xr spic 4 ,
.Xr ug 4 ,
.Xr vald 4 ,
.Xr wss 4 ,
.Xr ym 4 ,
.Xr acpidump 8 ,
.Xr amldb 8
.Rs
.%T ACPI specification
.%U http://www.acpi.info/
.Re
.Rs
.%T Intel ACPI CA (Component Architecture)
.%U http://developer.intel.com/technology/iapc/acpi/
.Re
.Sh HISTORY
The
.Nm
driver
appeared in
.Nx 1.6 .
.Sh BUGS
Most of the
.Tn ACPI
power management functionalities are not implemented.
