.\" $NetBSD: bthub.4,v 1.7 2007/08/21 10:56:11 kiyohara Exp $
.\"
.\" Copyright (c) 2006 Itronix Inc.
.\" All rights reserved.
.\"
.\" Written by Iain Hibbert for Itronix Inc.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of Itronix Inc. may not be used to endorse
.\"    or promote products derived from this software without specific
.\"    prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY ITRONIX INC. ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL ITRONIX INC. BE LIABLE FOR ANY
.\" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd August 21, 2007
.Dt BTHUB 4
.Os
.Sh NAME
.Nm bthub
.Nd Bluetooth Remote Device Hub
.Sh SYNOPSIS
.Cd "bthub* at bt3c?"
.Cd "bthub* at btbc?"
.Cd "bthub* at btuart?"
.Cd "bthub* at ubt?"
.Pp
.Cd "bthidev* at bthub?"
.Cd "btsco* at bthub?"
.Sh DESCRIPTION
The
.Nm
device is used to attach remote Bluetooth devices to the system, and
will attach to Bluetooth controllers as they are enabled.
.Sh CONFIGURATION
Normally, Bluetooth Remote Devices will be configured on the
.Nm
using the
.Xr btdevctl 8
program, which passes a
.Xr proplib 3
dictionary to the control file
.Pa /dev/bthub
with the
.Dv BTDEV_ATTACH
and
.Dv BTDEV_DETACH
.Xr ioctl 2
commands.
.Pp
The following properties are used by
.Nm :
.Pp
.Bl -tag
.It local-bdaddr
Local
.Dv BD_ADDR .
This required property should be a six byte data blob.
.It remote-bdaddr
Remote
.Dv BD_ADDR .
This required property should be a six byte data blob.
.It service-name
Service name.
This required property should be a string indicating the
service to configure, and may be one of the following:
.Pp
.Bl -tag -compact
.It HF
Handsfree, see
.Xr btsco 4 .
.It HID
Human Interface Device, see
.Xr bthidev 4 .
.It HSET
Headset, see
.Xr btsco 4 .
.El
.El
.Pp
Properties used by the configured device are listed in the appropriate
device manual page.
.Sh FILES
.Bl -tag -compact
.It Pa /dev/bthub
.El
.Sh SEE ALSO
.Xr bluetooth 4 ,
.Xr bthidev 4 ,
.Xr btsco 4 ,
.Xr btdevctl 8
.Sh HISTORY
The
.Nm
driver was written by
.An Iain Hibbert
under the sponsorship of Itronix, Inc. and first appeared in
.Nx 4.0 .
