.\" $NetBSD: dtide.4,v 1.4 2001/09/11 22:52:52 wiz Exp $
.\"
.\" Copyright (c) 2000 Ben Harris
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd June 13, 2001
.Os
.Dt DTIDE 4
.Sh NAME
.Nm dtide
.Nd D.T. Software IDE interface driver
.Sh SYNOPSIS
.Cd dtide* at podulebus0 slot ?
.Cd wd* at dtide? channel ? drive ?
.Cd atapibus* at dtide? channel ?
.Sh DESCRIPTION
The
.Nm
driver handles a D.T. Software IDE interface plugged into an Acorn expansion
slot.  It uses the standard
.Nx
IDE controller driver, and hence can use the standard
.Nm wd
and
.Nm atapibus
drivers.

The card provides two IDE channels.  The external IDE connector is channel 0,
while the internal connector is channel 1.
.Sh SEE ALSO
.Xr atapibus 4 ,
.Xr podulebus 4 ,
.Xr wd 4
.Sh BUGS
The driver was derived by reverse-engineering the card and its
.Tn RISC OS
driver, so it may not handle the card entirely optimally.
