.\" $NetBSD: dtv.4,v 1.2 2011/08/14 20:42:09 wiz Exp $
.\"
.\" Copyright (c) 2011 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Thomas Klausner.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd August 14, 2011
.Dt DTV 4
.Os
.Sh NAME
.Nm dtv
.Nd DVB (digital video broadcasting) programming interface
.Sh SYNOPSIS
.Cd "dtv* at dtvbus?"
.Pp
.In dev/dtv/dtvio.h
.In dev/dtv/dtvio_demux.h
.In dev/dtv/dtvio_frontend.h
.Sh DESCRIPTION
The
.Nm
driver provides support for a subset of the Linux DVB (digital
video broadcasting) APIs; in particular,
.Nm
provides the DVB Frontend API and the DVB Demux Device.
.Sh FILES
.Bl -tag -width 28n
.It Pa /dev/dvb/adapterN/frontend0
The frontend device, for controlling the tuner and demodulator hardware.
.It Pa /dev/dvb/adapterN/demux0
The demux device, for controlling the DVB hardware's filters.
.It Pa /dev/dvb/adapterN/dvr0
Digital video recording device
.El
.Sh SEE ALSO
.Xr auvitek 4 ,
.Xr coram 4 ,
.Xr cxdtv 4 ,
.Xr emdtv 4 ,
.Pa pkgsrc/multimedia/dvb-apps ,
.Pa pkgsrc/multimedia/mplayer ,
.Pa http://linuxtv.org/downloads/v4l-dvb-apis/dvbapi.html
.Sh HISTORY
The
.Nm
device driver first appeared in
.Nx 6.0 .
.Sh AUTHORS
.An -nosplit
The
.Nm
driver was written by
.An Jared D. McNeill
.Aq jmcneill@NetBSD.org .
