.\" $NetBSD: dtvi2c.4,v 1.3 2011/08/29 15:35:29 jruoho Exp $
.\"
.\" Copyright (c) 2011 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Thomas Klausner.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd August 29, 2011
.Dt DTVI2C 4
.Os
.Sh NAME
.Nm dtvi2c
.Nd Inter IC (I2C) modules for
.Ic dtv
.Sh DESCRIPTION
The
.Nm
modules provide support for
.Xr dtv 4
devices.
The
.Nm
group includes digital tuners, demodulators, and analog video decoders.
.Pp
The usual hardware structure consists of a host controller
(connected for instance via
.Xr usb 4
or
.Xr pci 4 )
that provides the data moving facilities (for the analog or
digital video streams) and an
.Xr iic 4
bus over which the other chips can be configured.
.Pp
For example, a typical
.Xr dtv 4
setup would look like this:
.Bl -enum -offset indent
.It
Initialize transport stream
.Pq Dv TS
port on the host controller.
.It
Configure the demodulator that
.Dq demodulates
the information from an intermediate frequency
.Pq Dv IF
that is provided to it by the associated tuner.
This step typically includes setting the desired
quadrature amplitude modulation
.Pq Dv QAM
and bandwidth, among other things.
.It
Configure the tuner.
Typically this step includes at least setting the frequency.
.It
Start TS transfer (using
.Dv DMA
transfers or
.Dv USB
high speed transfers).
.El
.Pp
The currently supported modules are:
.Bl -tag -width 10n -offset indent
.It Ic au8522
Auvitek AU8522 ATSC/QAM64/QAM256 demodulator
.It Ic cx24227
Conexant CX24227 ATSC/QAM64/QAM256 demodulator
.It Ic lg3303
LG LGDT3303 ATSC/QAM64/QAM256 demodulator
.It Ic mt2131
MicroTune MT2131 ATSC demodulator
.It Ic nxt2k
XXX description
.It Ic tvpll
Generic PLL-based tuners
.It Ic xc3028
XCeive XC3028 analog and digital tuner
.It Ic xc5k
Xceive XC5000 analog and digital tuner
.It Ic zl10353
Zarlink ZL10353 (Intel CE623x) demodulator
.El
.Sh FILES
.Bl -bullet
.It
.Pa dvb-fe-nxt2004.fw
needed by nxt2k
.It
.Pa xc3028L-v36.fw
(provided by
.Pa pkgsrc/sysutils/xc3028l-firmware )
or
.Pa xc3028-v27.fw
needed by xc3028
.It
.Pa dvb-fe-xc5000-1.6.114.fw
needed by xc5k, provided by
.Pa pkgsrc/sysutils/xc5k-firmware
.El
.Sh SEE ALSO
.Xr dtv 4 ,
.Xr iic 4
.Sh HISTORY
The
.Nm
modules first appeared in
.Nx 6.0 .
.Sh AUTHORS
.An -nosplit
The
.Nm
modules were written by
.An Jared D. McNeill
.Aq jmcneill@NetBSD.org ,
.An Jonathan A. Kollasch
.Aq jakllsch@NetBSD.org ,
and
.An Jukka Ruohonen
.Aq jruohonen@iki.fi .
