.\"	$NetBSD: ichlpcib.4,v 1.10 2009/09/27 21:07:29 wiz Exp $
.\"
.\" Copyright (c) 2004 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Minoura Makoto and Matthew R. Green.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd September 27, 2009
.Dt ICHLPCIB 4
.Os
.Sh NAME
.Nm ichlpcib
.Nd Intel ICH LPC Interface Bridge
.Sh SYNOPSIS
.Cd "ichlpcib* at pci? dev ? function ?"
.Cd "hpet0     at ichlpcib?"
.Cd "isa0      at ichlpcib?"
.Cd "gpio*     at ichlpcib?"
.Sh DESCRIPTION
The
.Nm
driver supports the Intel ICH LPC Interface Bridges on compatible
chipsets.
Supported functions include:
.Bl -bullet
.It
Watchdog timer.
The watchdog timer may be configured for a 2 seconds (on ICH6 or newer)
and 4 seconds (on ICH5 or older) min period and for a 39 seconds
(on ICH5 or older) or 613 seconds max period (on ICH6 or newer).
.It
Power Management timer.
A 24-bit timer available to be used by the timecounters framework.
.It
SpeedStep.
In some systems the SpeedStep function is also available, and can be
used to switch between high and low frequency (to reduce power consumption)
via the
.Li machdep.speedstep_state
.Xr sysctl 8
node.
A value of 0 will use the low frequency (low power) and a 1 will
enable the high frequency (full power).
.It
General Purpose Input/Output.
The ICH provides up to 64 I/O pins which can be accessed through the
.Xr gpio 4
framework.
.El
.Sh SEE ALSO
.Xr gpio 4 ,
.Xr sysctl 8 ,
.Xr wdogctl 8
.Sh HISTORY
The
.Nm
driver first appeared in
.Nx 3.0 .
.Sh AUTHORS
The
.Nm
driver was written by
.An Minoura Makoto
and
.An Matthew R. Green .
