.\" $NetBSD: nsclpcsio.4,v 1.2 2007/11/09 01:09:48 xtraeme Exp $
.\"
.Dd November 9, 2007
.Dt NSCLPCSIO 4
.Os
.Sh NAME
.Nm nsclpcsio
.Nd National Semiconductor PC87366 LPC Super I/O
.Sh SYNOPSIS
.Cd "nsclpcsio* at isa?"
.Cd "gpio* at nsclpcsio?"
.Sh DESCRIPTION
The
.Nm
driver provides support for the 
.Tn National Semiconductor
PC87366 LPC Super I/O. The Super I/O incorporates several logical
devices, the following ones are supported: GPIO, VLM and TMS.
.Pp
The GPIO logical device provides 29 I/O pins which can be accessed
through the
.Xr gpio 4
framework. The
.Xr gpioctl 8
program allows easy manipulation of the pins from userland.
.Pp
VLM and TMS logical devices provides hardware monitoring capabilities to
be used with the
.Xr envsys 4
API. The following 17 monitoring sensors are available:
.Bl -column "Sensor" "Units" "Typical" -offset indent
.It Sy "Sensor" Ta Sy "Units" Ta Sy "Typical Use"
.It Li "TSENS1" Ta "uK" Ta "Remote diode"
.It Li "TSENS2" Ta "uK" Ta "Remote diode"
.It Li "TNSC" Ta "uK" Ta "Local diode"
.It Li "VSENS0" Ta "uV DC" Ta "External source"
.It Li "VSENS1" Ta "uV DC" Ta "External source"
.It Li "VSENS2" Ta "uV DC" Ta "External source"
.It Li "VSENS3" Ta "uV DC" Ta "External source"
.It Li "VSENS4" Ta "uV DC" Ta "External source"
.It Li "VSENS5" Ta "uV DC" Ta "External source"
.It Li "VSENS6" Ta "uV DC" Ta "External source"
.It Li "VSB" Ta "uV DC" Ta "VSB"
.It Li "VDD" Ta "uV DC" Ta "VDD"
.It Li "VBAT" Ta "uV DC" Ta "VBAT"
.It Li "AVDD" Ta "uV DC" Ta "AVDD"
.It Li "TS1" Ta "uV DC" Ta "Thermistor"
.It Li "TS2" Ta "uV DC" Ta "Thermistor"
.It Li "TS3" Ta "uV DC" Ta "Thermistor"
.El
.Sh SEE ALSO
.Xr envsys 4 ,
.Xr envstat 8
.Sh HISTORY
The
.Nm
device appeared in
.Nx 2.0 .
.Sh BUGS
The chip decodes address ranges which are not obvious and
cannot be controlled by the kernel configuration file
(must be set up by the BIOS).
