.\"	$NetBSD: pci.4,v 1.22 1999/12/11 23:10:15 augustss Exp $
.\"
.\" Copyright (c) 1997 Jason R. Thorpe.  All rights reserved.
.\" Copyright (c) 1997 Jonathan Stone
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgements:
.\"      This product includes software developed by Jonathan Stone
.\" 4. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd March 31, 1997
.Dt PCI 4
.Os
.Sh NAME
.Nm pci
.Nd introduction to machine-independent PCI bus support and drivers
.Sh SYNOPSIS
.Pp
.Cd "pci* at mainbus? bus ?"
.Cd "pci* at pchb? bus ?"
.Cd "pci* at ppb? bus ?"
.Pp
Other
.Nm
attachments are machine-dependent and depend on the bus topology and
.Tn PCI
bus interface of your system.
See
.Xr intro 4
for your system for details.
.Sh INTRODUCTION
.Nx
includes a machine-independent
.Tn PCI
bus subsystem and
several machine-independent
.Tn PCI
device drivers.
.Pp
Your system may support additional
.Tn PCI
devices.
Drivers for
.Tn PCI
devices not listed here are machine-dependent.
Consult your system's
.Xr intro 4
for additional information.
.Sh SUPPORTED DEVICES
.Nx
includes machine-independent
.Tn PCI
drivers, sorted by device type and driver name:
.Pp
.Ss SCSI interfaces
.Bl -tag -width speaker -offset indent
.It ahc
Adaptec 29xx, 39xx, and other AIC-7xxx-based
.Tn SCSI
interfaces.
.It bha
Buslogic BT-9xx
.Tn SCSI
interfaces.
.It isp
QLogic ISP-1020, ISP-1040, and ISP-2100
.Tn SCSI
and
.Tn FibreChannel
interfaces.
.It ncr
Symbios Logic/NCR 53c8xx-family
.Tn SCSI
interfaces.
.El
.Pp
.Ss Network interfaces
.Bl -tag -width speaker -offset indent
.It de
.Tn DEC
DC21x4x (Tulip) based
.Tn Ethernet
interfaces, including the DE435,
DE450, and DE500, and Znyx, SMC, Cogent/Adaptec, and Asante single- and
multi-port
.Tn Ethernet
interfaces.  Multi-port interfaces are typically
configured as a
.Tn PCI Ns \- Ns Tn PCI
bridge with multiple
.Em de
instances on the
.Tn PCI
bus on the other side of the bridge.
.It en
Midway-based Efficent Networks Inc. and Adaptec ATM interfaces.
.It ep
3Com 3c590, 3c595, 3c900, and 3c905
.Tn Ethernet
interfaces.
.It fpa
.Tn DEC
DEFPA
.Tn FDDI
interfaces.
.It fxp
Intel EtherExpress PRO 10+/100B
.Tn Ethernet
interfaces.
.It le
PCNet-PCI
.Tn Ethernet
interfaces.
.It ne
NE2000-compatible
.Tn Ethernet
interfaces.
.It tl
Texas Instruments ThunderLAN-based
.Tn Ethernet
interfaces.
.El
.Pp
.Ss Serial interfaces
.Bl -tag -width speaker -offset indent
.It cy
Cyclades Cyclom-4Y, -8Y, and -16Y asynchronous serial communications
device interface.
.El
.Pp
.Ss Audio devices
.Bl -tag -width speaker -offset indent
.It clcs
Cirrus Logic CS4280 sound device.
.It eap
Ensoniq AudioPCI sound device.
.It eso
ESS Solo-1 PCI AudioDrive sound device.
.It fms
Forte Media FM801 sound device.
.It sv
S3 SonicVibes sound device.
.El
.Pp
.Ss Miscellaneous devices
.Bl -tag -width speaker -offset indent
.It cbb
.Tn PCI
Yenta compatible
.Tn CardBus
bridges.
.It ohci
USB OHCI host controller
.It pcic
.Tn PCI
.Tn PCMCIA
controllers, including the Cirrus Logic GD6729.
.It ppb
Generic
.Tn PCI Ns \- Ns Tn PCI
bridges, including
.Tn PCI
expansion backplanes.
.It puc
PCI
.Dq universal
communications cards, containing
.Nm com
and
.Nm lpt
communications ports.
.It uhci
USB UHCI host controller
.El
.Pp
.Sh SEE ALSO
.Xr intro 4 ,
.Xr ahc 4 ,
.Xr bha 4 ,
.Xr clcs 4 ,
.Xr cy 4 ,
.Xr de 4 ,
.Xr eap 4 ,
.Xr eso 4 ,
.Xr en 4 ,
.Xr ep 4 ,
.Xr eso 4 ,
.Xr fpa 4 ,
.Xr fxp 4 ,
.Xr isp 4 ,
.Xr le 4 ,
.Xr ncr 4 ,
.Xr ne 4 ,
.Xr pcic 4 ,
.Xr ppb 4 ,
.Xr puc 4 ,
.Xr sv 4 ,
.Xr tl 4 ,
.Xr usb 4
.Sh HISTORY
The machine-independent
.Tn PCI
subsystem appeared in
.Nx 1.2 .
