.\"	$NetBSD: pci.4,v 1.5.2.2 1997/11/11 02:04:17 thorpej Exp $
.\"
.\" Copyright (c) 1997 Jason R. Thorpe.  All rights reserved.
.\" Copyright (c) 1997 Jonathan Stone
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgements:
.\"      This product includes software developed by Jonathan Stone
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd March 31, 1997
.Dt PCI 4
.Os NetBSD
.Sh NAME
.Nm pci
.Nd introduction to PCI bus machine-independent drivers and support
.Sh SYNOPSIS
.Pp
.Cd "pci* at ppb? bus ?"
.Pp
Other
.Nm
attachments are machine-dependent and depends on the bus topology and
PCI bus interface of your system.  See
.Xr intro 4
for your system for details.
.Sh INTRODUCTION
.Nx
includes a machine-independent PCI bus subsystem and
several machine-independent PCI device drivers.
.Pp
Your system may support additional PCI devices.  Drivers for PCI
devices listed here are machine-dependent.
Consult your system's
.Xr intro 4
for additional information.
.Sh SUPPORTED DEVICES
.Nx
includes machine-independent PCI drivers, sorted by device type and
driver name:
.Pp
.Ss SCSI interfaces
.Bl -tag -width speaker -offset indent
.It ahc
Adaptec 29xx, 39xx, and other AIC-7xxx-based SCSI interfaces.
.It bha
Buslogic BT-9xx SCSI interfaces.
.It isp
QLogic ISP-1020, ISP-1040, and ISP-2100 SCSI and FibreChannel interfaces.
.It ncr
Symbios Logic/NCR 53c8xx-family SCSI interfaces.
.El
.Pp
.Ss Network interfaces
.Bl -tag -width speaker -offset indent
.It de
DEC DC21x4x (Tulip) based Ethernet interfaces, including the DE435,
DE450, and DE500, and Znyx, SMC, Cogent/Adaptec, and Asante single- and
multi-port Ethernet interfaces.  Multi-port interfaces are typically
configured as a PCI-PCI bridge with multiple
.Em de
instances on the PCI bus on the other side of the bridge.
.It en
Midway-based Efficent Networks Inc. and Adaptec ATM interfaces.
.It ep
3Com 3c590, 3c595, 3c900, and 3c905 Ethernet interfaces.
.It fpa
DEC DEFPA FDDI interfaces.
.It fxp
Intel EtherExpress PRO 10+/100B Ethernet interfaces.
.It le
PCNet-PCI Ethernet interfaces.
.It ne
NE2000-compatible Ethernet interfaces.
.It tl
Texas Instruments ThunderLAN-based Ethernet interfaces.
.El
.Pp
.Ss Serial interfaces
.Bl -tag -width speaker -offset indent
.It cy
Cyclades Cyclom-4Y, -8Y, and -16Y asynchronous serial communications
device interface
.El
.Pp
.Ss Miscellaneous devices
.Bl -tag -width speaker -offset indent
.It pcic
PCI PCMCIA controllers, including the Cirrus Logic GD6729.
.It ppb
Generic PCI-PCI bridges, including PCI expansion backplanes.
.El
.Pp
.Sh SEE ALSO
.Xr intro 4 ,
.Xr ahc 4 ,
.Xr bha 4 ,
.Xr cy 4 ,
.Xr de 4 ,
.Xr en 4 ,
.Xr ep 4 ,
.Xr fpa 4 ,
.Xr fxp 4 ,
.Xr isp 4 ,
.Xr le 4 ,
.Xr ncr 4 ,
.Xr ne 4 ,
.Xr pcic 4 ,
.Xr ppb 4 ,
.Xr tl 4
.Sh HISTORY
The machine-independent PCI subsystem appeared in
.Nx 1.2 .
