.\"	$NetBSD: sdtemp.4,v 1.6.6.1 2018/03/08 14:29:12 martin Exp $
.\"
.\" Copyright (c) 2008 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Paul Goyette.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd February 22, 2018
.Dt SDTEMP 4
.Os
.Sh NAME
.Nm sdtemp
.Nd JEDEC JC-42.4 compatible memory module temperature sensors
.Sh SYNOPSIS
.Cd "sdtemp* at iic? addr 0x18"
.Cd "sdtemp* at iic? addr 0x19"
.Cd "sdtemp* at iic? addr 0x1a"
.Cd "sdtemp* at iic? addr 0x1b"
.Cd "sdtemp* at iic? addr 0x1c"
.Cd "sdtemp* at iic? addr 0x1d"
.Cd "sdtemp* at iic? addr 0x1e"
.Cd "sdtemp* at iic? addr 0x1f"
.Sh DESCRIPTION
The
.Nm
driver provides support for the Microchip Technology
MCP9805/98242 and other chips that conform to JEDEC Standard 21-C section
4.7.
Memory module temperature sensors are optional on DDR2 and newer DIMMs.
Sensors provided by this driver, including the on-chip thresholds for the
Alarm Window and Critical level, are accessed through the
.Xr envsys 4
API.
.Pp
The
.Nm
supports temperature ranges from -256 to +255 degrees C.
.Pp
Chips supported by the
.Nm
driver include TSE2004av compliant devices and:
.Bl -bullet -offset indent
.It
Analog Devices ADT7408
.It
Atmel AT30TS00 and AT30TSE004
.It
On semiconductor (Catalyst) CAT34TS02, CAT34TS02C, CAT34TS04
and CAT6095
.It
Giantec Semiconductor GT30TS00 and GT34TS02
.It
Integrated Deviced Technology TSE2002B3, TSE2002GB2, TSE2004GB2,
TS3000B3, TS3000GB0, TS3000GB2, and TS30001GB2
.It
Maxim MAX6604
.It
Microchip Technology EMC1501, MCP9804, MCP9805, MCP9843, MCP98242,
MCP98243, and MCP98244
.It
NXP Semiconductors SE97 and SE98
.It
STmicroelectronics STTS424, STTS424E, STTS2002, STTS2004, and
STTS3000
.El
.Sh SEE ALSO
.Xr envsys 4 ,
.Xr envstat 8
.Sh HISTORY
The
.Nm
device appeared in
.Nx 6.0 .
.Sh BUGS
Interrupt support is unimplemented.
