.\"	$NetBSD: se.4,v 1.3 2000/03/13 22:40:15 soren Exp $
.\"
.Dd February 3, 1997
.Dt SE 4
.Os
.Sh NAME
.Nm se
.Nd Cabletron EA41x SCSI bus Ethernet interface driver
.Sh SYNOPSIS
.Cd "se* at scsibus? target ? lun ?"
.Sh DESCRIPTION
The
.Nm
driver supports the
.Tn Cabletron
EA41x
.Tn SCSI
bus
.Tn Ethernet
interface.
.Pp
This driver is a bit unusual.
It must look like a network interface and it must also appear to be a
.Tn SCSI
device to the
.Tn SCSI
system.
.Pp
In addition, to facilitate
.Tn SCSI
commands issued by userland programs, there are
.Fn open ,
.Fn close ,
and
.Fn ioctl
entry points.
This allows a user program to, for example,
display the EA41x statistic and download new code into the adaptor \-
functions which can't be performed through the
.Xr ifconfig 8
interface.
Normal operation does not require any special userland program.
.Sh SEE ALSO
.Xr scsi 4 ,
.Xr ifconfig 8
.Sh AUTHORS
Ian Dall <ian.dall@dsto.defence.gov.au>
.Pp
Acknowledgement: Thanks are due to Philip L. Budne <budd@cs.bu.edu>
who reverse engineered the EA41x.
In developing this code, Phil's userland daemon "etherd",
was refered to extensively in lieu of accurate documentation for the device.
.Sh BUGS
The EA41x doesn't conform to the
.Tn SCSI
specification in much at all.
About the only standard command supported is
.Qq inquiry .
Most commands are 6 bytes long, but the recv data is only 1 byte.
Data must be received by periodically polling the device with the
recv command.
