.\" $NetBSD: umidi.4,v 1.11 2009/05/18 08:56:32 wiz Exp $
.\"
.\" Copyright (c) 2001 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd October 14, 2007
.Dt UMIDI 4
.Os
.Sh NAME
.Nm umidi
.Nd USB support for MIDI devices
.Sh SYNOPSIS
.Cd "umidi* at uhub?"
.Cd "midi*  at umidi?"
.Sh DESCRIPTION
The
.Nm
driver supports USB MIDI devices that conform to the
.Em Universal Serial Bus Device Class Definition for MIDI Devices .
Vendor-specific support is also included for the following:
.Ss Midiman devices
.Bl -tag -width Dv -offset indent -compact
.It Tn MidiSport 2x4
.El
.Ss Roland and Edirol devices
.Bl -tag -width Dv -offset indent -compact
.It Tn Fantom-X
.It Tn PC300
.It Tn PCR
.It Tn SC8820
.It Tn SC8850
.It Tn SCD70
.It Tn SD20
.It Tn SD80
.It Tn SD90
.It Tn SK500
.It Tn SonicCell
.It Tn U8
.It Tn UA25
.It Tn UA100
.It Tn UA101
.It Tn UA10F
.It Tn UA4FX
.It Tn UA700
.It Tn UA1000
.It Tn UM1
.It Tn UM2
.It Tn UM3
.It Tn UM4
.It Tn UM550
.It Tn UM880N
.It Tn XV5050
.El
.Ss Yamaha devices
.Bl -tag -width Dv -offset indent -compact
.It Tn UX256
(product-specific support)
.It Tn Others
Other Yamaha MIDI devices
will be attached and are expected to work also.
.El
.Pp
Devices supported by the
.Nm
driver will appear as
.Xr midi 4
devices.
.Sh SEE ALSO
.Xr midi 4 ,
.Xr usb 4
.Sh HISTORY
The
.Nm
driver
appeared in
.Nx 1.6 .
