.\"     $NetBSD: userconf.4,v 1.7 2001/09/11 23:18:55 wiz Exp $
.\"
.\" Copyright (c) 2001 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Gregory McGarry.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"        This product includes software developed by the NetBSD
.\"        Foundation, Inc. and its contributors.
.\" 4. Neither the name of The NetBSD Foundation nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd July 1, 2001
.Dt USERCONF 9
.Os
.Sh NAME
.Nm userconf
.Nd in-kernel device configuration manager
.Sh SYNOPSIS
.Cd options USERCONF
.Sh DESCRIPTION
.Nm
is the in-kernel device configuration manager.
It is used to alter the kernel autoconfiguration framework at runtime.
.Nm
is activated from the boot loader by passing the
.Fl c
option to the kernel.
.Sh COMMAND SYNTAX
The general command syntax is:
.Bd -ragged -offset indent
.Ic command Op Ar option
.Ed
.Pp
.Nm
has a
.Xr more 1 -like
functionality; if a number of lines in a command's output exceeds the
number defined in the lines variable, then
.Nm
displays
.Dq "-- more --"
and waits for a response, which may be one of:
.Bl -tag -offset indent -width "<return>"
.It <return>
one more line.
.It <space>
one more page.
.It Ic q
abort the current command, and return to the command input mode.
.El
.Sh COMMANDS
.Nm
supports the following commands:
.Bl -tag -width 5n
.It Ic lines Ar count
Specify the number of lines before more.
.It Ic base Ar 8 | 10 | 16
Base for displaying large numbers.
.It Ic change Ar devno | dev
Change devices.
.It Ic disable Ar devno | dev
Disable devices.
.It Ic enable Ar devno | dev
Enable devices.
.It Ic exit
A synonym for
.Ic quit .
.It Ic find Ar devno | dev
Find devices.
.It Ic help
Display online help.
.It Ic list
List current configuration.
.It Ic quit
Leave userconf.
.It Ic ?
A synomym for
.Ic help .
.El
.Sh HISTORY
The
.Nm
framework first appeared in
.Ox 2.0 ,
and then integrated into
.Nx 1.6 .
.Sh AUTHORS
The
.Nm
framework was written by
.An Mats O Jansson
.Aq moj@stacken.kth.se .
