.\"	$NetBSD: uxrcom.4,v 1.4 2020/04/13 11:17:27 simonb Exp $
.\"	$OpenBSD: uxrcom.4,v 1.1 2019/03/27 22:11:21 kettenis Exp $
.\"
.\" Copyright (c) 2019 Mark Kettenis <kettenis@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd April 12, 2020
.Dt UXRCOM 4
.Os
.Sh NAME
.Nm uxrcom
.Nd Exar XR21V141x USB serial adapter
.Sh SYNOPSIS
.Cd "uxrcom* at uhub?"
.Cd "ucom* at uxrcom?"
.Sh HARDWARE
The
.Nm
driver supports serial adapters based on the
XR21V1410, XR21V1412, and XR21V1414 chipsets.
Devices range from single port to eight port (implemented as a
USB hub and two
.Nm
four port instances behind it).
Examples of hardware known to work with this driver are:
.Pp
.Bl -tag -width Dv -offset indent -compact
.It Gearmo GM-U28RS232 8 Port USB to Serial DB9 RS232 Adapter
.El
.Sh DESCRIPTION
The
.Nm
driver attaches the Exar XR21V141x multiport chipset with individual
port drivers via
.Xr ucom 4 ,
which makes it behave like a
.Xr tty 4 .
.Sh SEE ALSO
.Xr tty 4 ,
.Xr ucom 4 ,
.Xr uhub 4 ,
.Xr umodem 4 ,
.Xr usb 4
.Sh HISTORY
The
.Nm
device driver first appeared in
.Ox 6.5
and in
.Nx 9.1 .
.Sh AUTHORS
.An -nosplit
The
.Nm
driver for the single port XR21V1410 was written by
.An Mark Kettenis Aq Mt kettenis@openbsd.org .
The multi-port
.Nx
driver is based on the
.Ox
driver but uses the common
.Xr umodem 4
framework.
The
.Nx
driver was written by
by
.An Simon Burge
.Aq Mt simonb@NetBSD.org .
