.\"	$NetBSD: virt.4,v 1.2.12.1 2014/08/20 00:02:35 tls Exp $
.\"
.\" Copyright (c) 2010 Antti Kantee
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd July 3, 2013
.Dt VIRT 4
.Os
.Sh NAME
.Nm virt
.Nd rump kernel virtual network interface
.Sh DESCRIPTION
The
.Nm
interface acts as a link between a rump kernel and a host
.Xr tap 4
interface.
Interface number <n> always corresponds with the host tap interface tap<n>.
All data sent by
.Nm
is written into
.Pa /dev/tap<n>
and all data read from
.Pa /dev/tap<n>
is passed as Ethernet input to the rump kernel.
.Pp
A
.Nm
interface can be created and destroyed in the normal fashion with
.Xr ifconfig 8 .
.Pp
The host's
.Xr tap 4
interface can be further bridged with hardware interfaces to provide
full Internet access to a rump kernel.
.Sh SEE ALSO
.Xr rump 3 ,
.Xr bridge 4 ,
.Xr tap 4 ,
.Xr brconfig 8 ,
.Xr ifconfig 8
