#	$NetBSD: Makefile,v 1.1 2005/12/29 15:20:08 tsutsui Exp $

INCSDIR= /usr/include/ews4800mips

INCS=	ansi.h aout_machdep.h asm.h \
	bswap.h \
	cdefs.h cpu.h \
	db_machdep.h disklabel.h \
	ecoff_machdep.h elf_machdep.h endian.h endian_machdep.h \
	float.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intr.h \
	kcore.h kdbparam.h \
	limits.h lock.h locore.h \
	math.h mcontext.h mips_opcode.h \
	param.h pcb.h pdinfo.h pmap.h pmc.h proc.h profile.h psl.h pte.h \
	ptrace.h \
	reg.h regdef.h regnum.h reloc.h \
	setjmp.h signal.h stdarg.h \
	trap.h types.h \
	varargs.h vmparam.h vtoc.h \
	wchar_limits.h

.include <bsd.kinc.mk>
