#	$NetBSD: Makefile,v 1.4 2000/04/15 18:08:12 mrg Exp $

KDIR=	/sys/vm
INCSDIR= /usr/include/vm

INCS=	pglist.h pmap.h vm.h \
	vm_extern.h vm_inherit.h vm_kern.h vm_map.h vm_object.h vm_page.h \
	vm_pageout.h vm_pager.h vm_param.h vm_prot.h

.include <bsd.kinc.mk>
