#!/bin/sh
# $NetBSD: script,v 1.1 2004/03/09 20:06:42 garbled Exp $

if [ -n "$6" -a "$6" != "NEVER" ]; then
	CTIME=`date +%s`
	EXPIRE=`expr $6 \* 24 \* 60 \* 60 + $CTIME`
	EXPIRE=`echo "-e $EXPIRE"`
fi

ID=`id -u $1`
if [ $8 -eq $ID  ]; then
	UID=""
else
	UID="-u $8"
fi

if [ -z $3 ]; then
	SG=""
else
	SG="-G $3"
fi

usermod -g $2 $SG -c "$4" -d "$5" $EXPIRE -s $7 $UID -v $1
if [ $? -eq 0 ]; then
	echo "User $1 successfully modified."
fi
