.\" Copyright 1996 The Board of Trustees of The Leland Stanford
.\" Junior University. All Rights Reserved.
.\"
.\" Author: Jonathan Stone
.\"
.\" Permission to use, copy, modify, and distribute this
.\" software and its documentation for any purpose and without
.\" fee is hereby granted, provided that the above copyright
.\" notice and the above authorship notice appear in all copies.
.\" Stanford University makes no representations about the suitability
.\" of this software for any purpose.  It is provided "as is" without
.\" express or implied warranty.
.Dd September 30, 1996
.Dt ELF2AOUT 1
.Os NetBSD 1.2
.Sh NAME
.Nm elf2aout
.\" Why doesn't this work right?  mdoc(7) nor mdoc.samples(7) lists
.\" .Nd, except for a passing reference in the latter.
.Nd convert a NetBSD ELF-format executable to NetBSD a.out format
.Sh SYNOPSIS
.Nm elf2aout elf-file aout-file
.Sh DESCRIPTION
Reads a fully-linked ELF executable (such as a  linked kernel)
and produces an equivalent a.out format executable file.
.Pp
The
.Nm elf2aout
utility is used to convert native NetBSD ELF binaries
to a.out format, for compatibility with bootblocks and kernel-reading
utilities like
.Xr kvm 3
and
.Xr kvm_mkdb 8 ,
which currently expect an a.out format kernel.
.Pp
.\" .Sh DIAGNOSTICS
.Pp
.Sh SEE ALSO
.Xr elf2ecoff 1 ,
.Xr ld 1 ,
.Xr a.out 5 ,
.Xr elf 5 ,
.Xr kvm 3 ,
.Xr kvm_mkdb 8 .
.Sh BUGS
.Nm Elf2aout
assumes there are no multiply-referenced symbols in the input ELF symbol
section.   It may be necessary to link with
.Nm -x
to avoid such duplicate symbols.
.Pp
In some environments, the GNU binutils
.Nm objcopy
utility may be a better solution than
.Nm elf2aout .
.Sh HISTORY
.Nm Elf2aout
was originally developed  for NetBSD/pmax by Ted Lemon
and was first distributed with the pmax port of
.Nx 1.1 .
