.\" huntd
.\"
.\" Copyright (c) 1983-2003, Regents of the University of California.
.\" All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without 
.\" modification, are permitted provided that the following conditions are 
.\" met:
.\" 
.\" + Redistributions of source code must retain the above copyright 
.\"   notice, this list of conditions and the following disclaimer.
.\" + Redistributions in binary form must reproduce the above copyright 
.\"   notice, this list of conditions and the following disclaimer in the 
.\"   documentation and/or other materials provided with the distribution.
.\" + Neither the name of the University of California, San Francisco nor 
.\"   the names of its contributors may be used to endorse or promote 
.\"   products derived from this software without specific prior written 
.\"   permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS 
.\" IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED 
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
.\" PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
.\" OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
.\" OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.TH HUNTD 6 "21 August 1986"
.UC 4
.SH NAME
huntd \- hunt daemon, back-end for hunt game
.SH SYNOPSIS
\fB/usr/games/lib/huntd\fP [ \fB\-s\fP ] [ \fB\-p\fP port ]
.SH DESCRIPTION
.PP
.I huntd
controls the multi-player
.IR hunt (6)
game.
When it starts up, it tries to notify all members of the
.I hunt-players
mailing list (see
.IR sendmail (8))
by faking a
.IR talk (1)
request from user ``Hunt Game''.
.PP
The
.B \-s
option is for running
.I huntd
forever (server mode).
This is similar to running it under the control of
.I inetd
(see below),
but it consumes a process table entry when no one is playing.
.PP
The
.B \-p
option changes the udp port number used to rendezvous with the player
process and thus allows for private games of hunt.
This option turns off the notification of players on the
.I hunt-players
mailing list.
.SH INETD
.PP
To run
.I huntd
from
.IR inetd ,
you'll need to put the
.I hunt
service in
.BR /etc/services :
.IP
hunt 26740/udp		# multi-player/multi-host mazewars
.LP
and add a line in
.BR /etc/inetd.conf :
.IP
hunt dgram udp wait nobody /usr/games/lib/huntd HUNT
.LP
except for Suns which use
.BR /etc/servers :
.IP
hunt udp /usr/games/lib/huntd
.LP
Do not use any of the command line options \(em if you want
.I inetd
to start up
.I huntd
on a private port, change the port listed in
.BR /etc/services .
.SH "NETWORK RENDEZVOUS"
When
.IR hunt (6)
starts up, it broadcasts on the local area net
(using the broadcast address for each interface) to find a
.I hunt
game in progress.
If a
.I huntd
hears the request, it sends back the port number for the
.I hunt
process to connect to.
Otherwise, the
.I hunt
process starts up a
.I huntd
on the local machine and trys to rendezvous with it.
.SH "SEE ALSO"
hunt(6), talk(1), sendmail(8)
.SH AUTHORS
Conrad Huang, Ken Arnold, and Greg Couch;
.br
University of California, San Francisco, Computer Graphics Lab
.\"SH BUGS
