#	$NetBSD: Makefile,v 1.1.74.1 2014/08/20 00:00:23 tls Exp $

PROG=	huntd
SRCS=	answer.c draw.c driver.c execute.c expl.c \
	extern.c makemaze.c shots.c support.c terminal.c
MAN=	huntd.6

CPPFLAGS+=-I${.CURDIR}/../include

.include <bsd.prog.mk>
