#	$NetBSD: Makefile.openssl,v 1.11 2018/02/04 03:19:51 christos Exp $

.ifndef _MAKEFILE_OPENSSL_INCLUDED
_MAKEFILE_OPENSSL_INCLUDED=1

.include <bsd.own.mk>

OPENSSLSRC=	${CRYPTODIST}/external/bsd/${EXTERNAL_OPENSSL_SUBDIR}/dist
CPPFLAGS+=	-DOPENSSLDIR=\"/etc/openssl\"
CPPFLAGS+=	-DENGINESDIR=\"/usr/lib/openssl\"
CPPFLAGS+=	-DDSO_DLFCN -DHAVE_DLFCN_H

.endif
