make: "cond-op.mk" line 45: Malformed conditional ("!word" == !word)
make: "cond-op.mk" line 70: Malformed conditional (0 ${ERR::=evaluated})
make: "cond-op.mk" line 74: warning: After detecting a parse error, the rest is evaluated.
make: "cond-op.mk" line 78: Parsing continues until here.
make: "cond-op.mk" line 81: A B C   =>   (A || B) && C   A || B && C   A || (B && C)
make: "cond-op.mk" line 88: 0 0 0   =>   0               0             0
make: "cond-op.mk" line 88: 0 0 1   =>   0               0             0
make: "cond-op.mk" line 88: 0 1 0   =>   0               0             0
make: "cond-op.mk" line 88: 0 1 1   =>   1               1             1
make: "cond-op.mk" line 88: 1 0 0   =>   0               1             1
make: "cond-op.mk" line 88: 1 0 1   =>   1               1             1
make: "cond-op.mk" line 88: 1 1 0   =>   0               1             1
make: "cond-op.mk" line 88: 1 1 1   =>   1               1             1
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
