make: "cond-func.mk" line 34: warning: Missing closing parenthesis for defined()
make: "cond-func.mk" line 34: Malformed conditional (!defined(A B))
make: "cond-func.mk" line 49: warning: Missing closing parenthesis for defined()
make: "cond-func.mk" line 49: Malformed conditional (!defined(A&B))
make: "cond-func.mk" line 52: warning: Missing closing parenthesis for defined()
make: "cond-func.mk" line 52: Malformed conditional (!defined(A|B))
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
