Make_ExpandUse: examine all
MakeAddChild: need to examine important
Make_ExpandUse: examine important
MakeAddChild: need to examine optional
MakeAddChild: need to examine optional-cohort
Make_ExpandUse: examine optional
Make_ExpandUse: examine optional-cohort
Examining optional...non-existent...up-to-date.
Examining optional-cohort...non-existent...non-existent and no sources...out-of-date.
: This is not executed.
 recheck(optional-cohort): update time from  0:00:00 Jan 01, 1970 to now
Examining important...non-existent...modified before source "optional-cohort"...out-of-date.
: important is made.
 recheck(important): update time from  0:00:00 Jan 01, 1970 to now
Examining all...non-existent...modified before source "important"...out-of-date.
: all is made.
 recheck(all): update time from  0:00:00 Jan 01, 1970 to now
Examining .END...non-existent...non-existent and no sources...out-of-date.
 recheck(.END): update time from  0:00:00 Jan 01, 1970 to now
exit status 0
