make: "directive-ifmake.mk" line 10: ok: positive condition works
make: "directive-ifmake.mk" line 21: ok: negation works
make: "directive-ifmake.mk" line 27: ok: double negation works
make: "directive-ifmake.mk" line 34: ok: both mentioned
make: "directive-ifmake.mk" line 41: ok: only those mentioned
make: "directive-ifmake.mk" line 51: Targets can even be added at parse time.
make: "directive-ifmake.mk" line 69: ok
: first
: second
: late-target
exit status 0
