make: "directive-endif.mk" line 18: The .endif directive does not take arguments
make: "directive-endif.mk" line 23: The .endif directive does not take arguments
make: "directive-endif.mk" line 34: The .endif directive does not take arguments
make: "directive-endif.mk" line 41: The .endif directive does not take arguments
make: "directive-endif.mk" line 46: Unknown directive "endifx"
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
