make: in target "mod-unknown-direct": while evaluating variable "VAR" with value "TheVariable": Unknown modifier "Z"
make: in target "mod-unknown-indirect": while evaluating variable "VAR" with value "TheVariable": Unknown modifier "Z"
make: in target "unclosed-direct": while evaluating variable "VAR" with value "Thevariable": Unclosed expression, expecting '}' for modifier "S,V,v,"
make: in target "unclosed-indirect": while evaluating variable "VAR" with value "Thevariable": Unclosed expression after indirect modifier, expecting '}'
make: in target "unfinished-indirect": while evaluating variable "VAR" with value "TheVariable": Unfinished modifier (',' missing)
make: in target "unfinished-loop-1": while evaluating variable "UNDEF" with value "1 2 3": Unfinished modifier ('@' missing)
make: in target "unfinished-loop-2": while evaluating variable "UNDEF" with value "1 2 3": Unfinished modifier ('@' missing)
1 2 3
make: in target "loop-close-1": while evaluating variable "UNDEF" with value "1}... 2}... 3}...": Unclosed expression, expecting '}' for modifier "@var@${var}}...@"
1}... 2}... 3}...
make: in target "words-1": while evaluating variable "UNDEF" with value "1 2 3": Unfinished modifier (']' missing)
make: in target "words-2": while evaluating variable "UNDEF" with value "1 2 3": Unfinished modifier (']' missing)
13=
make: in target "words-3": while evaluating variable "UNDEF" with value "1 2 3": Bad modifier ":[123451234512345123451234512345]"
make: in target "exclam-1": while evaluating variable "VARNAME" with value "": Unfinished modifier ('!' missing)
make: in target "exclam-2": while evaluating variable "!" with value "!": Unfinished modifier ('!' missing)
make: in target "mod-subst-delimiter-1": while evaluating variable "VAR" with value "TheVariable": Missing delimiter for modifier ':S'
make: in target "mod-subst-delimiter-2": while evaluating variable "VAR" with value "TheVariable": Unfinished modifier (',' missing)
make: in target "mod-subst-delimiter-3": while evaluating variable "VAR" with value "TheVariable": Unfinished modifier (',' missing)
make: in target "mod-subst-delimiter-4": while evaluating variable "VAR" with value "TheVariable": Unfinished modifier (',' missing)
make: in target "mod-subst-delimiter-5": while evaluating variable "VAR" with value "TheVariable": Unfinished modifier (',' missing)
make: in target "mod-subst-delimiter-6": while evaluating variable "VAR" with value "TheVariable": Unclosed expression, expecting '}' for modifier "S,from,to,"
7: TheVariable
make: in target "mod-regex-delimiter-1": while evaluating variable "VAR" with value "TheVariable": Missing delimiter for modifier ':C'
make: in target "mod-regex-delimiter-2": while evaluating variable "VAR" with value "TheVariable": Unfinished modifier (',' missing)
make: in target "mod-regex-delimiter-3": while evaluating variable "VAR" with value "TheVariable": Unfinished modifier (',' missing)
make: in target "mod-regex-delimiter-4": while evaluating variable "VAR" with value "TheVariable": Unfinished modifier (',' missing)
make: in target "mod-regex-delimiter-5": while evaluating variable "VAR" with value "TheVariable": Unfinished modifier (',' missing)
make: in target "mod-regex-delimiter-6": while evaluating variable "VAR" with value "TheVariable": Unclosed expression, expecting '}' for modifier "C,from,to,"
7: TheVariable
112358132134
15152535558513521534
make: in target "mod-ts-parse-3": while evaluating variable "FIB" with value "1 1 2 3 5 8 13 21 34": Bad modifier ":ts\65oct"
make: in target "mod-ts-parse-4": while evaluating "${:U${FIB}:ts\65oct} # bad modifier, variable name is """ with value "1 1 2 3 5 8 13 21 34": Bad modifier ":ts\65oct"
make: in target "mod-ts-parse-5": while evaluating variable "FIB" with value "1 1 2 3 5 8 13 21 34": Bad modifier ":tsxy"
make: in target "mod-t-parse-1": while evaluating variable "FIB" with value "1 1 2 3 5 8 13 21 34": Bad modifier ":t"
make: in target "mod-t-parse-2": while evaluating variable "FIB" with value "1 1 2 3 5 8 13 21 34": Bad modifier ":txy"
make: in target "mod-t-parse-3": while evaluating variable "FIB" with value "1 1 2 3 5 8 13 21 34": Bad modifier ":t"
make: in target "mod-t-parse-4": while evaluating variable "FIB" with value "1 1 2 3 5 8 13 21 34": Bad modifier ":t"
make: in target "mod-ifelse-parse-1": while evaluating then-branch of condition "FIB": Unfinished modifier (':' missing)
make: in target "mod-ifelse-parse-2": while evaluating then-branch of condition "FIB": Unfinished modifier (':' missing)
make: in target "mod-ifelse-parse-3": while evaluating else-branch of condition "FIB": Unfinished modifier ('}' missing)
make: in target "mod-ifelse-parse-4": while evaluating else-branch of condition "FIB": Unfinished modifier ('}' missing)
then
1 1 2 3 5 8 13 21 34
make: in target "mod-remember-parse": while evaluating variable "FIB" with value "1 1 2 3 5 8 13 21 34": Unknown modifier "__"
make: in target "mod-sysv-parse-1": while evaluating variable "FIB" with value "1 1 2 3 5 8 13 21 34": Unknown modifier "3"
make: in target "mod-sysv-parse-1": while evaluating variable "FIB" with value "": Unclosed expression, expecting '}' for modifier "3"
make: in target "mod-sysv-parse-2": while evaluating variable "FIB" with value "1 1 2 3 5 8 13 21 34": Unknown modifier "3="
make: in target "mod-sysv-parse-2": while evaluating variable "FIB" with value "": Unclosed expression, expecting '}' for modifier "3="
make: in target "mod-sysv-parse-3": while evaluating variable "FIB" with value "1 1 2 3 5 8 13 21 34": Unknown modifier "3=x3"
make: in target "mod-sysv-parse-3": while evaluating variable "FIB" with value "": Unclosed expression, expecting '}' for modifier "3=x3"
1 1 2 x3 5 8 1x3 21 34
exit status 2
