path=':/bin:/tmp::/:.:/no/such/dir:.'
path='/bin:/tmp:/:/no/such/dir'
path='/bin:/tmp:/:/no/such/dir'
path='/bin':'/tmp':'/':'/no/such/dir'
path='/bin':'/tmp':'/':'/no/such/dir'
path_/usr/xbin=/opt/xbin/
paths=/bin /tmp / /no/such/dir /opt/xbin
PATHS=/BIN /TMP / /NO/SUCH/DIR /OPT/XBIN
The answer is 42
dirname of 'a/b/c def a.b.c a.b/c a a.a .gitignore a a.a' is 'a/b . . a.b . . . . .'
basename of 'a/b/c def a.b.c a.b/c a a.a .gitignore a a.a' is 'c def a.b.c c a a.a .gitignore a a.a'
suffix of 'a/b/c def a.b.c a.b/c a a.a .gitignore a a.a' is 'c b/c a gitignore a'
root of 'a/b/c def a.b.c a.b/c a a.a .gitignore a a.a' is 'a/b/c def a.b a a a a a'
S:
C:
@:
S:empty
C:empty
@:
mod-S:
:a b b c:
:a b b c:
: b c:
:a c:
:x__ 3 x__ 3:
12345
mod-C:
:a b b c:
:a b b c:
: b c:
make: RE substitution error: (details omitted)
make: Unclosed substitution for  (, missing)
:C,word,____,:Q}:
:a c:
:x__ 3 x__ 3:
:+one+ +two+ +three+:
mod-at-resolve:w1d2d3w w2i3w w1i2d3 2i${RES3}w w1d2d3 2i${RES3} 1i${RES2}w:
mod-at-dollar:(1) (2) (3).
mod-at-dollar:() () ().
mod-at-dollar:() () ().
mod-subst-dollar:$1:
mod-subst-dollar:$2:
mod-subst-dollar:$3:
mod-subst-dollar:$4:
mod-subst-dollar:$5:
mod-subst-dollar:$6:
mod-subst-dollar:$7:
mod-subst-dollar:$8:
mod-subst-dollar:U8:
mod-subst-dollar:$$$$:
mod-loop-dollar:1:
mod-loop-dollar:${word}$:
mod-loop-dollar:$3$:
mod-loop-dollar:$${word}$$:
mod-loop-dollar:$$5$$:
mod-loop-dollar:$$${word}$$$:
mod-C-limits:00-ok:1 2323 45456
make: No subexpression \1
make: No subexpression \1
make: No subexpression \1
make: No subexpression \1
mod-C-limits:11-missing:1 6
mod-C-limits:11-ok:1 22 446
make: No subexpression \2
make: No subexpression \2
make: No subexpression \2
make: No subexpression \2
mod-C-limits:22-missing:1 6
make: No subexpression \2
make: No subexpression \2
make: No subexpression \2
make: No subexpression \2
mod-C-limits:22-missing:1 6
mod-C-limits:22-ok:1 33 556
mod-C-limits:capture:ihgfedcbaabcdefghijABCDEFGHIJa0a1a2rest
mod-assign: first=1.
mod-assign: last=3.
mod-assign: appended=1 2 3.
1
2
3
mod-assign: ran:3.
mod-assign: global: 1, 3, 1 2 3, 3.
mod-assign-nested: then1t1
mod-assign-nested: else2e2
mod-assign-nested: then3t3
mod-assign-nested: else4e4
mod-tu-space: A   B
mod-Q: new

line
exit status 0
