: 'Making made-target.'
false
*** Error code 1 (continuing)
false
*** Error code 1 (continuing)
`all' not remade because of errors.
#*** Input graph:
# made-target, made MADE, type OP_DEPENDS|OP_PHONY|OP_HAS_COMMANDS|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_ALLSRC
#
# *** MAIN TARGET ***
# No unmade children
# last modified <timestamp>: made
# parents: all
made-target     :
	(null)


# error-target, made ERROR, type OP_DEPENDS|OP_PHONY|OP_HAS_COMMANDS|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_ALLSRC
#
# No unmade children
# nonexistent (maybe): error when made
# parents: all
error-target    :
	(null)


# aborted-target, made ABORTED, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND|OP_MARK, flags none
# aborted-target-dependency, made ERROR, type OP_DEPENDS|OP_PHONY|OP_HAS_COMMANDS|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_ALLSRC
#
# No unmade children
# nonexistent (maybe): error when made
# parents: aborted-target
aborted-target-dependency:
	(null)


# all, made ABORTED, type OP_DEPENDS|OP_DEPS_FOUND, flags CHILDMADE|FORCE
#
# 3 unmade children
# nonexistent (maybe): aborted
all             : made-target error-target aborted-target


# .END, made UNMADE, type OP_SPECIAL, flags none


#
#   Files that are only sources:
#	.END [.END]
#*** Global Variables:
.ALLTARGETS      =  made-target error-target aborted-target aborted-target-dependency all .END
.CURDIR          = <curdir>
.INCLUDES        = 
.LIBS            = 
.MAKE            = <details omitted>
.MAKE.DEPENDFILE = <details omitted>
.MAKE.GID        = <details omitted>
.MAKE.LEVEL      = <details omitted>
.MAKE.MAKEFILES  = <details omitted>
.MAKE.MAKEFILE_PREFERENCE = <details omitted>
.MAKE.OS         = <details omitted>
.MAKE.PATH_FILEMON = <details omitted>
.MAKE.PID        = <details omitted>
.MAKE.PPID       = <details omitted>
.MAKE.UID        = <details omitted>
.MAKEFLAGS       =  -r -k -d g2
.MAKEOVERRIDES   = 
.OBJDIR          = <curdir>
.PATH            = . <curdir>
.TARGETS         =  all
.newline         = 

MACHINE          = <details omitted>
MACHINE_ARCH     = <details omitted>
MAKE             = <details omitted>
MFLAGS           =   -r -k -d g2
#*** Command-line Variables:
.MAKE.LEVEL.ENV  = MAKELEVEL
.SHELL           = <details omitted>

#*** Directory Cache:
# Stats: 0 hits 4 misses 0 near misses 0 losers (0%)
#  refs  hits  directory
#     1     0  <curdir>
#     1     0  .
#     1     0  <defsyspath>

#*** Suffixes:
#*** Transformations:

Stop.
make: stopped in unit-tests
exit status 1
