: Making var-scope-local.c out of nothing.
: Making var-scope-local.o from var-scope-local.c.
: Making basename "var-scope-local.o" in "." from "var-scope-local.c" in "." VAR="local".
: Making var-scope-local2.c out of nothing.
: Making var-scope-local2.o from var-scope-local2.c.
: Making basename "var-scope-local2.o" in "." from "var-scope-local2.c" in "." VAR="local to var-scope-local2.o".
: Making var-scope-local3.c out of nothing.
: var-scope-local3.o uses .USE VAR="global+local"
: all overwritten VAR="global"
exit status 0
