make: Bad modifier ":OX" for variable "NUMBERS"
make: "varmod-order.mk" line 13: Undefined variable "${NUMBERS:OX"
make: Bad modifier ":OxXX" for variable "NUMBERS"
make: "varmod-order.mk" line 16: Undefined variable "${NUMBERS:Ox"
make: Unclosed variable expression, expecting '}' for modifier "O" of variable "NUMBERS" with value "eight five four nine one seven six ten three two"
make: Unclosed variable expression, expecting '}' for modifier "On" of variable "NUMBERS" with value "ten two three four five six seven eight nine one"
make: Unclosed variable expression, expecting '}' for modifier "Onr" of variable "NUMBERS" with value "ten two three four five six seven eight nine one"
make: Bad modifier ":Oxn" for variable "NUMBERS"
make: "varmod-order.mk" line 28: Malformed conditional (${NUMBERS:Oxn})
make: Bad modifier ":On_typo" for variable "NUMBERS"
make: "varmod-order.mk" line 38: Malformed conditional (${NUMBERS:On_typo})
make: Bad modifier ":Onr_typo" for variable "NUMBERS"
make: "varmod-order.mk" line 47: Malformed conditional (${NUMBERS:Onr_typo})
make: Bad modifier ":Orn_typo" for variable "NUMBERS"
make: "varmod-order.mk" line 56: Malformed conditional (${NUMBERS:Orn_typo})
make: Bad modifier ":Onn" for variable "NUMBERS"
make: "varmod-order.mk" line 67: Malformed conditional (${NUMBERS:Onn})
make: Bad modifier ":Onrr" for variable "NUMBERS"
make: "varmod-order.mk" line 76: Malformed conditional (${NUMBERS:Onrr})
make: Bad modifier ":Orrn" for variable "NUMBERS"
make: "varmod-order.mk" line 85: Malformed conditional (${NUMBERS:Orrn})
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
