make: "varmod-match.mk" line 236: warning: Unfinished character list in pattern 'a[' of modifier ':M'
make: "varmod-match.mk" line 244: warning: Unfinished character list in pattern 'a[^' of modifier ':M'
make: "varmod-match.mk" line 252: warning: Unfinished character list in pattern '[-x1-3' of modifier ':M'
make: "varmod-match.mk" line 260: warning: Unfinished character list in pattern '*[-x1-3' of modifier ':M'
make: "varmod-match.mk" line 269: warning: Unfinished character list in pattern '[^-x1-3' of modifier ':M'
make: "varmod-match.mk" line 283: warning: Unfinished character list in pattern '?[\' of modifier ':M'
make: "varmod-match.mk" line 291: warning: Unfinished character range in pattern '[x-' of modifier ':M'
make: "varmod-match.mk" line 303: warning: Unfinished character range in pattern '[^x-' of modifier ':M'
make: "varmod-match.mk" line 311: warning: Unfinished character list in pattern '[' of modifier ':M'
make: "varmod-match.mk" line 311: Unknown modifier "]"
make: "varmod-match.mk" line 311: Malformed conditional (${ ${:U\:} ${:U\:\:} :L:M[:]} != ":")
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
