make: "varmod-to-separator.mk" line 106: warning: The separator \400 is accepted even though it is out of bounds.
make: "varmod-to-separator.mk" line 118: warning: The separator \x100 is accepted even though it is out of bounds.
make: Bad modifier `:ts\-300' for WORDS
make: "varmod-to-separator.mk" line 124: Malformed conditional (${WORDS:[1..3]:ts\-300:tu})
make: Bad modifier `:ts\8' for 1 2 3
make: "varmod-to-separator.mk" line 132: Malformed conditional (${1 2 3:L:ts\8:tu})
make: Bad modifier `:ts\100L' for 1 2 3
make: "varmod-to-separator.mk" line 139: Malformed conditional (${1 2 3:L:ts\100L})
make: Bad modifier `:ts\x40g' for 1 2 3
make: "varmod-to-separator.mk" line 146: Malformed conditional (${1 2 3:L:ts\x40g})
make: Bad modifier `:tx' for WORDS
make: "varmod-to-separator.mk" line 154: Malformed conditional (${WORDS:tx} != "anything")
make: Bad modifier `:t\X' for WORDS
make: "varmod-to-separator.mk" line 161: Malformed conditional (${WORDS:t\X} != "anything")
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
