mod-regex:
:a b b c:
:a b b c:
: b c:
make: Regex compilation error: (details omitted)
:C,word,____,:Q}:
:a c:
:x__ 3 x__ 3:
mod-regex-limits:00-ok:1 2323 45456
make: No subexpression \1
make: No subexpression \1
make: No subexpression \1
make: No subexpression \1
mod-regex-limits:11-missing:1 6
mod-regex-limits:11-ok:1 22 446
make: No subexpression \2
make: No subexpression \2
make: No subexpression \2
make: No subexpression \2
mod-regex-limits:22-missing:1 6
make: No subexpression \2
make: No subexpression \2
make: No subexpression \2
make: No subexpression \2
mod-regex-limits:22-missing:1 6
mod-regex-limits:22-ok:1 33 556
mod-regex-limits:capture:ihgfedcbaabcdefghijABCDEFGHIJa0a1a2rest
make: Regex compilation error: (details omitted)
mod-regex-errors:
exit status 0
