make: "varmod-range.mk" line 43: Malformed conditional '${:range=5} != ""'
make: "varmod-range.mk" line 67: Invalid number "x}Rest" != "Rest"" for ':range' modifier
	while evaluating "${:U:range=x}Rest" != "Rest"" with value ""
make: "varmod-range.mk" line 67: Malformed conditional '"${:U:range=x}Rest" != "Rest"'
make: "varmod-range.mk" line 78: Unknown modifier "x0"
	while evaluating "${:U:range=0x0}Rest" != "Rest"" with value "1"
make: "varmod-range.mk" line 78: Malformed conditional '"${:U:range=0x0}Rest" != "Rest"'
make: "varmod-range.mk" line 96: Unknown modifier "rang"
	while evaluating variable "a b c" with value "a b c"
make: "varmod-range.mk" line 96: Malformed conditional '"${a b c:L:rang}Rest" != "Rest"'
make: "varmod-range.mk" line 105: Unknown modifier "rango"
	while evaluating variable "a b c" with value "a b c"
make: "varmod-range.mk" line 105: Malformed conditional '"${a b c:L:rango}Rest" != "Rest"'
make: "varmod-range.mk" line 114: Unknown modifier "ranger"
	while evaluating variable "a b c" with value "a b c"
make: "varmod-range.mk" line 114: Malformed conditional '"${a b c:L:ranger}Rest" != "Rest"'
make: Fatal errors encountered -- cannot continue
make: stopped making "all" in unit-tests
exit status 1
