make: "varmod-gmtime.mk" line 70: Invalid time value "-1"
make: "varmod-gmtime.mk" line 70: Malformed conditional (${:L:gmtime=-1} != "")
make: "varmod-gmtime.mk" line 79: Invalid time value " 1"
make: "varmod-gmtime.mk" line 79: Malformed conditional (${:L:gmtime= 1} != "")
make: "varmod-gmtime.mk" line 125: Invalid time value "10000000000000000000000000000000"
make: "varmod-gmtime.mk" line 125: Malformed conditional (${:L:gmtime=10000000000000000000000000000000} != "")
make: "varmod-gmtime.mk" line 136: Invalid time value "error"
make: "varmod-gmtime.mk" line 136: Malformed conditional (${:L:gmtime=error} != "")
make: "varmod-gmtime.mk" line 145: Invalid time value "100000S,1970,bad,"
make: "varmod-gmtime.mk" line 145: Malformed conditional (${%Y:L:gmtime=100000S,1970,bad,} != "bad")
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
