make: "varmod.mk" line 111: To escape a dollar, use \$, not $$, at "$$:L} != """
make: "varmod.mk" line 111: Invalid variable name ':', at "$:L} != """
make: "varmod.mk" line 117: Dollar followed by nothing
	while evaluating "${:Uword:@word@${word}$@} != "word"" with value "word"
make: "varmod.mk" line 127: Missing delimiter ':' after modifier "P"
	while evaluating variable "VAR" with value "VAR"
make: "varmod.mk" line 129: Missing argument for ".error"
make: "varmod.mk" line 135: Bad modifier ":[99333000222000111000]"
	while evaluating variable "word" with value "word"
make: "varmod.mk" line 138: Bad modifier ":[2147483648]"
	while evaluating variable "word" with value "word"
make: "varmod.mk" line 144: Invalid number "99333000222000111000}" for ':range' modifier
	while evaluating variable "word" with value "word"
make: "varmod.mk" line 151: Invalid time value "\"
	while evaluating indirect modifiers "gmtime=\"
	while evaluating "${:${:Ugmtime=\\}}" with value ""
make: "varmod.mk" line 166: Dollar followed by nothing
	while evaluating variable "VAR" with value "value$"
make: "varmod.mk" line 172: Dollar followed by nothing
	while evaluating variable "VAR" with value "value$"
make: "varmod.mk" line 172: Dollar followed by nothing
	while evaluating variable "VAR" with value "value$ appended$"
make: "varmod.mk" line 182: Dollar followed by nothing
	while evaluating variable "word" with value "word"
make: "varmod.mk" line 186: Bad modifier ":[$]"
	while evaluating variable "word" with value ""
make: "varmod.mk" line 203: Dollar followed by nothing
	while evaluating variable "VAR" with value "value$ appended$"
make: "varmod.mk" line 203: Invalid variable name '}', at "$} != "set""
	while evaluating variable "VAR" with value "value<space>appended"
make: "varmod.mk" line 207: Invalid variable name '}', at "$} != "fallback""
	while evaluating "${:Ufallback$} != "fallback"" with value ""
make: "varmod.mk" line 211: Invalid time value "1000$"
	while evaluating variable "%y" with value "%y"
make: "varmod.mk" line 217: Invalid time value "1000$"
	while evaluating variable "%y" with value "%y"
make: "varmod.mk" line 223: Dollar followed by nothing
	while evaluating variable "word" with value "word"
make: "varmod.mk" line 227: Dollar followed by nothing
	while evaluating variable "word" with value "word"
make: "varmod.mk" line 231: Invalid argument 'fallback$' for modifier ':mtime'
	while evaluating variable "." with value "."
make: "varmod.mk" line 245: Missing delimiter ':' after modifier "L"
	while evaluating variable "VAR" with value "VAR"
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
