dollars_stage_0: MAKEFLAGS=< -r -k >
dollars_stage_1: env MAKEFLAGS=< -r -k DOLLARS=\$\{varname\}>
dollars_stage_1: MAKEFLAGS=< -r -k DOLLARS=\{varname\}>
dollars_stage_1: MAKEFLAGS:q=< -r -k DOLLARS=\{varname\}>
dollars_stage_2: env MAKEFLAGS=< -r -k DOLLARS=>
dollars_stage_2: dollars=<>
dollars_stage_2: MAKEFLAGS=< -r -k DOLLARS=>
dollars_stage_3: env MAKEFLAGS=< -r -k DOLLARS=>
dollars_stage_3: dollars=<>
dollars_stage_3: MAKEFLAGS=< -r -k DOLLARS=>
exit status 0
