#	$NetBSD: Makefile,v 1.43.2.1 2013/02/25 00:28:29 tls Exp $

INCSDIR= /usr/include/arm

INCS=	aeabi.h ansi.h aout_machdep.h armreg.h asm.h atomic.h \
	bswap.h byte_swap.h \
	cdefs.h cpu.h cpuconf.h \
	disklabel.h \
	elf_machdep.h endian.h endian_machdep.h \
	float.h frame.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	kcore.h \
	limits.h lock.h \
	math.h mcontext.h mutex.h \
	param.h pcb.h pmc.h proc.h profile.h rwlock.h \
	ptrace.h \
	reg.h rwlock.h \
	setjmp.h signal.h swi.h sysarch.h \
	trap.h types.h \
	vfpreg.h \
	wchar_limits.h

.include <bsd.kinc.mk>
