#	$NetBSD: Makefile,v 1.22 2012/11/25 21:55:51 alnsn Exp $

INCSDIR= /usr/include/sgimips

INCS=	asm.h ansi.h autoconf.h \
	bswap.h \
	cdefs.h cpu.h \
	disklabel.h \
	ecoff_machdep.h elf_machdep.h endian.h endian_machdep.h \
	float.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intr.h \
	kcore.h kdbparam.h \
	limits.h lock.h locore.h \
	math.h mcontext.h mips_opcode.h mutex.h \
	param.h pci_machdep.h pcb.h pmap.h pmc.h proc.h profile.h psl.h pte.h \
	ptrace.h \
	reg.h regdef.h regnum.h reloc.h rwlock.h \
	setjmp.h signal.h sljitarch.h \
	trap.h types.h \
	vmparam.h \
	wchar_limits.h \
	z8530var.h \

.include <bsd.kinc.mk>
