#	$NetBSD: Makefile,v 1.1 2014/07/26 19:30:45 dholland Exp $
#
# Makefile for hpcsh
#

MENUS_MD=	menus.md.${SYSINSTLANG} menus.mbr
MSG_MD=		msg.md.${SYSINSTLANG} msg.mbr.${SYSINSTLANG}

LANGUAGES=	# no translations ready yet

.include "../../Makefile.inc"
