#	$NetBSD: Makefile,v 1.1.1.1 2003/09/11 18:37:09 lukem Exp $

XTODO=	only install on make distribution??

.include <bsd.own.mk>

.PATH:	${X11SRCDIR.xc}/lib/fontconfig

FILESDIR=/etc/fonts
FILES=	fonts.conf fonts.dtd

.include <bsd.prog.mk>
.include <bsd.x11.mk>
