.\" $NetBSD: amidisplaycc.4,v 1.9 2003/11/12 19:42:27 wiz Exp $
.Dd November 12, 2003
.Dt AMIDISPLAYCC 4 amiga
.Sh NAME
.Nm amidisplaycc
.Nd wscons interface to amiga custom chips drivers
.Sh SYNOPSIS
.Cd amidisplaycc0 at mainbus0
.Cd wsdisplay0 at amidisplaycc0
.Sh DESCRIPTION
This device acts as an adapter between the
.Xr wscons 4
framework and the Amiga custom chip driver functions.
It exports the internal
.Xr wsdisplay 4
interface and contains the necessary rendering functions to
operate a text terminal with virtual screens. It uses the
Amiga abstract graphic driver (grfabs) functions for the low-level
display management.
.Pp
Currently it does not support running X.
It can however coexist well enough with grf0 to make possible running
X the old way, but be warned, you cannot switch screens while
in X and when quitting it, it seems to hang. Switching a screen
then will bring up the text console. As always, we apologise for
the inconvenience.
.Pp
What it does support is hilite (bold), underline, reverse and
foreground/background colors.
.Ss Virtual terminals and screen types
The number of virtual screens is limited only by
the available chip memory.
.Pp
Each virtual screen can have a different screen type.
A screen type defines the following things: height and width
in pixels, number of colors, and font size.
The supported screen types are listed below.
.Bl -bullet -offset indent -compact
.It
80x64 - display size 640x512 with 8 colors, font size 8x8
.It
80x51 - display size 640x510 with 8 colors, font size 8x10
.It
80x50 - display size 640x400 with 8 colors, font size 8x8
.It
80x40 - display size 640x400 with 8 colors, font size 8x10
.It
80x32 - display size 640x512 with 8 colors, font size 8x16
.It
80x31 - display size 640x248 with 8 colors, font size 8x8
.It
80x25 - display size 640x400 with 8 colors, font size 8x16
.It
80x24 - display size 640x192 with 8 colors, font size 8x8
.It
default - same as either 80x64 or 80x50, depending on the presence
of GRF_NTSC and GRF_PAL in the kernel configuration.
.El
.Pp
The grfabs code determines the actual screen mode that is used.
The config options GRF_NTSC, GRF_PAL, GRF_AGA, etc. determine
what kind of chipsets/modes are available.
.Ss Fonts
Fonts of width 8 and any height are supported.
Fonts can be compiled into the kernel by specifying "options FONT_[fontname]"
in the configuration file, or loaded with the
.Xr wsfontload 8
utility runtime.
.Sh SEE ALSO
.Xr wscons 4 ,
.Xr wsdisplay 4 ,
.Xr wsfontload 8 ,
.Xr wsfont 9
