#	$NetBSD: Makefile,v 1.1 2011/02/06 18:44:29 pooka Exp $
#

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/lib/librumphijack

TESTS_SH=	t_tcpip
TESTS_C=	h_netget

FILES=		netstat.expout index.html
FILESDIR=	${TESTSDIR}

ATFFILE=	yes

.include <bsd.test.mk>
