/*-
 * Copyright (c) 2017 Mediatek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _ARM_MEDIATEK_MERCURY_REG_H
#define _ARM_MEDIATEK_MERCURY_REG_H

#define MTK_ARMTIMER_FREQ		(13*1000*1000)	/* 13MHz */
#define MTK_UART_FREQ			(26*1000*1000)

#define MTK_DRAM_BASE			(0x40000000)

#define MTK_IO_PHYS				(0x10000000)
#define MTK_IO_SIZE				(0x10000000)//(0x02000000)

/* IO register definitions */
#define PERICFG_BASE			(MTK_IO_PHYS + 0x00003000)
#define GPIO_BASE				(MTK_IO_PHYS + 0x00005000)
#define SLEEP_BASE				(MTK_IO_PHYS + 0x00006000)
#define TOP_RGU_BASE			(MTK_IO_PHYS + 0x00007000)
#define APXGPT_BASE				(MTK_IO_PHYS + 0x00008000)
#define EFUSEC_BASE				(MTK_IO_PHYS + 0x00009000)
#define PWRAP_REG_OFFSET		(0x0000f000)
#define PWRAP_BASE			(MTK_IO_PHYS + PWRAP_REG_OFFSET)
#define PWRAP_REG_SIZE			(0x1000)

#define MCUSYS_CFGREG_OFFSET		(0x00200000)
#define MCUSYS_CFGREG_BASE		(MTK_IO_PHYS + MCUSYS_CFGREG_OFFSET)
#define INT_POL_CTL0_OFFSET		(MCUSYS_CFGREG_OFFSET + 0x620)

#define UART0_REG_OFFSET		(0x01005000)
#define UART0_REG_BASE			(MTK_IO_PHYS + UART0_REG_OFFSET)
#define UART0_REG_SIZE			(0x1000)
#define UART1_REG_OFFSET		(0x01006000)
#define UART1_REG_BASE			(MTK_IO_PHYS + UART1_REG_OFFSET)
#define UART1_REG_SIZE			(0x1000)
#define UART2_REG_OFFSET		(0x01007000)
#define UART2_REG_BASE			(MTK_IO_PHYS + UART2_REG_OFFSET)
#define UART2_REG_SIZE			(0x1000)

#define I2C0_REG_OFFSET			(0x01009000)
#define I2C0_REG_BASE			(MTK_IO_PHYS + I2C0_REG_OFFSET)
#define I2C0_REG_SIZE			(0x70)
#define I2C1_REG_OFFSET			(0x0100a000)
#define I2C1_REG_BASE			(MTK_IO_PHYS + I2C1_REG_OFFSET)
#define I2C1_REG_SIZE			(0x70)
#define I2C2_REG_OFFSET			(0x0100b000)
#define I2C2_REG_BASE			(MTK_IO_PHYS + I2C2_REG_OFFSET)
#define I2C2_REG_SIZE			(0x70)

#define USB0_REG_OFFSET			(0x01100000)
#define USB0_REG_BASE			(MTK_IO_PHYS + USB0_REG_OFFSET)
#define USB0_REG_SIZE			(0x1000)
#define USB1_REG_OFFSET			(0x01190000)
#define USB1_REG_BASE			(MTK_IO_PHYS + USB1_REG_OFFSET)
#define USB1_REG_SIZE			(0x1000)

#define MSDC0_REG_OFFSET		(0x01120000)
#define MSDC0_REG_BASE			(MTK_IO_PHYS + MSDC0_REG_OFFSET)
#define MSDC0_REG_SIZE			(0x1000)
#define MSDC1_REG_OFFSET		(0x01130000)
#define MSDC1_REG_BASE			(MTK_IO_PHYS + MSDC1_REG_OFFSET)
#define MSDC1_REG_SIZE			(0x1000)
#define MSDC2_REG_OFFSET		(0x01170000)
#define MSDC2_REG_BASE			(MTK_IO_PHYS + MSDC2_REG_OFFSET)
#define MSDC2_REG_SIZE			(0x1000)

#define MTK_WDT_OFFSET			(0x00007000)
#define MTK_WDT_MODE			(MTK_WDT_OFFSET+0x0000)
#define MTK_WDT_LENGTH			(MTK_WDT_OFFSET+0x0004)
#define MTK_WDT_RESTART			(MTK_WDT_OFFSET+0x0008)
#define MTK_WDT_STATUS			(MTK_WDT_OFFSET+0x000C)
#define MTK_WDT_INTERVAL		(MTK_WDT_OFFSET+0x0010)
#define MTK_WDT_SWRST			(MTK_WDT_OFFSET+0x0014)
#define MTK_WDT_SWSYSRST		(MTK_WDT_OFFSET+0x0018)
#define MTK_WDT_NONRST_REG		(MTK_WDT_OFFSET+0x0020)
#define MTK_WDT_NONRST_REG2		(MTK_WDT_OFFSET+0x0024)
#define MTK_WDT_REQ_MODE		(MTK_WDT_OFFSET+0x0030)
#define MTK_WDT_REQ_IRQ_EN		(MTK_WDT_OFFSET+0x0034)
#define MTK_WDT_DRAMC_CTL		(MTK_WDT_OFFSET+0x0040)

/*WDT_MODE*/
#define MTK_WDT_MODE_KEYMASK	(0xff00)
#define MTK_WDT_MODE_KEY		(0x22000000)

#define MTK_WDT_MODE_DUAL_MODE  (0x0040)
#define MTK_WDT_MODE_IN_DIS		(0x0020) /* Reserved */
#define MTK_WDT_MODE_AUTO_RESTART	(0x0010) /* Reserved */
#define MTK_WDT_MODE_IRQ		(0x0008)
#define MTK_WDT_MODE_EXTEN		(0x0004)
#define MTK_WDT_MODE_EXT_POL	(0x0002)
#define MTK_WDT_MODE_ENABLE		(0x0001)


#endif /* _ARM_MEDIATEK_MERCURY_REG_H */
