#	$NetBSD: Makefile,v 1.22 2014/01/23 07:26:51 spz Exp $

SUBDIR= amd apm asm disktab emul fstab ftpd getdate hostapd \
        isdn lua npf pppd racoon supfiles syslogd wpa_supplicant wsmoused

.include <bsd.subdir.mk>
