#	$NetBSD: Makefile,v 1.3.4.1 2015/12/27 12:09:41 skrll Exp $

INCSDIR= /usr/include/rs6000

INCS=   bootinfo.h \
	disklabel.h \
	fenv.h \
	intr.h \
	sljit_machdep.h \
	vmparam.h

.include "../../powerpc/include/Makefile"
