.\" $NetBSD: pam_afslog.8,v 1.2 2005/09/23 19:56:16 wiz Exp $
.\"
.\" Copyright 2005 Tyler C. Sarna <tsarna@netbsd.org>
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Tyler C. Sarna
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Neither the name of The NetBSD Foundation nor the names of its
.\"    contributors may be used to endorse or promote products derived
.\"    from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd September 20, 2005
.Dt PAM_AFSLOG 8
.Os
.Sh NAME
.Nm pam_afslog
.Nd AFS credentials PAM module
.Sh SYNOPSIS
.Op Ar service-name
.Ar module-type
.Ar control-flag
.Pa pam_afslog
.Op Ar arguments
.Sh DESCRIPTION
The
.Nm
authentication service module for PAM provides functionality for
only one PAM category: authentication
.Ar ( module-type
of
.Dq Li auth ) .
.Pp
The
.Fn pam_sm_authenticate
function does nothing and thus the module should be used with an
.Ar control-flag
of
.Dq Li optional .
.Pp
The value of the module comes from its
.Fn pam_sm_setcred
function.
If the
.Ar afslog
parameter is enabled in
.Xr krb5.conf 5 ,
then the module will take Kerberos 5 credentials from the cache
created by
.Xr pam_krb5 8
and convert them into AFS tokens, after first creating a PAG (Process
Authentication Group) if necessary.
.Sh SEE ALSO
.Xr kafs 3 ,
.Xr pam.conf 5 ,
.Xr pam 8 ,
.Xr pam_krb5 8
.Sh HISTORY
The
.Nm
module was developed for
.Nx
by
.An Tyler C. Sarna .
The
.Nm
module appeared in
.Nx 4.0 .
