#	$NetBSD: Makefile,v 1.1.2.2 2015/04/06 15:18:08 skrll Exp $

INCSDIR= /usr/include/dev/hdaudio

# Only install includes which are used by userland
INCS=	hdaudioio.h hdaudioreg.h

.include <bsd.kinc.mk>
