#	$NetBSD: Makefile,v 1.18 2003/10/20 00:12:10 matt Exp $

INCSDIR= /usr/include/macppc

# Add the macppc specific includes.

INCS=	adbsys.h apmvar.h autoconf.h \
	disklabel.h \
	grfioctl.h \
	intr.h \
	keyboard.h \
	vmparam.h

.include "../../powerpc/include/Makefile"
