#	$NetBSD: Makefile,v 1.2 2002/11/26 23:30:32 lukem Exp $

INCSDIR= /usr/include/netccitt

INCS=	dll.h hd_var.h hdlc.h llc_var.h pk.h pk_extern.h pk_var.h x25.h \
	x25acct.h x25err.h

.include <bsd.kinc.mk>
