# $NetBSD: Makefile,v 1.15.10.1 2005/11/10 13:50:23 skrll Exp $

SUBDIR=		mkbootimage setnetbootinfo
SUBDIR+=	boot bootxx_cd9660 bootxx_ffs bootxx_ffsv2 bootxx_lfs
SUBDIR+=	netboot ustarboot

.include <bsd.subdir.mk>
