#	@(#)Makefile.irix	8.1 (Berkeley) 6/6/93
#
# $Id: Makefile.irix,v 1.1.1.1 1994/06/13 19:56:07 mycroft Exp $
#
# Extra Makefile definitions for IRIX
#

DEBUG = #-g -DDEBUG
CCOPTS = -I/usr/include/sun -I/usr/include/bsd -DIRIX
RESOLV = -lrpcsvc -lsun -lbsd
