#	from: @(#)Makefile.irix3	8.1 (Berkeley) 6/6/93
#	$Id: Makefile.irix3,v 1.3 1994/06/13 20:48:38 mycroft Exp $
#
# Extra Makefile definitions for IRIX
#

# For 3.3.x and earlier we might need to indicate the Sun and BSD include
# paths.
 
DEBUG = #-g -DDEBUG
CCOPTS = -I/usr/include/sun -I/usr/include/bsd
RESOLV = -lrpcsvc -lsun -lbsd
