.\"
.\" Copyright (c) 1992/3 Theo de Raadt <deraadt@fsa.ca>
.\" All rights reserved.
.\" Portions Copyright (c) 1994 Jason R. Thorpe.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote
.\"    products derived from this software without specific prior written
.\"    permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
.\" OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
.\" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     from: @(#)yp.8	1.0 (deraadt) 4/26/93
.\"	$Id: yp.8,v 1.6 1994/11/14 06:30:36 deraadt Exp $
.\"
.Dd April 5, 1993
.Dt YP 8
.Os
.Sh NAME
.Nm yp
.Nd description of the YP subsystem
.Sh SYNOPSIS
.Nm ypbind
.Op Fl ypset
.Nm ypbind
.Op Fl ypsetme
.Pp
.Nm ypset
.Op Fl h Ar host
.Op Fl d Ar domain
.Ar server
.Pp
.Nm yppoll
.Op Fl h Ar host
.Op Fl d Ar domain
.Ar mapname
.Pp
.Nm ypcat
.Op Fl kt
.Op Fl d Ar domainname
.Ar mapname
.Nm ypcat
.Fl x
.Pp
.Nm ypmatch
.Op Fl kt
.Op Fl d Ar domainname
.Ar key ... mapname
.Nm ypmatch
.Fl x
.Pp
.Nm ypwhich
.Op Fl d Ar domain
.Oo
.Op Fl t
.Fl m Op Ar mname
|
.Ar host
.Oc
.Nm ypwhich
.Fl x
.Sh DESCRIPTION
The
.Nm YP
subsystem allows network management of passwd and group file
entries through the functions
.Xr getpwent 3
and
.Xr getgrent 3 .
.Nm YP
also provides hooks for other client programs, such as
.Xr amd 8
and
.Xr bootparamd 8 ,
that can use
.Nm YP
maps.
.Pp
The
.Nm YP 
subsystem is started automatically in
.Pa /etc/rc
if the directory
.Pa /var/yp
exists.
.Sh BUGS
Only
.Nm YP
client functionality exists -- the server code has not yet been
written. Brave folk can contact the author.
.Pp
.Pa /etc/passwd
and
.Pa /etc/group
only support ``+'' entries.
.Pp
The
.Xr ypclnt 3
manual pages have not yet been written.
.Pp
Neither Sun nor this author have found a clean way to handle
the problems that occur when
.Xr ypbind 8
cannot find its server
upon bootup.
.Sh SEE ALSO
.Xr domainname 1 ,
.Xr ypbind 8 ,
.Xr ypcat 1 ,
.Xr ypmatch 1 ,
.Xr yppoll 8 , 
.Xr ypset 8 ,
.Xr ypwhich 1
.Sh HISTORY
The
.Nm YP
subsystem was written from the ground up by Theo de Raadt
to be compatible to Sun's implementation. No Sun code was
referenced.
