#	$NetBSD: Makefile,v 1.7 2004/03/20 17:02:34 bjh21 Exp $

MAN=	asc.4 autoconf.4 cosc.4 csc.4 ie.4 intro.4 iomdkbc.4 \
	kbd.4 lpt.4 mainbus.4 mem.4 podulebus.4 ptsc.4 qms.4 rpckbd.4 \
	vidcaudio.4

MLINKS=	mem.4 kmem.4

MANSUBDIR=/acorn32

.include <bsd.man.mk>
