.\"	$NetBSD: qms.4,v 1.2 2004/03/13 19:48:45 bjh21 Exp $
.\"
.\" written by Ben Harris, 2003
.\" This file is in the Public Domain
.\"
.Dd March 13, 2004
.Dt QMS 4 acorn32
.Os
.Sh NAME
.Nm qms
.Nd Quadrature mouse driver
.Sh SYNOPSIS
.Cd qms* at iomd?
.Cd wsmouse* at qms?
.Sh DESCRIPTION
This driver provides an interface to an IOMD quadrature mouse, found on
IOMD20-based systems such as the Acorn Risc PC.
The
.Nm qms
driver interfaces to the
.Xr wsmouse 4
driver to provide a generic, machine-independent mouse interface.
.Sh SEE ALSO
.Xr pms 4 ,
.Xr wsmouse 4
