#	$NetBSD: Makefile,v 1.5.2.2 2001/09/13 01:14:05 thorpej Exp $

KDIR=	/sys/arch/netwinder/include
INCSDIR= /usr/include/arm/netwinder

INCS=	bootconfig.h \
	frame.h \
	intr.h irqhandler.h \
	joystick.h \
	katelib.h kerndebug.h \
	netwinder_boot.h \
	param.h pci_machdep.h pmap.h psl.h \
	rtc.h \
	types.h \
	vmparam.h

.include <bsd.kinc.mk>
