#	$NetBSD: Makefile,v 1.17.122.2 2017/12/03 11:36:40 jdolecek Exp $

INCSDIR= /usr/include/sandpoint

INCS=	bootinfo.h \
	disklabel.h \
	fenv.h \
	intr.h \
	sljit_machdep.h \
	vmparam.h

.include "../../powerpc/include/Makefile"
