#	$NetBSD: Makefile,v 1.1 2011/07/16 15:52:21 tsutsui Exp $
CDBASE=		luna68kcd		# gives ${CDBASE}.iso
CDRELEASE=	true			# include $RELEASEDIR/$MACHINE

.include "${.CURDIR}/../../../common/Makefile.bootcd"
