#	$NetBSD: Makefile,v 1.1.44.1 2019/06/10 21:42:24 christos Exp $
CDBASE=		luna68kcd		# gives ${CDBASE}.iso
CDRELEASE=	true			# include $RELEASEDIR/$MACHINE
CDRELEASE_NODEBUG=	true

.include "${.CURDIR}/../../../common/Makefile.bootcd"
