#	$NetBSD: Makefile,v 1.3.6.2 2007/09/03 14:45:53 yamt Exp $
#

.include <bsd.own.mk>

LIB=		rumpuser

SRCS=		rumpuser.c

RUMPKERNEL=	no

.include "${NETBSDSRCDIR}/sys/rump/Makefile.rump"
.include <bsd.lib.mk>
