#	$NetBSD: Makefile,v 1.4.2.2 2007/10/31 23:14:19 joerg Exp $
#

.include <bsd.own.mk>

LIB=		rumpuser

SRCS=		rumpuser.c

RUMPKERNEL=	no

.include "${NETBSDSRCDIR}/sys/rump/Makefile.rump"
.include <bsd.lib.mk>
