#	$NetBSD: Makefile,v 1.1.4.1 2005/04/06 10:32:35 he Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}bebox-elf2pef
HOST_SRCDIR=	sys/arch/bebox/stand/elf2pef
HOST_CPPFLAGS=	-I${.CURDIR}

.include "${.CURDIR}/../Makefile.host"
