#	$NetBSD: Makefile,v 1.8.2.1 2000/10/19 16:31:23 he Exp $
#	from: @(#)Makefile	8.1 (Berkeley) 6/6/93

PROG=	id
MAN=	id.1 groups.1 whoami.1
LINKS=   ${BINDIR}/id ${BINDIR}/groups
LINKS+=  ${BINDIR}/id ${BINDIR}/whoami
WFORMAT=1

.include <bsd.prog.mk>
