#	$NetBSD: Makefile,v 1.17.10.1 2012/11/20 18:39:13 matt Exp $

SUBDIR+= usr.bin usr.sbin

# Speedup stubs for some subtrees that don't need to run these rules
includes-libexec:
	@true

.include <bsd.subdir.mk>
