#	$NetBSD: Makefile.dbe,v 1.3 2004/02/07 06:52:05 lukem Exp $

LIB=		dbe
.PATH:		${X11SRCDIR.xc}/programs/Xserver/${LIB}

SRCS+=		dbe.c midbe.c

CPPFLAGS+=	-I${X11SRCDIR.xc}/programs/Xserver/include \
		-I${XSERVERINCDIR} \
		-I${DESTDIR}${X11INCDIR}/X11 \
		-I${DESTDIR}${X11INCDIR}/X11/extensions

.include <bsd.x11.mk>
LIBDIR=	${XMODULEDIR}
.include <bsd.lib.mk>
