#	 @(#)Makefile	5.1 (Berkeley) 3/22/91
#	$NetBSD: Makefile,v 1.5 1997/06/22 05:19:43 mrg Exp $

MAN=	MAKEDEV.8 installboot.8 binpatch.8
MLINKS=	MAKEDEV.8 makedev.8
MANSUBDIR=/amiga

.include <bsd.prog.mk>
