#	$NetBSD: Makefile,v 1.1 2001/03/06 21:28:53 garbled Exp $

FILES=	form help
FILESDIR=${BINDIR}/sushi/system/weeklyconf
SCRIPTS= script script1 script3
SCRIPTSDIR=${BINDIR}/sushi/system/weeklyconf
MKOBJ=	no

.include "../../../Makefile.inc"
.include <bsd.prog.mk>
