#	$NetBSD: Makefile,v 1.7 2008/02/02 04:19:51 itohy Exp $
#
# Makefile for sandpoint
#

MENUS_MD=       menus.md.${SYSINSTLANG} menus.mbr
MSG_MD=         msg.md.${SYSINSTLANG} msg.mbr.${SYSINSTLANG}

.include "../../Makefile.inc"
