# This file is automatically generated.  DO NOT EDIT!
# Generated from: 	NetBSD: mknative-binutils,v 1.3 2003/12/04 14:38:00 mrg Exp 
#
G_DEFS=-DHAVE_CONFIG_H -I. -I/usr/src/tools/binutils/../../gnu/dist/binutils/ld -I.
G_EMUL=elf64_sparc
G_EMULATION_OFILES=eelf64_sparc.o eelf32_sparc.o esparcnbsd.o
G_INCLUDES=-D_GNU_SOURCE -I. -I/usr/src/tools/binutils/../../gnu/dist/binutils/ld -I../bfd -I/usr/src/tools/binutils/../../gnu/dist/binutils/ld/../bfd -I/usr/src/tools/binutils/../../gnu/dist/binutils/ld/../include -I/usr/src/tools/binutils/../../gnu/dist/binutils/ld/../intl -I../intl   -DLOCALEDIR="\"/usr/local/share/locale\""
G_OFILES=ldgram.o ldlex.o lexsup.o ldlang.o mri.o ldctor.o ldmain.o  ldwrite.o ldexp.o  ldemul.o ldver.o ldmisc.o  ldfile.o ldcref.o eelf64_sparc.o eelf32_sparc.o esparcnbsd.o 
G_STRINGIFY=astring.sed
G_TEXINFOS=ld.texinfo
G_target_alias=sparc64--netbsd
