# $NetBSD: md.cats,v 1.65 2022/05/03 12:53:51 uwe Exp $
./usr/X11R7/bin/X					xserver-xorg-server-bin	xorg
./usr/X11R7/bin/Xorg					xserver-xorg-server-bin	xorg
./usr/X11R7/bin/cvt					xserver-xorg-server-bin	xorg
./usr/X11R7/bin/gtf					xserver-xorg-server-bin	xorg
./usr/X11R7/bin/pcitweak				xserver-obsolete	obsolete
./usr/X11R7/bin/scanpci					xserver-obsolete	obsolete
./usr/X11R7/bin/xorgconfig				xserver-obsolete	obsolete
./usr/X11R7/lib/X11/Cards				xserver-obsolete	obsolete
./usr/X11R7/lib/X11/doc/README.DRI			xserver-obsolete	obsolete
./usr/X11R7/lib/X11/doc/README.fonts			xserver-obsolete	obsolete
./usr/X11R7/lib/X11/doc/README.modes			xserver-xorg-server-lib	xorg
./usr/X11R7/lib/X11/doc/README.rapidaccess		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/apm_drv.so		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/drivers/apm_drv.so		xserver-obsolete	xorg,xorg_server_ver=120,obsolete
./usr/X11R7/lib/modules/drivers/apm_drv.so.1		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/drivers/apm_drv.so.1		xserver-obsolete	xorg,xorg_server_ver=120,obsolete
./usr/X11R7/lib/modules/drivers/ark_drv.so		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/drivers/ark_drv.so		xserver-obsolete	xorg,xorg_server_ver=120,obsolete
./usr/X11R7/lib/modules/drivers/ark_drv.so.0		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/drivers/ark_drv.so.0		xserver-obsolete	xorg,xorg_server_ver=120,obsolete
./usr/X11R7/lib/modules/drivers/ast_drv.so		xserver-xf86-video-ast-drivers	xorg
./usr/X11R7/lib/modules/drivers/ast_drv.so.1		xserver-xf86-video-ast-drivers	xorg
./usr/X11R7/lib/modules/drivers/ati_drv.so		xserver-xf86-video-ati-drivers	xorg
./usr/X11R7/lib/modules/drivers/ati_drv.so.6		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/ati_drv.so.19		xserver-xf86-video-ati-drivers	xorg
./usr/X11R7/lib/modules/drivers/chips_drv.so		xserver-xf86-video-chips-drivers	xorg
./usr/X11R7/lib/modules/drivers/chips_drv.so.1		xserver-xf86-video-chips-drivers	xorg
./usr/X11R7/lib/modules/drivers/cirrus_alpine.so	xserver-xf86-video-cirrus_alpine-drivers	xorg
./usr/X11R7/lib/modules/drivers/cirrus_alpine.so.1	xserver-xf86-video-cirrus_alpine-drivers	xorg
./usr/X11R7/lib/modules/drivers/cirrus_alpine_drv.so	xdebug-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/cirrus_alpine_drv.so.1	xdebug-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/cirrus_drv.so		xserver-xf86-video-cirrus-drivers	xorg
./usr/X11R7/lib/modules/drivers/cirrus_drv.so.1		xserver-xf86-video-cirrus-drivers	xorg
./usr/X11R7/lib/modules/drivers/cirrus_laguna.so	xserver-xf86-video-cirrus_laguna-drivers	xorg
./usr/X11R7/lib/modules/drivers/cirrus_laguna.so.1	xserver-xf86-video-cirrus_laguna-drivers	xorg
./usr/X11R7/lib/modules/drivers/cirrus_laguna_drv.so	xdebug-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/cirrus_laguna_drv.so.1	xdebug-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/cyrix_drv.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/cyrix_drv.so.1		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/glint_drv.so		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/drivers/glint_drv.so		xserver-obsolete	xorg,xorg_server_ver=120,obsolete
./usr/X11R7/lib/modules/drivers/glint_drv.so.1		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/drivers/glint_drv.so.1		xserver-obsolete	xorg,xorg_server_ver=120,obsolete
./usr/X11R7/lib/modules/drivers/i128_drv.so		xserver-xf86-video-i128-drivers	xorg
./usr/X11R7/lib/modules/drivers/i128_drv.so.1		xserver-xf86-video-i128-drivers	xorg
./usr/X11R7/lib/modules/drivers/i740_drv.so		xserver-xf86-video-i740-drivers	xorg
./usr/X11R7/lib/modules/drivers/i740_drv.so.1		xserver-xf86-video-i740-drivers	xorg
./usr/X11R7/lib/modules/drivers/imstt_drv.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/imstt_drv.so.1		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/kbd_drv.so		xserver-xf86-input-keyboard-drivers	xorg
./usr/X11R7/lib/modules/drivers/kbd_drv.so.1		xserver-xf86-input-keyboard-drivers	xorg
./usr/X11R7/lib/modules/drivers/mga_drv.so		xserver-xf86-video-mga-drivers	xorg
./usr/X11R7/lib/modules/drivers/mga_drv.so.2		xserver-xf86-video-mga-drivers	xorg
./usr/X11R7/lib/modules/drivers/mouse_drv.so		xserver-xf86-input-mouse-drivers	xorg
./usr/X11R7/lib/modules/drivers/mouse_drv.so.1		xserver-xf86-input-mouse-drivers	xorg
./usr/X11R7/lib/modules/drivers/neomagic_drv.so		xserver-xf86-video-neomagic-drivers	xorg
./usr/X11R7/lib/modules/drivers/neomagic_drv.so.1	xserver-xf86-video-neomagic-drivers	xorg
./usr/X11R7/lib/modules/drivers/nsc_drv.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/nsc_drv.so.2		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/nv_drv.so		xserver-xf86-video-nv-drivers	xorg
./usr/X11R7/lib/modules/drivers/nv_drv.so.2		xserver-xf86-video-nv-drivers	xorg
./usr/X11R7/lib/modules/drivers/radeon_drv.so		xserver-xf86-video-radeon-kms-drivers	xorg
./usr/X11R7/lib/modules/drivers/radeon_drv.so.6		xserver-xf86-video-radeon-kms-drivers	xorg
./usr/X11R7/lib/modules/drivers/radeonhd_drv.so		xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/drivers/radeonhd_drv.so.1	xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/drivers/s3_drv.so		xserver-xf86-video-s3-drivers	xorg
./usr/X11R7/lib/modules/drivers/s3_drv.so.0		xserver-xf86-video-s3-drivers	xorg
./usr/X11R7/lib/modules/drivers/s3virge_drv.so		xserver-xf86-video-s3virge-drivers	xorg
./usr/X11R7/lib/modules/drivers/s3virge_drv.so.1	xserver-xf86-video-s3virge-drivers	xorg
./usr/X11R7/lib/modules/drivers/savage_drv.so		xserver-xf86-video-savage-drivers	xorg
./usr/X11R7/lib/modules/drivers/savage_drv.so.2		xserver-xf86-video-savage-drivers	xorg
./usr/X11R7/lib/modules/drivers/siliconmotion_drv.so	xserver-xf86-video-siliconmotion-drivers	xorg
./usr/X11R7/lib/modules/drivers/siliconmotion_drv.so.1	xserver-xf86-video-siliconmotion-drivers	xorg
./usr/X11R7/lib/modules/drivers/tdfx_drv.so		xserver-xf86-video-tdfx-drivers	xorg
./usr/X11R7/lib/modules/drivers/tdfx_drv.so.1		xserver-xf86-video-tdfx-drivers	xorg
./usr/X11R7/lib/modules/drivers/tga_drv.so		xserver-xf86-video-tga-drivers	xorg
./usr/X11R7/lib/modules/drivers/tga_drv.so.1		xserver-xf86-video-tga-drivers	xorg
./usr/X11R7/lib/modules/drivers/trident_drv.so		xserver-xf86-video-trident-drivers	xorg
./usr/X11R7/lib/modules/drivers/trident_drv.so.1	xserver-xf86-video-trident-drivers	xorg
./usr/X11R7/lib/modules/drivers/tseng_drv.so		xserver-xf86-video-tseng-drivers	xorg
./usr/X11R7/lib/modules/drivers/tseng_drv.so.1		xserver-xf86-video-tseng-drivers	xorg
./usr/X11R7/lib/modules/drivers/vesa_drv.so		xserver-xf86-video-vesa-drivers	xorg
./usr/X11R7/lib/modules/drivers/vesa_drv.so.2		xserver-xf86-video-vesa-drivers	xorg
./usr/X11R7/lib/modules/drivers/vga_drv.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/vga_drv.so.4		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/via_drv.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/via_drv.so.0		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/void_drv.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/void_drv.so.1		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/drivers/ws_drv.so		xserver-xf86-input-ws-drivers	xorg
./usr/X11R7/lib/modules/drivers/ws_drv.so.1		xserver-xf86-input-ws-drivers	xorg
./usr/X11R7/lib/modules/drivers/wsfb_drv.so		xserver-xf86-video-wsfb-drivers	xorg
./usr/X11R7/lib/modules/drivers/wsfb_drv.so.0		xserver-xf86-video-wsfb-drivers	xorg
./usr/X11R7/lib/modules/extensions/libcfb.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libcfb.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libcfb.so.0		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libcfb32.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libcfb32.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libcfb32.so.0	xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libcfb32_pic.a	xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libcfb_pic.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libdbe.a		xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/extensions/libdbe.so		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/extensions/libdbe.so		xserver-obsolete	xorg,xorg_server_ver=120,obsolete
./usr/X11R7/lib/modules/extensions/libdbe.so.0		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/extensions/libdbe.so.0		xserver-obsolete	xorg,xorg_server_ver=120,obsolete
./usr/X11R7/lib/modules/extensions/libdbe_pic.a		xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/extensions/libdri.a		xserver-dri-modules	xorg
./usr/X11R7/lib/modules/extensions/libdri.so		xserver-dri-modules	xorg
./usr/X11R7/lib/modules/extensions/libdri.so.0		xserver-dri-modules	xorg
./usr/X11R7/lib/modules/extensions/libdri2.a		xserver-dri2-modules	xorg
./usr/X11R7/lib/modules/extensions/libdri2.so		xserver-dri2-modules	xorg
./usr/X11R7/lib/modules/extensions/libdri2.so.0		xserver-dri2-modules	xorg
./usr/X11R7/lib/modules/extensions/libdri2_pic.a	xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/extensions/libdri_pic.a		xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/extensions/libextmod.a		xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/extensions/libextmod.so		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/extensions/libextmod.so		xserver-obsolete	xorg,xorg_server_ver=120,obsolete
./usr/X11R7/lib/modules/extensions/libextmod.so.0	-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/extensions/libextmod.so.0	xserver-obsolete	xorg,xorg_server_ver=120,obsolete
./usr/X11R7/lib/modules/extensions/libextmod_pic.a	xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/extensions/libglx.a		xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/extensions/libglx.so		xserver-glx-modules	xorg
./usr/X11R7/lib/modules/extensions/libglx.so.0		xserver-glx-modules	xorg
./usr/X11R7/lib/modules/extensions/libglx_pic.a		xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/extensions/libmfb.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libmfb.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libmfb.so.0		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libmfb_pic.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/librecord.a		xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/extensions/librecord.so		-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/extensions/librecord.so		xserver-obsolete	xorg,xorg_server_ver=120,obsolete
./usr/X11R7/lib/modules/extensions/librecord.so.0	-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/extensions/librecord.so.0	xserver-obsolete	xorg,xorg_server_ver=120,obsolete
./usr/X11R7/lib/modules/extensions/librecord_pic.a	xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/extensions/libshadow.a		xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/extensions/libshadow.so		xserver-shadow-modules	xorg
./usr/X11R7/lib/modules/extensions/libshadow.so.0	xserver-shadow-modules	xorg
./usr/X11R7/lib/modules/extensions/libshadow_pic.a	xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/extensions/libxtrap.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libxtrap.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libxtrap.so.0	xserver-obsolete	obsolete
./usr/X11R7/lib/modules/extensions/libxtrap_pic.a	xserver-obsolete	obsolete
./usr/X11R7/lib/modules/fonts/libfreetype.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/fonts/libfreetype.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/fonts/libfreetype.so.0		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/fonts/libfreetype_pic.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/fonts/libtype1.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/fonts/libtype1.so		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/fonts/libtype1.so.0		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/fonts/libtype1_pic.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libexa.a			xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/libexa.so			xserver-exa-modules	xorg
./usr/X11R7/lib/modules/libexa.so.0			xserver-exa-modules	xorg
./usr/X11R7/lib/modules/libexa_pic.a			xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/libfb.a				xserver-dixmods-modules	xorg
./usr/X11R7/lib/modules/libfb.so			xserver-dixmods-modules	xorg
./usr/X11R7/lib/modules/libfb.so.0			xserver-dixmods-modules	xorg
./usr/X11R7/lib/modules/libfb_pic.a			xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/libi2c.a			xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/libi2c.so			xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/libi2c.so.0			xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/libi2c_pic.a			xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/libint10.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libint10.so			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libint10.so.0			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libint10_pic.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libpcidata.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libpcidata.so			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libpcidata.so.0			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libpcidata_pic.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libscanpci.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libscanpci.so			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libscanpci.so.0			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libscanpci_pic.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libshadowfb.a			xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/libshadowfb.so			xserver-shadowfb-modules	xorg
./usr/X11R7/lib/modules/libshadowfb.so.0		xserver-shadowfb-modules	xorg
./usr/X11R7/lib/modules/libshadowfb_pic.a		xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/libvbe.a			xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/libvbe.so			xserver-vbe-modules	xorg
./usr/X11R7/lib/modules/libvbe.so.0			xserver-vbe-modules	xorg
./usr/X11R7/lib/modules/libvbe_pic.a			xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/libvgahw.a			xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/libvgahw.so			xserver-vgahw-modules	xorg
./usr/X11R7/lib/modules/libvgahw.so.0			xserver-vgahw-modules	xorg
./usr/X11R7/lib/modules/libvgahw_pic.a			xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/libxaa.a			xserver-obsolete	xorg,obsolete
./usr/X11R7/lib/modules/libxaa.so			-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/libxaa.so			xserver-obsolete	xorg,xorg_server_ver=120,obsolete
./usr/X11R7/lib/modules/libxaa.so.0			-unknown-	xorg,xorg_server_ver=110
./usr/X11R7/lib/modules/libxaa.so.0			xserver-obsolete	xorg,xorg_server_ver=120,obsolete
./usr/X11R7/lib/modules/libxaa_pic.a			xserver-obsolete	xorg,picinstall,obsolete
./usr/X11R7/lib/modules/libxf1bpp.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf1bpp.so			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf1bpp.so.0			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf1bpp_pic.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf4bpp.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf4bpp.so			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf4bpp.so.0			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf4bpp_pic.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf8_16bpp.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf8_16bpp.so			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf8_16bpp.so.0		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf8_16bpp_pic.a		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf8_32bpp.a			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf8_32bpp.so			xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf8_32bpp.so.0		xserver-obsolete	obsolete
./usr/X11R7/lib/modules/libxf8_32bpp_pic.a		xserver-obsolete	obsolete
./usr/X11R7/man/cat1/Xorg.0				xserver-xorg-server-catman	.cat,xorg
./usr/X11R7/man/cat1/cvt.0				xserver-xorg-server-catman	.cat,xorg
./usr/X11R7/man/cat1/gtf.0				xserver-xorg-server-catman	.cat,xorg
./usr/X11R7/man/cat1/pcitweak.0				xserver-obsolete	obsolete
./usr/X11R7/man/cat1/scanpci.0				xserver-obsolete	obsolete
./usr/X11R7/man/cat1/xorgconfig.0			xserver-obsolete	obsolete
./usr/X11R7/man/cat4/apm.0				-unknown-	.cat,xorg,xorg_server_ver=110
./usr/X11R7/man/cat4/apm.0				xserver-obsolete	.cat,xorg,xorg_server_ver=120,obsolete
./usr/X11R7/man/cat4/ati.0				xserver-xf86-video-ati-catman	.cat,xorg
./usr/X11R7/man/cat4/chips.0				xserver-xf86-video-chips-catman	.cat,xorg
./usr/X11R7/man/cat4/cirrus.0				xserver-xf86-video-cirrus-catman	.cat,xorg
./usr/X11R7/man/cat4/cyrix.0				xserver-obsolete	obsolete
./usr/X11R7/man/cat4/exa.0				xserver-xf86-video-exa-catman	.cat,xorg
./usr/X11R7/man/cat4/glint.0				-unknown-	.cat,xorg,xorg_server_ver=110
./usr/X11R7/man/cat4/glint.0				xserver-obsolete	.cat,xorg,xorg_server_ver=120,obsolete
./usr/X11R7/man/cat4/i128.0				xserver-xf86-video-i128-catman	.cat,xorg
./usr/X11R7/man/cat4/i740.0				xserver-xf86-video-i740-catman	.cat,xorg
./usr/X11R7/man/cat4/imstt.0				xserver-obsolete	obsolete
./usr/X11R7/man/cat4/kbd.0				xserver-xf86-input-keyboard-catman	.cat,xorg
./usr/X11R7/man/cat4/mga.0				xserver-xf86-video-mga-catman	.cat,xorg
./usr/X11R7/man/cat4/mousedrv.0				xserver-xf86-input-mouse-catman	.cat,xorg
./usr/X11R7/man/cat4/neomagic.0				xserver-xf86-video-neomagic-catman	.cat,xorg
./usr/X11R7/man/cat4/nsc.0				xserver-obsolete	obsolete
./usr/X11R7/man/cat4/nv.0				xserver-xf86-video-nv-catman	.cat,xorg
./usr/X11R7/man/cat4/radeon.0				xserver-xf86-video-radeon-kms-catman	.cat,xorg
./usr/X11R7/man/cat4/radeonhd.0				xserver-obsolete	.cat,xorg,obsolete
./usr/X11R7/man/cat4/s3.0				xserver-xf86-video-s3-catman	.cat,xorg
./usr/X11R7/man/cat4/s3virge.0				xserver-xf86-video-s3virge-catman	.cat,xorg
./usr/X11R7/man/cat4/savage.0				xserver-xf86-video-savage-catman	.cat,xorg
./usr/X11R7/man/cat4/siliconmotion.0			xserver-xf86-video-siliconmotion-catman	.cat,xorg
./usr/X11R7/man/cat4/tdfx.0				xserver-xf86-video-tdfx-catman	.cat,xorg
./usr/X11R7/man/cat4/trident.0				xserver-xf86-video-trident-catman	.cat,xorg
./usr/X11R7/man/cat4/tseng.0				xserver-xf86-video-tseng-catman	.cat,xorg
./usr/X11R7/man/cat4/vesa.0				xserver-xf86-video-vesa-catman	.cat,xorg
./usr/X11R7/man/cat4/vga.0				xserver-obsolete	obsolete
./usr/X11R7/man/cat4/via.0				xserver-obsolete	obsolete
./usr/X11R7/man/cat4/void.0				xserver-obsolete	obsolete
./usr/X11R7/man/cat4/ws.0				xserver-xf86-input-ws-catman	.cat,xorg
./usr/X11R7/man/cat4/wsfb.0				xserver-xf86-video-wsfb-catman	.cat,xorg
./usr/X11R7/man/cat5/xorg.conf.0			xserver-xorg-server-catman	.cat,xorg
./usr/X11R7/man/cat5/xorg.conf.d.0			xserver-xorg-server-catman	.cat,xorg
./usr/X11R7/man/html1/Xorg.html				xserver-xorg-server-htmlman	html,xorg
./usr/X11R7/man/html1/cvt.html				xserver-xorg-server-htmlman	html,xorg
./usr/X11R7/man/html1/gtf.html				xserver-xorg-server-htmlman	html,xorg
./usr/X11R7/man/html1/pcitweak.html			xserver-obsolete	obsolete
./usr/X11R7/man/html1/scanpci.html			xserver-obsolete	obsolete
./usr/X11R7/man/html1/xorgconfig.html			xserver-obsolete	obsolete
./usr/X11R7/man/html4/apm.html				-unknown-	html,xorg,xorg_server_ver=110
./usr/X11R7/man/html4/apm.html				xserver-obsolete	html,xorg,xorg_server_ver=120,obsolete
./usr/X11R7/man/html4/ati.html				xserver-xf86-video-ati-htmlman	html,xorg
./usr/X11R7/man/html4/chips.html			xserver-xf86-video-chips-htmlman	html,xorg
./usr/X11R7/man/html4/cirrus.html			xserver-xf86-video-cirrus-htmlman	html,xorg
./usr/X11R7/man/html4/cyrix.html			xserver-obsolete	obsolete
./usr/X11R7/man/html4/exa.html				xserver-xf86-video-exa-htmlman	html,xorg
./usr/X11R7/man/html4/glint.html			-unknown-	html,xorg,xorg_server_ver=110
./usr/X11R7/man/html4/glint.html			xserver-obsolete	html,xorg,xorg_server_ver=120,obsolete
./usr/X11R7/man/html4/i128.html				xserver-xf86-video-i128-htmlman	html,xorg
./usr/X11R7/man/html4/i740.html				xserver-xf86-video-i740-htmlman	html,xorg
./usr/X11R7/man/html4/imstt.html			xserver-obsolete	obsolete
./usr/X11R7/man/html4/kbd.html				xserver-xf86-input-keyboard-htmlman	html,xorg
./usr/X11R7/man/html4/mga.html				xserver-xf86-video-mga-htmlman	html,xorg
./usr/X11R7/man/html4/mousedrv.html			xserver-xf86-input-mouse-htmlman	html,xorg
./usr/X11R7/man/html4/neomagic.html			xserver-xf86-video-neomagic-htmlman	html,xorg
./usr/X11R7/man/html4/nsc.html				xserver-obsolete	obsolete
./usr/X11R7/man/html4/nv.html				xserver-xf86-video-nv-htmlman	html,xorg
./usr/X11R7/man/html4/radeon.html			xserver-xf86-video-radeon-kms-htmlman	html,xorg
./usr/X11R7/man/html4/radeonhd.html			xserver-obsolete	html,xorg,obsolete
./usr/X11R7/man/html4/s3.html				xserver-xf86-video-s3-htmlman	html,xorg
./usr/X11R7/man/html4/s3virge.html			xserver-xf86-video-s3virge-htmlman	html,xorg
./usr/X11R7/man/html4/savage.html			xserver-xf86-video-savage-htmlman	html,xorg
./usr/X11R7/man/html4/siliconmotion.html		xserver-xf86-video-siliconmotion-htmlman	html,xorg
./usr/X11R7/man/html4/tdfx.html				xserver-xf86-video-tdfx-htmlman	html,xorg
./usr/X11R7/man/html4/trident.html			xserver-xf86-video-trident-htmlman	html,xorg
./usr/X11R7/man/html4/tseng.html			xserver-xf86-video-tseng-htmlman	html,xorg
./usr/X11R7/man/html4/vesa.html				xserver-xf86-video-vesa-htmlman	html,xorg
./usr/X11R7/man/html4/vga.html				xserver-obsolete	obsolete
./usr/X11R7/man/html4/via.html				xserver-obsolete	obsolete
./usr/X11R7/man/html4/void.html				xserver-obsolete	obsolete
./usr/X11R7/man/html4/ws.html				xserver-xf86-input-ws-htmlman	html,xorg
./usr/X11R7/man/html4/wsfb.html				xserver-xf86-video-wsfb-htmlman	html,xorg
./usr/X11R7/man/html5/xorg.conf.html			xserver-xorg-server-htmlman	html,xorg
./usr/X11R7/man/html5/xorg.conf.d.html			xserver-xorg-server-htmlman	html,xorg
./usr/X11R7/man/man1/Xorg.1				xserver-xorg-server-man	.man,xorg
./usr/X11R7/man/man1/cvt.1				xserver-xorg-server-man	.man,xorg
./usr/X11R7/man/man1/gtf.1				xserver-xorg-server-man	.man,xorg
./usr/X11R7/man/man1/pcitweak.1				xserver-obsolete	obsolete
./usr/X11R7/man/man1/scanpci.1				xserver-obsolete	obsolete
./usr/X11R7/man/man1/xorgconfig.1			xserver-obsolete	obsolete
./usr/X11R7/man/man4/apm.4				-unknown-	.man,xorg,xorg_server_ver=110
./usr/X11R7/man/man4/apm.4				xserver-obsolete	.man,xorg,xorg_server_ver=120,obsolete
./usr/X11R7/man/man4/ati.4				xserver-xf86-video-ati-man	.man,xorg
./usr/X11R7/man/man4/chips.4				xserver-xf86-video-chips-man	.man,xorg
./usr/X11R7/man/man4/cirrus.4				xserver-xf86-video-cirrus-man	.man,xorg
./usr/X11R7/man/man4/cyrix.4				xserver-obsolete	obsolete
./usr/X11R7/man/man4/exa.4				xserver-xf86-video-exa-man	.man,xorg
./usr/X11R7/man/man4/glint.4				-unknown-	.man,xorg,xorg_server_ver=110
./usr/X11R7/man/man4/glint.4				xserver-obsolete	.man,xorg,xorg_server_ver=120,obsolete
./usr/X11R7/man/man4/i128.4				xserver-xf86-video-i128-man	.man,xorg
./usr/X11R7/man/man4/i740.4				xserver-xf86-video-i740-man	.man,xorg
./usr/X11R7/man/man4/imstt.4				xserver-obsolete	obsolete
./usr/X11R7/man/man4/kbd.4				xserver-xf86-input-keyboard-man	.man,xorg
./usr/X11R7/man/man4/mga.4				xserver-xf86-video-mga-man	.man,xorg
./usr/X11R7/man/man4/mousedrv.4				xserver-xf86-input-mouse-man	.man,xorg
./usr/X11R7/man/man4/neomagic.4				xserver-xf86-video-neomagic-man	.man,xorg
./usr/X11R7/man/man4/nsc.4				xserver-obsolete	obsolete
./usr/X11R7/man/man4/nv.4				xserver-xf86-video-nv-man	.man,xorg
./usr/X11R7/man/man4/radeon.4				xserver-xf86-video-radeon-kms-man	.man,xorg
./usr/X11R7/man/man4/radeonhd.4				xserver-obsolete	.man,xorg,obsolete
./usr/X11R7/man/man4/s3.4				xserver-xf86-video-s3-man	.man,xorg
./usr/X11R7/man/man4/s3virge.4				xserver-xf86-video-s3virge-man	.man,xorg
./usr/X11R7/man/man4/savage.4				xserver-xf86-video-savage-man	.man,xorg
./usr/X11R7/man/man4/siliconmotion.4			xserver-xf86-video-siliconmotion-man	.man,xorg
./usr/X11R7/man/man4/tdfx.4				xserver-xf86-video-tdfx-man	.man,xorg
./usr/X11R7/man/man4/trident.4				xserver-xf86-video-trident-man	.man,xorg
./usr/X11R7/man/man4/tseng.4				xserver-xf86-video-tseng-man	.man,xorg
./usr/X11R7/man/man4/vesa.4				xserver-xf86-video-vesa-man	.man,xorg
./usr/X11R7/man/man4/vga.4				xserver-obsolete	obsolete
./usr/X11R7/man/man4/via.4				xserver-obsolete	obsolete
./usr/X11R7/man/man4/void.4				xserver-obsolete	obsolete
./usr/X11R7/man/man4/ws.4				xserver-xf86-input-ws-man	.man,xorg
./usr/X11R7/man/man4/wsfb.4				xserver-xf86-video-wsfb-man	.man,xorg
./usr/X11R7/man/man5/xorg.conf.5			xserver-xorg-server-man	.man,xorg
./usr/X11R7/man/man5/xorg.conf.d.5			xserver-xorg-server-man	.man,xorg
./usr/X11R7/share/aclocal/xorg-server.m4		xserver-xorg-server-share	xorg
