#	$NetBSD: Makefile,v 1.5 2001/07/14 00:23:10 matt Exp $

KDIR=	/sys/arch/arm/include/arm32
INCSDIR= /usr/include/arm/arm32

INCS=	frame.h katelib.h param.h pcb.h pmap.h psl.h rtc.h

.include <bsd.kinc.mk>
