#	$NetBSD: Makefile,v 1.1 2020/05/18 21:19:35 jmcneill Exp $

TARGETS+=	dtblist

SUBDIR+=	allwinner
SUBDIR+=	amlogic
SUBDIR+=	broadcom
SUBDIR+=	freescale
SUBDIR+=	nvidia
SUBDIR+=	rockchip

.include <bsd.subdir.mk>
